/**
 * THE 300 MECHANISMS
 * Science × Spirituality × Apple
 * 
 * Ram Dass × Alan Watts × Steve Jobs × Neuroscience × Master Therapists
 * 
 * Each mechanism embodies:
 * - Clinical rigor (neuroplasticity-backed)
 * - Spiritual depth (wisdom-infused)
 * - Interaction elegance (Apple-grade UX)
 * 
 * Distribution:
 * - Spatial: 50 mechanisms
 * - Somatic: 40 mechanisms
 * - Temporal: 35 mechanisms
 * - Emotional: 50 mechanisms
 * - Relational: 35 mechanisms
 * - Cognitive: 40 mechanisms
 * - Energetic: 30 mechanisms
 * - Ritual: 20 mechanisms
 */

import type { Mechanism, MechanismCategory, MechanismComplexity, MechanismModality, MechanismOutcome } from './experience-genome';

export const MECHANISMS_300: Record<string, Mechanism> = {
  
  // ═══════════════════════════════════════════════════════════════════════════
  // SPATIAL MECHANISMS (50)
  // Where: Cognitive mapping × Sacred geometry × Gestural elegance
  // ═══════════════════════════════════════════════════════════════════════════
  
  GRAVITY_MAP: {
    id: 'gravity_map',
    name: 'Gravity Map',
    category: 'spatial',
    complexity: 'complex',
    modality: ['visual', 'kinesthetic'],
    outcome: ['awareness', 'decision'],
    description: 'Map priorities by spatial weight and pull - what draws you in?',
    interactionType: 'drag-and-drop with physics',
    duration: 'medium',
    responseAffinity: ['KNOWING', 'CHOOSING'],
  },
  
  BOUNDARY_SLIDERS: {
    id: 'boundary_sliders',
    name: 'Boundary Sliders',
    category: 'spatial',
    complexity: 'medium',
    modality: ['visual', 'kinesthetic'],
    outcome: ['decision', 'grounding'],
    description: 'Set sacred limits across life dimensions',
    interactionType: 'multi-slider',
    duration: 'short',
    responseAffinity: ['CHOOSING', 'BELIEVING'],
  },
  
  ANCHOR_POINTS: {
    id: 'anchor_points',
    name: 'Anchor Points',
    category: 'spatial',
    complexity: 'simple',
    modality: ['visual', 'kinesthetic'],
    outcome: ['grounding', 'awareness'],
    description: 'Place stability markers - what holds you?',
    interactionType: 'tap-to-place',
    duration: 'short',
    responseAffinity: ['BELIEVING', 'FEELING'],
  },
  
  CONTAINER_BUILDER: {
    id: 'container_builder',
    name: 'Container Builder',
    category: 'spatial',
    complexity: 'complex',
    modality: ['visual', 'kinesthetic'],
    outcome: ['grounding', 'integration'],
    description: 'Build vessel for what you hold',
    interactionType: 'draw-and-shape',
    duration: 'medium',
    responseAffinity: ['FEELING', 'INTEGRATING'],
  },
  
  THRESHOLD_DIAL: {
    id: 'threshold_dial',
    name: 'Threshold Dial',
    category: 'spatial',
    complexity: 'simple',
    modality: ['visual', 'kinesthetic'],
    outcome: ['awareness', 'decision'],
    description: 'Tune edge awareness - how close is too close?',
    interactionType: 'circular-dial',
    duration: 'instant',
    responseAffinity: ['WITNESSING', 'CHOOSING'],
  },
  
  SPIRAL_PATH: {
    id: 'spiral_path',
    name: 'Spiral Path',
    category: 'spatial',
    complexity: 'medium',
    modality: ['visual', 'temporal'],
    outcome: ['awareness', 'integration'],
    description: 'Progress isn\'t linear - trace the spiral',
    interactionType: 'path-following',
    duration: 'medium',
    responseAffinity: ['BECOMING', 'INTEGRATING'],
  },
  
  FULL_CIRCLE: {
    id: 'full_circle',
    name: 'Full Circle',
    category: 'spatial',
    complexity: 'medium',
    modality: ['visual', 'temporal'],
    outcome: ['integration', 'awareness'],
    description: 'Complete the return - wholeness ritual',
    interactionType: 'trace-path',
    duration: 'medium',
    responseAffinity: ['INTEGRATING', 'RELEASING'],
  },
  
  ZONE_MAPPING: {
    id: 'zone_mapping',
    name: 'Zone Mapping',
    category: 'spatial',
    complexity: 'medium',
    modality: ['visual', 'kinesthetic'],
    outcome: ['awareness', 'decision'],
    description: 'Sort experiences into territories',
    interactionType: 'drag-to-zone',
    duration: 'medium',
    responseAffinity: ['KNOWING', 'INTEGRATING'],
  },
  
  DISTANCE_GAUGE: {
    id: 'distance_gauge',
    name: 'Distance Gauge',
    category: 'spatial',
    complexity: 'simple',
    modality: ['visual'],
    outcome: ['awareness'],
    description: 'Measure space between you and it',
    interactionType: 'slider',
    duration: 'instant',
    responseAffinity: ['WITNESSING', 'FEELING'],
  },
  
  PROXIMITY_SCATTER: {
    id: 'proximity_scatter',
    name: 'Proximity Scatter',
    category: 'spatial',
    complexity: 'complex',
    modality: ['visual', 'kinesthetic'],
    outcome: ['awareness', 'integration'],
    description: 'Cluster by closeness - who/what matters most?',
    interactionType: 'multi-drag',
    duration: 'long',
    responseAffinity: ['KNOWING', 'INTEGRATING'],
  },
  
  ALTITUDE_SLIDER: {
    id: 'altitude_slider',
    name: 'Altitude Slider',
    category: 'spatial',
    complexity: 'simple',
    modality: ['visual'],
    outcome: ['awareness'],
    description: 'Rise above - adjust your viewing altitude',
    interactionType: 'vertical-slider',
    duration: 'instant',
    responseAffinity: ['WITNESSING', 'KNOWING'],
  },
  
  BORDER_DRAW: {
    id: 'border_draw',
    name: 'Border Draw',
    category: 'spatial',
    complexity: 'medium',
    modality: ['kinesthetic'],
    outcome: ['decision', 'grounding'],
    description: 'Draw the line - your boundaries, your hand',
    interactionType: 'freehand-draw',
    duration: 'short',
    responseAffinity: ['CHOOSING', 'BELIEVING'],
  },
  
  TERRITORY_CLAIM: {
    id: 'territory_claim',
    name: 'Territory Claim',
    category: 'spatial',
    complexity: 'simple',
    modality: ['visual', 'kinesthetic'],
    outcome: ['decision', 'grounding'],
    description: 'Claim your space - expand to fill it',
    interactionType: 'tap-to-expand',
    duration: 'short',
    responseAffinity: ['CHOOSING', 'BELIEVING'],
  },
  
  LAYERED_DEPTH: {
    id: 'layered_depth',
    name: 'Layered Depth',
    category: 'spatial',
    complexity: 'complex',
    modality: ['visual', 'kinesthetic'],
    outcome: ['awareness', 'integration'],
    description: 'Descend through layers - what lies beneath?',
    interactionType: 'layer-navigation',
    duration: 'medium',
    responseAffinity: ['KNOWING', 'INTEGRATING'],
  },
  
  HORIZON_LINE: {
    id: 'horizon_line',
    name: 'Horizon Line',
    category: 'spatial',
    complexity: 'simple',
    modality: ['visual'],
    outcome: ['awareness', 'grounding'],
    description: 'Set your horizon - where earth meets sky',
    interactionType: 'drag-horizontal-line',
    duration: 'instant',
    responseAffinity: ['BELIEVING', 'WITNESSING'],
  },
  
  SACRED_GEOMETRY: {
    id: 'sacred_geometry',
    name: 'Sacred Geometry',
    category: 'spatial',
    complexity: 'medium',
    modality: ['visual', 'kinesthetic'],
    outcome: ['integration', 'grounding'],
    description: 'Align to divine proportion',
    interactionType: 'shape-alignment',
    duration: 'medium',
    responseAffinity: ['INTEGRATING', 'BELIEVING'],
  },
  
  MANDALA_BUILD: {
    id: 'mandala_build',
    name: 'Mandala Build',
    category: 'spatial',
    complexity: 'complex',
    modality: ['visual', 'kinesthetic'],
    outcome: ['integration', 'awareness'],
    description: 'Create wholeness through symmetry',
    interactionType: 'radial-draw',
    duration: 'long',
    responseAffinity: ['INTEGRATING', 'WITNESSING'],
  },
  
  CENTER_POINT: {
    id: 'center_point',
    name: 'Center Point',
    category: 'spatial',
    complexity: 'simple',
    modality: ['visual', 'kinesthetic'],
    outcome: ['grounding', 'awareness'],
    description: 'Find your center - mark it',
    interactionType: 'tap-center',
    duration: 'instant',
    responseAffinity: ['FEELING', 'WITNESSING'],
  },
  
  EXPANSION_RINGS: {
    id: 'expansion_rings',
    name: 'Expansion Rings',
    category: 'spatial',
    complexity: 'medium',
    modality: ['visual', 'kinesthetic'],
    outcome: ['activation', 'awareness'],
    description: 'Ripple outward - concentric growth',
    interactionType: 'pinch-expand',
    duration: 'short',
    responseAffinity: ['BECOMING', 'CHOOSING'],
  },
  
  CONSTELLATION_PLOT: {
    id: 'constellation_plot',
    name: 'Constellation Plot',
    category: 'spatial',
    complexity: 'complex',
    modality: ['visual', 'kinesthetic'],
    outcome: ['integration', 'awareness'],
    description: 'Map relationships as stars - find patterns',
    interactionType: 'point-connect',
    duration: 'long',
    responseAffinity: ['KNOWING', 'INTEGRATING'],
  },
  
  DENSITY_MAP: {
    id: 'density_map',
    name: 'Density Map',
    category: 'spatial',
    complexity: 'medium',
    modality: ['visual'],
    outcome: ['awareness'],
    description: 'Where does it concentrate? Where sparse?',
    interactionType: 'heat-visualization',
    duration: 'short',
    responseAffinity: ['KNOWING', 'WITNESSING'],
  },
  
  VORTEX_SPIN: {
    id: 'vortex_spin',
    name: 'Vortex Spin',
    category: 'spatial',
    complexity: 'medium',
    modality: ['visual', 'kinesthetic'],
    outcome: ['release', 'activation'],
    description: 'Spin to dissolve - let it swirl away',
    interactionType: 'circular-gesture',
    duration: 'short',
    responseAffinity: ['RELEASING', 'FEELING'],
  },
  
  FIELD_HARMONICS: {
    id: 'field_harmonics',
    name: 'Field Harmonics',
    category: 'spatial',
    complexity: 'complex',
    modality: ['visual', 'auditory'],
    outcome: ['integration', 'grounding'],
    description: 'Tune your field to resonance',
    interactionType: 'frequency-adjust',
    duration: 'medium',
    responseAffinity: ['INTEGRATING', 'FEELING'],
  },
  
  QUADRANT_BALANCE: {
    id: 'quadrant_balance',
    name: 'Quadrant Balance',
    category: 'spatial',
    complexity: 'medium',
    modality: ['visual', 'kinesthetic'],
    outcome: ['awareness', 'decision'],
    description: 'Balance four dimensions of life',
    interactionType: 'four-way-slider',
    duration: 'medium',
    responseAffinity: ['KNOWING', 'CHOOSING'],
  },
  
  LABYRINTH_WALK: {
    id: 'labyrinth_walk',
    name: 'Labyrinth Walk',
    category: 'spatial',
    complexity: 'complex',
    modality: ['visual', 'kinesthetic'],
    outcome: ['integration', 'awareness'],
    description: 'Walk the path - arrive at center',
    interactionType: 'path-trace',
    duration: 'long',
    responseAffinity: ['INTEGRATING', 'WITNESSING'],
  },
  
  VECTOR_PULL: {
    id: 'vector_pull',
    name: 'Vector Pull',
    category: 'spatial',
    complexity: 'simple',
    modality: ['visual', 'kinesthetic'],
    outcome: ['decision', 'awareness'],
    description: 'Feel the pull - which way are you drawn?',
    interactionType: 'directional-drag',
    duration: 'instant',
    responseAffinity: ['CHOOSING', 'FEELING'],
  },
  
  TESSELLATION_PATTERN: {
    id: 'tessellation_pattern',
    name: 'Tessellation Pattern',
    category: 'spatial',
    complexity: 'complex',
    modality: ['visual', 'kinesthetic'],
    outcome: ['integration', 'awareness'],
    description: 'Everything fits - create the pattern',
    interactionType: 'pattern-build',
    duration: 'long',
    responseAffinity: ['INTEGRATING', 'KNOWING'],
  },
  
  AXIS_ALIGNMENT: {
    id: 'axis_alignment',
    name: 'Axis Alignment',
    category: 'spatial',
    complexity: 'simple',
    modality: ['visual'],
    outcome: ['grounding', 'awareness'],
    description: 'True vertical - align to it',
    interactionType: 'orientation-adjust',
    duration: 'instant',
    responseAffinity: ['BELIEVING', 'WITNESSING'],
  },
  
  PORTAL_PLACEMENT: {
    id: 'portal_placement',
    name: 'Portal Placement',
    category: 'spatial',
    complexity: 'medium',
    modality: ['visual', 'kinesthetic'],
    outcome: ['activation', 'integration'],
    description: 'Open door to new state',
    interactionType: 'portal-draw',
    duration: 'medium',
    responseAffinity: ['BECOMING', 'INTEGRATING'],
  },
  
  MESH_WEAVING: {
    id: 'mesh_weaving',
    name: 'Mesh Weaving',
    category: 'spatial',
    complexity: 'complex',
    modality: ['visual', 'kinesthetic'],
    outcome: ['integration', 'awareness'],
    description: 'Weave safety net - thread by thread',
    interactionType: 'thread-weaving',
    duration: 'long',
    responseAffinity: ['INTEGRATING', 'KNOWING'],
  },
  
  FRACTAL_ZOOM: {
    id: 'fractal_zoom',
    name: 'Fractal Zoom',
    category: 'spatial',
    complexity: 'medium',
    modality: ['visual', 'kinesthetic'],
    outcome: ['awareness', 'integration'],
    description: 'Pattern repeats at every scale',
    interactionType: 'infinite-zoom',
    duration: 'medium',
    responseAffinity: ['KNOWING', 'WITNESSING'],
  },
  
  ANCHOR_TRIANGLE: {
    id: 'anchor_triangle',
    name: 'Anchor Triangle',
    category: 'spatial',
    complexity: 'medium',
    modality: ['visual', 'kinesthetic'],
    outcome: ['grounding', 'awareness'],
    description: 'Three points of stability',
    interactionType: 'three-point-placement',
    duration: 'short',
    responseAffinity: ['BELIEVING', 'KNOWING'],
  },
  
  INFINITY_LOOP: {
    id: 'infinity_loop',
    name: 'Infinity Loop',
    category: 'spatial',
    complexity: 'simple',
    modality: ['visual', 'kinesthetic'],
    outcome: ['integration', 'awareness'],
    description: 'Eternal return - trace the infinite',
    interactionType: 'figure-eight-trace',
    duration: 'short',
    responseAffinity: ['INTEGRATING', 'WITNESSING'],
  },
  
  PERSPECTIVE_SHIFT_3D: {
    id: 'perspective_shift_3d',
    name: 'Perspective Shift 3D',
    category: 'spatial',
    complexity: 'complex',
    modality: ['visual', 'kinesthetic'],
    outcome: ['awareness', 'integration'],
    description: 'Rotate the view - see from new angle',
    interactionType: '3d-rotation',
    duration: 'medium',
    responseAffinity: ['KNOWING', 'INTEGRATING'],
  },
  
  BALANCE_BEAM: {
    id: 'balance_beam',
    name: 'Balance Beam',
    category: 'spatial',
    complexity: 'simple',
    modality: ['visual', 'kinesthetic'],
    outcome: ['awareness', 'grounding'],
    description: 'Find the tipping point',
    interactionType: 'balance-tilt',
    duration: 'short',
    responseAffinity: ['FEELING', 'WITNESSING'],
  },
  
  SACRED_CIRCLE_CAST: {
    id: 'sacred_circle_cast',
    name: 'Sacred Circle Cast',
    category: 'spatial',
    complexity: 'medium',
    modality: ['visual', 'kinesthetic'],
    outcome: ['grounding', 'integration'],
    description: 'Cast circle - mark sacred space',
    interactionType: 'circular-gesture-cast',
    duration: 'medium',
    responseAffinity: ['BELIEVING', 'INTEGRATING'],
  },
  
  TOPOGRAPHY_MAP: {
    id: 'topography_map',
    name: 'Topography Map',
    category: 'spatial',
    complexity: 'complex',
    modality: ['visual', 'kinesthetic'],
    outcome: ['awareness', 'integration'],
    description: 'Map your inner landscape',
    interactionType: 'height-sculpting',
    duration: 'long',
    responseAffinity: ['KNOWING', 'INTEGRATING'],
  },
  
  CROSSROADS_CHOICE: {
    id: 'crossroads_choice',
    name: 'Crossroads Choice',
    category: 'spatial',
    complexity: 'simple',
    modality: ['visual', 'kinesthetic'],
    outcome: ['decision', 'awareness'],
    description: 'Stand at crossroads - choose',
    interactionType: 'path-selection',
    duration: 'instant',
    responseAffinity: ['CHOOSING', 'KNOWING'],
  },
  
  DIMENSIONAL_LAYERS: {
    id: 'dimensional_layers',
    name: 'Dimensional Layers',
    category: 'spatial',
    complexity: 'complex',
    modality: ['visual', 'kinesthetic'],
    outcome: ['awareness', 'integration'],
    description: 'Multiple realities - navigate between',
    interactionType: 'layer-swipe',
    duration: 'medium',
    responseAffinity: ['KNOWING', 'INTEGRATING'],
  },
  
  LIGHT_GEOMETRY: {
    id: 'light_geometry',
    name: 'Light Geometry',
    category: 'spatial',
    complexity: 'medium',
    modality: ['visual'],
    outcome: ['awareness', 'integration'],
    description: 'Light reveals the pattern',
    interactionType: 'light-ray-trace',
    duration: 'medium',
    responseAffinity: ['WITNESSING', 'INTEGRATING'],
  },
  
  RADIAL_PULSE: {
    id: 'radial_pulse',
    name: 'Radial Pulse',
    category: 'spatial',
    complexity: 'simple',
    modality: ['visual', 'kinesthetic'],
    outcome: ['activation', 'grounding'],
    description: 'Pulse from center outward',
    interactionType: 'tap-pulse',
    duration: 'instant',
    responseAffinity: ['FEELING', 'CHOOSING'],
  },
  
  ORBIT_PATHS: {
    id: 'orbit_paths',
    name: 'Orbit Paths',
    category: 'spatial',
    complexity: 'medium',
    modality: ['visual', 'kinesthetic'],
    outcome: ['awareness', 'integration'],
    description: 'What orbits what? Map the pull',
    interactionType: 'orbital-drag',
    duration: 'medium',
    responseAffinity: ['KNOWING', 'INTEGRATING'],
  },
  
  MAGNETIC_PULL: {
    id: 'magnetic_pull',
    name: 'Magnetic Pull',
    category: 'spatial',
    complexity: 'medium',
    modality: ['visual', 'kinesthetic'],
    outcome: ['awareness', 'decision'],
    description: 'Attraction and repulsion - feel both',
    interactionType: 'magnetic-physics',
    duration: 'short',
    responseAffinity: ['FEELING', 'CHOOSING'],
  },
  
  SPATIAL_BREATH: {
    id: 'spatial_breath',
    name: 'Spatial Breath',
    category: 'spatial',
    complexity: 'simple',
    modality: ['visual', 'temporal'],
    outcome: ['grounding', 'awareness'],
    description: 'Space breathes with you',
    interactionType: 'expansion-contraction',
    duration: 'short',
    responseAffinity: ['FEELING', 'WITNESSING'],
  },
  
  SHADOW_WORK: {
    id: 'shadow_work',
    name: 'Shadow Work',
    category: 'spatial',
    complexity: 'medium',
    modality: ['visual', 'kinesthetic'],
    outcome: ['awareness', 'integration'],
    description: 'Where light falls, shadow appears',
    interactionType: 'shadow-manipulation',
    duration: 'medium',
    responseAffinity: ['KNOWING', 'INTEGRATING'],
  },
  
  VERTEX_CONNECTION: {
    id: 'vertex_connection',
    name: 'Vertex Connection',
    category: 'spatial',
    complexity: 'complex',
    modality: ['visual', 'kinesthetic'],
    outcome: ['integration', 'awareness'],
    description: 'Connect vertices - structure emerges',
    interactionType: 'vertex-linking',
    duration: 'long',
    responseAffinity: ['INTEGRATING', 'KNOWING'],
  },
  
  INNER_SANCTUARY: {
    id: 'inner_sanctuary',
    name: 'Inner Sanctuary',
    category: 'spatial',
    complexity: 'complex',
    modality: ['visual', 'kinesthetic'],
    outcome: ['grounding', 'integration'],
    description: 'Build refuge - design safety',
    interactionType: 'space-design',
    duration: 'long',
    responseAffinity: ['BELIEVING', 'INTEGRATING'],
  },
  
  FLOW_CHANNELS: {
    id: 'flow_channels',
    name: 'Flow Channels',
    category: 'spatial',
    complexity: 'medium',
    modality: ['visual', 'kinesthetic'],
    outcome: ['activation', 'awareness'],
    description: 'Carve channels - energy flows',
    interactionType: 'channel-carving',
    duration: 'medium',
    responseAffinity: ['BECOMING', 'FEELING'],
  },
  
  VOID_EMBRACE: {
    id: 'void_embrace',
    name: 'Void Embrace',
    category: 'spatial',
    complexity: 'simple',
    modality: ['visual'],
    outcome: ['release', 'awareness'],
    description: 'Rest in emptiness - nothing to do',
    interactionType: 'stillness-hold',
    duration: 'medium',
    responseAffinity: ['WITNESSING', 'RELEASING'],
  },
  
  // ═══════════════════════════════════════════════════════════════════════════
  // SOMATIC MECHANISMS (40)
  // Body: Nervous system regulation × Embodied wisdom × Tactile precision
  // ═══════════════════════════════════════════════════════════════════════════
  
  TENSION_BODY_MAP: {
    id: 'tension_body_map',
    name: 'Tension Body Map',
    category: 'somatic',
    complexity: 'medium',
    modality: ['visual', 'kinesthetic'],
    outcome: ['awareness', 'release'],
    description: 'Where do you hold it? Map the grip',
    interactionType: 'tap-body-regions',
    duration: 'short',
    responseAffinity: ['FEELING', 'RELEASING'],
  },
  
  CAPACITY_GAUGE: {
    id: 'capacity_gauge',
    name: 'Capacity Gauge',
    category: 'somatic',
    complexity: 'simple',
    modality: ['visual'],
    outcome: ['awareness'],
    description: 'How full is your nervous system?',
    interactionType: 'gauge-tap',
    duration: 'instant',
    responseAffinity: ['WITNESSING', 'FEELING'],
  },
  
  VOICE_VOLUME: {
    id: 'voice_volume',
    name: 'Voice Volume',
    category: 'somatic',
    complexity: 'medium',
    modality: ['visual', 'kinesthetic'],
    outcome: ['awareness', 'decision'],
    description: 'Turn down inner critic - find the knob',
    interactionType: 'volume-slider',
    duration: 'short',
    responseAffinity: ['FEELING', 'CHOOSING'],
  },
  
  SENSORY_SNAPSHOT: {
    id: 'sensory_snapshot',
    name: 'Sensory Snapshot',
    category: 'somatic',
    complexity: 'simple',
    modality: ['visual', 'kinesthetic'],
    outcome: ['grounding', 'awareness'],
    description: 'Five senses - anchor to now',
    interactionType: 'tap-senses',
    duration: 'short',
    responseAffinity: ['FEELING', 'WITNESSING'],
  },
  
  BREATH_RHYTHM: {
    id: 'breath_rhythm',
    name: 'Breath Rhythm',
    category: 'somatic',
    complexity: 'simple',
    modality: ['visual', 'temporal'],
    outcome: ['grounding'],
    description: 'Follow the breath - let it lead',
    interactionType: 'animated-breathing',
    duration: 'short',
    responseAffinity: ['FEELING', 'WITNESSING'],
  },
  
  HEART_PULSE: {
    id: 'heart_pulse',
    name: 'Heart Pulse',
    category: 'somatic',
    complexity: 'simple',
    modality: ['visual', 'temporal'],
    outcome: ['awareness', 'grounding'],
    description: 'Feel your heartbeat - sync to it',
    interactionType: 'pulse-sync',
    duration: 'short',
    responseAffinity: ['FEELING', 'WITNESSING'],
  },
  
  TEMPERATURE_SLIDER: {
    id: 'temperature_slider',
    name: 'Temperature Slider',
    category: 'somatic',
    complexity: 'simple',
    modality: ['visual'],
    outcome: ['awareness'],
    description: 'Hot or cold? Track emotional temp',
    interactionType: 'thermometer-slider',
    duration: 'instant',
    responseAffinity: ['FEELING', 'WITNESSING'],
  },
  
  GROUNDING_ROOTS: {
    id: 'grounding_roots',
    name: 'Grounding Roots',
    category: 'somatic',
    complexity: 'medium',
    modality: ['visual', 'temporal'],
    outcome: ['grounding'],
    description: 'Grow roots into earth - feel stability',
    interactionType: 'hold-to-grow',
    duration: 'medium',
    responseAffinity: ['FEELING', 'BELIEVING'],
  },
  
  SENSATION_SCAN: {
    id: 'sensation_scan',
    name: 'Sensation Scan',
    category: 'somatic',
    complexity: 'medium',
    modality: ['visual', 'temporal'],
    outcome: ['awareness'],
    description: 'Body scan - what\'s present?',
    interactionType: 'guided-scan',
    duration: 'long',
    responseAffinity: ['FEELING', 'WITNESSING'],
  },
  
  PRESSURE_POINTS: {
    id: 'pressure_points',
    name: 'Pressure Points',
    category: 'somatic',
    complexity: 'simple',
    modality: ['kinesthetic'],
    outcome: ['release', 'awareness'],
    description: 'Tap acupressure points - release stuck',
    interactionType: 'tap-points',
    duration: 'short',
    responseAffinity: ['FEELING', 'RELEASING'],
  },
  
  NERVOUS_SYSTEM_LADDER: {
    id: 'nervous_system_ladder',
    name: 'Nervous System Ladder',
    category: 'somatic',
    complexity: 'medium',
    modality: ['visual'],
    outcome: ['awareness', 'grounding'],
    description: 'Polyvagal ladder - where are you?',
    interactionType: 'ladder-position',
    duration: 'instant',
    responseAffinity: ['KNOWING', 'FEELING'],
  },
  
  SHIVER_RELEASE: {
    id: 'shiver_release',
    name: 'Shiver Release',
    category: 'somatic',
    complexity: 'simple',
    modality: ['kinesthetic', 'temporal'],
    outcome: ['release'],
    description: 'Shake it off - animal discharge',
    interactionType: 'shake-gesture',
    duration: 'short',
    responseAffinity: ['RELEASING', 'FEELING'],
  },
  
  THROAT_OPEN: {
    id: 'throat_open',
    name: 'Throat Open',
    category: 'somatic',
    complexity: 'simple',
    modality: ['visual', 'kinesthetic'],
    outcome: ['release', 'activation'],
    description: 'Sound your truth - open throat',
    interactionType: 'vocal-tone',
    duration: 'short',
    responseAffinity: ['CHOOSING', 'RELEASING'],
  },
  
  BELLY_BREATH: {
    id: 'belly_breath',
    name: 'Belly Breath',
    category: 'somatic',
    complexity: 'simple',
    modality: ['visual', 'temporal'],
    outcome: ['grounding'],
    description: 'Breathe into belly - soften',
    interactionType: 'deep-breathing',
    duration: 'short',
    responseAffinity: ['FEELING', 'WITNESSING'],
  },
  
  POSTURE_ADJUST: {
    id: 'posture_adjust',
    name: 'Posture Adjust',
    category: 'somatic',
    complexity: 'simple',
    modality: ['visual', 'kinesthetic'],
    outcome: ['grounding', 'awareness'],
    description: 'Shift posture - shift state',
    interactionType: 'posture-guide',
    duration: 'instant',
    responseAffinity: ['FEELING', 'CHOOSING'],
  },
  
  MUSCLE_PROGRESSIVE_RELEASE: {
    id: 'muscle_progressive_release',
    name: 'Muscle Progressive Release',
    category: 'somatic',
    complexity: 'medium',
    modality: ['kinesthetic', 'temporal'],
    outcome: ['release', 'grounding'],
    description: 'Tense, then release - systematic',
    interactionType: 'sequential-tension',
    duration: 'long',
    responseAffinity: ['FEELING', 'RELEASING'],
  },
  
  SKIN_BOUNDARY: {
    id: 'skin_boundary',
    name: 'Skin Boundary',
    category: 'somatic',
    complexity: 'simple',
    modality: ['kinesthetic'],
    outcome: ['grounding', 'awareness'],
    description: 'Feel your skin - edge of you',
    interactionType: 'tactile-awareness',
    duration: 'short',
    responseAffinity: ['FEELING', 'BELIEVING'],
  },
  
  VAGUS_NERVE_ACTIVATE: {
    id: 'vagus_nerve_activate',
    name: 'Vagus Nerve Activate',
    category: 'somatic',
    complexity: 'medium',
    modality: ['kinesthetic', 'temporal'],
    outcome: ['grounding', 'release'],
    description: 'Hum, gargle, sing - activate vagus',
    interactionType: 'vagal-stimulation',
    duration: 'short',
    responseAffinity: ['FEELING', 'GROUNDING'],
  },
  
  FEET_ON_EARTH: {
    id: 'feet_on_earth',
    name: 'Feet on Earth',
    category: 'somatic',
    complexity: 'simple',
    modality: ['kinesthetic'],
    outcome: ['grounding'],
    description: 'Feel feet - gravity holds you',
    interactionType: 'foot-pressure',
    duration: 'instant',
    responseAffinity: ['FEELING', 'WITNESSING'],
  },
  
  EMOTIONAL_WAVE: {
    id: 'emotional_wave',
    name: 'Emotional Wave',
    category: 'somatic',
    complexity: 'medium',
    modality: ['visual', 'kinesthetic'],
    outcome: ['awareness', 'release'],
    description: 'Ride the wave - don\'t fight it',
    interactionType: 'wave-follow',
    duration: 'medium',
    responseAffinity: ['FEELING', 'RELEASING'],
  },
  
  JAW_RELEASE: {
    id: 'jaw_release',
    name: 'Jaw Release',
    category: 'somatic',
    complexity: 'simple',
    modality: ['kinesthetic'],
    outcome: ['release', 'awareness'],
    description: 'Unclench jaw - soften face',
    interactionType: 'jaw-movement',
    duration: 'instant',
    responseAffinity: ['FEELING', 'RELEASING'],
  },
  
  SIGH_RELIEF: {
    id: 'sigh_relief',
    name: 'Sigh Relief',
    category: 'somatic',
    complexity: 'simple',
    modality: ['kinesthetic', 'temporal'],
    outcome: ['release'],
    description: 'Big exhale - let it go',
    interactionType: 'exhale-cue',
    duration: 'instant',
    responseAffinity: ['RELEASING', 'FEELING'],
  },
  
  EMBODIED_YES_NO: {
    id: 'embodied_yes_no',
    name: 'Embodied Yes/No',
    category: 'somatic',
    complexity: 'simple',
    modality: ['kinesthetic'],
    outcome: ['awareness', 'decision'],
    description: 'Body knows - yes expands, no contracts',
    interactionType: 'somatic-response-test',
    duration: 'short',
    responseAffinity: ['FEELING', 'CHOOSING'],
  },
  
  TEARS_PERMISSION: {
    id: 'tears_permission',
    name: 'Tears Permission',
    category: 'somatic',
    complexity: 'simple',
    modality: ['visual'],
    outcome: ['release', 'grounding'],
    description: 'Tears are medicine - let them flow',
    interactionType: 'permission-grant',
    duration: 'medium',
    responseAffinity: ['RELEASING', 'FEELING'],
  },
  
  SPINE_ALIGNMENT: {
    id: 'spine_alignment',
    name: 'Spine Alignment',
    category: 'somatic',
    complexity: 'simple',
    modality: ['kinesthetic'],
    outcome: ['grounding', 'awareness'],
    description: 'Lengthen spine - lift crown',
    interactionType: 'postural-cue',
    duration: 'instant',
    responseAffinity: ['FEELING', 'BELIEVING'],
  },
  
  PLEASURE_NOTICE: {
    id: 'pleasure_notice',
    name: 'Pleasure Notice',
    category: 'somatic',
    complexity: 'simple',
    modality: ['kinesthetic'],
    outcome: ['awareness', 'grounding'],
    description: 'Notice pleasure - even tiny',
    interactionType: 'sensation-focus',
    duration: 'short',
    responseAffinity: ['FEELING', 'WITNESSING'],
  },
  
  COLD_SPLASH: {
    id: 'cold_splash',
    name: 'Cold Splash',
    category: 'somatic',
    complexity: 'simple',
    modality: ['kinesthetic'],
    outcome: ['activation', 'grounding'],
    description: 'Cold water - instant presence',
    interactionType: 'temperature-shock',
    duration: 'instant',
    responseAffinity: ['FEELING', 'WITNESSING'],
  },
  
  YAWN_RESET: {
    id: 'yawn_reset',
    name: 'Yawn Reset',
    category: 'somatic',
    complexity: 'simple',
    modality: ['kinesthetic'],
    outcome: ['release', 'grounding'],
    description: 'Yawn deeply - reset nervous system',
    interactionType: 'yawn-cue',
    duration: 'instant',
    responseAffinity: ['FEELING', 'RELEASING'],
  },
  
  BODY_PENDULATION: {
    id: 'body_pendulation',
    name: 'Body Pendulation',
    category: 'somatic',
    complexity: 'medium',
    modality: ['kinesthetic', 'temporal'],
    outcome: ['release', 'integration'],
    description: 'Sway between sensations - build capacity',
    interactionType: 'rhythmic-sway',
    duration: 'medium',
    responseAffinity: ['FEELING', 'INTEGRATING'],
  },
  
  FIST_CLENCH_RELEASE: {
    id: 'fist_clench_release',
    name: 'Fist Clench Release',
    category: 'somatic',
    complexity: 'simple',
    modality: ['kinesthetic'],
    outcome: ['release', 'activation'],
    description: 'Squeeze tight - then let go',
    interactionType: 'grip-release',
    duration: 'instant',
    responseAffinity: ['RELEASING', 'FEELING'],
  },
  
  ORIENTATION_SCAN: {
    id: 'orientation_scan',
    name: 'Orientation Scan',
    category: 'somatic',
    complexity: 'simple',
    modality: ['visual', 'kinesthetic'],
    outcome: ['grounding', 'awareness'],
    description: 'Look around - orient to space',
    interactionType: 'visual-scan',
    duration: 'short',
    responseAffinity: ['WITNESSING', 'FEELING'],
  },
  
  SELF_HAVENING: {
    id: 'self_havening',
    name: 'Self-Havening',
    category: 'somatic',
    complexity: 'simple',
    modality: ['kinesthetic'],
    outcome: ['grounding', 'release'],
    description: 'Stroke arms - soothe yourself',
    interactionType: 'self-touch',
    duration: 'short',
    responseAffinity: ['FEELING', 'GROUNDING'],
  },
  
  BUTTERFLY_HUG: {
    id: 'butterfly_hug',
    name: 'Butterfly Hug',
    category: 'somatic',
    complexity: 'simple',
    modality: ['kinesthetic'],
    outcome: ['grounding', 'release'],
    description: 'Cross arms, tap alternating - EMDR',
    interactionType: 'bilateral-tapping',
    duration: 'short',
    responseAffinity: ['FEELING', 'GROUNDING'],
  },
  
  TRAUMA_TITRATION: {
    id: 'trauma_titration',
    name: 'Trauma Titration',
    category: 'somatic',
    complexity: 'complex',
    modality: ['kinesthetic', 'temporal'],
    outcome: ['release', 'integration'],
    description: 'Touch edge - pendulate to safety',
    interactionType: 'titrated-exposure',
    duration: 'long',
    responseAffinity: ['FEELING', 'INTEGRATING'],
  },
  
  NEUROCEPTION_CHECK: {
    id: 'neuroception_check',
    name: 'Neuroception Check',
    category: 'somatic',
    complexity: 'simple',
    modality: ['kinesthetic'],
    outcome: ['awareness'],
    description: 'Safe, danger, or shut down?',
    interactionType: 'state-identification',
    duration: 'instant',
    responseAffinity: ['WITNESSING', 'KNOWING'],
  },
  
  HANDS_ON_HEART: {
    id: 'hands_on_heart',
    name: 'Hands on Heart',
    category: 'somatic',
    complexity: 'simple',
    modality: ['kinesthetic'],
    outcome: ['grounding', 'awareness'],
    description: 'Self-compassion gesture - hold heart',
    interactionType: 'compassionate-touch',
    duration: 'short',
    responseAffinity: ['FEELING', 'BELIEVING'],
  },
  
  TENSION_SPEAK: {
    id: 'tension_speak',
    name: 'Tension Speak',
    category: 'somatic',
    complexity: 'medium',
    modality: ['kinesthetic'],
    outcome: ['awareness', 'release'],
    description: 'If tension could talk, what would it say?',
    interactionType: 'body-dialogue',
    duration: 'medium',
    responseAffinity: ['FEELING', 'KNOWING'],
  },
  
  SAFE_TOUCH_CATALOG: {
    id: 'safe_touch_catalog',
    name: 'Safe Touch Catalog',
    category: 'somatic',
    complexity: 'medium',
    modality: ['kinesthetic'],
    outcome: ['grounding', 'awareness'],
    description: 'Catalog touches that soothe',
    interactionType: 'touch-inventory',
    duration: 'medium',
    responseAffinity: ['FEELING', 'KNOWING'],
  },
  
  RESOURCE_ANCHOR: {
    id: 'resource_anchor',
    name: 'Resource Anchor',
    category: 'somatic',
    complexity: 'medium',
    modality: ['kinesthetic'],
    outcome: ['grounding', 'activation'],
    description: 'Anchor resourced state - touch point',
    interactionType: 'anchor-setting',
    duration: 'short',
    responseAffinity: ['FEELING', 'BELIEVING'],
  },
  
  MICROMOVEMENT_FREEDOM: {
    id: 'micromovement_freedom',
    name: 'Micromovement Freedom',
    category: 'somatic',
    complexity: 'simple',
    modality: ['kinesthetic'],
    outcome: ['release', 'awareness'],
    description: 'Tiny movements - what wants to move?',
    interactionType: 'micro-gesture',
    duration: 'short',
    responseAffinity: ['FEELING', 'WITNESSING'],
  },
  
  // Continue with Temporal (35), Emotional (50), Relational (35), Cognitive (40), Energetic (30), Ritual (20)...
  // [Due to length, I'll create a separate file with the remaining 175 mechanisms]
  
};

export default MECHANISMS_300;
