/**
 * THE 300 MECHANISMS (Part 3 - FINAL)
 * Relational, Cognitive, Energetic, Ritual
 * 
 * Completing the trinity: Science × Spirituality × Apple
 * Ram Dass × Alan Watts × Steve Jobs × Neuroscience × Master Therapists
 */

import type { Mechanism } from './experience-genome';

export const MECHANISMS_300_PART3: Record<string, Mechanism> = {
  
  // ═══════════════════════════════════════════════════════════════════════════
  // RELATIONAL MECHANISMS (35)
  // Connection: Attachment theory × Interdependence × Gesture intimacy
  // ═══════════════════════════════════════════════════════════════════════════
  
  ENERGY_EXCHANGE: {
    id: 'energy_exchange',
    name: 'Energy Exchange',
    category: 'relational',
    complexity: 'medium',
    modality: ['visual', 'kinesthetic'],
    outcome: ['awareness', 'decision'],
    description: 'Give/receive - are you balanced?',
    interactionType: 'balance-slider',
    duration: 'short',
    responseAffinity: ['KNOWING', 'CHOOSING'],
  },
  
  CONNECTION_WEB: {
    id: 'connection_web',
    name: 'Connection Web',
    category: 'relational',
    complexity: 'complex',
    modality: ['visual', 'kinesthetic'],
    outcome: ['awareness', 'integration'],
    description: 'Map your web - who holds you?',
    interactionType: 'node-linking',
    duration: 'long',
    responseAffinity: ['KNOWING', 'INTEGRATING'],
  },
  
  MIRROR_CONVERSATION: {
    id: 'mirror_conversation',
    name: 'Mirror Conversation',
    category: 'relational',
    complexity: 'complex',
    modality: ['visual'],
    outcome: ['awareness', 'integration'],
    description: 'Talk to self as other',
    interactionType: 'text-dialogue',
    duration: 'long',
    responseAffinity: ['WITNESSING', 'INTEGRATING'],
  },
  
  ATTACHMENT_STYLE: {
    id: 'attachment_style',
    name: 'Attachment Style',
    category: 'relational',
    complexity: 'medium',
    modality: ['visual'],
    outcome: ['awareness'],
    description: 'Your attachment - name it',
    interactionType: 'style-select',
    duration: 'short',
    responseAffinity: ['KNOWING', 'WITNESSING'],
  },
  
  NEEDS_INVENTORY: {
    id: 'needs_inventory',
    name: 'Needs Inventory',
    category: 'relational',
    complexity: 'medium',
    modality: ['visual', 'kinesthetic'],
    outcome: ['awareness', 'decision'],
    description: 'What do you need right now?',
    interactionType: 'multi-select',
    duration: 'short',
    responseAffinity: ['KNOWING', 'CHOOSING'],
  },
  
  BOUNDARY_RING: {
    id: 'boundary_ring',
    name: 'Boundary Ring',
    category: 'relational',
    complexity: 'medium',
    modality: ['visual', 'kinesthetic'],
    outcome: ['decision', 'grounding'],
    description: 'Draw the ring - this far, no further',
    interactionType: 'circular-boundary',
    duration: 'short',
    responseAffinity: ['CHOOSING', 'BELIEVING'],
  },
  
  EMPATHY_BRIDGE: {
    id: 'empathy_bridge',
    name: 'Empathy Bridge',
    category: 'relational',
    complexity: 'medium',
    modality: ['visual'],
    outcome: ['awareness', 'integration'],
    description: 'Build bridge to their world',
    interactionType: 'bridge-build',
    duration: 'medium',
    responseAffinity: ['FEELING', 'INTEGRATING'],
  },
  
  PROJECTION_SCREEN: {
    id: 'projection_screen',
    name: 'Projection Screen',
    category: 'relational',
    complexity: 'complex',
    modality: ['visual'],
    outcome: ['awareness'],
    description: 'What are you projecting on them?',
    interactionType: 'reflection-select',
    duration: 'medium',
    responseAffinity: ['WITNESSING', 'KNOWING'],
  },
  
  CODEPENDENCE_SCALE: {
    id: 'codependence_scale',
    name: 'Codependence Scale',
    category: 'relational',
    complexity: 'simple',
    modality: ['visual'],
    outcome: ['awareness'],
    description: 'Where\'s the enmeshment?',
    interactionType: 'scale-slider',
    duration: 'instant',
    responseAffinity: ['KNOWING', 'WITNESSING'],
  },
  
  REPAIR_RITUAL: {
    id: 'repair_ritual',
    name: 'Repair Ritual',
    category: 'relational',
    complexity: 'complex',
    modality: ['visual', 'kinesthetic'],
    outcome: ['integration', 'release'],
    description: 'Rupture happens - repair it',
    interactionType: 'ritual-steps',
    duration: 'long',
    responseAffinity: ['INTEGRATING', 'RELEASING'],
  },
  
  DIFFERENTIATION_MARKER: {
    id: 'differentiation_marker',
    name: 'Differentiation Marker',
    category: 'relational',
    complexity: 'simple',
    modality: ['visual'],
    outcome: ['awareness', 'grounding'],
    description: 'You are you, they are them',
    interactionType: 'separation-visual',
    duration: 'instant',
    responseAffinity: ['KNOWING', 'BELIEVING'],
  },
  
  LISTENING_DEPTH: {
    id: 'listening_depth',
    name: 'Listening Depth',
    category: 'relational',
    complexity: 'simple',
    modality: ['visual'],
    outcome: ['awareness'],
    description: 'How deeply are you listening?',
    interactionType: 'depth-meter',
    duration: 'instant',
    responseAffinity: ['WITNESSING', 'FEELING'],
  },
  
  BID_COUNTER: {
    id: 'bid_counter',
    name: 'Bid Counter',
    category: 'relational',
    complexity: 'simple',
    modality: ['visual'],
    outcome: ['awareness'],
    description: 'Track bids for connection',
    interactionType: 'bid-tally',
    duration: 'short',
    responseAffinity: ['KNOWING', 'WITNESSING'],
  },
  
  TURN_TOWARD: {
    id: 'turn_toward',
    name: 'Turn Toward',
    category: 'relational',
    complexity: 'simple',
    modality: ['kinesthetic'],
    outcome: ['activation', 'decision'],
    description: 'Choose to turn toward',
    interactionType: 'directional-choice',
    duration: 'instant',
    responseAffinity: ['CHOOSING', 'FEELING'],
  },
  
  STONEWALLING_NOTICE: {
    id: 'stonewalling_notice',
    name: 'Stonewalling Notice',
    category: 'relational',
    complexity: 'simple',
    modality: ['visual'],
    outcome: ['awareness'],
    description: 'Notice the wall going up',
    interactionType: 'pattern-alert',
    duration: 'instant',
    responseAffinity: ['WITNESSING', 'KNOWING'],
  },
  
  CONFLICT_STYLE: {
    id: 'conflict_style',
    name: 'Conflict Style',
    category: 'relational',
    complexity: 'medium',
    modality: ['visual'],
    outcome: ['awareness'],
    description: 'How do you handle conflict?',
    interactionType: 'style-identify',
    duration: 'short',
    responseAffinity: ['KNOWING', 'WITNESSING'],
  },
  
  RECIPROCITY_CHECK: {
    id: 'reciprocity_check',
    name: 'Reciprocity Check',
    category: 'relational',
    complexity: 'simple',
    modality: ['visual'],
    outcome: ['awareness'],
    description: 'Is this reciprocal?',
    interactionType: 'balance-check',
    duration: 'instant',
    responseAffinity: ['KNOWING', 'FEELING'],
  },
  
  CONTEMPT_ANTIDOTE: {
    id: 'contempt_antidote',
    name: 'Contempt Antidote',
    category: 'relational',
    complexity: 'medium',
    modality: ['visual'],
    outcome: ['integration', 'release'],
    description: 'Find appreciation antidote',
    interactionType: 'reframe-shift',
    duration: 'medium',
    responseAffinity: ['FEELING', 'INTEGRATING'],
  },
  
  CO_REGULATION: {
    id: 'co_regulation',
    name: 'Co-Regulation',
    category: 'relational',
    complexity: 'medium',
    modality: ['visual', 'temporal'],
    outcome: ['grounding', 'awareness'],
    description: 'Sync nervous systems - breathe together',
    interactionType: 'sync-animation',
    duration: 'medium',
    responseAffinity: ['FEELING', 'WITNESSING'],
  },
  
  SECURE_BASE: {
    id: 'secure_base',
    name: 'Secure Base',
    category: 'relational',
    complexity: 'simple',
    modality: ['visual'],
    outcome: ['grounding', 'awareness'],
    description: 'Who is your secure base?',
    interactionType: 'person-identify',
    duration: 'short',
    responseAffinity: ['KNOWING', 'BELIEVING'],
  },
  
  RUPTURE_NOTICE: {
    id: 'rupture_notice',
    name: 'Rupture Notice',
    category: 'relational',
    complexity: 'simple',
    modality: ['visual'],
    outcome: ['awareness'],
    description: 'Notice disconnect - name it',
    interactionType: 'break-alert',
    duration: 'instant',
    responseAffinity: ['WITNESSING', 'KNOWING'],
  },
  
  ATTUNEMENT_CHECK: {
    id: 'attunement_check',
    name: 'Attunement Check',
    category: 'relational',
    complexity: 'simple',
    modality: ['visual'],
    outcome: ['awareness'],
    description: 'Are you attuned right now?',
    interactionType: 'alignment-meter',
    duration: 'instant',
    responseAffinity: ['WITNESSING', 'FEELING'],
  },
  
  REQUEST_NOT_DEMAND: {
    id: 'request_not_demand',
    name: 'Request Not Demand',
    category: 'relational',
    complexity: 'medium',
    modality: ['visual'],
    outcome: ['decision', 'awareness'],
    description: 'Reframe demand as request',
    interactionType: 'language-shift',
    duration: 'short',
    responseAffinity: ['CHOOSING', 'KNOWING'],
  },
  
  DEFENSIVENESS_DROP: {
    id: 'defensiveness_drop',
    name: 'Defensiveness Drop',
    category: 'relational',
    complexity: 'medium',
    modality: ['kinesthetic'],
    outcome: ['release', 'awareness'],
    description: 'Notice defense - drop armor',
    interactionType: 'somatic-release',
    duration: 'short',
    responseAffinity: ['FEELING', 'CHOOSING'],
  },
  
  CRITICISM_SOFTEN: {
    id: 'criticism_soften',
    name: 'Criticism Soften',
    category: 'relational',
    complexity: 'medium',
    modality: ['visual'],
    outcome: ['integration', 'decision'],
    description: 'Turn criticism to gentle start-up',
    interactionType: 'language-reframe',
    duration: 'medium',
    responseAffinity: ['CHOOSING', 'FEELING'],
  },
  
  FLOODING_TIMEOUT: {
    id: 'flooding_timeout',
    name: 'Flooding Timeout',
    category: 'relational',
    complexity: 'simple',
    modality: ['temporal'],
    outcome: ['grounding', 'decision'],
    description: 'System flooded - take timeout',
    interactionType: 'pause-timer',
    duration: 'medium',
    responseAffinity: ['CHOOSING', 'FEELING'],
  },
  
  LOVE_MAP_UPDATE: {
    id: 'love_map_update',
    name: 'Love Map Update',
    category: 'relational',
    complexity: 'medium',
    modality: ['visual'],
    outcome: ['awareness', 'integration'],
    description: 'Update your knowing of them',
    interactionType: 'knowledge-catalog',
    duration: 'medium',
    responseAffinity: ['KNOWING', 'INTEGRATING'],
  },
  
  FONDNESS_ADMIRATION: {
    id: 'fondness_admiration',
    name: 'Fondness & Admiration',
    category: 'relational',
    complexity: 'simple',
    modality: ['visual'],
    outcome: ['integration', 'grounding'],
    description: 'Recall what you admire',
    interactionType: 'appreciation-focus',
    duration: 'short',
    responseAffinity: ['FEELING', 'INTEGRATING'],
  },
  
  LONGING_NAME: {
    id: 'longing_name',
    name: 'Longing Name',
    category: 'relational',
    complexity: 'simple',
    modality: ['visual'],
    outcome: ['awareness'],
    description: 'What do you long for from them?',
    interactionType: 'desire-name',
    duration: 'short',
    responseAffinity: ['KNOWING', 'FEELING'],
  },
  
  PARALLEL_PRESENCE: {
    id: 'parallel_presence',
    name: 'Parallel Presence',
    category: 'relational',
    complexity: 'simple',
    modality: ['visual'],
    outcome: ['grounding', 'awareness'],
    description: 'Together but separate - both ok',
    interactionType: 'side-by-side-visual',
    duration: 'short',
    responseAffinity: ['WITNESSING', 'BELIEVING'],
  },
  
  VULNERABILITY_OFFER: {
    id: 'vulnerability_offer',
    name: 'Vulnerability Offer',
    category: 'relational',
    complexity: 'complex',
    modality: ['kinesthetic'],
    outcome: ['activation', 'integration'],
    description: 'Risk being seen - offer truth',
    interactionType: 'courage-action',
    duration: 'medium',
    responseAffinity: ['CHOOSING', 'INTEGRATING'],
  },
  
  HOLDING_SPACE: {
    id: 'holding_space',
    name: 'Holding Space',
    category: 'relational',
    complexity: 'simple',
    modality: ['visual', 'temporal'],
    outcome: ['grounding', 'awareness'],
    description: 'Just hold - don\'t fix',
    interactionType: 'presence-hold',
    duration: 'medium',
    responseAffinity: ['WITNESSING', 'FEELING'],
  },
  
  SOCIAL_ENGAGEMENT: {
    id: 'social_engagement',
    name: 'Social Engagement',
    category: 'relational',
    complexity: 'simple',
    modality: ['visual'],
    outcome: ['awareness', 'activation'],
    description: 'Ventral vagal - safe to connect',
    interactionType: 'safety-signal',
    duration: 'instant',
    responseAffinity: ['FEELING', 'CHOOSING'],
  },
  
  RELATIONAL_NEEDS: {
    id: 'relational_needs',
    name: 'Relational Needs',
    category: 'relational',
    complexity: 'medium',
    modality: ['visual'],
    outcome: ['awareness', 'decision'],
    description: 'Name needs without shame',
    interactionType: 'needs-catalog',
    duration: 'medium',
    responseAffinity: ['KNOWING', 'CHOOSING'],
  },
  
  REUNION_REPAIR: {
    id: 'reunion_repair',
    name: 'Reunion Repair',
    category: 'relational',
    complexity: 'medium',
    modality: ['visual', 'temporal'],
    outcome: ['integration', 'grounding'],
    description: 'Repair after separation',
    interactionType: 'reconnection-ritual',
    duration: 'medium',
    responseAffinity: ['INTEGRATING', 'FEELING'],
  },
  
  POWER_DYNAMIC_MAP: {
    id: 'power_dynamic_map',
    name: 'Power Dynamic Map',
    category: 'relational',
    complexity: 'complex',
    modality: ['visual'],
    outcome: ['awareness', 'integration'],
    description: 'Map power in relationship',
    interactionType: 'dynamic-visualization',
    duration: 'long',
    responseAffinity: ['KNOWING', 'INTEGRATING'],
  },
  
  // ═══════════════════════════════════════════════════════════════════════════
  // COGNITIVE MECHANISMS (40)
  // Mind: CBT/ACT precision × Zen paradox × Intuitive interface
  // ═══════════════════════════════════════════════════════════════════════════
  
  WISDOM_WELL: {
    id: 'wisdom_well',
    name: 'Wisdom Well',
    category: 'cognitive',
    complexity: 'medium',
    modality: ['visual', 'kinesthetic'],
    outcome: ['awareness', 'integration'],
    description: 'Draw from inner knowing',
    interactionType: 'tap-to-reveal',
    duration: 'short',
    responseAffinity: ['KNOWING', 'BELIEVING'],
  },
  
  NARRATIVE_THREAD: {
    id: 'narrative_thread',
    name: 'Narrative Thread',
    category: 'cognitive',
    complexity: 'complex',
    modality: ['visual'],
    outcome: ['integration', 'awareness'],
    description: 'Connect story threads',
    interactionType: 'thread-weaving',
    duration: 'long',
    responseAffinity: ['INTEGRATING', 'KNOWING'],
  },
  
  BELIEF_BUBBLE: {
    id: 'belief_bubble',
    name: 'Belief Bubble',
    category: 'cognitive',
    complexity: 'simple',
    modality: ['visual', 'kinesthetic'],
    outcome: ['awareness', 'release'],
    description: 'Pop limiting belief - watch it dissolve',
    interactionType: 'tap-to-pop',
    duration: 'instant',
    responseAffinity: ['KNOWING', 'RELEASING'],
  },
  
  VALUE_STACK: {
    id: 'value_stack',
    name: 'Value Stack',
    category: 'cognitive',
    complexity: 'medium',
    modality: ['visual', 'kinesthetic'],
    outcome: ['decision', 'awareness'],
    description: 'Order values - what matters most?',
    interactionType: 'drag-to-order',
    duration: 'medium',
    responseAffinity: ['CHOOSING', 'KNOWING'],
  },
  
  ASSUMPTION_FILTER: {
    id: 'assumption_filter',
    name: 'Assumption Filter',
    category: 'cognitive',
    complexity: 'medium',
    modality: ['visual'],
    outcome: ['awareness'],
    description: 'Reveal hidden assumptions',
    interactionType: 'reveal-filter',
    duration: 'short',
    responseAffinity: ['KNOWING', 'WITNESSING'],
  },
  
  PERSPECTIVE_SHIFT: {
    id: 'perspective_shift',
    name: 'Perspective Shift',
    category: 'cognitive',
    complexity: 'medium',
    modality: ['visual', 'kinesthetic'],
    outcome: ['awareness', 'integration'],
    description: 'Rotate viewpoint - see new angle',
    interactionType: 'rotate-view',
    duration: 'short',
    responseAffinity: ['KNOWING', 'INTEGRATING'],
  },
  
  REFRAME_LENS: {
    id: 'reframe_lens',
    name: 'Reframe Lens',
    category: 'cognitive',
    complexity: 'medium',
    modality: ['visual'],
    outcome: ['awareness', 'integration'],
    description: 'Apply new lens - shift meaning',
    interactionType: 'lens-select',
    duration: 'short',
    responseAffinity: ['KNOWING', 'INTEGRATING'],
  },
  
  THOUGHT_SORTING: {
    id: 'thought_sorting',
    name: 'Thought Sorting',
    category: 'cognitive',
    complexity: 'medium',
    modality: ['kinesthetic'],
    outcome: ['awareness', 'decision'],
    description: 'Sort thoughts - helpful vs unhelpful',
    interactionType: 'swipe-to-sort',
    duration: 'medium',
    responseAffinity: ['KNOWING', 'CHOOSING'],
  },
  
  MEANING_MAKER: {
    id: 'meaning_maker',
    name: 'Meaning Maker',
    category: 'cognitive',
    complexity: 'complex',
    modality: ['visual'],
    outcome: ['integration'],
    description: 'What does this mean to you?',
    interactionType: 'text-synthesis',
    duration: 'long',
    responseAffinity: ['INTEGRATING', 'KNOWING'],
  },
  
  COGNITIVE_TRIANGLE: {
    id: 'cognitive_triangle',
    name: 'Cognitive Triangle',
    category: 'cognitive',
    complexity: 'complex',
    modality: ['visual', 'kinesthetic'],
    outcome: ['awareness', 'integration'],
    description: 'Thought → Feeling → Behavior loop',
    interactionType: 'triangle-plot',
    duration: 'medium',
    responseAffinity: ['KNOWING', 'INTEGRATING'],
  },
  
  DEFUSION_DISTANCE: {
    id: 'defusion_distance',
    name: 'Defusion Distance',
    category: 'cognitive',
    complexity: 'medium',
    modality: ['visual', 'kinesthetic'],
    outcome: ['awareness', 'release'],
    description: 'You are not your thoughts - create space',
    interactionType: 'thought-separate',
    duration: 'short',
    responseAffinity: ['KNOWING', 'RELEASING'],
  },
  
  CORE_BELIEF_MAP: {
    id: 'core_belief_map',
    name: 'Core Belief Map',
    category: 'cognitive',
    complexity: 'complex',
    modality: ['visual'],
    outcome: ['awareness', 'integration'],
    description: 'Map the core - what\'s underneath?',
    interactionType: 'layered-reveal',
    duration: 'long',
    responseAffinity: ['KNOWING', 'INTEGRATING'],
  },
  
  EVIDENCE_COLLECTOR: {
    id: 'evidence_collector',
    name: 'Evidence Collector',
    category: 'cognitive',
    complexity: 'medium',
    modality: ['visual'],
    outcome: ['awareness', 'integration'],
    description: 'Gather evidence - for and against',
    interactionType: 'evidence-catalog',
    duration: 'medium',
    responseAffinity: ['KNOWING', 'INTEGRATING'],
  },
  
  MENTAL_FILTER_NOTICE: {
    id: 'mental_filter_notice',
    name: 'Mental Filter Notice',
    category: 'cognitive',
    complexity: 'simple',
    modality: ['visual'],
    outcome: ['awareness'],
    description: 'Notice distortion - name it',
    interactionType: 'distortion-label',
    duration: 'instant',
    responseAffinity: ['KNOWING', 'WITNESSING'],
  },
  
  ALL_OR_NOTHING_SPECTRUM: {
    id: 'all_or_nothing_spectrum',
    name: 'All-or-Nothing Spectrum',
    category: 'cognitive',
    complexity: 'simple',
    modality: ['visual'],
    outcome: ['awareness', 'integration'],
    description: 'Find the grey between black/white',
    interactionType: 'spectrum-place',
    duration: 'instant',
    responseAffinity: ['KNOWING', 'INTEGRATING'],
  },
  
  CATASTROPHE_SCALE: {
    id: 'catastrophe_scale',
    name: 'Catastrophe Scale',
    category: 'cognitive',
    complexity: 'simple',
    modality: ['visual'],
    outcome: ['awareness', 'grounding'],
    description: 'Scale the catastrophe - 0-10',
    interactionType: 'reality-scale',
    duration: 'instant',
    responseAffinity: ['KNOWING', 'FEELING'],
  },
  
  SHOULD_STATEMENT_REWRITE: {
    id: 'should_statement_rewrite',
    name: 'Should Statement Rewrite',
    category: 'cognitive',
    complexity: 'simple',
    modality: ['visual'],
    outcome: ['awareness', 'release'],
    description: 'Replace "should" with "could"',
    interactionType: 'language-replace',
    duration: 'instant',
    responseAffinity: ['KNOWING', 'RELEASING'],
  },
  
  MENTAL_TIME_TRAVEL: {
    id: 'mental_time_travel',
    name: 'Mental Time Travel',
    category: 'cognitive',
    complexity: 'medium',
    modality: ['visual'],
    outcome: ['awareness', 'integration'],
    description: 'Visit past/future - return to now',
    interactionType: 'timeline-journey',
    duration: 'medium',
    responseAffinity: ['KNOWING', 'INTEGRATING'],
  },
  
  THOUGHT_RECORD: {
    id: 'thought_record',
    name: 'Thought Record',
    category: 'cognitive',
    complexity: 'complex',
    modality: ['visual'],
    outcome: ['awareness', 'integration'],
    description: 'CBT classic - record and examine',
    interactionType: 'structured-entry',
    duration: 'long',
    responseAffinity: ['KNOWING', 'INTEGRATING'],
  },
  
  MIND_READING_CHECK: {
    id: 'mind_reading_check',
    name: 'Mind Reading Check',
    category: 'cognitive',
    complexity: 'simple',
    modality: ['visual'],
    outcome: ['awareness'],
    description: 'Are you assuming you know?',
    interactionType: 'assumption-alert',
    duration: 'instant',
    responseAffinity: ['KNOWING', 'WITNESSING'],
  },
  
  FORTUNE_TELLING_PAUSE: {
    id: 'fortune_telling_pause',
    name: 'Fortune Telling Pause',
    category: 'cognitive',
    complexity: 'simple',
    modality: ['visual'],
    outcome: ['awareness', 'grounding'],
    description: 'You don\'t know the future',
    interactionType: 'prediction-check',
    duration: 'instant',
    responseAffinity: ['KNOWING', 'WITNESSING'],
  },
  
  PERSONALIZATION_DEPERSONALIZE: {
    id: 'personalization_depersonalize',
    name: 'Personalization Depersonalize',
    category: 'cognitive',
    complexity: 'simple',
    modality: ['visual'],
    outcome: ['awareness', 'release'],
    description: 'It\'s not all about you',
    interactionType: 'perspective-widen',
    duration: 'short',
    responseAffinity: ['KNOWING', 'RELEASING'],
  },
  
  MAGNIFICATION_MINIMIZE: {
    id: 'magnification_minimize',
    name: 'Magnification/Minimize',
    category: 'cognitive',
    complexity: 'simple',
    modality: ['visual'],
    outcome: ['awareness', 'grounding'],
    description: 'Right-size the problem',
    interactionType: 'scale-adjust',
    duration: 'short',
    responseAffinity: ['KNOWING', 'FEELING'],
  },
  
  LABELING_UNLABEL: {
    id: 'labeling_unlabel',
    name: 'Labeling Unlabel',
    category: 'cognitive',
    complexity: 'simple',
    modality: ['visual'],
    outcome: ['awareness', 'release'],
    description: 'Remove the label - see complexity',
    interactionType: 'label-remove',
    duration: 'short',
    responseAffinity: ['KNOWING', 'INTEGRATING'],
  },
  
  EMOTIONAL_REASONING: {
    id: 'emotional_reasoning',
    name: 'Emotional Reasoning',
    category: 'cognitive',
    complexity: 'simple',
    modality: ['visual'],
    outcome: ['awareness'],
    description: 'Feeling ≠ fact',
    interactionType: 'distinction-highlight',
    duration: 'instant',
    responseAffinity: ['KNOWING', 'WITNESSING'],
  },
  
  RULE_FLEXIBILITY: {
    id: 'rule_flexibility',
    name: 'Rule Flexibility',
    category: 'cognitive',
    complexity: 'medium',
    modality: ['visual'],
    outcome: ['awareness', 'integration'],
    description: 'Loosen rigid rules',
    interactionType: 'rule-soften',
    duration: 'medium',
    responseAffinity: ['KNOWING', 'INTEGRATING'],
  },
  
  HELPFUL_VS_TRUE: {
    id: 'helpful_vs_true',
    name: 'Helpful vs True',
    category: 'cognitive',
    complexity: 'simple',
    modality: ['visual'],
    outcome: ['awareness', 'decision'],
    description: 'Is this thought helpful?',
    interactionType: 'utility-check',
    duration: 'instant',
    responseAffinity: ['KNOWING', 'CHOOSING'],
  },
  
  OBSERVER_SELF: {
    id: 'observer_self',
    name: 'Observer Self',
    category: 'cognitive',
    complexity: 'medium',
    modality: ['visual'],
    outcome: ['awareness', 'integration'],
    description: 'The you watching you',
    interactionType: 'meta-awareness',
    duration: 'medium',
    responseAffinity: ['WITNESSING', 'INTEGRATING'],
  },
  
  VALUES_COMPASS: {
    id: 'values_compass',
    name: 'Values Compass',
    category: 'cognitive',
    complexity: 'medium',
    modality: ['visual', 'kinesthetic'],
    outcome: ['awareness', 'decision'],
    description: 'Align action to values',
    interactionType: 'values-align',
    duration: 'medium',
    responseAffinity: ['CHOOSING', 'KNOWING'],
  },
  
  WILLINGNESS_METER: {
    id: 'willingness_meter',
    name: 'Willingness Meter',
    category: 'cognitive',
    complexity: 'simple',
    modality: ['visual'],
    outcome: ['awareness', 'decision'],
    description: 'How willing are you? Measure',
    interactionType: 'willingness-slider',
    duration: 'instant',
    responseAffinity: ['CHOOSING', 'FEELING'],
  },
  
  COMMITTED_ACTION: {
    id: 'committed_action',
    name: 'Committed Action',
    category: 'cognitive',
    complexity: 'medium',
    modality: ['visual'],
    outcome: ['decision', 'activation'],
    description: 'Small action aligned to values',
    interactionType: 'action-commit',
    duration: 'short',
    responseAffinity: ['CHOOSING', 'BECOMING'],
  },
  
  ACCEPTANCE_MOVE: {
    id: 'acceptance_move',
    name: 'Acceptance Move',
    category: 'cognitive',
    complexity: 'medium',
    modality: ['visual'],
    outcome: ['integration', 'activation'],
    description: 'Accept what is, move anyway',
    interactionType: 'paradox-hold',
    duration: 'medium',
    responseAffinity: ['INTEGRATING', 'CHOOSING'],
  },
  
  CREATIVE_HOPELESSNESS: {
    id: 'creative_hopelessness',
    name: 'Creative Hopelessness',
    category: 'cognitive',
    complexity: 'complex',
    modality: ['visual'],
    outcome: ['awareness', 'integration'],
    description: 'What you\'ve tried hasn\'t worked',
    interactionType: 'pattern-acknowledge',
    duration: 'long',
    responseAffinity: ['KNOWING', 'INTEGRATING'],
  },
  
  EXPANSION_PRACTICE: {
    id: 'expansion_practice',
    name: 'Expansion Practice',
    category: 'cognitive',
    complexity: 'medium',
    modality: ['visual', 'kinesthetic'],
    outcome: ['grounding', 'integration'],
    description: 'Make room for discomfort',
    interactionType: 'space-expand',
    duration: 'medium',
    responseAffinity: ['FEELING', 'INTEGRATING'],
  },
  
  SELF_AS_CONTEXT: {
    id: 'self_as_context',
    name: 'Self as Context',
    category: 'cognitive',
    complexity: 'complex',
    modality: ['visual'],
    outcome: ['awareness', 'integration'],
    description: 'You are the space, not the content',
    interactionType: 'perspective-shift',
    duration: 'long',
    responseAffinity: ['WITNESSING', 'INTEGRATING'],
  },
  
  THOUGHT_BUS: {
    id: 'thought_bus',
    name: 'Thought Bus',
    category: 'cognitive',
    complexity: 'simple',
    modality: ['visual'],
    outcome: ['awareness', 'release'],
    description: 'Thoughts are passengers - let them ride',
    interactionType: 'metaphor-visual',
    duration: 'short',
    responseAffinity: ['KNOWING', 'RELEASING'],
  },
  
  LEAVES_ON_STREAM: {
    id: 'leaves_on_stream',
    name: 'Leaves on Stream',
    category: 'cognitive',
    complexity: 'simple',
    modality: ['visual', 'temporal'],
    outcome: ['awareness', 'release'],
    description: 'Watch thoughts float by',
    interactionType: 'flowing-animation',
    duration: 'medium',
    responseAffinity: ['WITNESSING', 'RELEASING'],
  },
  
  STRUGGLE_SWITCH: {
    id: 'struggle_switch',
    name: 'Struggle Switch',
    category: 'cognitive',
    complexity: 'simple',
    modality: ['visual'],
    outcome: ['awareness', 'decision'],
    description: 'Notice struggle - flip switch',
    interactionType: 'toggle-switch',
    duration: 'instant',
    responseAffinity: ['CHOOSING', 'KNOWING'],
  },
  
  WORKABILITY_CHECK: {
    id: 'workability_check',
    name: 'Workability Check',
    category: 'cognitive',
    complexity: 'simple',
    modality: ['visual'],
    outcome: ['awareness', 'decision'],
    description: 'Is this working for you?',
    interactionType: 'outcome-assess',
    duration: 'instant',
    responseAffinity: ['KNOWING', 'CHOOSING'],
  },
  
  KOAN_CONTEMPLATION: {
    id: 'koan_contemplation',
    name: 'Koan Contemplation',
    category: 'cognitive',
    complexity: 'complex',
    modality: ['visual'],
    outcome: ['awareness', 'integration'],
    description: 'Sit with paradox - don\'t solve',
    interactionType: 'meditation-hold',
    duration: 'long',
    responseAffinity: ['WITNESSING', 'INTEGRATING'],
  },
  
  // ═══════════════════════════════════════════════════════════════════════════
  // ENERGETIC MECHANISMS (30)
  // Energy: Vitality tracking × Subtle body wisdom × Flow state design
  // ═══════════════════════════════════════════════════════════════════════════
  
  ENERGY_PIES: {
    id: 'energy_pies',
    name: 'Energy Pies',
    category: 'energetic',
    complexity: 'medium',
    modality: ['visual', 'kinesthetic'],
    outcome: ['awareness', 'decision'],
    description: 'Allocate energy - visualize spend',
    interactionType: 'pie-chart-adjust',
    duration: 'short',
    responseAffinity: ['KNOWING', 'CHOOSING'],
  },
  
  VITALITY_GAUGE: {
    id: 'vitality_gauge',
    name: 'Vitality Gauge',
    category: 'energetic',
    complexity: 'simple',
    modality: ['visual'],
    outcome: ['awareness'],
    description: 'Measure life force - how full?',
    interactionType: 'gauge-tap',
    duration: 'instant',
    responseAffinity: ['WITNESSING', 'FEELING'],
  },
  
  CHARGE_BATTERY: {
    id: 'charge_battery',
    name: 'Charge Battery',
    category: 'energetic',
    complexity: 'simple',
    modality: ['visual', 'temporal'],
    outcome: ['grounding', 'activation'],
    description: 'Recharge - hold to fill',
    interactionType: 'hold-to-charge',
    duration: 'short',
    responseAffinity: ['FEELING', 'CHOOSING'],
  },
  
  CHAKRA_SCAN: {
    id: 'chakra_scan',
    name: 'Chakra Scan',
    category: 'energetic',
    complexity: 'medium',
    modality: ['visual', 'kinesthetic'],
    outcome: ['awareness'],
    description: 'Scan energy centers - notice blocks',
    interactionType: 'body-tap-sequence',
    duration: 'medium',
    responseAffinity: ['FEELING', 'WITNESSING'],
  },
  
  DRAIN_DETECTOR: {
    id: 'drain_detector',
    name: 'Drain Detector',
    category: 'energetic',
    complexity: 'medium',
    modality: ['visual'],
    outcome: ['awareness'],
    description: 'What drains you? Identify',
    interactionType: 'multi-select',
    duration: 'short',
    responseAffinity: ['KNOWING', 'WITNESSING'],
  },
  
  RESTORATION_RITUAL: {
    id: 'restoration_ritual',
    name: 'Restoration Ritual',
    category: 'energetic',
    complexity: 'complex',
    modality: ['visual', 'temporal'],
    outcome: ['grounding', 'integration'],
    description: 'Multi-step energy restoration',
    interactionType: 'ritual-sequence',
    duration: 'long',
    responseAffinity: ['FEELING', 'INTEGRATING'],
  },
  
  FLOW_STATE_DIAL: {
    id: 'flow_state_dial',
    name: 'Flow State Dial',
    category: 'energetic',
    complexity: 'simple',
    modality: ['visual'],
    outcome: ['awareness', 'activation'],
    description: 'Tune into flow frequency',
    interactionType: 'dial-adjust',
    duration: 'instant',
    responseAffinity: ['FEELING', 'CHOOSING'],
  },
  
  AURA_EXPANSION: {
    id: 'aura_expansion',
    name: 'Aura Expansion',
    category: 'energetic',
    complexity: 'medium',
    modality: ['visual', 'kinesthetic'],
    outcome: ['grounding', 'activation'],
    description: 'Expand your field',
    interactionType: 'pinch-to-expand',
    duration: 'short',
    responseAffinity: ['FEELING', 'BELIEVING'],
  },
  
  VIBRATION_TUNER: {
    id: 'vibration_tuner',
    name: 'Vibration Tuner',
    category: 'energetic',
    complexity: 'simple',
    modality: ['visual', 'auditory'],
    outcome: ['grounding'],
    description: 'Tune frequency - raise vibration',
    interactionType: 'frequency-slider',
    duration: 'short',
    responseAffinity: ['FEELING', 'CHOOSING'],
  },
  
  PROTECTION_SHIELD: {
    id: 'protection_shield',
    name: 'Protection Shield',
    category: 'energetic',
    complexity: 'simple',
    modality: ['visual', 'kinesthetic'],
    outcome: ['grounding', 'decision'],
    description: 'Activate shield - boundary up',
    interactionType: 'tap-to-shield',
    duration: 'instant',
    responseAffinity: ['BELIEVING', 'CHOOSING'],
  },
  
  CORD_CUTTING: {
    id: 'cord_cutting',
    name: 'Cord Cutting',
    category: 'energetic',
    complexity: 'medium',
    modality: ['visual', 'kinesthetic'],
    outcome: ['release', 'grounding'],
    description: 'Cut energetic cords - reclaim power',
    interactionType: 'gesture-cut',
    duration: 'medium',
    responseAffinity: ['RELEASING', 'BELIEVING'],
  },
  
  GROUNDING_CORD: {
    id: 'grounding_cord',
    name: 'Grounding Cord',
    category: 'energetic',
    complexity: 'simple',
    modality: ['visual'],
    outcome: ['grounding'],
    description: 'Drop cord to earth - release down',
    interactionType: 'downward-flow',
    duration: 'short',
    responseAffinity: ['FEELING', 'WITNESSING'],
  },
  
  LIGHT_COLUMN: {
    id: 'light_column',
    name: 'Light Column',
    category: 'energetic',
    complexity: 'medium',
    modality: ['visual', 'temporal'],
    outcome: ['activation', 'grounding'],
    description: 'Column of light - heaven to earth',
    interactionType: 'vertical-flow',
    duration: 'medium',
    responseAffinity: ['FEELING', 'BELIEVING'],
  },
  
  ENERGY_PULL_BACK: {
    id: 'energy_pull_back',
    name: 'Energy Pull Back',
    category: 'energetic',
    complexity: 'simple',
    modality: ['visual', 'kinesthetic'],
    outcome: ['grounding', 'awareness'],
    description: 'Call energy back to you',
    interactionType: 'gathering-gesture',
    duration: 'short',
    responseAffinity: ['FEELING', 'CHOOSING'],
  },
  
  PSYCHIC_HYGIENE: {
    id: 'psychic_hygiene',
    name: 'Psychic Hygiene',
    category: 'energetic',
    complexity: 'medium',
    modality: ['visual', 'temporal'],
    outcome: ['grounding', 'release'],
    description: 'Clear energy - daily practice',
    interactionType: 'cleansing-ritual',
    duration: 'medium',
    responseAffinity: ['FEELING', 'INTEGRATING'],
  },
  
  ELEMENTAL_BALANCE: {
    id: 'elemental_balance',
    name: 'Elemental Balance',
    category: 'energetic',
    complexity: 'medium',
    modality: ['visual'],
    outcome: ['awareness', 'integration'],
    description: 'Balance earth, water, fire, air',
    interactionType: 'four-element-adjust',
    duration: 'medium',
    responseAffinity: ['KNOWING', 'INTEGRATING'],
  },
  
  KI_CIRCULATION: {
    id: 'ki_circulation',
    name: 'Ki Circulation',
    category: 'energetic',
    complexity: 'medium',
    modality: ['visual', 'kinesthetic'],
    outcome: ['activation', 'grounding'],
    description: 'Circulate life force',
    interactionType: 'orbital-trace',
    duration: 'medium',
    responseAffinity: ['FEELING', 'WITNESSING'],
  },
  
  SOLAR_RECHARGE: {
    id: 'solar_recharge',
    name: 'Solar Recharge',
    category: 'energetic',
    complexity: 'simple',
    modality: ['visual', 'temporal'],
    outcome: ['activation', 'grounding'],
    description: 'Absorb sun energy',
    interactionType: 'light-absorption',
    duration: 'medium',
    responseAffinity: ['FEELING', 'BELIEVING'],
  },
  
  LUNAR_RELEASE: {
    id: 'lunar_release',
    name: 'Lunar Release',
    category: 'energetic',
    complexity: 'simple',
    modality: ['visual', 'temporal'],
    outcome: ['release', 'grounding'],
    description: 'Release to moon - let go',
    interactionType: 'moonlight-release',
    duration: 'medium',
    responseAffinity: ['RELEASING', 'BELIEVING'],
  },
  
  CRYSTALLINE_GRID: {
    id: 'crystalline_grid',
    name: 'Crystalline Grid',
    category: 'energetic',
    complexity: 'complex',
    modality: ['visual', 'kinesthetic'],
    outcome: ['grounding', 'integration'],
    description: 'Build energy grid',
    interactionType: 'pattern-placement',
    duration: 'long',
    responseAffinity: ['INTEGRATING', 'BELIEVING'],
  },
  
  MERKABA_ACTIVATION: {
    id: 'merkaba_activation',
    name: 'Merkaba Activation',
    category: 'energetic',
    complexity: 'complex',
    modality: ['visual', 'temporal'],
    outcome: ['activation', 'integration'],
    description: 'Activate light body',
    interactionType: 'geometric-spin',
    duration: 'long',
    responseAffinity: ['FEELING', 'INTEGRATING'],
  },
  
  ENERGY_SIGNATURE: {
    id: 'energy_signature',
    name: 'Energy Signature',
    category: 'energetic',
    complexity: 'simple',
    modality: ['visual'],
    outcome: ['awareness'],
    description: 'Read energy signature of moment',
    interactionType: 'frequency-read',
    duration: 'instant',
    responseAffinity: ['WITNESSING', 'KNOWING'],
  },
  
  POWER_ANIMAL: {
    id: 'power_animal',
    name: 'Power Animal',
    category: 'energetic',
    complexity: 'medium',
    modality: ['visual'],
    outcome: ['activation', 'grounding'],
    description: 'Call on animal medicine',
    interactionType: 'ally-invoke',
    duration: 'medium',
    responseAffinity: ['BELIEVING', 'FEELING'],
  },
  
  ANCESTRAL_LINE: {
    id: 'ancestral_line',
    name: 'Ancestral Line',
    category: 'energetic',
    complexity: 'complex',
    modality: ['visual'],
    outcome: ['integration', 'grounding'],
    description: 'Connect to lineage - draw strength',
    interactionType: 'lineage-connection',
    duration: 'long',
    responseAffinity: ['INTEGRATING', 'BELIEVING'],
  },
  
  FREQUENCY_SHIFT: {
    id: 'frequency_shift',
    name: 'Frequency Shift',
    category: 'energetic',
    complexity: 'simple',
    modality: ['auditory', 'temporal'],
    outcome: ['activation', 'grounding'],
    description: 'Shift frequency with sound',
    interactionType: 'tone-adjust',
    duration: 'short',
    responseAffinity: ['FEELING', 'CHOOSING'],
  },
  
  ENERGETIC_SCAN: {
    id: 'energetic_scan',
    name: 'Energetic Scan',
    category: 'energetic',
    complexity: 'medium',
    modality: ['visual', 'kinesthetic'],
    outcome: ['awareness'],
    description: 'Scan for blocks and flows',
    interactionType: 'body-energy-scan',
    duration: 'medium',
    responseAffinity: ['FEELING', 'WITNESSING'],
  },
  
  VORTEX_CLEARING: {
    id: 'vortex_clearing',
    name: 'Vortex Clearing',
    category: 'energetic',
    complexity: 'medium',
    modality: ['visual', 'kinesthetic'],
    outcome: ['release', 'grounding'],
    description: 'Clear stuck energy vortex',
    interactionType: 'spin-clear',
    duration: 'medium',
    responseAffinity: ['RELEASING', 'FEELING'],
  },
  
  ATTUNEMENT_FREQUENCY: {
    id: 'attunement_frequency',
    name: 'Attunement Frequency',
    category: 'energetic',
    complexity: 'simple',
    modality: ['auditory'],
    outcome: ['grounding', 'integration'],
    description: 'Attune to healing frequency',
    interactionType: 'frequency-sync',
    duration: 'medium',
    responseAffinity: ['FEELING', 'INTEGRATING'],
  },
  
  SUBTLE_BODY_SCAN: {
    id: 'subtle_body_scan',
    name: 'Subtle Body Scan',
    category: 'energetic',
    complexity: 'medium',
    modality: ['visual', 'kinesthetic'],
    outcome: ['awareness'],
    description: 'Scan beyond physical',
    interactionType: 'etheric-scan',
    duration: 'medium',
    responseAffinity: ['WITNESSING', 'FEELING'],
  },
  
  PRANIC_BREATHING: {
    id: 'pranic_breathing',
    name: 'Pranic Breathing',
    category: 'energetic',
    complexity: 'simple',
    modality: ['kinesthetic', 'temporal'],
    outcome: ['activation', 'grounding'],
    description: 'Breathe life force',
    interactionType: 'pranayama-pattern',
    duration: 'medium',
    responseAffinity: ['FEELING', 'WITNESSING'],
  },
  
  // ═══════════════════════════════════════════════════════════════════════════
  // RITUAL MECHANISMS (20)
  // Ceremony: Rites of passage × Sacred action × Intentional design
  // ═══════════════════════════════════════════════════════════════════════════
  
  PERMISSION_STAMPS: {
    id: 'permission_stamps',
    name: 'Permission Stamps',
    category: 'ritual',
    complexity: 'simple',
    modality: ['visual', 'kinesthetic'],
    outcome: ['activation', 'decision'],
    description: 'Grant yourself permission - stamp it',
    interactionType: 'tap-to-stamp',
    duration: 'instant',
    responseAffinity: ['CHOOSING', 'BELIEVING'],
  },
  
  CELEBRATION_CONFETTI: {
    id: 'celebration_confetti',
    name: 'Celebration Confetti',
    category: 'ritual',
    complexity: 'simple',
    modality: ['visual', 'kinesthetic'],
    outcome: ['integration'],
    description: 'Celebrate wins - confetti burst',
    interactionType: 'shake-for-confetti',
    duration: 'instant',
    responseAffinity: ['FEELING', 'INTEGRATING'],
  },
  
  COMMITMENT_WEIGHT: {
    id: 'commitment_weight',
    name: 'Commitment Weight',
    category: 'ritual',
    complexity: 'medium',
    modality: ['visual', 'kinesthetic'],
    outcome: ['decision', 'awareness'],
    description: 'Feel weight of commitment',
    interactionType: 'hold-to-feel',
    duration: 'short',
    responseAffinity: ['CHOOSING', 'FEELING'],
  },
  
  RESOURCE_INVENTORY: {
    id: 'resource_inventory',
    name: 'Resource Inventory',
    category: 'ritual',
    complexity: 'medium',
    modality: ['visual'],
    outcome: ['awareness', 'activation'],
    description: 'Name resources - activate them',
    interactionType: 'multi-select',
    duration: 'short',
    responseAffinity: ['KNOWING', 'CHOOSING'],
  },
  
  THRESHOLD_CROSSING: {
    id: 'threshold_crossing',
    name: 'Threshold Crossing',
    category: 'ritual',
    complexity: 'medium',
    modality: ['visual', 'kinesthetic'],
    outcome: ['activation', 'integration'],
    description: 'Cross threshold - enter new',
    interactionType: 'swipe-to-cross',
    duration: 'medium',
    responseAffinity: ['BECOMING', 'INTEGRATING'],
  },
  
  VOW_RECITATION: {
    id: 'vow_recitation',
    name: 'Vow Recitation',
    category: 'ritual',
    complexity: 'medium',
    modality: ['visual'],
    outcome: ['decision', 'grounding'],
    description: 'Speak vow - make it real',
    interactionType: 'text-recite',
    duration: 'medium',
    responseAffinity: ['CHOOSING', 'BELIEVING'],
  },
  
  ALTAR_BUILD: {
    id: 'altar_build',
    name: 'Altar Build',
    category: 'ritual',
    complexity: 'complex',
    modality: ['visual', 'kinesthetic'],
    outcome: ['integration', 'grounding'],
    description: 'Build altar - make sacred',
    interactionType: 'drag-objects',
    duration: 'long',
    responseAffinity: ['INTEGRATING', 'BELIEVING'],
  },
  
  BLESSING_CAST: {
    id: 'blessing_cast',
    name: 'Blessing Cast',
    category: 'ritual',
    complexity: 'simple',
    modality: ['visual', 'kinesthetic'],
    outcome: ['activation', 'integration'],
    description: 'Cast blessing - gesture grace',
    interactionType: 'gesture-draw',
    duration: 'instant',
    responseAffinity: ['BELIEVING', 'INTEGRATING'],
  },
  
  PHOENIX_RISE: {
    id: 'phoenix_rise',
    name: 'Phoenix Rise',
    category: 'ritual',
    complexity: 'complex',
    modality: ['visual', 'temporal'],
    outcome: ['integration', 'activation'],
    description: 'Death and rebirth - rise from ash',
    interactionType: 'animation-sequence',
    duration: 'long',
    responseAffinity: ['BECOMING', 'INTEGRATING'],
  },
  
  WITNESS_CIRCLE: {
    id: 'witness_circle',
    name: 'Witness Circle',
    category: 'ritual',
    complexity: 'medium',
    modality: ['visual'],
    outcome: ['integration', 'grounding'],
    description: 'Be witnessed - hold space',
    interactionType: 'circle-animation',
    duration: 'medium',
    responseAffinity: ['WITNESSING', 'INTEGRATING'],
  },
  
  NAMING_CEREMONY: {
    id: 'naming_ceremony',
    name: 'Naming Ceremony',
    category: 'ritual',
    complexity: 'medium',
    modality: ['visual'],
    outcome: ['integration', 'grounding'],
    description: 'Name yourself anew',
    interactionType: 'name-declaration',
    duration: 'medium',
    responseAffinity: ['BECOMING', 'INTEGRATING'],
  },
  
  FIRE_CEREMONY: {
    id: 'fire_ceremony',
    name: 'Fire Ceremony',
    category: 'ritual',
    complexity: 'medium',
    modality: ['visual', 'kinesthetic'],
    outcome: ['release', 'integration'],
    description: 'Burn what no longer serves',
    interactionType: 'flame-release',
    duration: 'medium',
    responseAffinity: ['RELEASING', 'INTEGRATING'],
  },
  
  WATER_BLESSING: {
    id: 'water_blessing',
    name: 'Water Blessing',
    category: 'ritual',
    complexity: 'simple',
    modality: ['visual', 'kinesthetic'],
    outcome: ['grounding', 'integration'],
    description: 'Bless with water - cleanse',
    interactionType: 'water-gesture',
    duration: 'short',
    responseAffinity: ['FEELING', 'INTEGRATING'],
  },
  
  EARTH_OFFERING: {
    id: 'earth_offering',
    name: 'Earth Offering',
    category: 'ritual',
    complexity: 'medium',
    modality: ['visual', 'kinesthetic'],
    outcome: ['release', 'grounding'],
    description: 'Offer to earth - return',
    interactionType: 'burial-gesture',
    duration: 'medium',
    responseAffinity: ['RELEASING', 'BELIEVING'],
  },
  
  SMOKE_CLEARING: {
    id: 'smoke_clearing',
    name: 'Smoke Clearing',
    category: 'ritual',
    complexity: 'simple',
    modality: ['visual', 'kinesthetic'],
    outcome: ['release', 'grounding'],
    description: 'Clear with smoke - sage',
    interactionType: 'smoke-gesture',
    duration: 'short',
    responseAffinity: ['FEELING', 'GROUNDING'],
  },
  
  OATH_SEAL: {
    id: 'oath_seal',
    name: 'Oath Seal',
    category: 'ritual',
    complexity: 'medium',
    modality: ['visual', 'kinesthetic'],
    outcome: ['decision', 'grounding'],
    description: 'Seal oath - wax on promise',
    interactionType: 'seal-gesture',
    duration: 'medium',
    responseAffinity: ['CHOOSING', 'BELIEVING'],
  },
  
  DEDICATION_OFFERING: {
    id: 'dedication_offering',
    name: 'Dedication Offering',
    category: 'ritual',
    complexity: 'medium',
    modality: ['visual'],
    outcome: ['integration', 'grounding'],
    description: 'Dedicate action to larger than self',
    interactionType: 'offering-dedication',
    duration: 'medium',
    responseAffinity: ['BELIEVING', 'INTEGRATING'],
  },
  
  COMPLETION_RITUAL: {
    id: 'completion_ritual',
    name: 'Completion Ritual',
    category: 'ritual',
    complexity: 'complex',
    modality: ['visual', 'temporal'],
    outcome: ['integration', 'release'],
    description: 'Mark ending - honor cycle',
    interactionType: 'closing-ceremony',
    duration: 'long',
    responseAffinity: ['INTEGRATING', 'RELEASING'],
  },
  
  INITIATION_RITE: {
    id: 'initiation_rite',
    name: 'Initiation Rite',
    category: 'ritual',
    complexity: 'complex',
    modality: ['visual', 'temporal'],
    outcome: ['activation', 'integration'],
    description: 'Enter new phase - initiation',
    interactionType: 'multi-phase-ritual',
    duration: 'long',
    responseAffinity: ['BECOMING', 'INTEGRATING'],
  },
  
  GRATITUDE_OFFERING: {
    id: 'gratitude_offering',
    name: 'Gratitude Offering',
    category: 'ritual',
    complexity: 'simple',
    modality: ['visual'],
    outcome: ['integration', 'grounding'],
    description: 'Offer thanks - complete circle',
    interactionType: 'gratitude-gesture',
    duration: 'short',
    responseAffinity: ['FEELING', 'INTEGRATING'],
  },
  
};

export default MECHANISMS_300_PART3;

// ═══════════════════════════════════════════════════════════════════════════
// COMPLETE: 300 MECHANISMS
// Science × Spirituality × Apple
// ═══════════════════════════════════════════════════════════════════════════
