/**
 * THE 300 MECHANISMS (Part 2)
 * Temporal, Emotional, Relational, Cognitive, Energetic, Ritual
 * 
 * Completing the trinity: Science × Spirituality × Apple
 */

import type { Mechanism } from './experience-genome';

export const MECHANISMS_300_PART2: Record<string, Mechanism> = {
  
  // ═══════════════════════════════════════════════════════════════════════════
  // TEMPORAL MECHANISMS (35)
  // Time: Pattern recognition × Cyclical wisdom × Momentum design
  // ═══════════════════════════════════════════════════════════════════════════
  
  MOMENTUM_TRACKER: {
    id: 'momentum_tracker',
    name: 'Momentum Tracker',
    category: 'temporal',
    complexity: 'medium',
    modality: ['visual', 'temporal'],
    outcome: ['awareness', 'activation'],
    description: 'Progress isn\'t linear - see the arc',
    interactionType: 'timeline-graph',
    duration: 'medium',
    responseAffinity: ['BECOMING', 'KNOWING'],
  },
  
  PATTERN_INTERRUPT: {
    id: 'pattern_interrupt',
    name: 'Pattern Interrupt',
    category: 'temporal',
    complexity: 'simple',
    modality: ['kinesthetic', 'temporal'],
    outcome: ['awareness', 'activation'],
    description: 'Break the loop - shake it',
    interactionType: 'shake-to-break',
    duration: 'instant',
    responseAffinity: ['CHOOSING', 'RELEASING'],
  },
  
  MICRO_COMMITMENT: {
    id: 'micro_commitment',
    name: 'Micro-Commitment',
    category: 'temporal',
    complexity: 'simple',
    modality: ['visual'],
    outcome: ['decision', 'activation'],
    description: 'Tiny promise - next 10 minutes',
    interactionType: 'tap-to-commit',
    duration: 'instant',
    responseAffinity: ['CHOOSING', 'BECOMING'],
  },
  
  FUTURE_SELF_POSTCARD: {
    id: 'future_self_postcard',
    name: 'Future Self Postcard',
    category: 'temporal',
    complexity: 'complex',
    modality: ['visual', 'kinesthetic'],
    outcome: ['integration', 'awareness'],
    description: 'Message from future you',
    interactionType: 'text-input',
    duration: 'long',
    responseAffinity: ['BECOMING', 'INTEGRATING'],
  },
  
  CYCLE_WHEEL: {
    id: 'cycle_wheel',
    name: 'Cycle Wheel',
    category: 'temporal',
    complexity: 'medium',
    modality: ['visual', 'kinesthetic'],
    outcome: ['awareness'],
    description: 'Patterns repeat - map the wheel',
    interactionType: 'circular-drag',
    duration: 'medium',
    responseAffinity: ['KNOWING', 'WITNESSING'],
  },
  
  TIMELINE_PINPOINT: {
    id: 'timeline_pinpoint',
    name: 'Timeline Pinpoint',
    category: 'temporal',
    complexity: 'simple',
    modality: ['visual', 'kinesthetic'],
    outcome: ['awareness'],
    description: 'Mark the moment - when did it shift?',
    interactionType: 'tap-timeline',
    duration: 'instant',
    responseAffinity: ['WITNESSING', 'KNOWING'],
  },
  
  RHYTHM_TAP: {
    id: 'rhythm_tap',
    name: 'Rhythm Tap',
    category: 'temporal',
    complexity: 'simple',
    modality: ['kinesthetic', 'auditory'],
    outcome: ['grounding', 'awareness'],
    description: 'Find your natural rhythm',
    interactionType: 'tap-rhythm',
    duration: 'short',
    responseAffinity: ['FEELING', 'WITNESSING'],
  },
  
  DURATION_SLIDER: {
    id: 'duration_slider',
    name: 'Duration Slider',
    category: 'temporal',
    complexity: 'simple',
    modality: ['visual'],
    outcome: ['awareness'],
    description: 'How long did it last? Estimate',
    interactionType: 'time-slider',
    duration: 'instant',
    responseAffinity: ['WITNESSING', 'KNOWING'],
  },
  
  SEASON_SELECTOR: {
    id: 'season_selector',
    name: 'Season Selector',
    category: 'temporal',
    complexity: 'simple',
    modality: ['visual'],
    outcome: ['awareness'],
    description: 'What season are you in?',
    interactionType: 'seasonal-tap',
    duration: 'instant',
    responseAffinity: ['WITNESSING', 'KNOWING'],
  },
  
  PACE_ADJUSTER: {
    id: 'pace_adjuster',
    name: 'Pace Adjuster',
    category: 'temporal',
    complexity: 'simple',
    modality: ['visual'],
    outcome: ['decision', 'grounding'],
    description: 'Sustainable speed - set yours',
    interactionType: 'speed-slider',
    duration: 'instant',
    responseAffinity: ['CHOOSING', 'FEELING'],
  },
  
  BEFORE_AFTER_SPLIT: {
    id: 'before_after_split',
    name: 'Before/After Split',
    category: 'temporal',
    complexity: 'simple',
    modality: ['visual'],
    outcome: ['awareness', 'integration'],
    description: 'Life before this, life after',
    interactionType: 'timeline-divide',
    duration: 'short',
    responseAffinity: ['KNOWING', 'INTEGRATING'],
  },
  
  REPLAY_REWRITE: {
    id: 'replay_rewrite',
    name: 'Replay & Rewrite',
    category: 'temporal',
    complexity: 'complex',
    modality: ['visual', 'kinesthetic'],
    outcome: ['integration', 'awareness'],
    description: 'Replay moment - rewrite ending',
    interactionType: 'scenario-revision',
    duration: 'long',
    responseAffinity: ['INTEGRATING', 'KNOWING'],
  },
  
  WAIT_TOLERANCE: {
    id: 'wait_tolerance',
    name: 'Wait Tolerance',
    category: 'temporal',
    complexity: 'simple',
    modality: ['temporal'],
    outcome: ['grounding', 'awareness'],
    description: 'Practice pause - can you wait?',
    interactionType: 'delay-timer',
    duration: 'medium',
    responseAffinity: ['FEELING', 'CHOOSING'],
  },
  
  TIME_HORIZON: {
    id: 'time_horizon',
    name: 'Time Horizon',
    category: 'temporal',
    complexity: 'simple',
    modality: ['visual'],
    outcome: ['awareness', 'decision'],
    description: 'Looking how far ahead?',
    interactionType: 'horizon-slider',
    duration: 'instant',
    responseAffinity: ['KNOWING', 'CHOOSING'],
  },
  
  PAST_SELF_COMPASSION: {
    id: 'past_self_compassion',
    name: 'Past Self Compassion',
    category: 'temporal',
    complexity: 'medium',
    modality: ['visual'],
    outcome: ['integration', 'release'],
    description: 'Look back with kindness',
    interactionType: 'timeline-reflection',
    duration: 'medium',
    responseAffinity: ['INTEGRATING', 'RELEASING'],
  },
  
  TIPPING_POINT: {
    id: 'tipping_point',
    name: 'Tipping Point',
    category: 'temporal',
    complexity: 'medium',
    modality: ['visual', 'kinesthetic'],
    outcome: ['awareness'],
    description: 'When did it tip? Mark it',
    interactionType: 'inflection-point',
    duration: 'short',
    responseAffinity: ['KNOWING', 'WITNESSING'],
  },
  
  HABIT_CHAIN_LINK: {
    id: 'habit_chain_link',
    name: 'Habit Chain Link',
    category: 'temporal',
    complexity: 'simple',
    modality: ['visual'],
    outcome: ['activation', 'awareness'],
    description: 'Don\'t break the chain',
    interactionType: 'streak-tracking',
    duration: 'instant',
    responseAffinity: ['BECOMING', 'CHOOSING'],
  },
  
  WINDOW_AWARENESS: {
    id: 'window_awareness',
    name: 'Window Awareness',
    category: 'temporal',
    complexity: 'simple',
    modality: ['visual'],
    outcome: ['awareness', 'decision'],
    description: 'Window is open - act now',
    interactionType: 'opportunity-alert',
    duration: 'instant',
    responseAffinity: ['CHOOSING', 'WITNESSING'],
  },
  
  DECAY_NOTICE: {
    id: 'decay_notice',
    name: 'Decay Notice',
    category: 'temporal',
    complexity: 'simple',
    modality: ['visual'],
    outcome: ['awareness'],
    description: 'What\'s fading? Notice decay',
    interactionType: 'fade-visualization',
    duration: 'short',
    responseAffinity: ['WITNESSING', 'KNOWING'],
  },
  
  FREQUENCY_COUNTER: {
    id: 'frequency_counter',
    name: 'Frequency Counter',
    category: 'temporal',
    complexity: 'simple',
    modality: ['visual'],
    outcome: ['awareness'],
    description: 'How often? Track frequency',
    interactionType: 'occurrence-count',
    duration: 'short',
    responseAffinity: ['KNOWING', 'WITNESSING'],
  },
  
  CRESCENDO_BUILD: {
    id: 'crescendo_build',
    name: 'Crescendo Build',
    category: 'temporal',
    complexity: 'medium',
    modality: ['visual', 'temporal'],
    outcome: ['activation', 'awareness'],
    description: 'Feel the build - crescendo awareness',
    interactionType: 'intensity-curve',
    duration: 'medium',
    responseAffinity: ['FEELING', 'WITNESSING'],
  },
  
  TEMPO_SHIFT: {
    id: 'tempo_shift',
    name: 'Tempo Shift',
    category: 'temporal',
    complexity: 'simple',
    modality: ['temporal', 'auditory'],
    outcome: ['activation', 'grounding'],
    description: 'Change tempo - shift state',
    interactionType: 'bpm-adjust',
    duration: 'instant',
    responseAffinity: ['FEELING', 'CHOOSING'],
  },
  
  AGE_REGRESSION_COMPASS: {
    id: 'age_regression_compass',
    name: 'Age Regression Compass',
    category: 'temporal',
    complexity: 'complex',
    modality: ['visual'],
    outcome: ['awareness', 'integration'],
    description: 'How old does this part feel?',
    interactionType: 'age-selector',
    duration: 'medium',
    responseAffinity: ['KNOWING', 'INTEGRATING'],
  },
  
  MOONPHASE_TRACKER: {
    id: 'moonphase_tracker',
    name: 'Moonphase Tracker',
    category: 'temporal',
    complexity: 'simple',
    modality: ['visual'],
    outcome: ['awareness'],
    description: 'Track with lunar cycle',
    interactionType: 'phase-visualization',
    duration: 'instant',
    responseAffinity: ['WITNESSING', 'FEELING'],
  },
  
  SUNRISE_SUNSET: {
    id: 'sunrise_sunset',
    name: 'Sunrise/Sunset',
    category: 'temporal',
    complexity: 'simple',
    modality: ['visual'],
    outcome: ['awareness', 'grounding'],
    description: 'Beginning or ending? Which phase?',
    interactionType: 'phase-selection',
    duration: 'instant',
    responseAffinity: ['WITNESSING', 'KNOWING'],
  },
  
  REPETITION_COUNTER: {
    id: 'repetition_counter',
    name: 'Repetition Counter',
    category: 'temporal',
    complexity: 'simple',
    modality: ['visual'],
    outcome: ['awareness'],
    description: 'How many times have you been here?',
    interactionType: 'repetition-count',
    duration: 'instant',
    responseAffinity: ['KNOWING', 'WITNESSING'],
  },
  
  TURNING_POINT_MARKER: {
    id: 'turning_point_marker',
    name: 'Turning Point Marker',
    category: 'temporal',
    complexity: 'simple',
    modality: ['visual', 'kinesthetic'],
    outcome: ['awareness', 'integration'],
    description: 'This is it - mark turning point',
    interactionType: 'milestone-marker',
    duration: 'short',
    responseAffinity: ['KNOWING', 'INTEGRATING'],
  },
  
  VELOCITY_GAUGE: {
    id: 'velocity_gauge',
    name: 'Velocity Gauge',
    category: 'temporal',
    complexity: 'simple',
    modality: ['visual'],
    outcome: ['awareness'],
    description: 'How fast is change happening?',
    interactionType: 'speed-meter',
    duration: 'instant',
    responseAffinity: ['WITNESSING', 'KNOWING'],
  },
  
  ELAPSED_TIME: {
    id: 'elapsed_time',
    name: 'Elapsed Time',
    category: 'temporal',
    complexity: 'simple',
    modality: ['visual'],
    outcome: ['awareness'],
    description: 'It\'s been ___ since last time',
    interactionType: 'time-since',
    duration: 'instant',
    responseAffinity: ['WITNESSING', 'KNOWING'],
  },
  
  ANTICIPATION_SLIDER: {
    id: 'anticipation_slider',
    name: 'Anticipation Slider',
    category: 'temporal',
    complexity: 'simple',
    modality: ['visual'],
    outcome: ['awareness'],
    description: 'How much anticipation? Measure',
    interactionType: 'future-feeling-slider',
    duration: 'instant',
    responseAffinity: ['FEELING', 'WITNESSING'],
  },
  
  PRESENT_MOMENT_ANCHOR: {
    id: 'present_moment_anchor',
    name: 'Present Moment Anchor',
    category: 'temporal',
    complexity: 'simple',
    modality: ['visual', 'temporal'],
    outcome: ['grounding', 'awareness'],
    description: 'Now. Only now. Come back',
    interactionType: 'now-pulse',
    duration: 'instant',
    responseAffinity: ['WITNESSING', 'FEELING'],
  },
  
  LIFESPAN_ZOOM: {
    id: 'lifespan_zoom',
    name: 'Lifespan Zoom',
    category: 'temporal',
    complexity: 'medium',
    modality: ['visual'],
    outcome: ['awareness', 'integration'],
    description: 'Zoom out to whole life',
    interactionType: 'timeline-zoom',
    duration: 'medium',
    responseAffinity: ['WITNESSING', 'INTEGRATING'],
  },
  
  SEQUENCE_BREAKER: {
    id: 'sequence_breaker',
    name: 'Sequence Breaker',
    category: 'temporal',
    complexity: 'simple',
    modality: ['kinesthetic'],
    outcome: ['activation', 'decision'],
    description: 'Break the sequence - do different',
    interactionType: 'pattern-disrupt',
    duration: 'instant',
    responseAffinity: ['CHOOSING', 'BECOMING'],
  },
  
  HOUR_BY_HOUR: {
    id: 'hour_by_hour',
    name: 'Hour by Hour',
    category: 'temporal',
    complexity: 'simple',
    modality: ['visual'],
    outcome: ['grounding', 'decision'],
    description: 'Not the whole day - just this hour',
    interactionType: 'hour-focus',
    duration: 'instant',
    responseAffinity: ['CHOOSING', 'FEELING'],
  },
  
  TRANSITION_RITUAL: {
    id: 'transition_ritual',
    name: 'Transition Ritual',
    category: 'temporal',
    complexity: 'medium',
    modality: ['kinesthetic', 'temporal'],
    outcome: ['grounding', 'integration'],
    description: 'Mark passage between states',
    interactionType: 'ritual-sequence',
    duration: 'medium',
    responseAffinity: ['INTEGRATING', 'BELIEVING'],
  },
  
  // ═══════════════════════════════════════════════════════════════════════════
  // EMOTIONAL MECHANISMS (50)
  // Heart: Affect regulation × Emotional wisdom × Feeling elegance
  // ═══════════════════════════════════════════════════════════════════════════
  
  MOOD_MOLECULE: {
    id: 'mood_molecule',
    name: 'Mood Molecule',
    category: 'emotional',
    complexity: 'complex',
    modality: ['visual', 'kinesthetic'],
    outcome: ['awareness', 'integration'],
    description: 'Emotions are complex - build the molecule',
    interactionType: 'connect-emotions',
    duration: 'medium',
    responseAffinity: ['FEELING', 'INTEGRATING'],
  },
  
  BELIEF_WEATHER: {
    id: 'belief_weather',
    name: 'Belief Weather',
    category: 'emotional',
    complexity: 'medium',
    modality: ['visual'],
    outcome: ['awareness'],
    description: 'What\'s your inner climate?',
    interactionType: 'weather-select',
    duration: 'short',
    responseAffinity: ['FEELING', 'WITNESSING'],
  },
  
  RESISTANCE_RADAR: {
    id: 'resistance_radar',
    name: 'Resistance Radar',
    category: 'emotional',
    complexity: 'medium',
    modality: ['visual', 'kinesthetic'],
    outcome: ['awareness'],
    description: 'Map what you avoid',
    interactionType: 'radar-plot',
    duration: 'medium',
    responseAffinity: ['KNOWING', 'WITNESSING'],
  },
  
  FORGIVENESS_FLAME: {
    id: 'forgiveness_flame',
    name: 'Forgiveness Flame',
    category: 'emotional',
    complexity: 'medium',
    modality: ['visual', 'kinesthetic'],
    outcome: ['release', 'integration'],
    description: 'Burn it - release ritual',
    interactionType: 'swipe-to-burn',
    duration: 'medium',
    responseAffinity: ['RELEASING', 'INTEGRATING'],
  },
  
  EMOTION_SPECTRUM: {
    id: 'emotion_spectrum',
    name: 'Emotion Spectrum',
    category: 'emotional',
    complexity: 'simple',
    modality: ['visual'],
    outcome: ['awareness'],
    description: 'Not binary - find your place on spectrum',
    interactionType: 'spectrum-slider',
    duration: 'instant',
    responseAffinity: ['FEELING', 'WITNESSING'],
  },
  
  HEART_COMPASS: {
    id: 'heart_compass',
    name: 'Heart Compass',
    category: 'emotional',
    complexity: 'medium',
    modality: ['visual', 'kinesthetic'],
    outcome: ['awareness', 'decision'],
    description: 'Where does heart point?',
    interactionType: 'compass-spin',
    duration: 'short',
    responseAffinity: ['FEELING', 'CHOOSING'],
  },
  
  GRATITUDE_GARDEN: {
    id: 'gratitude_garden',
    name: 'Gratitude Garden',
    category: 'emotional',
    complexity: 'medium',
    modality: ['visual', 'kinesthetic'],
    outcome: ['integration', 'grounding'],
    description: 'Plant flowers of thanks',
    interactionType: 'tap-to-plant',
    duration: 'medium',
    responseAffinity: ['FEELING', 'INTEGRATING'],
  },
  
  EMOTION_LAYERS: {
    id: 'emotion_layers',
    name: 'Emotion Layers',
    category: 'emotional',
    complexity: 'complex',
    modality: ['visual', 'kinesthetic'],
    outcome: ['awareness', 'integration'],
    description: 'Peel back - what\'s underneath?',
    interactionType: 'swipe-to-reveal',
    duration: 'medium',
    responseAffinity: ['FEELING', 'KNOWING'],
  },
  
  JOY_SPARK: {
    id: 'joy_spark',
    name: 'Joy Spark',
    category: 'emotional',
    complexity: 'simple',
    modality: ['visual', 'kinesthetic'],
    outcome: ['activation'],
    description: 'Light the spark - feel joy',
    interactionType: 'tap-to-spark',
    duration: 'instant',
    responseAffinity: ['FEELING', 'CHOOSING'],
  },
  
  GRIEF_WAVE: {
    id: 'grief_wave',
    name: 'Grief Wave',
    category: 'emotional',
    complexity: 'medium',
    modality: ['visual', 'temporal'],
    outcome: ['release', 'awareness'],
    description: 'Ride it - don\'t drown',
    interactionType: 'wave-animation',
    duration: 'medium',
    responseAffinity: ['FEELING', 'RELEASING'],
  },
  
  ANGER_ALCHEMY: {
    id: 'anger_alchemy',
    name: 'Anger Alchemy',
    category: 'emotional',
    complexity: 'medium',
    modality: ['visual', 'kinesthetic'],
    outcome: ['integration', 'activation'],
    description: 'Transform anger to power',
    interactionType: 'energy-conversion',
    duration: 'medium',
    responseAffinity: ['FEELING', 'CHOOSING'],
  },
  
  SHAME_DISSOLVE: {
    id: 'shame_dissolve',
    name: 'Shame Dissolve',
    category: 'emotional',
    complexity: 'complex',
    modality: ['visual', 'kinesthetic'],
    outcome: ['release', 'integration'],
    description: 'Shame shrinks in light - expose it',
    interactionType: 'exposure-fade',
    duration: 'long',
    responseAffinity: ['RELEASING', 'INTEGRATING'],
  },
  
  FEAR_FRIEND: {
    id: 'fear_friend',
    name: 'Fear Friend',
    category: 'emotional',
    complexity: 'medium',
    modality: ['visual'],
    outcome: ['integration', 'awareness'],
    description: 'What if fear is trying to help?',
    interactionType: 'reframe-dialogue',
    duration: 'medium',
    responseAffinity: ['KNOWING', 'INTEGRATING'],
  },
  
  ENVY_COMPASS: {
    id: 'envy_compass',
    name: 'Envy Compass',
    category: 'emotional',
    complexity: 'simple',
    modality: ['visual'],
    outcome: ['awareness', 'decision'],
    description: 'Envy shows what you want',
    interactionType: 'desire-mapping',
    duration: 'short',
    responseAffinity: ['KNOWING', 'CHOOSING'],
  },
  
  GUILT_GIFT: {
    id: 'guilt_gift',
    name: 'Guilt Gift',
    category: 'emotional',
    complexity: 'medium',
    modality: ['visual'],
    outcome: ['awareness', 'integration'],
    description: 'What is guilt protecting?',
    interactionType: 'protective-reveal',
    duration: 'medium',
    responseAffinity: ['KNOWING', 'INTEGRATING'],
  },
  
  LONELINESS_NOTICE: {
    id: 'loneliness_notice',
    name: 'Loneliness Notice',
    category: 'emotional',
    complexity: 'simple',
    modality: ['visual'],
    outcome: ['awareness', 'grounding'],
    description: 'Loneliness is not wrongness',
    interactionType: 'validation-statement',
    duration: 'short',
    responseAffinity: ['FEELING', 'BELIEVING'],
  },
  
  ANXIETY_UNPACK: {
    id: 'anxiety_unpack',
    name: 'Anxiety Unpack',
    category: 'emotional',
    complexity: 'complex',
    modality: ['visual', 'kinesthetic'],
    outcome: ['awareness', 'integration'],
    description: 'Unpack the bundle - what\'s in there?',
    interactionType: 'unfolding-reveal',
    duration: 'long',
    responseAffinity: ['KNOWING', 'INTEGRATING'],
  },
  
  CONTENTMENT_REST: {
    id: 'contentment_rest',
    name: 'Contentment Rest',
    category: 'emotional',
    complexity: 'simple',
    modality: ['visual'],
    outcome: ['grounding', 'awareness'],
    description: 'Rest in enough-ness',
    interactionType: 'stillness-settle',
    duration: 'medium',
    responseAffinity: ['FEELING', 'WITNESSING'],
  },
  
  BOREDOM_PORTAL: {
    id: 'boredom_portal',
    name: 'Boredom Portal',
    category: 'emotional',
    complexity: 'simple',
    modality: ['visual'],
    outcome: ['awareness', 'integration'],
    description: 'Boredom is gateway - enter it',
    interactionType: 'invitation-frame',
    duration: 'short',
    responseAffinity: ['WITNESSING', 'INTEGRATING'],
  },
  
  HOPE_KINDLE: {
    id: 'hope_kindle',
    name: 'Hope Kindle',
    category: 'emotional',
    complexity: 'simple',
    modality: ['visual', 'kinesthetic'],
    outcome: ['activation', 'grounding'],
    description: 'Kindle small flame of hope',
    interactionType: 'flame-grow',
    duration: 'short',
    responseAffinity: ['FEELING', 'BELIEVING'],
  },
  
  DESPAIR_COMPANION: {
    id: 'despair_companion',
    name: 'Despair Companion',
    category: 'emotional',
    complexity: 'complex',
    modality: ['visual'],
    outcome: ['integration', 'grounding'],
    description: 'Sit with despair - not alone',
    interactionType: 'presence-hold',
    duration: 'long',
    responseAffinity: ['FEELING', 'INTEGRATING'],
  },
  
  EXCITEMENT_CHANNEL: {
    id: 'excitement_channel',
    name: 'Excitement Channel',
    category: 'emotional',
    complexity: 'simple',
    modality: ['kinesthetic'],
    outcome: ['activation', 'awareness'],
    description: 'Channel excitement into action',
    interactionType: 'energy-direction',
    duration: 'short',
    responseAffinity: ['CHOOSING', 'FEELING'],
  },
  
  OVERWHELM_CHUNK: {
    id: 'overwhelm_chunk',
    name: 'Overwhelm Chunk',
    category: 'emotional',
    complexity: 'medium',
    modality: ['visual', 'kinesthetic'],
    outcome: ['grounding', 'decision'],
    description: 'Too much - break into pieces',
    interactionType: 'divide-and-sort',
    duration: 'medium',
    responseAffinity: ['FEELING', 'CHOOSING'],
  },
  
  DISAPPOINTMENT_HONOR: {
    id: 'disappointment_honor',
    name: 'Disappointment Honor',
    category: 'emotional',
    complexity: 'simple',
    modality: ['visual'],
    outcome: ['integration', 'release'],
    description: 'You hoped - that matters',
    interactionType: 'acknowledgment-ritual',
    duration: 'short',
    responseAffinity: ['FEELING', 'INTEGRATING'],
  },
  
  CURIOSITY_SPARK: {
    id: 'curiosity_spark',
    name: 'Curiosity Spark',
    category: 'emotional',
    complexity: 'simple',
    modality: ['visual'],
    outcome: ['activation', 'awareness'],
    description: 'Get curious instead of critical',
    interactionType: 'reframe-cue',
    duration: 'instant',
    responseAffinity: ['KNOWING', 'FEELING'],
  },
  
  PRIDE_CELEBRATE: {
    id: 'pride_celebrate',
    name: 'Pride Celebrate',
    category: 'emotional',
    complexity: 'simple',
    modality: ['visual', 'kinesthetic'],
    outcome: ['integration', 'grounding'],
    description: 'You did that - celebrate it',
    interactionType: 'win-marker',
    duration: 'instant',
    responseAffinity: ['FEELING', 'INTEGRATING'],
  },
  
  NUMBNESS_THAW: {
    id: 'numbness_thaw',
    name: 'Numbness Thaw',
    category: 'emotional',
    complexity: 'complex',
    modality: ['visual', 'kinesthetic'],
    outcome: ['awareness', 'activation'],
    description: 'Gentle thaw - don\'t force',
    interactionType: 'gradual-warming',
    duration: 'long',
    responseAffinity: ['FEELING', 'BECOMING'],
  },
  
  NOSTALGIA_BRIDGE: {
    id: 'nostalgia_bridge',
    name: 'Nostalgia Bridge',
    category: 'emotional',
    complexity: 'medium',
    modality: ['visual'],
    outcome: ['integration', 'awareness'],
    description: 'Bridge past to present with love',
    interactionType: 'timeline-connection',
    duration: 'medium',
    responseAffinity: ['INTEGRATING', 'FEELING'],
  },
  
  AMBIVALENCE_HOLD: {
    id: 'ambivalence_hold',
    name: 'Ambivalence Hold',
    category: 'emotional',
    complexity: 'medium',
    modality: ['visual', 'kinesthetic'],
    outcome: ['awareness', 'grounding'],
    description: 'Hold both truths - no rush',
    interactionType: 'paradox-embrace',
    duration: 'medium',
    responseAffinity: ['WITNESSING', 'INTEGRATING'],
  },
  
  PEACE_SETTLE: {
    id: 'peace_settle',
    name: 'Peace Settle',
    category: 'emotional',
    complexity: 'simple',
    modality: ['visual', 'temporal'],
    outcome: ['grounding', 'awareness'],
    description: 'Let peace settle like snow',
    interactionType: 'settling-animation',
    duration: 'medium',
    responseAffinity: ['FEELING', 'WITNESSING'],
  },
  
  RAGE_CONTAINER: {
    id: 'rage_container',
    name: 'Rage Container',
    category: 'emotional',
    complexity: 'medium',
    modality: ['visual', 'kinesthetic'],
    outcome: ['grounding', 'awareness'],
    description: 'Contain it safely - don\'t suppress',
    interactionType: 'containment-build',
    duration: 'short',
    responseAffinity: ['FEELING', 'CHOOSING'],
  },
  
  TENDER_NOTICE: {
    id: 'tender_notice',
    name: 'Tender Notice',
    category: 'emotional',
    complexity: 'simple',
    modality: ['visual'],
    outcome: ['awareness', 'grounding'],
    description: 'Notice tenderness - it\'s ok',
    interactionType: 'gentle-acknowledgment',
    duration: 'short',
    responseAffinity: ['FEELING', 'WITNESSING'],
  },
  
  JEALOUSY_DECODE: {
    id: 'jealousy_decode',
    name: 'Jealousy Decode',
    category: 'emotional',
    complexity: 'medium',
    modality: ['visual'],
    outcome: ['awareness', 'integration'],
    description: 'What does jealousy reveal?',
    interactionType: 'meaning-extraction',
    duration: 'medium',
    responseAffinity: ['KNOWING', 'INTEGRATING'],
  },
  
  RELIEF_EXHALE: {
    id: 'relief_exhale',
    name: 'Relief Exhale',
    category: 'emotional',
    complexity: 'simple',
    modality: ['kinesthetic'],
    outcome: ['release', 'grounding'],
    description: 'Big exhale - feel relief',
    interactionType: 'breath-release',
    duration: 'instant',
    responseAffinity: ['RELEASING', 'FEELING'],
  },
  
  AWE_EXPANSION: {
    id: 'awe_expansion',
    name: 'Awe Expansion',
    category: 'emotional',
    complexity: 'simple',
    modality: ['visual', 'temporal'],
    outcome: ['integration', 'awareness'],
    description: 'Let awe expand you',
    interactionType: 'expansive-animation',
    duration: 'medium',
    responseAffinity: ['FEELING', 'WITNESSING'],
  },
  
  CONFUSION_CLARITY: {
    id: 'confusion_clarity',
    name: 'Confusion Clarity',
    category: 'emotional',
    complexity: 'medium',
    modality: ['visual'],
    outcome: ['awareness', 'grounding'],
    description: 'Confusion before clarity - natural',
    interactionType: 'fog-to-clear',
    duration: 'medium',
    responseAffinity: ['KNOWING', 'WITNESSING'],
  },
  
  SURPRISE_WELCOME: {
    id: 'surprise_welcome',
    name: 'Surprise Welcome',
    category: 'emotional',
    complexity: 'simple',
    modality: ['visual'],
    outcome: ['awareness', 'integration'],
    description: 'Unexpected doesn\'t mean wrong',
    interactionType: 'openness-frame',
    duration: 'short',
    responseAffinity: ['WITNESSING', 'INTEGRATING'],
  },
  
  DISGUST_BOUNDARY: {
    id: 'disgust_boundary',
    name: 'Disgust Boundary',
    category: 'emotional',
    complexity: 'simple',
    modality: ['visual'],
    outcome: ['awareness', 'decision'],
    description: 'Disgust says "not this"',
    interactionType: 'boundary-signal',
    duration: 'instant',
    responseAffinity: ['FEELING', 'CHOOSING'],
  },
  
  TRUST_RESTORE: {
    id: 'trust_restore',
    name: 'Trust Restore',
    category: 'emotional',
    complexity: 'complex',
    modality: ['visual', 'temporal'],
    outcome: ['integration', 'grounding'],
    description: 'Rebuild trust - brick by brick',
    interactionType: 'incremental-build',
    duration: 'long',
    responseAffinity: ['BELIEVING', 'INTEGRATING'],
  },
  
  ANTICIPATORY_ANXIETY: {
    id: 'anticipatory_anxiety',
    name: 'Anticipatory Anxiety',
    category: 'emotional',
    complexity: 'medium',
    modality: ['visual'],
    outcome: ['awareness', 'grounding'],
    description: 'Future fear is not now',
    interactionType: 'temporal-separation',
    duration: 'short',
    responseAffinity: ['KNOWING', 'FEELING'],
  },
  
  CALM_ABIDING: {
    id: 'calm_abiding',
    name: 'Calm Abiding',
    category: 'emotional',
    complexity: 'simple',
    modality: ['visual', 'temporal'],
    outcome: ['grounding', 'awareness'],
    description: 'Shamatha - rest in calm',
    interactionType: 'meditative-rest',
    duration: 'long',
    responseAffinity: ['WITNESSING', 'FEELING'],
  },
  
  HEARTBREAK_HOLD: {
    id: 'heartbreak_hold',
    name: 'Heartbreak Hold',
    category: 'emotional',
    complexity: 'complex',
    modality: ['visual', 'kinesthetic'],
    outcome: ['integration', 'release'],
    description: 'Hold broken heart with both hands',
    interactionType: 'compassionate-holding',
    duration: 'long',
    responseAffinity: ['FEELING', 'INTEGRATING'],
  },
  
  DEFENSIVE_SOFTEN: {
    id: 'defensive_soften',
    name: 'Defensive Soften',
    category: 'emotional',
    complexity: 'medium',
    modality: ['kinesthetic'],
    outcome: ['release', 'awareness'],
    description: 'Notice armor - choose to soften',
    interactionType: 'tension-release-cue',
    duration: 'short',
    responseAffinity: ['FEELING', 'CHOOSING'],
  },
  
  INDIGNATION_POWER: {
    id: 'indignation_power',
    name: 'Indignation Power',
    category: 'emotional',
    complexity: 'medium',
    modality: ['visual'],
    outcome: ['activation', 'decision'],
    description: 'Righteous anger - use it',
    interactionType: 'energy-harness',
    duration: 'short',
    responseAffinity: ['CHOOSING', 'FEELING'],
  },
  
  MELANCHOLY_BEAUTY: {
    id: 'melancholy_beauty',
    name: 'Melancholy Beauty',
    category: 'emotional',
    complexity: 'simple',
    modality: ['visual'],
    outcome: ['integration', 'awareness'],
    description: 'Melancholy has beauty too',
    interactionType: 'reframe-appreciation',
    duration: 'medium',
    responseAffinity: ['FEELING', 'INTEGRATING'],
  },
  
  IRRITATION_MESSAGE: {
    id: 'irritation_message',
    name: 'Irritation Message',
    category: 'emotional',
    complexity: 'simple',
    modality: ['visual'],
    outcome: ['awareness'],
    description: 'What is irritation trying to tell you?',
    interactionType: 'signal-decode',
    duration: 'short',
    responseAffinity: ['KNOWING', 'FEELING'],
  },
  
  EXASPERATION_PAUSE: {
    id: 'exasperation_pause',
    name: 'Exasperation Pause',
    category: 'emotional',
    complexity: 'simple',
    modality: ['temporal'],
    outcome: ['grounding', 'awareness'],
    description: 'Pause before explosion',
    interactionType: 'interrupt-timer',
    duration: 'short',
    responseAffinity: ['CHOOSING', 'FEELING'],
  },
  
  // To be continued in Part 3: Relational (35), Cognitive (40), Energetic (30), Ritual (20)
  
};

export default MECHANISMS_300_PART2;
