import { useEffect, useRef } from 'react';
import type { AtomProps } from '../types';
import { advanceEntrance, drawAtmosphere, easeOutCubic, lerpColor, parseColor, px, rgba, roundedRect, setupCanvas } from '../atom-utils';
const clamp=(v:number,min:number,max:number)=>Math.max(min,Math.min(max,v)); const STEP_T=0.42; const COMPLETE_T=0.97; type Point={x:number;y:number;t:number};
export default function FossilizationPressAtom({ color, accentColor, viewport, phase, composed, onHaptic, onStateChange, onResolve }: AtomProps){
 const canvasRef=useRef<HTMLCanvasElement>(null); const callbacksRef=useRef({onHaptic,onStateChange,onResolve}); const propsRef=useRef({color,accentColor,phase,composed}); const holdRef=useRef(false); const dragRef=useRef<{active:boolean;last:Point|null}>({active:false,last:null}); const stateRef=useRef({entranceProgress:0,primaryRgb:parseColor(color),accentRgb:parseColor(accentColor),cover:0,press:0,thresholdFired:false,completionFired:false});
 useEffect(()=>{callbacksRef.current={onHaptic,onStateChange,onResolve};},[onHaptic,onStateChange,onResolve]); useEffect(()=>{propsRef.current={color,accentColor,phase,composed};},[color,accentColor,phase,composed]); useEffect(()=>{stateRef.current.primaryRgb=parseColor(color); stateRef.current.accentRgb=parseColor(accentColor);},[color,accentColor]);
 useEffect(()=>{const canvas=canvasRef.current; if(!canvas)return; const ctx=canvas.getContext('2d'); if(!ctx)return; let raf=0;
  const render=()=>{const s=stateRef.current,p=propsRef.current,cb=callbacksRef.current; const {w,h,cx,cy,minDim}=setupCanvas(canvas,ctx,viewport.width,viewport.height); const {progress,entrance}=advanceEntrance(s.entranceProgress,p.phase); s.entranceProgress=progress; if(!p.composed) drawAtmosphere(ctx,cx,cy,w,h,minDim,s.primaryRgb,entrance); if((holdRef.current&&s.cover>0.6)||p.phase==='resolve') s.press+=(1-s.press)*0.06; const reveal=easeOutCubic(clamp((s.cover*0.5+s.press*0.5),0,1)); cb.onStateChange?.(reveal); if(reveal>=STEP_T&&!s.thresholdFired){s.thresholdFired=true; cb.onHaptic('step_advance');} if(reveal>=COMPLETE_T&&!s.completionFired){s.completionFired=true; cb.onHaptic('completion'); cb.onResolve?.();}
   const primary=s.primaryRgb,accent=s.accentRgb,deep=lerpColor([4,6,10],primary,0.1), fossil=lerpColor(primary,[244,247,255],0.88), sediment=lerpColor(accent,[144,132,120],0.22); ctx.fillStyle=rgba(deep,0.98*entrance); ctx.fillRect(0,0,w,h);
   ctx.beginPath(); ctx.arc(cx,cy,minDim*0.12,0,Math.PI*2); ctx.strokeStyle=rgba(fossil,(0.1+(1-s.press)*0.36)*entrance); ctx.lineWidth=px(0.012,minDim); ctx.stroke();
   roundedRect(ctx,w*(0.16+s.cover*0.1),h*0.36,w*0.68,h*0.18,minDim*0.02); ctx.fillStyle=rgba(sediment,(0.14+s.cover*0.44)*entrance); ctx.fill();
   if(s.press>0.1){ ctx.beginPath(); ctx.arc(cx,cy,minDim*(0.12+s.press*0.02),Math.PI*0.2,Math.PI*1.8); ctx.strokeStyle=rgba(fossil,s.press*entrance); ctx.lineWidth=px(0.01,minDim); ctx.stroke(); }
   ctx.restore(); raf=window.requestAnimationFrame(render);
  };
  const getPoint=(e:PointerEvent):Point=>{const rect=canvas.getBoundingClientRect(); return {x:((e.clientX-rect.left)/rect.width)*viewport.width,y:((e.clientY-rect.top)/rect.height)*viewport.height,t:performance.now()};};
  const onDown=(e:PointerEvent)=>{dragRef.current={active:true,last:getPoint(e)}; canvas.setPointerCapture(e.pointerId);};
  const onMove=(e:PointerEvent)=>{if(!dragRef.current.active||!dragRef.current.last)return; const next=getPoint(e); const dx=next.x-dragRef.current.last.x; if(dx>0) stateRef.current.cover=clamp(stateRef.current.cover+(dx/viewport.width)*2.1,0,1); dragRef.current.last=next;};
  const onUp=(e:PointerEvent)=>{dragRef.current={active:false,last:null}; canvas.releasePointerCapture(e.pointerId);};
  const onHoldDown=(e:PointerEvent)=>{holdRef.current=true; callbacksRef.current.onHaptic('hold_start');}; const onHoldUp=()=>{holdRef.current=false;};
  raf=window.requestAnimationFrame(render); canvas.addEventListener('pointerdown',onDown); canvas.addEventListener('pointermove',onMove); canvas.addEventListener('pointerup',onUp); canvas.addEventListener('pointercancel',onUp); canvas.addEventListener('pointerdown',onHoldDown); canvas.addEventListener('pointerup',onHoldUp); canvas.addEventListener('pointercancel',onHoldUp); return ()=>{window.cancelAnimationFrame(raf); canvas.removeEventListener('pointerdown',onDown); canvas.removeEventListener('pointermove',onMove); canvas.removeEventListener('pointerup',onUp); canvas.removeEventListener('pointercancel',onUp); canvas.removeEventListener('pointerdown',onHoldDown); canvas.removeEventListener('pointerup',onHoldUp); canvas.removeEventListener('pointercancel',onHoldUp);};
 },[viewport.width,viewport.height]);
 return <div style={{position:'absolute',inset:0}}><canvas ref={canvasRef} style={{display:'block',width:'100%',height:'100%',touchAction:'none'}}/></div>;
}
