import { useEffect, useRef } from 'react';
import type { AtomProps } from '../types';
import { advanceEntrance, drawAtmosphere, easeOutCubic, lerpColor, parseColor, px, rgba, roundedRect, setupCanvas } from '../atom-utils';
const clamp=(v:number,min:number,max:number)=>Math.max(min,Math.min(max,v)); const STEP_T=0.42; const COMPLETE_T=0.97; type Point={x:number;y:number;t:number};
export default function KineticPotentialSpringAtom({ color, accentColor, viewport, phase, composed, onHaptic, onStateChange, onResolve }: AtomProps){
 const canvasRef=useRef<HTMLCanvasElement>(null); const callbacksRef=useRef({onHaptic,onStateChange,onResolve}); const propsRef=useRef({color,accentColor,phase,composed}); const dragRef=useRef<{active:boolean;last:Point|null}>({active:false,last:null}); const stateRef=useRef({entranceProgress:0,primaryRgb:parseColor(color),accentRgb:parseColor(accentColor),coil:0,thresholdFired:false,completionFired:false});
 useEffect(()=>{callbacksRef.current={onHaptic,onStateChange,onResolve};},[onHaptic,onStateChange,onResolve]); useEffect(()=>{propsRef.current={color,accentColor,phase,composed};},[color,accentColor,phase,composed]); useEffect(()=>{stateRef.current.primaryRgb=parseColor(color); stateRef.current.accentRgb=parseColor(accentColor);},[color,accentColor]);
 useEffect(()=>{const canvas=canvasRef.current; if(!canvas)return; const ctx=canvas.getContext('2d'); if(!ctx)return; let raf=0;
  const render=()=>{const s=stateRef.current,p=propsRef.current,cb=callbacksRef.current; const {w,h,cx,cy,minDim}=setupCanvas(canvas,ctx,viewport.width,viewport.height); const {progress,entrance}=advanceEntrance(s.entranceProgress,p.phase); s.entranceProgress=progress; if(!p.composed) drawAtmosphere(ctx,cx,cy,w,h,minDim,s.primaryRgb,entrance); if(p.phase==='resolve') s.coil+=(1-s.coil)*0.08; const reveal=easeOutCubic(clamp(s.coil,0,1)); cb.onStateChange?.(reveal); if(reveal>=STEP_T&&!s.thresholdFired){s.thresholdFired=true; cb.onHaptic('step_advance');} if(reveal>=COMPLETE_T&&!s.completionFired){s.completionFired=true; cb.onHaptic('completion'); cb.onResolve?.();}
   const primary=s.primaryRgb,accent=s.accentRgb,deep=lerpColor([4,6,10],primary,0.1), block=lerpColor(accent,[142,134,124],0.2), line=lerpColor(primary,[245,247,255],0.88); ctx.fillStyle=rgba(deep,0.98*entrance); ctx.fillRect(0,0,w,h);
   roundedRect(ctx,w*0.16 + reveal*w*0.12, cy-minDim*0.08, w*0.18, minDim*0.16, minDim*0.02); ctx.fillStyle=rgba(block,0.58*entrance); ctx.fill();
   for(let i=0;i<10;i+=1){ const x=w*(0.34+i*0.028); const y=cy + Math.sin(i*Math.PI*0.8)*minDim*(0.05+reveal*0.02); ctx.beginPath(); if(i===0) ctx.moveTo(x,y); else ctx.lineTo(x,y); ctx.strokeStyle=rgba(line,(0.18+reveal*0.42)*entrance); ctx.lineWidth=px(0.008,minDim); ctx.stroke(); }
   const gaugeY=h*0.24; ctx.beginPath(); ctx.moveTo(w*0.2,gaugeY); ctx.lineTo(w*0.8,gaugeY); ctx.strokeStyle=rgba(line,0.22*entrance); ctx.lineWidth=px(0.004,minDim); ctx.stroke(); ctx.fillStyle=rgba(lerpColor([255,96,72],accent,0.2),(0.12+reveal*0.7)*entrance); ctx.fillRect(w*0.2,gaugeY-minDim*0.01,w*0.6*reveal,minDim*0.02);
   ctx.restore(); raf=window.requestAnimationFrame(render);
  };
  const getPoint=(e:PointerEvent):Point=>{const rect=canvas.getBoundingClientRect(); return {x:((e.clientX-rect.left)/rect.width)*viewport.width,y:((e.clientY-rect.top)/rect.height)*viewport.height,t:performance.now()};};
  const onDown=(e:PointerEvent)=>{dragRef.current={active:true,last:getPoint(e)}; canvas.setPointerCapture(e.pointerId); callbacksRef.current.onHaptic('hold_start');};
  const onMove=(e:PointerEvent)=>{if(!dragRef.current.active || !dragRef.current.last)return; const next=getPoint(e); const dx=Math.abs(next.x-dragRef.current.last.x); stateRef.current.coil=clamp(stateRef.current.coil+(dx/viewport.width)*2.1,0,1); dragRef.current.last=next;};
  const onUp=(e:PointerEvent)=>{dragRef.current={active:false,last:null}; canvas.releasePointerCapture(e.pointerId);};
  raf=window.requestAnimationFrame(render); canvas.addEventListener('pointerdown',onDown); canvas.addEventListener('pointermove',onMove); canvas.addEventListener('pointerup',onUp); canvas.addEventListener('pointercancel',onUp); return ()=>{window.cancelAnimationFrame(raf); canvas.removeEventListener('pointerdown',onDown); canvas.removeEventListener('pointermove',onMove); canvas.removeEventListener('pointerup',onUp); canvas.removeEventListener('pointercancel',onUp);};
 },[viewport.width,viewport.height]);
 return <div style={{position:'absolute',inset:0}}><canvas ref={canvasRef} style={{display:'block',width:'100%',height:'100%',touchAction:'none'}}/></div>;
}
