import { useEffect, useRef } from 'react';
import type { AtomProps } from '../types';
import { advanceEntrance, drawAtmosphere, easeOutCubic, lerpColor, parseColor, px, rgba, roundedRect, setupCanvas } from '../atom-utils';
const clamp=(v:number,min:number,max:number)=>Math.max(min,Math.min(max,v)); const STEP_T=0.44; const COMPLETE_T=0.97; type Point={x:number;y:number}; const distance=(a:Point,b:Point)=>Math.hypot(a.x-b.x,a.y-b.y);
export default function StratigraphyCompressAtom({ color, accentColor, viewport, phase, composed, onHaptic, onStateChange, onResolve }: AtomProps){
 const canvasRef=useRef<HTMLCanvasElement>(null); const callbacksRef=useRef({onHaptic,onStateChange,onResolve}); const propsRef=useRef({color,accentColor,phase,composed}); const stateRef=useRef({entranceProgress:0,primaryRgb:parseColor(color),accentRgb:parseColor(accentColor),pointers:{} as Record<number,Point>, pinchBaseline:0, targetReveal:0, reveal:0, thresholdFired:false, completionFired:false});
 useEffect(()=>{callbacksRef.current={onHaptic,onStateChange,onResolve};},[onHaptic,onStateChange,onResolve]); useEffect(()=>{propsRef.current={color,accentColor,phase,composed};},[color,accentColor,phase,composed]); useEffect(()=>{stateRef.current.primaryRgb=parseColor(color); stateRef.current.accentRgb=parseColor(accentColor);},[color,accentColor]);
 useEffect(()=>{const canvas=canvasRef.current; if(!canvas)return; const ctx=canvas.getContext('2d'); if(!ctx)return; let raf=0;
  const render=()=>{const s=stateRef.current,p=propsRef.current,cb=callbacksRef.current; const {w,h,cx,minDim}=setupCanvas(canvas,ctx,viewport.width,viewport.height); const {progress,entrance}=advanceEntrance(s.entranceProgress,p.phase); s.entranceProgress=progress; if(!p.composed) drawAtmosphere(ctx,cx,h*0.5,w,h,minDim,s.primaryRgb,entrance); if(p.phase==='resolve') s.targetReveal=1; const pts=Object.values(s.pointers); if(pts.length>=2){const d=distance(pts[0],pts[1]); if(s.pinchBaseline===0) s.pinchBaseline=d; s.targetReveal=Math.max(s.targetReveal,clamp((s.pinchBaseline-d)/(minDim*0.24),0,1));} else s.pinchBaseline=0; s.reveal+=(s.targetReveal-s.reveal)*0.12; const reveal=easeOutCubic(clamp(s.reveal,0,1)); cb.onStateChange?.(reveal); if(reveal>=STEP_T&&!s.thresholdFired){s.thresholdFired=true; cb.onHaptic('step_advance');} if(reveal>=COMPLETE_T&&!s.completionFired){s.completionFired=true; cb.onHaptic('completion'); cb.onResolve?.();}
   const primary=s.primaryRgb,accent=s.accentRgb,deep=lerpColor([4,6,10],primary,0.1); ctx.fillStyle=rgba(deep,0.98*entrance); ctx.fillRect(0,0,w,h); const tones=[[116,92,84],[124,102,88],[96,84,78],[142,120,102]].map(t=>lerpColor(t as [number,number,number],accent,0.08));
   tones.forEach((tone,i)=>{ const y=h*(0.28+i*0.11)+reveal*h*0.06*(i-1.5); roundedRect(ctx,w*0.22,y,w*0.56,h*0.08-reveal*h*0.02,minDim*0.01); ctx.fillStyle=rgba(tone,(0.18+reveal*0.46)*entrance); ctx.fill(); });
   ctx.beginPath(); ctx.moveTo(w*0.2,h*0.76-reveal*h*0.12); ctx.lineTo(w*0.8,h*0.76-reveal*h*0.12); ctx.strokeStyle=rgba(lerpColor(primary,[245,247,255],0.88),reveal*entrance); ctx.lineWidth=px(0.012,minDim); ctx.stroke();
   ctx.restore(); raf=window.requestAnimationFrame(render);
  };
  const getPoint=(e:PointerEvent):Point=>{const rect=canvas.getBoundingClientRect(); return {x:((e.clientX-rect.left)/rect.width)*viewport.width,y:((e.clientY-rect.top)/rect.height)*viewport.height};};
  const onDown=(e:PointerEvent)=>{stateRef.current.pointers[e.pointerId]=getPoint(e); canvas.setPointerCapture(e.pointerId); callbacksRef.current.onHaptic('hold_start');}; const onMove=(e:PointerEvent)=>{if(!(e.pointerId in stateRef.current.pointers))return; stateRef.current.pointers[e.pointerId]=getPoint(e);}; const onUp=(e:PointerEvent)=>{delete stateRef.current.pointers[e.pointerId]; canvas.releasePointerCapture(e.pointerId);};
  raf=window.requestAnimationFrame(render); canvas.addEventListener('pointerdown',onDown); canvas.addEventListener('pointermove',onMove); canvas.addEventListener('pointerup',onUp); canvas.addEventListener('pointercancel',onUp); return ()=>{window.cancelAnimationFrame(raf); canvas.removeEventListener('pointerdown',onDown); canvas.removeEventListener('pointermove',onMove); canvas.removeEventListener('pointerup',onUp); canvas.removeEventListener('pointercancel',onUp);};
 },[viewport.width,viewport.height]);
 return <div style={{position:'absolute',inset:0}}><canvas ref={canvasRef} style={{display:'block',width:'100%',height:'100%',touchAction:'none'}}/></div>;
}
