import { useEffect, useRef } from 'react';
import type { AtomProps } from '../types';
import { advanceEntrance, drawAtmosphere, easeOutCubic, lerpColor, parseColor, px, rgba, roundedRect, setupCanvas } from '../atom-utils';
const clamp=(v:number,min:number,max:number)=>Math.max(min,Math.min(max,v)); const STEP_T=0.42; const COMPLETE_T=0.97; type Point={x:number;y:number}; const distance=(a:Point,b:Point)=>Math.hypot(a.x-b.x,a.y-b.y);
export default function TremorValveAtom({ color, accentColor, viewport, phase, composed, onHaptic, onStateChange, onResolve }: AtomProps){
 const canvasRef=useRef<HTMLCanvasElement>(null); const callbacksRef=useRef({onHaptic,onStateChange,onResolve}); const propsRef=useRef({color,accentColor,phase,composed}); const stateRef=useRef({entranceProgress:0,primaryRgb:parseColor(color),accentRgb:parseColor(accentColor),pointers:{} as Record<number,Point>, baseline:0, targetReveal:0, reveal:0, tremor:0, thresholdFired:false,completionFired:false});
 useEffect(()=>{callbacksRef.current={onHaptic,onStateChange,onResolve};},[onHaptic,onStateChange,onResolve]); useEffect(()=>{propsRef.current={color,accentColor,phase,composed};},[color,accentColor,phase,composed]); useEffect(()=>{stateRef.current.primaryRgb=parseColor(color); stateRef.current.accentRgb=parseColor(accentColor);},[color,accentColor]);
 useEffect(()=>{const canvas=canvasRef.current; if(!canvas)return; const ctx=canvas.getContext('2d'); if(!ctx)return; let raf=0;
  const render=()=>{const s=stateRef.current,p=propsRef.current,cb=callbacksRef.current; const {w,h,cx,cy,minDim}=setupCanvas(canvas,ctx,viewport.width,viewport.height); const {progress,entrance}=advanceEntrance(s.entranceProgress,p.phase); s.entranceProgress=progress; if(!p.composed) drawAtmosphere(ctx,cx,cy,w,h,minDim,s.primaryRgb,entrance); if(p.phase==='resolve') s.targetReveal=1; s.tremor+=0.08; const pts=Object.values(s.pointers); if(pts.length>=2){ const d=distance(pts[0],pts[1]); if(s.baseline===0) s.baseline=d; s.targetReveal=Math.max(s.targetReveal,clamp((d-s.baseline)/(minDim*0.26),0,1)); } else s.baseline=0; s.reveal+=(s.targetReveal-s.reveal)*0.12; const reveal=easeOutCubic(clamp(s.reveal,0,1)); cb.onStateChange?.(reveal); if(reveal>=STEP_T&&!s.thresholdFired){s.thresholdFired=true; cb.onHaptic('drag_snap');} if(reveal>=COMPLETE_T&&!s.completionFired){s.completionFired=true; cb.onHaptic('completion'); cb.onResolve?.();}
   const primary=s.primaryRgb,accent=s.accentRgb,deep=lerpColor([4,6,10],primary,0.1), rock=lerpColor(accent,[134,126,118],0.22), line=lerpColor(primary,[245,247,255],0.86), warn=lerpColor([255,92,72],accent,0.2); ctx.fillStyle=rgba(deep,0.98*entrance); ctx.fillRect(0,0,w,h);
   const jitter=(1-reveal)*Math.sin(s.tremor)*minDim*0.004; roundedRect(ctx,w*0.14+jitter,h*0.28,w*0.72,h*0.44,minDim*0.03); ctx.fillStyle=rgba(rock,0.52*entrance); ctx.fill();
   ctx.beginPath(); ctx.moveTo(cx-minDim*0.02,h*0.3); ctx.lineTo(cx+minDim*0.02,h*0.7); ctx.strokeStyle=rgba(warn,(0.12+(1-reveal)*0.36)*entrance); ctx.lineWidth=px(0.004,minDim); ctx.stroke();
   if(reveal>0.1){ ctx.beginPath(); ctx.moveTo(cx-minDim*(0.02+reveal*0.12),cy); ctx.lineTo(cx+minDim*(0.02+reveal*0.12),cy); ctx.strokeStyle=rgba(line,reveal*entrance); ctx.lineWidth=px(0.012,minDim); ctx.stroke(); }
   ctx.restore(); raf=window.requestAnimationFrame(render); };
  const getPoint=(e:PointerEvent):Point=>{const rect=canvas.getBoundingClientRect(); return {x:((e.clientX-rect.left)/rect.width)*viewport.width,y:((e.clientY-rect.top)/rect.height)*viewport.height};};
  const onDown=(e:PointerEvent)=>{stateRef.current.pointers[e.pointerId]=getPoint(e); canvas.setPointerCapture(e.pointerId); callbacksRef.current.onHaptic('hold_start');}; const onMove=(e:PointerEvent)=>{if(!(e.pointerId in stateRef.current.pointers))return; stateRef.current.pointers[e.pointerId]=getPoint(e);}; const onUp=(e:PointerEvent)=>{delete stateRef.current.pointers[e.pointerId]; canvas.releasePointerCapture(e.pointerId);};
  raf=window.requestAnimationFrame(render); canvas.addEventListener('pointerdown',onDown); canvas.addEventListener('pointermove',onMove); canvas.addEventListener('pointerup',onUp); canvas.addEventListener('pointercancel',onUp); return ()=>{window.cancelAnimationFrame(raf); canvas.removeEventListener('pointerdown',onDown); canvas.removeEventListener('pointermove',onMove); canvas.removeEventListener('pointerup',onUp); canvas.removeEventListener('pointercancel',onUp);};
 },[viewport.width,viewport.height]);
 return <div style={{position:'absolute',inset:0}}><canvas ref={canvasRef} style={{display:'block',width:'100%',height:'100%',touchAction:'none'}}/></div>;
}
