/**
 * ATOM REGISTRY
 * =============
 *
 * Metadata for 700 interactive therapeutic atoms across 70 series.
 *
 * Each entry is a blueprint — it describes WHAT the atom is and
 * HOW it behaves, not how it looks. The component implements the look.
 *
 * ZERO imports from outside this folder.
 *
 * STATUS KEY:
 *   'designed'  — intent, physics, and interaction contract defined
 *   'building'  — component in active development
 *   'complete'  — shipped, tested, integrated
 */

import type { AtomId, AtomMeta } from './types';
import { SERIES_CATALOG } from './series-registry';
import { S11, S12, S13, S14, S15, S16, S17, S18, S19, S20 } from './atom-registry-c2';
import { S21, S22, S23, S24, S25, S26, S27, S28, S29, S30 } from './atom-registry-c3';
import { S31, S32, S33, S34, S35, S36, S37, S38, S39, S40 } from './atom-registry-c4';
import { S41, S42, S43, S44, S45, S46, S47, S48, S49, S50 } from './atom-registry-c5';
import { S51, S52, S53, S54, S55, S56, S57, S58, S59, S60 } from './atom-registry-c6';
import { S61, S62, S63, S64, S65, S66, S67, S68, S69, S70 } from './atom-registry-c7';

// =====================================================================
// SERIES 1: THE PHYSICS ENGINES (Atoms 1–10)
// =====================================================================

const S1: AtomMeta[] = [
  {
    id: 'chrono-kinetic',
    number: 1,
    series: 'physics-engines',
    seriesPosition: 1,
    name: 'The Chrono-Kinetic Engine',
    intent: 'Anxiety accelerates time; depression freezes it. This atom allows the user to manually take control of their perception of time, using physical gestures to slow down panic or fast-forward through temporary pain.',
    physics: 'Rotational friction, heavy digital flywheels, variable scrolling speeds. GSAP timelines mapped to touch-drag velocity.',
    renderMode: 'canvas',
    defaultScale: 'focus',
    surfaces: ['draggable', 'holdable', 'breathable'],
    hapticEvents: ['tap', 'drag_snap', 'hold_threshold'],
    hapticSignature: 'Heavy, clicking physical gear — rotational inertia with distinct detents',
    stateRange: [2, 8],
    continuous: true,
    hasResolution: false,
    breathCoupling: 'modulates',
    deviceRequirements: ['haptics'],
    implementations: ['Tempo Dial', 'Deep Time Scroll', 'Patience Muscle'],
    status: 'complete',
  },
  {
    id: 'phase-shift',
    number: 2,
    series: 'physics-engines',
    seriesPosition: 2,
    name: 'The Phase-Shift Engine',
    intent: 'Moving from brokenness to integration. The user actively repairs, melts, or transforms a toxic thought into a healthy one.',
    physics: 'Fluid dynamics, particle cohesion, vector path drawing. WebGL shaders for fluid — feels like melting ice, mixing paint, sealing glass.',
    renderMode: 'webgl',
    defaultScale: 'full',
    surfaces: ['tappable', 'draggable', 'breathable'],
    hapticEvents: ['tap', 'step_advance', 'completion'],
    hapticSignature: 'Warm, liquid flow that solidifies into a crystalline lock upon completion',
    stateRange: [2, 6],
    continuous: true,
    hasResolution: true,
    breathCoupling: 'modulates',
    deviceRequirements: ['haptics'],
    implementations: ['Kintsugi File', 'Shame Solvent', 'Color Soak'],
    status: 'complete',
  },
  {
    id: 'z-axis-parallax',
    number: 3,
    series: 'physics-engines',
    seriesPosition: 3,
    name: 'The Z-Axis Parallax Engine',
    intent: 'Cognitive fusion is the belief that "I am my thoughts." This atom forces the Overview Effect, using 3D depth to pull the user out of the narrative.',
    physics: 'Exponential camera zooms, multi-layered depth sorting, gyroscope-driven parallax. The Z-axis must feel infinite.',
    renderMode: 'webgl',
    defaultScale: 'full',
    surfaces: ['pinchable', 'gyroscopic', 'observable'],
    hapticEvents: ['breath_peak', 'step_advance'],
    hapticSignature: 'Shifts from claustrophobic buzz to massive, echoing, silent pulse',
    stateRange: [3, 10],
    continuous: true,
    hasResolution: false,
    breathCoupling: 'none',
    deviceRequirements: ['haptics', 'gyroscope'],
    implementations: ['Ego Zoom', 'Perspective Balcony', 'Negative Space'],
    status: 'complete',
  },
  {
    id: 'somatic-resonance',
    number: 4,
    series: 'physics-engines',
    seriesPosition: 4,
    name: 'The Somatic Resonance Engine',
    intent: 'You cannot reason with a hijacked amygdala. This atom bypasses the intellect entirely, using the device hardware to directly entrain the autonomic nervous system.',
    physics: 'Subsonic haptic frequencies, breath-synced scaling, audio waveforms. CoreHaptics as a musical instrument.',
    renderMode: 'canvas',
    defaultScale: 'full',
    surfaces: ['breathable', 'holdable', 'observable'],
    hapticEvents: ['breath_peak', 'hold_start', 'hold_threshold', 'hold_release'],
    hapticSignature: 'Meticulously crafted musical chord played through the haptic motor',
    stateRange: [2, 5],
    continuous: true,
    hasResolution: false,
    breathCoupling: 'drives',
    deviceRequirements: ['haptics', 'audio-output'],
    implementations: ['Vagal Hum', 'Bilateral Tap', 'Oxygen Flood'],
    status: 'complete',
  },
  {
    id: 'constructive-destructive',
    number: 5,
    series: 'physics-engines',
    seriesPosition: 5,
    name: 'The Constructive / Destructive Engine',
    intent: 'The physical manifestation of saying "No" or building a safe container. Highly tactile structural interactions.',
    physics: 'Rigid-body physics, gravity, particle shattering, magnetic snapping. Objects must have mass.',
    renderMode: 'canvas',
    defaultScale: 'field',
    surfaces: ['draggable', 'tappable', 'swipeable', 'holdable'],
    hapticEvents: ['tap', 'drag_snap', 'swipe_commit', 'completion'],
    hapticSignature: 'Satisfying solid clack of setting a boundary — immovable once placed',
    stateRange: [3, 8],
    continuous: false,
    hasResolution: true,
    breathCoupling: 'none',
    deviceRequirements: ['haptics'],
    implementations: ['Boundary Brick', 'Sunk Cost Cut', 'Notification Nuke'],
    status: 'complete',
  },
  {
    id: 'cryptographic',
    number: 6,
    series: 'physics-engines',
    seriesPosition: 6,
    name: 'The Cryptographic Engine',
    intent: 'The ego hides truth behind noise. The user peels back layers, decrypts signals, or wipes away fog to reveal core reality.',
    physics: 'Opacity masks, scratch-to-reveal mechanics, signal-to-noise sliders. Like wiping condensation off a mirror.',
    renderMode: 'canvas',
    defaultScale: 'full',
    surfaces: ['swipeable', 'draggable', 'tappable'],
    hapticEvents: ['swipe_commit', 'step_advance', 'completion'],
    hapticSignature: 'Surface friction giving way to smooth clarity — grit to glass',
    stateRange: [3, 7],
    continuous: false,
    hasResolution: true,
    breathCoupling: 'none',
    deviceRequirements: ['haptics'],
    implementations: ['Translator', 'Dust Off', 'Blur (Schrödinger)'],
    status: 'complete',
  },
  {
    id: 'symbiotic',
    number: 7,
    series: 'physics-engines',
    seriesPosition: 7,
    name: 'The Symbiotic Engine',
    intent: 'The ego operates in isolation; the Sovereign Mind operates in connection. Heals the illusion of separation.',
    physics: 'Elastic constraints, node-based routing, bezier spring tension, magnetic attraction. Taut stretching that resolves into a harmonic snap.',
    renderMode: 'svg',
    defaultScale: 'field',
    surfaces: ['draggable', 'tappable', 'typeable'],
    hapticEvents: ['drag_snap', 'step_advance', 'completion'],
    hapticSignature: 'Taut stretching tension that snaps into locked, harmonic unity',
    stateRange: [2, 6],
    continuous: true,
    hasResolution: true,
    breathCoupling: 'modulates',
    deviceRequirements: ['haptics'],
    implementations: ['Peace Thread', 'Connection Bridge', 'Repair Stitch'],
    status: 'complete',
  },
  {
    id: 'optical',
    number: 8,
    series: 'physics-engines',
    seriesPosition: 8,
    name: 'The Optical Engine',
    intent: 'You cannot always change the problem, but you can change the lens. Physically alters how the user sees the data.',
    physics: 'Lens blurs, depth-of-field focal pulls, color grading, light refraction. Like twisting a heavy DSLR focus ring.',
    renderMode: 'dom',
    defaultScale: 'full',
    surfaces: ['draggable', 'scrubable', 'tappable'],
    hapticEvents: ['drag_snap', 'step_advance'],
    hapticSignature: 'Heavy grooved focus ring — clicking softly until the image becomes razor-sharp',
    stateRange: [3, 8],
    continuous: true,
    hasResolution: false,
    breathCoupling: 'none',
    deviceRequirements: ['haptics'],
    implementations: ['Spotlight Shift', 'Color Grade', 'Contrast Adjust'],
    status: 'complete',
  },
  {
    id: 'equilibrium',
    number: 9,
    series: 'physics-engines',
    seriesPosition: 9,
    name: 'The Equilibrium Engine',
    intent: 'Restoring homeostasis. When pulled off center, this atom forces the user to physically re-calibrate their center of mass.',
    physics: 'Gyroscopic tilt, pendulum physics, fulcrums, weight distribution. DeviceOrientation API as hero.',
    renderMode: 'canvas',
    defaultScale: 'focus',
    surfaces: ['gyroscopic', 'draggable', 'breathable'],
    hapticEvents: ['drag_snap', 'completion'],
    hapticSignature: 'Rolling unbalanced rumble that clicks heavily and definitively at perfect zero-point equilibrium',
    stateRange: [2, 5],
    continuous: true,
    hasResolution: true,
    breathCoupling: 'modulates',
    deviceRequirements: ['haptics', 'gyroscope'],
    implementations: ['Drift Correction', 'Value Exchange', 'Leverage Lever'],
    status: 'complete',
  },
  {
    id: 'thermodynamic',
    number: 10,
    series: 'physics-engines',
    seriesPosition: 10,
    name: 'The Thermodynamic Engine',
    intent: 'Managing the heat of the nervous system. Cool anger, stoke motivation, or safely discharge excess emotional voltage.',
    physics: 'Particle velocity mapped to color/temperature, thermodynamic dissipation, fluid boiling/freezing. GLSL Perlin noise for fire/smoke/heat distortion.',
    renderMode: 'webgl',
    defaultScale: 'full',
    surfaces: ['tappable', 'draggable', 'holdable'],
    hapticEvents: ['tap', 'hold_start', 'hold_threshold', 'step_advance', 'completion'],
    hapticSignature: 'Chaotic violent popping crackle that interpolates into cool, slow, icy heartbeat',
    stateRange: [3, 8],
    continuous: true,
    hasResolution: true,
    breathCoupling: 'modulates',
    deviceRequirements: ['haptics'],
    implementations: ['Anger Forge', 'De-Escalation', 'Fire Stoke'],
    status: 'complete',
  },
];

// =====================================================================
// SERIES 2: THE QUANTUM MECHANICS (Atoms 11–20)
// =====================================================================

const S2: AtomMeta[] = [
  {
    id: 'wave-collapse',
    number: 11,
    series: 'quantum-mechanics',
    seriesPosition: 1,
    name: 'The Wave Collapse Engine',
    intent: 'Anxiety is a probability cloud — a million terrible things that might happen. Observing the data forces it to collapse into a single, manageable reality.',
    physics: 'Gaussian blur interpolation, procedural noise reduction, focal crystallisation. CSS backdrop-filter over WebGL particle clouds.',
    renderMode: 'webgl',
    defaultScale: 'full',
    surfaces: ['tappable', 'holdable', 'breathable'],
    hapticEvents: ['hold_start', 'hold_threshold', 'completion'],
    hapticSignature: 'Wide airy diffuse static that condenses into a single sharp crystalline ping at blur 0px',
    stateRange: [2, 5],
    continuous: true,
    hasResolution: true,
    breathCoupling: 'drives',
    deviceRequirements: ['haptics'],
    implementations: ['Wave Collapse', 'Raw Data'],
    status: 'complete',
  },
  {
    id: 'schrodinger-box',
    number: 12,
    series: 'quantum-mechanics',
    seriesPosition: 2,
    name: 'The Schrödinger Box Engine',
    intent: 'The ego demands immediate certainty. This atom trains the nervous system to hold two contradictory outcomes in superposition until the moment action is required.',
    physics: 'State-toggling variables, superposed visual rendering, cryptographic reveals. Two UI states oscillating via mix-blend-mode.',
    renderMode: 'dom',
    defaultScale: 'focus',
    surfaces: ['tappable', 'holdable', 'observable'],
    hapticEvents: ['tap', 'completion'],
    hapticSignature: 'Frantic coin toss that suddenly slaps flat onto the glass',
    stateRange: [2, 3],
    continuous: false,
    hasResolution: true,
    breathCoupling: 'none',
    deviceRequirements: ['haptics'],
    implementations: ['Schrödinger\'s Box', 'Quantum Coin'],
    status: 'complete',
  },
  {
    id: 'double-slit',
    number: 13,
    series: 'quantum-mechanics',
    seriesPosition: 3,
    name: 'The Double Slit Engine',
    intent: 'Physically proving that how the user looks at a problem literally changes the nature of the problem itself.',
    physics: 'Real-time transitioning between sine-wave mathematics and rigid particle grids. Toggle fluid ↔ grid based on touch.',
    renderMode: 'webgl',
    defaultScale: 'full',
    surfaces: ['tappable', 'observable'],
    hapticEvents: ['tap', 'step_advance'],
    hapticSignature: 'Liquid fluidity that snaps into crystalline rigidity the instant the finger lands',
    stateRange: [2, 2],
    continuous: false,
    hasResolution: false,
    breathCoupling: 'none',
    deviceRequirements: [],
    implementations: ['Double Slit'],
    status: 'complete',
  },
  {
    id: 'many-worlds',
    number: 14,
    series: 'quantum-mechanics',
    seriesPosition: 4,
    name: 'The Many-Worlds Engine',
    intent: 'Curing fatalism. Every micro-choice forks reality into infinite new timelines.',
    physics: 'Fractal branching path generation, multi-axis panning, ghost-trailing. SVG Bezier curves that branch on swipe direction.',
    renderMode: 'svg',
    defaultScale: 'field',
    surfaces: ['swipeable', 'draggable'],
    hapticEvents: ['swipe_commit', 'step_advance'],
    hapticSignature: 'Branching split — a fork felt in the fingertip, unchosen paths fading with a soft exhale',
    stateRange: [3, 8],
    continuous: false,
    hasResolution: true,
    breathCoupling: 'none',
    deviceRequirements: ['haptics'],
    implementations: ['Many-Worlds Map', 'Parallel Self Chat'],
    status: 'complete',
  },
  {
    id: 'entanglement',
    number: 15,
    series: 'quantum-mechanics',
    seriesPosition: 5,
    name: 'The Entanglement Engine',
    intent: 'Teaching that distance and separation are illusions. What you heal in yourself, you instantly heal in the network.',
    physics: 'Mirrored coordinate mapping, inverted axis tracking, zero-latency synchronisation. Touch one → the other mirrors instantly.',
    renderMode: 'canvas',
    defaultScale: 'field',
    surfaces: ['draggable', 'observable'],
    hapticEvents: ['drag_snap'],
    hapticSignature: 'Quantum lock — both particles vibrate identically, a harmonic mirror',
    stateRange: [2, 4],
    continuous: true,
    hasResolution: false,
    breathCoupling: 'modulates',
    deviceRequirements: ['haptics'],
    implementations: ['Entanglement Check', 'Spooky Action'],
    status: 'complete',
  },
  {
    id: 'uncertainty-blur',
    number: 16,
    series: 'quantum-mechanics',
    seriesPosition: 6,
    name: 'The Uncertainty Blur Engine',
    intent: 'The obsession with knowing exactly what will happen creates paralysis. Embrace momentum over perfect clarity.',
    physics: 'Inverse depth-of-field scaling based on pinch/zoom velocity. The harder they focus on micro, the blurrier it gets.',
    renderMode: 'dom',
    defaultScale: 'full',
    surfaces: ['pinchable', 'observable'],
    hapticEvents: ['step_advance'],
    hapticSignature: 'Slippery and evasive — the harder you grip, the more it slides away',
    stateRange: [2, 5],
    continuous: true,
    hasResolution: false,
    breathCoupling: 'none',
    deviceRequirements: ['haptics'],
    implementations: ['Uncertainty Blur'],
    status: 'complete',
  },
  {
    id: 'quantum-tunnel',
    number: 17,
    series: 'quantum-mechanics',
    seriesPosition: 7,
    name: 'The Quantum Tunnel Engine',
    intent: 'Seemingly impossible barriers contain microscopic space. You don\'t always have to break a wall; sometimes you can pass through it.',
    physics: 'Collision detection with 5% ghost/pass-through variable. Gentle persistence disables collision; force reinforces it.',
    renderMode: 'canvas',
    defaultScale: 'focus',
    surfaces: ['draggable', 'holdable'],
    hapticEvents: ['hold_start', 'hold_threshold', 'completion'],
    hapticSignature: 'Brick wall resistance softening into impossible, miraculous phase-through',
    stateRange: [2, 3],
    continuous: false,
    hasResolution: true,
    breathCoupling: 'none',
    deviceRequirements: ['haptics'],
    implementations: ['Quantum Tunnel'],
    status: 'complete',
  },
  {
    id: 'zero-point-field',
    number: 18,
    series: 'quantum-mechanics',
    seriesPosition: 8,
    name: 'The Zero-Point Field Engine',
    intent: 'Curing the fear of emptiness. The void is not dead — it is teeming with latent, infinite energy waiting for an architect.',
    physics: 'Ambient occlusion, hidden particle grids, pressure-sensitive revelation. Dense glowing grid at opacity 0, revealed by touch pressure.',
    renderMode: 'canvas',
    defaultScale: 'full',
    surfaces: ['holdable', 'pressure-sensitive', 'tappable'],
    hapticEvents: ['hold_start', 'hold_threshold', 'step_advance'],
    hapticSignature: 'Total silence erupting into dense, vibrating, hyper-energetic grid',
    stateRange: [2, 5],
    continuous: true,
    hasResolution: false,
    breathCoupling: 'none',
    deviceRequirements: ['haptics', 'pressure'],
    implementations: ['Zero Point', 'Dark Matter'],
    status: 'complete',
  },
  {
    id: 'retrocausal',
    number: 19,
    series: 'quantum-mechanics',
    seriesPosition: 9,
    name: 'The Retrocausal Engine',
    intent: 'The ego believes the past dictates the present. How you act today literally changes the structural meaning of yesterday.',
    physics: 'Reverse-time simulations, timeline scrubbing, structural re-rendering. Array manipulation — slider forward heals the past.',
    renderMode: 'dom',
    defaultScale: 'full',
    surfaces: ['scrubable', 'draggable'],
    hapticEvents: ['drag_snap', 'step_advance', 'completion'],
    hapticSignature: 'Time flowing backward — broken elements clicking back into wholeness',
    stateRange: [3, 8],
    continuous: true,
    hasResolution: true,
    breathCoupling: 'none',
    deviceRequirements: ['haptics'],
    implementations: ['Retrocausality', 'The Prequel'],
    status: 'complete',
  },
  {
    id: 'holographic',
    number: 20,
    series: 'quantum-mechanics',
    seriesPosition: 10,
    name: 'The Holographic Engine',
    intent: 'You are not a tiny broken piece. The entire universe is folded perfectly inside you.',
    physics: 'Recursive rendering, infinite Z-axis looping, fractal mathematics. Zoom in at 1000% → reveals the original scene inside.',
    renderMode: 'webgl',
    defaultScale: 'full',
    surfaces: ['pinchable', 'observable'],
    hapticEvents: ['step_advance'],
    hapticSignature: 'Infinite descent — each level a subtle harmonic of the last, never ending',
    stateRange: [2, 5],
    continuous: true,
    hasResolution: false,
    breathCoupling: 'none',
    deviceRequirements: [],
    implementations: ['Hologram', 'Net of Indra'],
    status: 'complete',
  },
];

// =====================================================================
// SERIES 3: THE BIOMIMETIC ALGORITHMS (Atoms 21–30)
// =====================================================================

const S3: AtomMeta[] = [
  {
    id: 'l-system-branching',
    number: 21,
    series: 'biomimetic-algorithms',
    seriesPosition: 1,
    name: 'The L-System Branching Engine',
    intent: 'Healing is not linear; it is fractal. A single micro-yes expands into a massive canopy of new pathways.',
    physics: 'Lindenmayer systems, procedural fractal generation, organic easing. Growth with hesitation and burst of living tissue.',
    renderMode: 'canvas',
    defaultScale: 'full',
    surfaces: ['tappable', 'breathable', 'observable'],
    hapticEvents: ['tap', 'breath_peak', 'step_advance'],
    hapticSignature: 'Slow deep woody creak — living tissue pushing through soil',
    stateRange: [3, 10],
    continuous: true,
    hasResolution: false,
    breathCoupling: 'drives',
    deviceRequirements: ['haptics'],
    implementations: ['Root Drop', 'Generational Lens'],
    status: 'complete',
  },
  {
    id: 'boids-flocking',
    number: 22,
    series: 'biomimetic-algorithms',
    seriesPosition: 2,
    name: 'The Boids Flocking Engine',
    intent: 'The ego believes it is a dictator. The Sovereign Mind knows it is a parliament. Guide chaotic thoughts like a flock — influence, not force.',
    physics: 'Craig Reynolds\' Boids (Cohesion, Alignment, Separation). Touch as gentle attractor; move too fast → flock scatters.',
    renderMode: 'canvas',
    defaultScale: 'full',
    surfaces: ['draggable', 'tappable', 'holdable'],
    hapticEvents: ['hold_start', 'step_advance'],
    hapticSignature: 'Scattered chaos harmonising into unified flow — birds finding formation',
    stateRange: [2, 5],
    continuous: true,
    hasResolution: false,
    breathCoupling: 'modulates',
    deviceRequirements: ['haptics'],
    implementations: ['Hive Mind', 'Signal Pulse'],
    status: 'complete',
  },
  {
    id: 'composting',
    number: 23,
    series: 'biomimetic-algorithms',
    seriesPosition: 3,
    name: 'The Composting Engine',
    intent: 'Destroying the concept of a mistake. In nature there is no trash; only fertiliser.',
    physics: 'Cellular decay, particle settling, organic chromatic shifting. SVG feTurbulence + feDisplacementMap for dissolution.',
    renderMode: 'svg',
    defaultScale: 'field',
    surfaces: ['tappable', 'draggable'],
    hapticEvents: ['tap', 'step_advance', 'completion'],
    hapticSignature: 'Crumbling dissolution followed by warm, rising nutrient glow',
    stateRange: [3, 6],
    continuous: false,
    hasResolution: true,
    breathCoupling: 'none',
    deviceRequirements: ['haptics'],
    implementations: ['Regret Compost', 'Composting'],
    status: 'complete',
  },
  {
    id: 'mycelial-routing',
    number: 24,
    series: 'biomimetic-algorithms',
    seriesPosition: 4,
    name: 'The Mycelial Routing Engine',
    intent: 'Actions don\'t exist in a vacuum. Every decision sends nutrients across a vast invisible network.',
    physics: 'Algorithmic pathfinding (A*/Dijkstra), node-linking, pulse-wave telemetry. Light packets racing along bezier curves.',
    renderMode: 'webgl',
    defaultScale: 'full',
    surfaces: ['tappable', 'breathable', 'observable'],
    hapticEvents: ['tap', 'breath_peak', 'step_advance'],
    hapticSignature: 'Racing branching electrical current — lightning through roots',
    stateRange: [2, 8],
    continuous: true,
    hasResolution: false,
    breathCoupling: 'drives',
    deviceRequirements: ['haptics'],
    implementations: ['Invisible Thread', 'Mycelial Map'],
    status: 'complete',
  },
  {
    id: 'symbiosis',
    number: 25,
    series: 'biomimetic-algorithms',
    seriesPosition: 5,
    name: 'The Symbiosis Engine',
    intent: 'Burnout comes from believing you must constantly output. You cannot exhale forever; let the forest breathe back into you.',
    physics: 'Bidirectional particle flow, perfect equilibrium, loop mechanics. Circular emitters — closed-loop, nothing lost.',
    renderMode: 'canvas',
    defaultScale: 'field',
    surfaces: ['scrubable', 'breathable', 'observable'],
    hapticEvents: ['breath_peak', 'drag_snap'],
    hapticSignature: 'Rising swell of inhale followed by falling, comforting rush of exhale',
    stateRange: [2, 4],
    continuous: true,
    hasResolution: false,
    breathCoupling: 'drives',
    deviceRequirements: ['haptics'],
    implementations: ['Breath Exchange', 'Symbiosis Check'],
    status: 'complete',
  },
  {
    id: 'pruning',
    number: 26,
    series: 'biomimetic-algorithms',
    seriesPosition: 6,
    name: 'The Pruning Engine',
    intent: 'Boundary setting as ecological maintenance. Not cutting off in anger; pruning dead branches so fruit can grow.',
    physics: 'Snapping geometry, severing links, flow redirection. Heavy shears — intense resistance then violent snap.',
    renderMode: 'svg',
    defaultScale: 'field',
    surfaces: ['swipeable', 'tappable'],
    hapticEvents: ['swipe_commit', 'completion'],
    hapticSignature: 'Heavy garden shears — intense kinetic resistance then sharp violent snap, followed by soft swelling glow',
    stateRange: [3, 6],
    continuous: false,
    hasResolution: true,
    breathCoupling: 'none',
    deviceRequirements: ['haptics'],
    implementations: ['Pruning Shears', 'Kill Your Darlings'],
    status: 'complete',
  },
  {
    id: 'dormancy',
    number: 27,
    series: 'biomimetic-algorithms',
    seriesPosition: 7,
    name: 'The Dormancy Engine',
    intent: 'The ego panics when not producing. This atom visualises winter: nothing happens on the surface, but massive architecture is built in the dark.',
    physics: 'Sub-surface activity, masking layers, slow-pulsing heat maps. CSS mask-image or WebGL depth testing.',
    renderMode: 'dom',
    defaultScale: 'full',
    surfaces: ['holdable', 'observable'],
    hapticEvents: ['hold_start', 'hold_threshold'],
    hapticSignature: 'Complete silence above — deep rapid heartbeat revealed only when you peek beneath',
    stateRange: [2, 4],
    continuous: false,
    hasResolution: false,
    breathCoupling: 'none',
    deviceRequirements: ['haptics'],
    implementations: ['Winter Rest', 'Chrysalis Wait'],
    status: 'complete',
  },
  {
    id: 'ecosystem-balancer',
    number: 28,
    series: 'biomimetic-algorithms',
    seriesPosition: 8,
    name: 'The Ecosystem Balancer',
    intent: 'The old paradigm fights bad habits. The ecological paradigm introduces counter-balances. You don\'t fight the dark; you add more light.',
    physics: 'Lotka-Volterra fluid equations, color mixing, dynamic equilibrium. Fluid dynamics sandbox.',
    renderMode: 'canvas',
    defaultScale: 'full',
    surfaces: ['draggable', 'tappable'],
    hapticEvents: ['drag_snap', 'step_advance'],
    hapticSignature: 'Chemical harmony — chaotic particles settling into balanced organic rhythm',
    stateRange: [3, 6],
    continuous: true,
    hasResolution: true,
    breathCoupling: 'modulates',
    deviceRequirements: ['haptics'],
    implementations: ['Ecosystem Balance'],
    status: 'complete',
  },
  {
    id: 'pollination',
    number: 29,
    series: 'biomimetic-algorithms',
    seriesPosition: 9,
    name: 'The Pollination Engine',
    intent: 'Breaking isolated, rigid thinking. Good ideas are sterile alone — they need to cross-pollinate to survive.',
    physics: 'Wind-driven particle dynamics, collision detection, procedural blooming. Particle A hits Target B → flower blooms.',
    renderMode: 'canvas',
    defaultScale: 'field',
    surfaces: ['draggable', 'tappable'],
    hapticEvents: ['tap', 'drag_snap', 'completion'],
    hapticSignature: 'Seeds scattering in wind, then sudden bursting bloom on collision',
    stateRange: [3, 8],
    continuous: false,
    hasResolution: true,
    breathCoupling: 'modulates',
    deviceRequirements: ['haptics'],
    implementations: ['Pollinator', 'Seed Bank'],
    status: 'complete',
  },
  {
    id: 'erosion',
    number: 30,
    series: 'biomimetic-algorithms',
    seriesPosition: 10,
    name: 'The Erosion Engine',
    intent: 'Calming the desire for instant transformation. Nature does not use hammers; it uses water and time.',
    physics: 'Procedural mesh deformation, smoothing algorithms, continuous fluid pressure. WebGL displacement map with decreasing roughness.',
    renderMode: 'webgl',
    defaultScale: 'focus',
    surfaces: ['holdable', 'observable'],
    hapticEvents: ['hold_start', 'hold_threshold', 'completion'],
    hapticSignature: 'Rough abrasive scratch transitioning to perfectly smooth polished glide',
    stateRange: [2, 5],
    continuous: true,
    hasResolution: true,
    breathCoupling: 'none',
    deviceRequirements: ['haptics'],
    implementations: ['Water Flow'],
    status: 'complete',
  },
];

// =====================================================================
// SERIES 4–10: DESIGNED ATOMS (2 per series from blueprint)
// + placeholder entries for the remaining 8 per series
// =====================================================================

function placeholder(
  id: AtomId,
  number: number,
  series: AtomMeta['series'],
  seriesPosition: number,
): AtomMeta {
  return {
    id,
    number,
    series,
    seriesPosition,
    name: `${series} #${seriesPosition}`,
    intent: 'Pending design — series structure reserved',
    physics: 'To be defined',
    renderMode: 'canvas',
    defaultScale: 'focus',
    surfaces: ['observable'],
    hapticEvents: [],
    hapticSignature: 'Pending',
    stateRange: [2, 5],
    continuous: true,
    hasResolution: false,
    breathCoupling: 'modulates',
    deviceRequirements: [],
    implementations: [],
    status: 'designed',
  };
}

const S4: AtomMeta[] = [
  {
    id: 'sensory-deprivation',
    number: 31,
    series: 'via-negativa',
    seriesPosition: 1,
    name: 'The Sensory Deprivation Engine',
    intent: 'The screen goes completely dark. No haptics. No UI. The user floats in OLED blackness before text emerges.',
    physics: 'Pure negative space, timed reveals, absolute minimalism.',
    renderMode: 'dom',
    defaultScale: 'full',
    surfaces: ['observable'],
    hapticEvents: ['entrance_land'],
    hapticSignature: 'Total absence — then a single, devastating emergence',
    stateRange: [2, 3],
    continuous: false,
    hasResolution: true,
    breathCoupling: 'none',
    deviceRequirements: [],
    implementations: ['Sensory Deprivation'],
    status: 'complete',
  },
  {
    id: 'un-naming',
    number: 32,
    series: 'via-negativa',
    seriesPosition: 2,
    name: 'The Un-Naming Engine',
    intent: 'The screen is cluttered with labels and judgments. The user physically rubs them out, erasing text to reveal pure geometric reality.',
    physics: 'Canvas masking, scratch-to-reveal, progressive erasure.',
    renderMode: 'canvas',
    defaultScale: 'full',
    surfaces: ['drawable', 'swipeable'],
    hapticEvents: ['swipe_commit', 'step_advance', 'completion'],
    hapticSignature: 'Labels dissolving under pressure — rough text giving way to clean geometry',
    stateRange: [3, 8],
    continuous: false,
    hasResolution: true,
    breathCoupling: 'none',
    deviceRequirements: ['haptics'],
    implementations: ['Un-Naming'],
    status: 'complete',
  },
  {
    id: 'figure-ground-reversal',
    number: 33,
    series: 'via-negativa',
    seriesPosition: 3,
    name: 'The Figure-Ground Reversal Engine',
    intent: 'The ego believes it is the most important object. This atom dissolves the figure into the ground, revealing that the space was always the protagonist.',
    physics: 'Procedural mandala dissolution, attachment decay, background luminosity inversion, particle emission.',
    renderMode: 'canvas',
    defaultScale: 'full',
    surfaces: ['holdable', 'observable'],
    hapticEvents: ['hold_start', 'step_advance', 'completion'],
    hapticSignature: 'Ego trembling then dissolving — solid structure giving way to spacious emptiness',
    stateRange: [2, 5],
    continuous: true,
    hasResolution: true,
    breathCoupling: 'none',
    deviceRequirements: ['haptics'],
    implementations: ['Ego Death', 'Negative Space'],
    status: 'complete',
  },
  {
    id: 'vacuum-seal',
    number: 34,
    series: 'via-negativa',
    seriesPosition: 4,
    name: 'The Vacuum Seal Engine',
    intent: 'When the mind is too loud, suffocate the noise. Chaotic particles implode under containment pressure and seal away.',
    physics: 'Reverse-particle emitters, implosion toward center, containment radius shrinking, instant seal moment.',
    renderMode: 'canvas',
    defaultScale: 'full',
    surfaces: ['holdable', 'draggable'],
    hapticEvents: ['hold_start', 'step_advance', 'seal_stamp'],
    hapticSignature: 'Chaotic buzzing compressed to silence — then one devastating metallic vault clack',
    stateRange: [2, 5],
    continuous: true,
    hasResolution: true,
    breathCoupling: 'none',
    deviceRequirements: ['haptics'],
    implementations: ['Silence Vacuum'],
    status: 'complete',
  },
  {
    id: 'dark-matter',
    number: 35,
    series: 'via-negativa',
    seriesPosition: 5,
    name: 'The Dark Matter Engine',
    intent: 'You do not need to be loud or visible to have massive influence. Your invisible gravity bends everything around it.',
    physics: 'Invisible gravity wells, gravitational lensing on dust motes and light filaments, inverse-square orbital deflection.',
    renderMode: 'canvas',
    defaultScale: 'full',
    surfaces: ['holdable', 'observable'],
    hapticEvents: ['hold_start', 'hold_threshold'],
    hapticSignature: 'Deep invisible pull — spacetime warping around your presence',
    stateRange: [2, 5],
    continuous: true,
    hasResolution: false,
    breathCoupling: 'modulates',
    deviceRequirements: ['haptics'],
    implementations: ['Dark Matter'],
    status: 'complete',
  },
  {
    id: 'static-clear',
    number: 36,
    series: 'via-negativa',
    seriesPosition: 6,
    name: 'The Static Clear Engine',
    intent: 'Anxiety is just static. The true signal is always underneath, waiting for the interference to be cleared.',
    physics: 'Procedural noise generation, scratch-to-reveal masking, auto-dissolve at threshold, CRT scan lines.',
    renderMode: 'canvas',
    defaultScale: 'full',
    surfaces: ['drawable', 'swipeable'],
    hapticEvents: ['swipe_commit', 'step_advance', 'completion'],
    hapticSignature: 'Static crackle under finger giving way to smooth signal clarity',
    stateRange: [3, 8],
    continuous: false,
    hasResolution: true,
    breathCoupling: 'none',
    deviceRequirements: ['haptics'],
    implementations: ['Static Clear', 'Frequency Tune'],
    status: 'complete',
  },
  {
    id: 'apneic-pause',
    number: 37,
    series: 'via-negativa',
    seriesPosition: 7,
    name: 'The Apneic Pause Engine',
    intent: 'Most breathwork focuses on inhale and exhale. This atom focuses on the cessation — the absolute stillness at the bottom of the exhale where wisdom lives.',
    physics: 'Decelerating expansion, suspended animation, zero-velocity states. All animations freeze on hold.',
    renderMode: 'canvas',
    defaultScale: 'full',
    surfaces: ['holdable', 'breathable', 'observable'],
    hapticEvents: ['hold_start', 'breath_peak', 'hold_release'],
    hapticSignature: 'Total systemic cessation — silence so complete it has weight',
    stateRange: [2, 5],
    continuous: true,
    hasResolution: false,
    breathCoupling: 'drives',
    deviceRequirements: ['haptics'],
    implementations: ['Breath Hold', 'Breath Gap'],
    status: 'complete',
  },
  {
    id: 'format-reset',
    number: 38,
    series: 'via-negativa',
    seriesPosition: 8,
    name: 'The Format/Reset Engine',
    intent: 'Sometimes you just need to format the hard drive and restart. No analysis. No processing. Just wipe.',
    physics: 'System-level wipe aesthetics, progress ring, flashbang white-out, void phase, reboot cursor.',
    renderMode: 'canvas',
    defaultScale: 'full',
    surfaces: ['holdable'],
    hapticEvents: ['hold_start', 'step_advance', 'seal_stamp', 'entrance_land'],
    hapticSignature: 'Terrifying 3-second charge → devastating flashbang → void silence → gentle reboot',
    stateRange: [2, 5],
    continuous: false,
    hasResolution: true,
    breathCoupling: 'none',
    deviceRequirements: ['haptics'],
    implementations: ['Reset Button', 'Game Reset'],
    status: 'complete',
  },
  {
    id: 'noise-gate',
    number: 39,
    series: 'via-negativa',
    seriesPosition: 9,
    name: 'The Noise Gate Engine',
    intent: 'Not every thought or critique deserves to be heard. Set a threshold for what enters consciousness.',
    physics: 'Visual threshold clipping, frequency gating, multi-waveform rendering with amplitude-based deletion.',
    renderMode: 'canvas',
    defaultScale: 'full',
    surfaces: ['draggable', 'scrubable'],
    hapticEvents: ['drag_snap', 'step_advance', 'completion'],
    hapticSignature: 'Chaotic noise silenced notch by notch — until only the sovereign signal remains',
    stateRange: [3, 8],
    continuous: true,
    hasResolution: true,
    breathCoupling: 'none',
    deviceRequirements: ['haptics'],
    implementations: ['Noise Gate', 'Mute Button'],
    status: 'complete',
  },
  {
    id: 'singularity',
    number: 40,
    series: 'via-negativa',
    seriesPosition: 10,
    name: 'The Singularity Engine',
    intent: 'The ultimate Via Negativa. Zero is the origin point of all geometry, time, and potential. Collapse complexity into a single point of absolute power.',
    physics: 'Infinite compression, orbital collapse, singularity rendering, post-singularity breath-coupled dot.',
    renderMode: 'canvas',
    defaultScale: 'full',
    surfaces: ['holdable', 'pinchable'],
    hapticEvents: ['hold_start', 'step_advance', 'seal_stamp', 'breath_peak'],
    hapticSignature: 'Massive gravitational implosion → crystalline ringing silence → the dot breathes',
    stateRange: [2, 5],
    continuous: true,
    hasResolution: true,
    breathCoupling: 'modulates',
    deviceRequirements: ['haptics'],
    implementations: ['Zero Seal'],
    status: 'complete',
  },
];

const S5: AtomMeta[] = [
  {
    id: 'phase-lock',
    number: 41,
    series: 'chrono-acoustic',
    seriesPosition: 1,
    name: 'The Phase Lock Engine',
    intent: 'Two conflicting waveforms visualised. The user drags them into alignment — chaotic audio phase-shifts into a resonant chord.',
    physics: 'Web Audio API, dual oscillator visualisation, phase alignment mechanics.',
    renderMode: 'audio',
    defaultScale: 'field',
    surfaces: ['draggable', 'observable'],
    hapticEvents: ['drag_snap', 'completion'],
    hapticSignature: 'Grating dissonance resolving into breathtaking resonant harmony with full-device hum',
    stateRange: [2, 5],
    continuous: true,
    hasResolution: true,
    breathCoupling: 'none',
    deviceRequirements: ['haptics', 'audio-output'],
    implementations: ['Phase Lock'],
    status: 'complete',
  },
  {
    id: 'vagal-hum',
    number: 42,
    series: 'chrono-acoustic',
    seriesPosition: 2,
    name: 'The Vagal Hum Engine',
    intent: 'The device pulses at a specific frequency. The user hums along until their lips buzz, creating real-time biological coherence.',
    physics: 'Web Audio oscillator, microphone input analysis, frequency matching.',
    renderMode: 'audio',
    defaultScale: 'focus',
    surfaces: ['voice', 'breathable', 'observable'],
    hapticEvents: ['breath_peak', 'completion'],
    hapticSignature: 'Device vibration at vagal frequency — resonance when the user\'s hum matches',
    stateRange: [2, 4],
    continuous: true,
    hasResolution: true,
    breathCoupling: 'drives',
    deviceRequirements: ['haptics', 'microphone', 'audio-output'],
    implementations: ['Vagal Hum'],
    status: 'complete',
  },
  {
    id: 'isochronic-pacer',
    number: 43,
    series: 'chrono-acoustic',
    seriesPosition: 3,
    name: 'The Isochronic Pacer Engine',
    intent: 'The anxious brain fires erratically. Isochronic tones force brainwaves to sync to a steady, predictable grid — neural entrainment through precision timing.',
    physics: 'Web Audio API scheduling (not setInterval), metronomic visual scaling, isochronic tone gating, 4-7-8 breath overlay.',
    renderMode: 'audio',
    defaultScale: 'focus',
    surfaces: ['holdable', 'breathable', 'observable'],
    hapticEvents: ['tap', 'step_advance', 'completion'],
    hapticSignature: 'Perfectly timed subsonic thuds at resting heart rate — neural grid locking into place',
    stateRange: [2, 5],
    continuous: true,
    hasResolution: true,
    breathCoupling: 'modulates',
    deviceRequirements: ['haptics', 'audio-output'],
    implementations: ['Isochronic Focus', '4-7-8 Haptic Pacer'],
    status: 'complete',
  },
  {
    id: 'cymatic-coherence',
    number: 44,
    series: 'chrono-acoustic',
    seriesPosition: 4,
    name: 'The Cymatic Coherence Engine',
    intent: 'Translates internal chaos into visible geometry. Touch stillness smooths jagged harmonics into a perfect cymatic mandala — proof that calm has a shape.',
    physics: 'Fourier harmonic superposition, polar cymatic rendering, phase alignment, touch-velocity-driven chaos injection.',
    renderMode: 'canvas',
    defaultScale: 'full',
    surfaces: ['holdable', 'breathable', 'observable'],
    hapticEvents: ['hold_start', 'step_advance', 'completion'],
    hapticSignature: 'Jagged erratic tremor smoothing into perfect geometric symmetry',
    stateRange: [2, 5],
    continuous: true,
    hasResolution: true,
    breathCoupling: 'modulates',
    deviceRequirements: ['haptics'],
    implementations: ['Heart Coherence Visualizer', 'Sound Bath'],
    status: 'complete',
  },
  {
    id: 'audio-zoom',
    number: 45,
    series: 'chrono-acoustic',
    seriesPosition: 5,
    name: 'The Audio Zoom Engine',
    intent: 'In overwhelm, everything feels equally loud. The user surgically isolates the one true signal hidden inside a wall of noise.',
    physics: 'Multi-band frequency spectrum, bandpass BiquadFilterNode, focal window narrowing, white noise → bell chime isolation.',
    renderMode: 'audio',
    defaultScale: 'full',
    surfaces: ['draggable', 'holdable', 'observable'],
    hapticEvents: ['drag_snap', 'step_advance', 'completion'],
    hapticSignature: 'Dense chaotic noise field narrowing to a single pure bell chime — clarity from cacophony',
    stateRange: [2, 5],
    continuous: true,
    hasResolution: true,
    breathCoupling: 'none',
    deviceRequirements: ['haptics', 'audio-output'],
    implementations: ['Audio Zoom', 'Overtone', 'Signal in the Noise'],
    status: 'complete',
  },
  {
    id: 'brown-noise',
    number: 46,
    series: 'chrono-acoustic',
    seriesPosition: 6,
    name: 'The Brown Noise Engine',
    intent: 'Sometimes the world is too sharp. Brown noise mimics the deep roar of a waterfall, masking anxiety transients with a protective blanket of sound.',
    physics: 'Procedural Brownian noise generation, low-pass filter with user-controlled cutoff, visual blanket descent.',
    renderMode: 'audio',
    defaultScale: 'full',
    surfaces: ['draggable', 'holdable', 'observable'],
    hapticEvents: ['hold_start', 'step_advance', 'completion'],
    hapticSignature: 'Sharp crystalline world muffling into deep, safe, waterfall rumble',
    stateRange: [2, 5],
    continuous: true,
    hasResolution: true,
    breathCoupling: 'modulates',
    deviceRequirements: ['haptics', 'audio-output'],
    implementations: ['Brown Noise Blanket', 'Silence Soak'],
    status: 'complete',
  },
  {
    id: 'tempo-override',
    number: 47,
    series: 'chrono-acoustic',
    seriesPosition: 7,
    name: 'The Tempo Override Engine',
    intent: 'The conscious mind is too slow to interrupt a panic attack, but the body can intercept it through rhythm. The user taps a new, slower, dominant beat and the frantic environment decelerates to match.',
    physics: 'Tap-tempo detection, exponential weighted moving average of inter-tap intervals, environment BPM lerp with momentum inertia.',
    renderMode: 'audio',
    defaultScale: 'full',
    surfaces: ['tappable', 'observable'],
    hapticEvents: ['tap', 'step_advance', 'completion'],
    hapticSignature: 'Frantic heartbeat decelerating under the user\'s dominant rhythm — panic yielding to sovereignty',
    stateRange: [2, 5],
    continuous: true,
    hasResolution: true,
    breathCoupling: 'none',
    deviceRequirements: ['haptics'],
    implementations: ['Rhythm Game', 'Tempo Dial', 'Tempo Control'],
    status: 'complete',
  },
  {
    id: 'crescendo',
    number: 48,
    series: 'chrono-acoustic',
    seriesPosition: 8,
    name: 'The Crescendo Engine',
    intent: 'Suppressing an emotion just stores it. This atom provides a safe container — long-press to build to absolute peak, then release for cathartic silence.',
    physics: 'Exponential gain amplification (ease-in curve), particle convergence/burst, audio swell with instant zero-drop on release.',
    renderMode: 'audio',
    defaultScale: 'full',
    surfaces: ['holdable', 'observable'],
    hapticEvents: ['hold_start', 'completion'],
    hapticSignature: 'Terrifying exponential buildup → devastating instant silence → soft beautiful echo',
    stateRange: [2, 5],
    continuous: true,
    hasResolution: true,
    breathCoupling: 'none',
    deviceRequirements: ['haptics', 'audio-output'],
    implementations: ['Crescendo', 'Feral Howl'],
    status: 'complete',
  },
  {
    id: 'standing-wave',
    number: 49,
    series: 'chrono-acoustic',
    seriesPosition: 9,
    name: 'The Standing Wave Engine',
    intent: 'True peace is not the absence of energy — it is energy in perfect balance. A standing wave contains massive power but appears completely still.',
    physics: 'Counter-propagating sine waves, frequency matching via drag, node/antinode visualisation, standing wave envelope rendering.',
    renderMode: 'audio',
    defaultScale: 'full',
    surfaces: ['draggable', 'observable'],
    hapticEvents: ['drag_snap', 'step_advance', 'completion'],
    hapticSignature: 'Chaotic interference freezing into dynamic stillness — continuous unwavering hum',
    stateRange: [2, 5],
    continuous: true,
    hasResolution: true,
    breathCoupling: 'modulates',
    deviceRequirements: ['haptics', 'audio-output'],
    implementations: ['Standing Wave', 'Universal Hum'],
    status: 'complete',
  },
  {
    id: 'silent-rest',
    number: 50,
    series: 'chrono-acoustic',
    seriesPosition: 10,
    name: 'The Silent Rest Engine',
    intent: 'The music is not the notes — it is the space between them. The user must resist tapping during 5 seconds of profound silence to earn the next note.',
    physics: 'Timed suspension, anti-interaction detection, sequential note arcs, silence counter with reset on touch.',
    renderMode: 'canvas',
    defaultScale: 'full',
    surfaces: ['observable'],
    hapticEvents: ['entrance_land', 'tap', 'completion'],
    hapticSignature: 'Beautiful arcs playing → devastating silence → the softest, most beautiful note earned through stillness',
    stateRange: [2, 5],
    continuous: false,
    hasResolution: true,
    breathCoupling: 'none',
    deviceRequirements: ['haptics'],
    implementations: ['Rest Note', 'Pause as Currency'],
    status: 'complete',
  },
];

const S6: AtomMeta[] = [
  {
    id: 'fourth-wall-break',
    number: 51,
    series: 'meta-system-glitch',
    seriesPosition: 1,
    name: 'The Fourth Wall Break Engine',
    intent: 'The UI appears to freeze or glitch into a terminal window. The clean aesthetic falls away to reveal raw source code of the user\'s belief system.',
    physics: 'Intentional UI tearing, CSS distortion, terminal aesthetics, editable variable injection.',
    renderMode: 'dom',
    defaultScale: 'full',
    surfaces: ['typeable', 'observable'],
    hapticEvents: ['entrance_land', 'step_advance', 'completion'],
    hapticSignature: 'Digital distortion — screen tearing followed by the cold clarity of raw code',
    stateRange: [3, 6],
    continuous: false,
    hasResolution: true,
    breathCoupling: 'none',
    deviceRequirements: ['haptics'],
    implementations: ['Fourth Wall Break', 'Fourth Wall (Omega Point)'],
    status: 'complete',
  },
  {
    id: 'lag-spike',
    number: 52,
    series: 'meta-system-glitch',
    seriesPosition: 2,
    name: 'The Lag Spike Engine',
    intent: 'The ego expects instant digital gratification. A 3-second intentional delay traps the user in their own frustration — turning a UI flaw into a profound mindfulness trigger.',
    physics: 'Artificial event suppression, frozen visual feedback for exactly 3000ms, smooth post-delay transition.',
    renderMode: 'canvas',
    defaultScale: 'full',
    surfaces: ['tappable', 'observable'],
    hapticEvents: ['step_advance', 'completion'],
    hapticSignature: 'Frozen nothing — absolute dead silence — then a single gentle pulse that says "you\'re still here"',
    stateRange: [2, 3],
    continuous: false,
    hasResolution: true,
    breathCoupling: 'modulates',
    deviceRequirements: ['haptics'],
    implementations: ['Lag Spike'],
    status: 'complete',
  },
  {
    id: 'phantom-alert',
    number: 53,
    series: 'meta-system-glitch',
    seriesPosition: 3,
    name: 'The Phantom Alert Engine',
    intent: 'Exposes the user\'s biological addiction to the red badge. Mimics native notification alerts to trigger the heart rate spike, then immediately deconstructs it.',
    physics: 'Native UI mimicry, particle dissolution on touch, gravity-pulled ash, color desaturation.',
    renderMode: 'canvas',
    defaultScale: 'full',
    surfaces: ['tappable', 'observable'],
    hapticEvents: ['entrance_land', 'tap', 'completion'],
    hapticSignature: 'The dopamine spike of a red badge — then hollow deflating ash — then devastating quiet',
    stateRange: [2, 5],
    continuous: false,
    hasResolution: true,
    breathCoupling: 'none',
    deviceRequirements: ['haptics'],
    implementations: ['Fake Notification', 'Notification Nuke'],
    status: 'complete',
  },
  {
    id: 'kernel-panic',
    number: 54,
    series: 'meta-system-glitch',
    seriesPosition: 4,
    name: 'The Kernel Panic Engine',
    intent: 'When the brain is stuck in a catastrophic rumination loop, the system has crashed. We visualise this as a fatal error — CRT tearing, hex dumps, blue screen — forcing a hard reboot of the psyche.',
    physics: 'CRT screen tearing via canvas scan-line displacement, chromatic aberration (triple RGB text rendering), hexadecimal memory dump scrolling, deterministic crash sequence.',
    renderMode: 'canvas',
    defaultScale: 'full',
    surfaces: ['tappable', 'observable'],
    hapticEvents: ['entrance_land', 'step_advance', 'completion'],
    hapticSignature: 'Harsh electrical buzz at crash — dead silence at halt — warm return at reboot',
    stateRange: [3, 6],
    continuous: false,
    hasResolution: true,
    breathCoupling: 'modulates',
    deviceRequirements: ['haptics'],
    implementations: ['Blue Screen', 'Hex Dump'],
    status: 'complete',
  },
  {
    id: 'algorithm-jammer',
    number: 55,
    series: 'meta-system-glitch',
    seriesPosition: 5,
    name: 'The Algorithm Jammer Engine',
    intent: 'Physically arrests the kinetic momentum of the infinite scroll. Massive digital friction grinds the dopamine loop to a shuddering halt.',
    physics: 'High-velocity Y-axis tile scrolling, exponential friction (v *= 0.93/frame), velocity-mapped blur stretching, horizontal shudder jitter, speed-tier haptic grinding.',
    renderMode: 'canvas',
    defaultScale: 'full',
    surfaces: ['holdable', 'observable'],
    hapticEvents: ['hold_start', 'drag_snap', 'completion'],
    hapticSignature: 'Grinding deceleration — shuddering drag snaps at each speed tier — devastating silence at full stop',
    stateRange: [2, 5],
    continuous: true,
    hasResolution: true,
    breathCoupling: 'modulates',
    deviceRequirements: ['haptics'],
    implementations: ['Algorithm Jammer', 'Doomscroll Brake'],
    status: 'complete',
  },
  {
    id: 'reality-tear',
    number: 56,
    series: 'meta-system-glitch',
    seriesPosition: 6,
    name: 'The Reality Tear Engine',
    intent: 'Proves that limiting beliefs are not physical laws — they are lines of code that can be rewritten. The user tears a UI element apart to reveal its source code and flips the variable.',
    physics: 'Horizontal drag tears card via jagged clipping paths, source code layer exposed behind tear, tappable variable state flip, reform animation with breath-coupled glow.',
    renderMode: 'canvas',
    defaultScale: 'full',
    surfaces: ['draggable', 'tappable'],
    hapticEvents: ['drag_snap', 'step_advance', 'completion'],
    hapticSignature: 'Tearing friction as the drag pulls — the decisive click of the variable flip — warm seal as the card reforms',
    stateRange: [3, 5],
    continuous: false,
    hasResolution: true,
    breathCoupling: 'modulates',
    deviceRequirements: ['haptics'],
    implementations: ['Reality Tear', 'Source Code'],
    status: 'complete',
  },
  {
    id: 'muscle-memory',
    number: 57,
    series: 'meta-system-glitch',
    seriesPosition: 7,
    name: 'The Muscle Memory Engine',
    intent: 'The user navigates their phone like a robot, relying on spatial muscle memory. This atom intentionally moves the interactive targets to force the user to wake up and look at what they are doing.',
    physics: 'Hit-box evasion, spatial shifting, bounding box constraints. Button slides away as finger approaches.',
    renderMode: 'canvas',
    defaultScale: 'full',
    surfaces: ['tappable', 'observable'],
    hapticEvents: ['tap', 'step_advance', 'completion'],
    hapticSignature: 'The familiar tap location yields nothing — disorientation — then the satisfying click of conscious contact',
    stateRange: [2, 6],
    continuous: false,
    hasResolution: true,
    breathCoupling: 'none',
    deviceRequirements: ['haptics'],
    implementations: ['The Wrong Button', 'Muscle Memory'],
    status: 'complete',
  },
  {
    id: 'pixelation',
    number: 58,
    series: 'meta-system-glitch',
    seriesPosition: 8,
    name: 'The Pixelation Engine',
    intent: 'The ego suffers because its identity is too rigid, too sharp, too highly defined. This atom lowers the resolution of the self, allowing for fluidity and reinvention.',
    physics: 'Mosaic shaders, downscaling algorithms, blocky rendering. Drag slider to increase pixel size from 1px to 50px.',
    renderMode: 'canvas',
    defaultScale: 'full',
    surfaces: ['draggable', 'observable'],
    hapticEvents: ['drag_snap', 'step_advance', 'completion'],
    hapticSignature: 'Sharp crystalline definition softening into warm abstract color blocks',
    stateRange: [2, 5],
    continuous: true,
    hasResolution: true,
    breathCoupling: 'modulates',
    deviceRequirements: ['haptics'],
    implementations: ['The Pixelated Self', 'Identity Resolution'],
    status: 'complete',
  },
  {
    id: 'attention-paywall',
    number: 59,
    series: 'meta-system-glitch',
    seriesPosition: 9,
    name: 'The Attention Paywall Engine',
    intent: 'Ruminating feels free so the mind does it endlessly. This atom visualizes the hidden metabolic cost of overthinking, making the user pay for every anxious loop.',
    physics: 'Depleting energy bars, friction drag, transaction aesthetics. Tapping a thought drains the battery by 10%.',
    renderMode: 'canvas',
    defaultScale: 'full',
    surfaces: ['tappable', 'observable'],
    hapticEvents: ['tap', 'step_advance', 'completion'],
    hapticSignature: 'Heavy draining downward slide for each thought engaged — preservation warmth when thoughts are let go',
    stateRange: [2, 8],
    continuous: true,
    hasResolution: true,
    breathCoupling: 'modulates',
    deviceRequirements: ['haptics'],
    implementations: ['Attention Paywall', 'Rumination Cost'],
    status: 'complete',
  },
  {
    id: 'semantic-crash',
    number: 60,
    series: 'meta-system-glitch',
    seriesPosition: 10,
    name: 'The Semantic Crash Engine',
    intent: 'Semantic satiation — repeating a word until it loses meaning. This atom strips the power from a terrifying word by looping it into abstract geometry.',
    physics: 'Rapid typography looping, overlapping text rendering, auditory/visual blurring. Word rendered 100 times, morphing into abstract shapes.',
    renderMode: 'canvas',
    defaultScale: 'full',
    surfaces: ['tappable', 'observable'],
    hapticEvents: ['tap', 'step_advance', 'completion'],
    hapticSignature: 'Frantic buzzing that tires out and goes flat — the word loses its teeth',
    stateRange: [2, 5],
    continuous: true,
    hasResolution: true,
    breathCoupling: 'none',
    deviceRequirements: ['haptics'],
    implementations: ['The Loop Crash', 'Semantic Satiation'],
    status: 'complete',
  },
];

const S7: AtomMeta[] = [
  { id: 'audio-rescore', number: 61, series: 'retro-causal', seriesPosition: 1, name: 'The Audio Rescore Engine', intent: 'A memory feels tragic because the ego plays a tragic soundtrack. Change the music, change the neurochemistry.', physics: 'Web Audio API crossfading, waveform visualisation, mixing fader mechanics.', renderMode: 'canvas', defaultScale: 'focus', surfaces: ['draggable', 'scrubable'], hapticEvents: ['drag_snap', 'step_advance', 'completion'], hapticSignature: 'Grinding minor-key fader smoothing into bright, rising, open tones', stateRange: [0, 1], continuous: true, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics', 'audio-output'], implementations: ['Memory Rescore'], status: 'complete' },
  { id: 'chromatic-grade', number: 62, series: 'retro-causal', seriesPosition: 2, name: 'The Chromatic Grade Engine', intent: 'Trauma desaturates memory. The user manually injects warmth and colour back into their own history.', physics: 'Radial colour grading, composite canvas masking, gaussian falloff warmth.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['holdable', 'draggable'], hapticEvents: ['hold_start', 'drag_snap', 'completion'], hapticSignature: 'Cold grey warming into rich golden-hour amber — warmth radiates from touch', stateRange: [0, 1], continuous: true, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Color Grade'], status: 'complete' },
  { id: 'narrative-flip', number: 63, series: 'retro-causal', seriesPosition: 3, name: 'The Narrative Flip Engine', intent: 'The ego labels failure "The End." The sovereign mind labels it "The Inciting Incident." Physically reverse gravity.', physics: 'Reverse kinematics, gravity inversion, spring compression, trajectory reversal.', renderMode: 'canvas', defaultScale: 'focus', surfaces: ['swipeable', 'observable'], hapticEvents: ['swipe_commit', 'completion'], hapticSignature: 'Falling weight caught and reversed — momentum shift felt in the wrist', stateRange: [0, 1], continuous: false, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Narrative Flip', 'Plot Twist'], status: 'complete' },
  { id: 'splicing-timeline', number: 64, series: 'retro-causal', seriesPosition: 4, name: 'The Splicing Engine', intent: 'Depression edits out the light. Find the bright clip and splice it back into the timeline.', physics: 'Horizontal filmstrip, magnetic clip snapping, sequential illumination cascade.', renderMode: 'canvas', defaultScale: 'field', surfaces: ['draggable'], hapticEvents: ['drag_snap', 'seal_stamp', 'completion'], hapticSignature: 'Magnetic snap into the gap — heavy satisfying click that illuminates the timeline', stateRange: [0, 1], continuous: false, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Deleted Scene'], status: 'complete' },
  { id: 'prequel-context', number: 65, series: 'retro-causal', seriesPosition: 5, name: 'The Prequel Engine', intent: 'They were not reacting to you. Pull the timeline backward to see the wound behind the attack.', physics: 'Horizontal timeline scrolling, node connection reveal, colour softening.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['draggable', 'scrubable'], hapticEvents: ['drag_snap', 'step_advance', 'completion'], hapticSignature: 'Timeline scrub notches leading to a soft, empathic revelation thud', stateRange: [0, 1], continuous: true, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Prequel'], status: 'complete' },
  { id: 'metadata-rewrite', number: 66, series: 'retro-causal', seriesPosition: 6, name: 'The Metadata Engine', intent: 'The memory is neutral data. The pain is the metadata tag. Rewrite FLAW to DATA.', physics: 'Typography morphing, badge colour drain, lock/unlock animation.', renderMode: 'canvas', defaultScale: 'focus', surfaces: ['holdable'], hapticEvents: ['hold_start', 'hold_threshold', 'step_advance', 'completion'], hapticSignature: 'Lock click, letter-by-letter morph ticks, then emotional weight lifts', stateRange: [0, 1], continuous: false, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Metadata Edit'], status: 'complete' },
  { id: 'forgiveness-filter', number: 67, series: 'retro-causal', seriesPosition: 7, name: 'The Forgiveness Filter Engine', intent: 'Anger requires a monster. Forgiveness reveals the terrified child inside. Pinch apart the shadow to find the light.', physics: 'Multi-layer shadow splitting, two-finger lens opening, fragile inner light reveal.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['pinchable'], hapticEvents: ['hold_start', 'drag_snap', 'completion'], hapticSignature: 'Shadow tearing apart, then a gentle, warm pulse as the fragile light emerges', stateRange: [0, 1], continuous: true, hasResolution: true, breathCoupling: 'modulates', deviceRequirements: ['haptics'], implementations: ['Forgiveness Filter', 'Villain De-Mask'], status: 'complete' },
  { id: 'ancestral-cut', number: 68, series: 'retro-causal', seriesPosition: 8, name: 'The Ancestral Cut Engine', intent: 'Generational trauma is a 200-year movie. You are the first one with the power to cut the film.', physics: 'Vertical chain severing, horizontal swipe detection, spring retraction, particle dissolution.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['swipeable'], hapticEvents: ['swipe_commit', 'completion'], hapticSignature: 'Decisive horizontal slash — the chain snaps with a resonant, final crack', stateRange: [0, 1], continuous: false, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Ancestral Cut', 'Trauma Breaker'], status: 'complete' },
  { id: 'time-travel-rescue', number: 69, series: 'retro-causal', seriesPosition: 9, name: 'The Time Travel Engine', intent: 'A part of the psyche is still trapped in a past moment. Reach back through time and extract the child.', physics: 'Z-depth portal concentric rings, perspective projection, extraction drag with friction.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['draggable', 'holdable'], hapticEvents: ['hold_start', 'drag_snap', 'completion'], hapticSignature: 'Friction grip at depth, then layers of relief as the light surfaces and merges', stateRange: [0, 1], continuous: true, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Time Travel Rescue', 'Inner Child Rescue'], status: 'complete' },
  { id: 'third-person-shift', number: 70, series: 'retro-causal', seriesPosition: 10, name: 'The Third-Person Shift Engine', intent: 'First-person fusion causes pain. Shift to third-person to become the Director.', physics: 'Camera perspective rotation, isometric projection, vignette dissolution, avatar reveal.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['pinchable'], hapticEvents: ['drag_snap', 'step_advance', 'completion'], hapticSignature: 'Camera breaking free of its lock — a liberating, spacious opening', stateRange: [0, 1], continuous: true, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Third-Person Shift', 'Fourth Wall'], status: 'complete' },
];

const S8: AtomMeta[] = [
  { id: 'overview-effect', number: 71, series: 'kinematic-topology', seriesPosition: 1, name: 'The Overview Engine', intent: 'From orbit, borders and deadlines disappear. Pull the camera back until the crisis is a pixel on a marble.', physics: 'Exponential Z-axis zooming, 5-regime visual transitions, cosmic rendering.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['pinchable', 'draggable'], hapticEvents: ['step_advance', 'completion'], hapticSignature: 'Claustrophobic compression releasing into vast, echoing, cosmic silence', stateRange: [0, 1], continuous: true, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Overview Effect', 'Perspective Drone'], status: 'complete' },
  { id: 'fractal-zoom', number: 72, series: 'kinematic-topology', seriesPosition: 2, name: 'The Fractal Zoom Engine', intent: 'No matter how deep or far you zoom, the architecture is consistent. You cannot fall out of the system.', physics: 'Mandelbrot set progressive rendering, infinite pinch-zoom, seamless loop boundary.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['pinchable', 'tappable'], hapticEvents: ['step_advance'], hapticSignature: 'Infinite descent — each zoom level a subtle harmonic tick, never bottoming out', stateRange: [0, 1], continuous: true, hasResolution: false, breathCoupling: 'none', deviceRequirements: [], implementations: ['Fractal Zoom', 'Hologram'], status: 'complete' },
  { id: 'deep-time', number: 73, series: 'kinematic-topology', seriesPosition: 3, name: 'The Deep Time Engine', intent: 'The ego panics in hours. The earth thinks in millennia. Every mountain eventually becomes dust.', physics: 'Procedural erosion, terrain smoothing, geological timeline scrubbing.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['scrubable', 'draggable'], hapticEvents: ['drag_snap', 'step_advance', 'completion'], hapticSignature: 'Geological grinding giving way to fertile, flat, peaceful stillness', stateRange: [0, 1], continuous: true, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Deep Time Scroll'], status: 'complete' },
  { id: 'systemic-zoom', number: 74, series: 'kinematic-topology', seriesPosition: 4, name: 'The Systemic Zoom Engine', intent: 'You are obsessing over one diseased leaf. Zoom out to see the health of the entire forest.', physics: 'Node-graph camera zoom, point cloud rendering, network connectivity reveals.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['tappable', 'pinchable'], hapticEvents: ['step_advance', 'completion'], hapticSignature: 'Each zoom level reveals a wider, healthier, more connected world', stateRange: [0, 1], continuous: false, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['System View', 'Zoom Out'], status: 'complete' },
  { id: 'ego-zoom', number: 75, series: 'kinematic-topology', seriesPosition: 5, name: 'The Ego Zoom Engine', intent: 'Expand identity from Body to Home to City to Country to Species to Earth to Cosmos.', physics: 'Concentric expanding rings, radial ripple physics, identity layer labels.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['holdable', 'breathable'], hapticEvents: ['breath_peak', 'completion'], hapticSignature: 'Stone dropped in still water — expanding outward waves of identity', stateRange: [0, 7], continuous: false, hasResolution: true, breathCoupling: 'modulates', deviceRequirements: ['haptics'], implementations: ['Ego Zoom', 'Boundary Hug'], status: 'complete' },
  { id: 'micro-step', number: 76, series: 'kinematic-topology', seriesPosition: 6, name: 'The Micro-Step Engine', intent: 'A task too massive to lift. Double-tap to shrink it until it is too small to fail.', physics: 'Extreme downscaling, friction elimination, physics mass reduction, flick-off.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['tappable', 'draggable'], hapticEvents: ['tap', 'step_advance', 'completion'], hapticSignature: 'Heavy impossibility shrinking into weightless, joyful, flick-away ease', stateRange: [0, 1], continuous: false, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Micro-Step', 'Inertia Break'], status: 'complete' },
  { id: 'vastness-expansion', number: 77, series: 'kinematic-topology', seriesPosition: 7, name: 'The Vastness Engine', intent: 'Claustrophobia of the mind. Push the walls of reality outward, creating breathing room.', physics: 'Radial vignette repulsion, elastic overshoot, warm background reveal.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['pinchable'], hapticEvents: ['drag_snap', 'completion'], hapticSignature: 'Tight restrictive buzz stretching into a massive, resonant, open gong', stateRange: [0, 1], continuous: true, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Vastness', 'Panoramic Soften'], status: 'complete' },
  { id: 'horizon-infinite', number: 78, series: 'kinematic-topology', seriesPosition: 8, name: 'The Horizon Engine', intent: 'The horizon is not a destination. It is an orientation. Infinite forward motion without arrival.', physics: 'Parallax scrolling, unreachable horizon line, rhythmic forward momentum.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['swipeable', 'breathable'], hapticEvents: ['breath_peak'], hapticSignature: 'Rhythmic forward pulse matching the walk — never arriving, always moving', stateRange: [0, 1], continuous: true, hasResolution: false, breathCoupling: 'modulates', deviceRequirements: ['haptics'], implementations: ['Horizon Line', 'Unfinished Symphony'], status: 'complete' },
  { id: 'stardust-dissolve', number: 79, series: 'kinematic-topology', seriesPosition: 9, name: 'The Stardust Engine', intent: 'You are not solid. You are particles temporarily holding a shape. Dissolve the rigidity.', physics: '2000-particle cohesion physics, gravitational decoupling, orbital dispersion.', renderMode: 'canvas', defaultScale: 'field', surfaces: ['tappable', 'holdable'], hapticEvents: ['tap', 'completion'], hapticSignature: 'Cohesion bonds snapping — a release into weightless, luminous freedom', stateRange: [0, 1], continuous: true, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Stardust Check', 'Galaxy Spin'], status: 'complete' },
  { id: 'holographic-drop', number: 80, series: 'kinematic-topology', seriesPosition: 10, name: 'The Holographic Fragment Engine', intent: 'The drop dies so the ocean can be born. Surrender ego to integrate with the whole.', physics: 'Water drop fall, surface impact, concentric ripple mathematics, ego dissolution.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['tappable'], hapticEvents: ['tap', 'entrance_land', 'completion'], hapticSignature: 'The drop falls, the impact resounds, the ripple expands to infinity', stateRange: [0, 1], continuous: false, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Drop in the Ocean', 'Unity'], status: 'complete' },
];

const S9: AtomMeta[] = [
  { id: 'crucible-fire', number: 81, series: 'shadow-crucible', seriesPosition: 1, name: 'The Crucible Engine', intent: 'Hold your finger in the fire. That is the only instruction. Endure the heat — lead becomes gold.', physics: 'Procedural fire particles, sustained-hold mechanics, block melting and resolidification.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['holdable', 'pressure-sensitive'], hapticEvents: ['hold_start', 'hold_threshold', 'completion'], hapticSignature: 'Intense chaotic fire crackle smoothing into warm, molten, golden flow', stateRange: [0, 1], continuous: true, hasResolution: true, breathCoupling: 'modulates', deviceRequirements: ['haptics'], implementations: ['Crucible', 'Lead to Gold', 'Transmutation Fire'], status: 'complete' },
  { id: 'shadow-hug', number: 82, series: 'shadow-crucible', seriesPosition: 2, name: 'The Shadow Hug Engine', intent: 'We fight our demons, making them stronger. Approach with agonising slowness. Hug the monster.', physics: 'Velocity-inverse evasion, slow approach detection, jagged-to-smooth vertex collapse.', renderMode: 'canvas', defaultScale: 'field', surfaces: ['draggable', 'holdable'], hapticEvents: ['hold_start', 'hold_threshold', 'hold_release', 'completion'], hapticSignature: 'Fearful trembling softening into trusting warmth — the shadow exhales', stateRange: [0, 1], continuous: false, hasResolution: true, breathCoupling: 'modulates', deviceRequirements: ['haptics'], implementations: ['Shadow Hug'], status: 'complete' },
  { id: 'projection-mirror', number: 83, series: 'shadow-crucible', seriesPosition: 3, name: 'The Projection Engine', intent: 'What you hate in them is a shadow in you. Wipe the glass to reveal your own reflection.', physics: 'Scrub-to-reveal mask accumulation, vertex morphing from sharp to soft.', renderMode: 'canvas', defaultScale: 'focus', surfaces: ['draggable'], hapticEvents: ['drag_snap', 'step_advance', 'completion'], hapticSignature: 'Glass-wiping friction giving way to a quiet, recognising sigh', stateRange: [0, 1], continuous: true, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Projection Check', 'Mirror of Projection'], status: 'complete' },
  { id: 'solve-coagula', number: 84, series: 'shadow-crucible', seriesPosition: 4, name: 'The Coagula Engine', intent: 'Solve et Coagula. Dissolve the old form completely, then reassemble into something stronger.', physics: 'Voronoi shattering, gravity-driven scatter, magnetic reassembly into new geometry.', renderMode: 'canvas', defaultScale: 'focus', surfaces: ['tappable', 'holdable'], hapticEvents: ['tap', 'hold_start', 'seal_stamp', 'completion'], hapticSignature: 'Shatter crack, scattered silence, then magnetic pull fusing into a triumphant lock', stateRange: [0, 1], continuous: false, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Solve', 'Coagula'], status: 'complete' },
  { id: 'paradox-tension', number: 85, series: 'shadow-crucible', seriesPosition: 5, name: 'The Paradox Tension Engine', intent: 'The sovereign mind holds two contradictions simultaneously. Drag the repelling nodes into fusion.', physics: 'Mutual repulsion, two-finger dual-node control, tension arcs, fusion event.', renderMode: 'canvas', defaultScale: 'field', surfaces: ['draggable', 'holdable'], hapticEvents: ['drag_snap', 'hold_threshold', 'completion'], hapticSignature: 'Violent grinding resistance welding into a single iridescent harmonic', stateRange: [0, 1], continuous: true, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Paradox Hold', 'Both/And Bridge'], status: 'complete' },
  { id: 'monster-taming', number: 86, series: 'shadow-crucible', seriesPosition: 6, name: 'The Monster Taming Engine', intent: 'The demon is a guardian gone feral. Hold still. Feed it calm. Give it a new job.', physics: 'Chaotic particle swarm, calm accumulation, velocity damping, orbital stabilisation.', renderMode: 'canvas', defaultScale: 'field', surfaces: ['holdable'], hapticEvents: ['hold_start', 'drag_snap', 'hold_threshold', 'completion'], hapticSignature: 'Stinging chaotic attacks calming into a rhythmic, protective, silver orbit', stateRange: [0, 1], continuous: true, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Monster Feed'], status: 'complete' },
  { id: 'shame-compass', number: 87, series: 'shadow-crucible', seriesPosition: 7, name: 'The Compass of Shame Engine', intent: 'Shame guards the gate to your values. The needle points into the dark. Walk through it.', physics: 'Inverse magnetic attraction, dark-zone proximity revelation, threshold light burst.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['draggable'], hapticEvents: ['drag_snap', 'step_advance', 'completion'], hapticSignature: 'Increasing dread giving way to a blinding, joyful, revelatory burst', stateRange: [0, 1], continuous: true, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Shame Compass'], status: 'complete' },
  { id: 'anger-forge', number: 88, series: 'shadow-crucible', seriesPosition: 8, name: 'The Forge Engine', intent: 'Anger is kinetic energy. Strike the anvil rhythmically to forge something useful from the rage.', physics: 'Rhythmic tap detection, vertex deformation, temperature cooling, shape emergence.', renderMode: 'canvas', defaultScale: 'focus', surfaces: ['tappable'], hapticEvents: ['tap', 'step_advance', 'completion'], hapticSignature: 'Heavy metallic CLANG on each strike — cooling into precise, sharp steel', stateRange: [0, 1], continuous: false, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Anger Forge', 'Transmutation Seal'], status: 'complete' },
  { id: 'inner-child', number: 89, series: 'shadow-crucible', seriesPosition: 9, name: 'The Inner Child Engine', intent: 'Logic cannot heal the deepest wounds. Drop the armour. Provide pure presence.', physics: 'Concentric spinning defensive rings, gentle-touch detection, ring shedding, breath-synced core.', renderMode: 'canvas', defaultScale: 'focus', surfaces: ['holdable'], hapticEvents: ['hold_start', 'step_advance', 'completion'], hapticSignature: 'Metallic rings decelerating, falling away, revealing a soft pulse synced to breath', stateRange: [0, 4], continuous: false, hasResolution: true, breathCoupling: 'modulates', deviceRequirements: ['haptics'], implementations: ['Inner Child Rescue', 'Armor Drop'], status: 'complete' },
  { id: 'phoenix-ash', number: 90, series: 'shadow-crucible', seriesPosition: 10, name: 'The Phoenix Engine', intent: 'The ash is not the end. It is the cradle. Blow away the ash to reveal the jewel beneath.', physics: '3000-particle ash layer, drag-to-blow wind physics, optional microphone breath input.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['draggable', 'voice'], hapticEvents: ['drag_snap', 'step_advance', 'completion'], hapticSignature: 'Ash scattering like dry leaves, then a pristine, glowing, unshakeable warmth', stateRange: [0, 1], continuous: true, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics', 'microphone'], implementations: ['Phoenix Burn', 'Phoenix Ash'], status: 'complete' },
];

const S10: AtomMeta[] = [
  { id: 'atmosphere-weather', number: 91, series: 'reality-bender', seriesPosition: 1, name: 'The Atmosphere Engine', intent: 'Do not just enter the room. Happen to the room. You bring the weather.', physics: 'Gesture velocity analysis, procedural weather particle generation, ambient mood shifting.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['drawable', 'swipeable'], hapticEvents: ['step_advance', 'drag_snap'], hapticSignature: 'The user\'s gesture made tangible — wind, warmth, or sharp crisp light', stateRange: [0, 1], continuous: true, hasResolution: false, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Atmosphere Engineer'], status: 'complete' },
  { id: 'distortion-grid', number: 92, series: 'reality-bender', seriesPosition: 2, name: 'The Distortion Engine', intent: 'Reality is consensus hallucination. The rules can be bent. Warp the grid.', physics: 'Grid vertex displacement, gaussian touch influence, spring-return physics.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['draggable', 'holdable'], hapticEvents: ['drag_snap', 'hold_start'], hapticSignature: 'Stretching thick satisfying silicone — the grid yields to your will', stateRange: [0, 1], continuous: true, hasResolution: false, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Reality Distortion'], status: 'complete' },
  { id: 'belief-bridge', number: 93, series: 'reality-bender', seriesPosition: 3, name: 'The Belief Bridge Engine', intent: 'The bridge only appears because you take the step. Step into the void.', physics: 'Proximity-based tile materialisation, chasm crossing, faith-as-mechanic.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['draggable'], hapticEvents: ['seal_stamp', 'completion'], hapticSignature: 'Each step into the void answered by a resounding, solid, stone clack', stateRange: [0, 12], continuous: false, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Belief Bridge'], status: 'complete' },
  { id: 'future-memory', number: 94, series: 'reality-bender', seriesPosition: 4, name: 'The Future Memory Engine', intent: 'The brain cannot distinguish vivid memory from vivid simulation. Construct your future.', physics: 'Particle crystallisation, seed-crystal text input, brownian-to-geometric phase transition.', renderMode: 'canvas', defaultScale: 'focus', surfaces: ['typeable', 'observable'], hapticEvents: ['tap', 'seal_stamp', 'completion'], hapticSignature: 'Each keystroke crystallises the haze — the future locks into the timeline', stateRange: [0, 1], continuous: true, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Future Memory', 'Future Draft'], status: 'complete' },
  { id: 'luck-surface', number: 95, series: 'reality-bender', seriesPosition: 5, name: 'The Luck Surface Engine', intent: 'Luck is geometry. Expand your surface area to catch more opportunities.', physics: 'Pinch-to-expand circle, ambient collision detection, particle absorption counting.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['pinchable'], hapticEvents: ['drag_snap', 'tap', 'completion'], hapticSignature: 'Each caught opportunity a satisfying energetic ping — a cascade of luck', stateRange: [0, 10], continuous: false, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Luck Surface'], status: 'complete' },
  { id: 'possibility-prism', number: 96, series: 'reality-bender', seriesPosition: 6, name: 'The Possibility Prism Engine', intent: 'An event is white light. Pass it through a prism. See the spectrum of possibilities.', physics: 'Light refraction simulation, prism drag-to-intercept, spectral beam splitting.', renderMode: 'canvas', defaultScale: 'field', surfaces: ['draggable'], hapticEvents: ['drag_snap', 'step_advance', 'completion'], hapticSignature: 'White light splitting into a rainbow of usable, illuminating possibilities', stateRange: [0, 5], continuous: false, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Possibility Prism', 'Identity Prism'], status: 'complete' },
  { id: 'architect-stone', number: 97, series: 'reality-bender', seriesPosition: 7, name: 'The Architect Engine', intent: 'Every castle needs a cornerstone. Lay it with absolute, unshakeable permanence.', physics: 'Extreme mass simulation, high-friction drag, zero-rebound placement, architectural alignment.', renderMode: 'canvas', defaultScale: 'focus', surfaces: ['draggable'], hapticEvents: ['drag_snap', 'seal_stamp', 'completion'], hapticSignature: 'The deepest, heaviest single thud the hardware can produce — absolute permanence', stateRange: [0, 1], continuous: false, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Foundation Stone', 'Architect Seal'], status: 'complete' },
  { id: 'narrative-override', number: 98, series: 'reality-bender', seriesPosition: 8, name: 'The Narrative Override Engine', intent: 'You are the author. The pen never leaves your hand. Erase the dark script. Write in gold.', physics: 'Pointer-trail erasing, ink-bleed transitions, golden text reveal, semantic overwriting.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['draggable'], hapticEvents: ['drag_snap', 'step_advance', 'completion'], hapticSignature: 'Wet ink bleeding away, replaced by the satisfying scratch of a golden pen', stateRange: [0, 1], continuous: true, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Narrative Override', 'Mythos Seal'], status: 'complete' },
  { id: 'pure-yes', number: 99, series: 'reality-bender', seriesPosition: 9, name: 'The Pure Yes Engine', intent: 'Remove all resistance. Allow infinite, joyful, unhindered expansion. Zero friction. Zero limit.', physics: 'Unbounded radial scaling, frictionless acceleration, luminous exponential bloom.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['holdable'], hapticEvents: ['hold_start', 'breath_peak'], hapticSignature: 'A rising, open, triumphant chord that simply never stops expanding', stateRange: [0, 1], continuous: true, hasResolution: false, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Pure Yes'], status: 'complete' },
  { id: 'infinite-ouroboros', number: 100, series: 'reality-bender', seriesPosition: 10, name: 'The Infinite Engine', intent: 'Mastery is not a destination. It is an eternal, beautiful loop. The end is always the beginning.', physics: 'Lemniscate parametric path, frictionless trace-following, accumulating light trail.', renderMode: 'canvas', defaultScale: 'focus', surfaces: ['drawable', 'breathable'], hapticEvents: ['breath_peak'], hapticSignature: 'Frictionless eternal glide — smooth harmonic pulse at each crossing point', stateRange: [0, 1], continuous: true, hasResolution: false, breathCoupling: 'drives', deviceRequirements: ['haptics'], implementations: ['Infinite Seal', 'Ouroboros'], status: 'complete' },
];

// =====================================================================
// COLLECTION 2: THE TELEMETRIC NAVIGATOR (Atoms 101–200)
// Series 11–20 registry entries are in /src/app/components/atoms/atom-registry-c2.ts
// =====================================================================

// =====================================================================
// ASSEMBLED CATALOG
// =====================================================================

const ALL_ATOMS: AtomMeta[] = [
  ...S1, ...S2, ...S3, ...S4, ...S5,
  ...S6, ...S7, ...S8, ...S9, ...S10,
  ...S11, ...S12, ...S13, ...S14, ...S15,
  ...S16, ...S17, ...S18, ...S19, ...S20,
  ...S21, ...S22, ...S23, ...S24, ...S25,
  ...S26, ...S27, ...S28, ...S29, ...S30,
  // Collection 4: The Alchemical Synthesizer
  ...S31, ...S32, ...S33, ...S34, ...S35,
  ...S36, ...S37, ...S38, ...S39, ...S40,
  // Collection 5: The Non-Euclidean Diver
  ...S41, ...S42, ...S43, ...S44, ...S45,
  ...S46, ...S47, ...S48, ...S49, ...S50,
  // Collection 6: The Chrono-Weaver
  ...S51, ...S52, ...S53, ...S54, ...S55,
  ...S56, ...S57, ...S58, ...S59, ...S60,
  // Collection 7: The Fluid Tactician
  ...S61, ...S62, ...S63, ...S64, ...S65,
  ...S66, ...S67, ...S68, ...S69, ...S70,
];

/** Full catalog keyed by AtomId */
export const ATOM_CATALOG: Record<AtomId, AtomMeta> = Object.fromEntries(
  ALL_ATOMS.map(a => [a.id, a]),
) as Record<AtomId, AtomMeta>;

/** Ordered list of all atom IDs (1–700) */
export const ATOM_IDS: readonly AtomId[] = ALL_ATOMS.map(a => a.id);

/** Color lookup — derived from series registry (single source of truth) */
export const ATOM_COLORS: Record<AtomId, string> = Object.fromEntries(
  ALL_ATOMS.map(a => [a.id, SERIES_CATALOG[a.series].colorIdentity]),
) as Record<AtomId, string>;

/** Count of designed (non-placeholder) atoms */
export const DESIGNED_ATOM_COUNT = ALL_ATOMS.filter(
  a => a.implementations.length > 0,
).length;

/** Count of total atoms */
export const TOTAL_ATOM_COUNT = ALL_ATOMS.length;