/**
 * ATOM REGISTRY — COLLECTION 3: THE TRANSCENDENT WITNESS
 * =======================================================
 * Metadata for atoms 201–300 across series 21–30.
 * Split from atom-registry.ts for maintainability.
 *
 * ZERO imports from outside this folder.
 *
 * IMPORTANT: Each atom is built one-by-one. Status starts as 'designed'.
 * When a component is implemented, flip status to 'complete' and add
 * the import + ATOM_COMPONENTS entry in index.ts.
 *
 * Name collisions with C1/C2 are avoided by using unique kebab-case IDs.
 */

import type { AtomMeta } from './types';

// SERIES 21: THE METACOGNITIVE MIRROR (Atoms 201–210)
export const S21: AtomMeta[] = [
  { id: 'theater-lens', number: 201, series: 'metacognitive-mirror', seriesPosition: 1, name: 'The Theater Lens Engine', intent: 'When fused with a thought, it presses against your cornea. Pull back — reveal it is a tiny movie on a flat screen in a massive, silent theater.', physics: 'Exponential Z-axis camera extraction, focal plane rendering, spatial audio dampening.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['pinchable'], hapticEvents: ['hold_start', 'step_advance', 'completion'], hapticSignature: 'Deafening rumble collapsing into vast echoing silence of an empty room', stateRange: [0, 1], continuous: true, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Z-Axis Decoupling'], status: 'complete' },
  { id: 'focal-glass', number: 202, series: 'metacognitive-mirror', seriesPosition: 2, name: 'The Focal Glass Engine', intent: 'Shift focus from the content of the thought to the container holding it — the window, not the storm.', physics: 'Depth-of-field manipulation, WebGL Gaussian blurring, refractive index shifting.', renderMode: 'webgl', defaultScale: 'full', surfaces: ['holdable'], hapticEvents: ['hold_start', 'hold_threshold', 'completion'], hapticSignature: 'Sharp aggressive focus softening into warm diffused glass condensation', stateRange: [0, 1], continuous: true, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Figure-Ground Shift'], status: 'complete' },
  { id: 'syntactic-severance', number: 203, series: 'metacognitive-mirror', seriesPosition: 3, name: 'The Syntactic Severance Engine', intent: 'The ego fuses identity to temporary states. Sever the pronoun from the predicate — "I AM" remains, the label turns to ash.', physics: 'Typography vector splitting, kinetic typography, structural gravity.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['swipeable'], hapticEvents: ['swipe_commit', 'completion'], hapticSignature: 'Structural link snapping — "I AM" locking center with massive radiant light, label dissolving to ash', stateRange: [0, 1], continuous: false, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['The I Dissolver'], status: 'complete' },
  { id: 'traffic-observer', number: 204, series: 'metacognitive-mirror', seriesPosition: 4, name: 'The Traffic Observer Engine', intent: 'You are not the traffic — you are the one watching. Let thoughts drive by without jumping in front.', physics: 'Horizontal continuous scrolling, parallax layering, velocity easing.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['observable', 'holdable'], hapticEvents: ['hold_start', 'completion'], hapticSignature: 'Aggressive vibration fading to distant muffled hum as camera elevates to the overpass', stateRange: [0, 1], continuous: true, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Urge Surfing'], status: 'complete' },
  { id: 'sky-and-clouds', number: 205, series: 'metacognitive-mirror', seriesPosition: 5, name: 'The Sky and Clouds Engine', intent: 'The thoughts are clouds. You are the sky. The sky is never damaged by the storm that passes through it.', physics: 'Volumetric cloud rendering, negative space expansion, atmospheric lighting.', renderMode: 'webgl', defaultScale: 'full', surfaces: ['pinchable'], hapticEvents: ['hold_start', 'step_advance', 'completion'], hapticSignature: 'Dense dark pressure parting into infinite open radiant sky clarity', stateRange: [0, 1], continuous: true, hasResolution: true, breathCoupling: 'modulates', deviceRequirements: ['haptics'], implementations: ['The Space Between'], status: 'complete' },
  { id: 'empty-boat', number: 206, series: 'metacognitive-mirror', seriesPosition: 6, name: 'The Empty Boat Engine', intent: 'Dark shapes float aggressively — tap each to reveal they are completely hollow and empty inside.', physics: 'Fluid dynamics, buoyant collision, opacity masking.', renderMode: 'canvas', defaultScale: 'field', surfaces: ['tappable'], hapticEvents: ['tap', 'step_advance', 'completion'], hapticSignature: 'Threatening heavy impact dissolving to soft hollow wooden tock', stateRange: [0, 1], continuous: false, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Attribution Error'], status: 'complete' },
  { id: 'glass-wall', number: 207, series: 'metacognitive-mirror', seriesPosition: 7, name: 'The Glass Wall Engine', intent: 'Observation does not require absorption. Draw an impenetrable glass wall between you and the chaos.', physics: 'Rigid-body barrier generation, particle swarming, refractive glass shading.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['drawable'], hapticEvents: ['drag_snap', 'completion'], hapticSignature: 'Frantic buzzing silenced by smooth icy clack of glass snapping into existence', stateRange: [0, 1], continuous: false, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['The Aquarium'], status: 'complete' },
  { id: 'echomaker', number: 208, series: 'metacognitive-mirror', seriesPosition: 8, name: 'The Echomaker Engine', intent: 'Hear your thought as if it belongs to someone else. Bounce it off a canyon wall — realize it is just sound.', physics: 'Web Audio API delay nodes, reverb impulse responses, waveform trailing.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['voice'], hapticEvents: ['hold_start', 'step_advance', 'completion'], hapticSignature: 'Harsh jagged waveform pushed deep into canyon reverb — distant, echoing, separate', stateRange: [0, 1], continuous: true, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics', 'microphone'], implementations: ['Acoustic Distancing'], status: 'complete' },
  { id: 'holographic-parallax', number: 209, series: 'metacognitive-mirror', seriesPosition: 9, name: 'The Holographic Parallax Engine', intent: 'A tangled knot is just a straight line from the wrong angle. Tilt the device to separate the illusion.', physics: 'Device accelerometer/gyroscope mapping, 3D layer separation, Z-axis spacing.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['gyroscopic'], hapticEvents: ['step_advance', 'completion'], hapticSignature: 'Chaotic overlay resolving into clean separated layers as device tilts to solution angle', stateRange: [0, 1], continuous: true, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics', 'gyroscope'], implementations: ['The Optical Illusion'], status: 'complete' },
  { id: 'observer-seal', number: 210, series: 'metacognitive-mirror', seriesPosition: 10, name: 'The Observer Seal', intent: 'The capstone: I am the Witness. The observer of the panic is completely free from the panic.', physics: 'Rotational vortex dynamics, extreme center-point stabilization, noise-cancellation.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['holdable'], hapticEvents: ['hold_start', 'hold_threshold', 'seal_stamp'], hapticSignature: 'Raging vortex surrounding perfect dead-zero silence at center — the eye of the storm', stateRange: [0, 1], continuous: true, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Center of the Cyclone'], status: 'complete' },
];

// SERIES 22: THE PREDICTIVE OVERRIDE (Atoms 211–220)
export const S22: AtomMeta[] = [
  { id: 'semantic-stripping', number: 211, series: 'predictive-override', seriesPosition: 1, name: 'The Semantic Stripping Engine', intent: 'Remove the word. See it raw. React to the sensation, not the label.', physics: 'Text-to-mesh morphing, Gaussian blurring, pure chromatic expansion.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['holdable'], hapticEvents: ['hold_start', 'step_advance', 'completion'], hapticSignature: 'Jagged buzz transforming to smooth warm undulation as text melts to pure color', stateRange: [0, 1], continuous: true, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Menu vs Meal'], status: 'complete' },
  { id: 'raw-data', number: 212, series: 'predictive-override', seriesPosition: 2, name: 'The Raw Data Engine', intent: 'Blur reality until the brain gives up labeling. Just experience light and color.', physics: 'Real-time camera feed processing, extreme bokeh/blur shaders, luminance mapping.', renderMode: 'webgl', defaultScale: 'full', surfaces: ['scrubable'], hapticEvents: ['drag_snap', 'completion'], hapticSignature: 'Sharp stressful clarity melting into stunning soft shifting light painting', stateRange: [0, 1], continuous: true, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics', 'camera'], implementations: ['Optical Defocus'], status: 'complete' },
  { id: 'color-deconstruct', number: 213, series: 'predictive-override', seriesPosition: 3, name: 'The Color Deconstruct Engine', intent: 'Break a monolithic emotional block into its constituent manageable parts — RGB channel separation.', physics: 'Additive/Subtractive color splitting, RGB channel separation, spatial dispersing.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['tappable'], hapticEvents: ['tap', 'step_advance', 'completion'], hapticSignature: 'Massive heavy thud splitting into lighter discrete harmonic clicks', stateRange: [0, 1], continuous: false, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Chromatic Breakdown'], status: 'complete' },
  { id: 'taste-explode', number: 214, series: 'predictive-override', seriesPosition: 4, name: 'The Taste Explode Engine', intent: 'The anxious mind moves too fast to taste. Slow to micro-sensory perception with massive mindfulness.', physics: 'Macro-scale particle bursting, ultra-slow-motion easing, localized high-definition haptics.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['holdable', 'pressure-sensitive'], hapticEvents: ['hold_start', 'step_advance', 'completion'], hapticSignature: 'Individual crystalline pops synced with visual droplets — slow-motion sensory fireworks', stateRange: [0, 1], continuous: true, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Micro-Perception'], status: 'complete' },
  { id: 'acoustic-unnaming', number: 215, series: 'predictive-override', seriesPosition: 5, name: 'The Acoustic Un-Naming Engine', intent: 'Stop naming the source of a sound — just hear the raw waveform. Neutralize its power.', physics: 'Real-time microphone FFT, waveform magnification, bandpass isolation.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['pinchable', 'voice'], hapticEvents: ['step_advance', 'completion'], hapticSignature: 'Sharp labeled spikes smoothing into beautiful mathematical rolling hills', stateRange: [0, 1], continuous: true, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics', 'microphone'], implementations: ['Waveform Zoom'], status: 'complete' },
  { id: 'tabula-rasa', number: 216, series: 'predictive-override', seriesPosition: 6, name: 'The Tabula Rasa Engine', intent: 'Labels make you blind. Erase every category to see the raw, unedited luminance underneath.', physics: 'Multi-layer alpha masking, kinetic erasure, luminescence revealing.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['drawable'], hapticEvents: ['drag_snap', 'step_advance', 'completion'], hapticSignature: 'Clinical rigid labels dissolving under finger — stunning vibrant life glowing through', stateRange: [0, 1], continuous: true, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Shoshin Reset'], status: 'complete' },
  { id: 'wabi-sabi', number: 217, series: 'predictive-override', seriesPosition: 7, name: 'The Wabi-Sabi Engine', intent: 'The ego demands perfect symmetry. Train the brain to find beauty in the fracture.', physics: 'Procedural fracturing, ceramic material rendering, asymmetric settling.', renderMode: 'svg', defaultScale: 'focus', surfaces: ['tappable', 'draggable'], hapticEvents: ['tap', 'drag_snap', 'completion'], hapticSignature: 'Pristine crack splitting into hollow earthy resonant clinks — beauty in asymmetry', stateRange: [0, 1], continuous: false, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Perfection Override'], status: 'complete' },
  { id: 'somatic-trust', number: 218, series: 'predictive-override', seriesPosition: 8, name: 'The Somatic Trust Engine', intent: 'Remove visual prediction entirely. Walk forward in physical darkness — feel the ground.', physics: 'Accelerometer integration, pitch-black rendering, audio-haptic stepping.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['gyroscopic', 'observable'], hapticEvents: ['step_advance', 'completion'], hapticSignature: 'Massive deeply reassuring haptic pulse with resonant bass note on each physical step', stateRange: [0, 1], continuous: false, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics', 'gyroscope'], implementations: ['Blind Walk'], status: 'complete' },
  { id: 'texture-touch', number: 219, series: 'predictive-override', seriesPosition: 9, name: 'The Texture Touch Engine', intent: 'Route 100% of processing power to the microscopic feeling under your fingertip. Rumination impossible.', physics: 'Extreme macro displacement maps, friction rendering, high-fidelity localized haptics.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['draggable', 'pressure-sensitive'], hapticEvents: ['drag_snap', 'hold_start', 'completion'], hapticSignature: 'Incredibly rapid tiny distinct clicks matching visual ridges — illusion of physical texture on glass', stateRange: [0, 1], continuous: true, hasResolution: false, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Tactile Override'], status: 'complete' },
  { id: 'perception-seal', number: 220, series: 'predictive-override', seriesPosition: 10, name: 'The Perception Seal', intent: 'The capstone: hold the gaze of reality without adding story, label, or prediction. The Unblinking Eye.', physics: 'Eye-tracking simulation, sustained holding, UI stabilization.', renderMode: 'canvas', defaultScale: 'focus', surfaces: ['holdable'], hapticEvents: ['hold_start', 'hold_threshold', 'seal_stamp'], hapticSignature: 'Erratic mind squinting screen blurring — perfect stillness opens wide hyper-sharp warm continuous hum', stateRange: [0, 1], continuous: true, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['The Unblinking Eye'], status: 'complete' },
];

// SERIES 23: THE FLUIDITY MECHANICS (Atoms 221–230)
export const S23: AtomMeta[] = [
  { id: 'binary-breaker', number: 221, series: 'fluidity-mechanics', seriesPosition: 1, name: 'The Binary Breaker Engine', intent: 'Destroy binary thinking — black and white fluids beautifully, inevitably mix into infinite gradient.', physics: '2D WebGL fluid dynamics, viscosity algorithms, real-time color blending.', renderMode: 'webgl', defaultScale: 'full', surfaces: ['draggable', 'swipeable'], hapticEvents: ['swipe_commit', 'drag_snap', 'completion'], hapticSignature: 'Rigid line melting into smooth heavy rolling hum as colors marble together', stateRange: [0, 1], continuous: true, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Non-Dual Fluidity'], status: 'complete' },
  { id: 'water-mode', number: 222, series: 'fluidity-mechanics', seriesPosition: 2, name: 'The Water Mode Engine', intent: 'The ego hits obstacles and smashes. The Sovereign Mind flows around them. Be water.', physics: 'Soft-body particle constraints, obstacle collision detection, surface tension.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['holdable', 'gyroscopic'], hapticEvents: ['hold_start', 'error_boundary', 'completion'], hapticSignature: 'Harsh jarring error vibration on collision — melting to effortless flowing whoosh', stateRange: [0, 1], continuous: true, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics', 'gyroscope'], implementations: ['Adaptive Yielding'], status: 'complete' },
  { id: 'identity-fluidity', number: 223, series: 'fluidity-mechanics', seriesPosition: 3, name: 'The Identity Fluidity Engine', intent: 'You are the water, not the cup. When the cup breaks, you take a new shape.', physics: 'Liquid volume transfer, gravity simulation, dynamic container filling.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['draggable'], hapticEvents: ['drag_snap', 'step_advance', 'completion'], hapticSignature: 'Glass shattering chaos resolving into liquid perfectly filling new container shape', stateRange: [0, 1], continuous: false, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['The Vessel'], status: 'complete' },
  { id: 'harmonic-synthesis', number: 224, series: 'fluidity-mechanics', seriesPosition: 4, name: 'The Harmonic Synthesis Engine', intent: 'Two opposing forces orbit and melt into a superior third option — thesis and antithesis become synthesis.', physics: 'Centripetal fluid merging, orbital decay, color phase-shifting.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['draggable'], hapticEvents: ['drag_snap', 'step_advance', 'completion'], hapticSignature: 'Jarring dissonant collisions resolving into perfect harmonious vibration as purple sphere forms', stateRange: [0, 1], continuous: true, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Harmonic Orbit'], status: 'complete' },
  { id: 'wu-wei', number: 225, series: 'fluidity-mechanics', seriesPosition: 5, name: 'The Wu Wei Engine', intent: 'Effort is interference. The current knows where to go. Let go of the screen to let the system work.', physics: 'Vector field flow lines, kinetic friction, autonomous pathfinding.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['draggable', 'observable'], hapticEvents: ['error_boundary', 'hold_release', 'completion'], hapticSignature: 'Grinding resistance while touching — blinding effortless speed the instant finger lifts', stateRange: [0, 1], continuous: true, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Effortless Action'], status: 'complete' },
  { id: 'thawing', number: 226, series: 'fluidity-mechanics', seriesPosition: 6, name: 'The Thawing Engine', intent: 'Anxiety is frozen energy. Press your palm to the glass — thaw the frost with your simulated heat.', physics: 'Procedural ice-cracking shaders, thermal melting gradients, condensation physics.', renderMode: 'webgl', defaultScale: 'full', surfaces: ['holdable', 'pressure-sensitive'], hapticEvents: ['hold_start', 'hold_threshold', 'completion'], hapticSignature: 'Brittle crystalline cracks giving way to warm liquid dripping — vibrant warmth revealed', stateRange: [0, 1], continuous: true, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Breaking Rigidity'], status: 'complete' },
  { id: 'proteus', number: 227, series: 'fluidity-mechanics', seriesPosition: 7, name: 'The Proteus Engine', intent: 'Rigidity is death. Fluidity is life. Manually distort your shape to fit through the gate.', physics: 'Elastic polygon morphing, anchor point manipulation, spring-tension easing.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['draggable'], hapticEvents: ['drag_snap', 'step_advance', 'completion'], hapticSignature: 'Stretchy elastic resistance giving way to satisfying slip through the impossible gate', stateRange: [0, 1], continuous: false, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Metamorphosis'], status: 'complete' },
  { id: 'ocean-depth', number: 228, series: 'fluidity-mechanics', seriesPosition: 8, name: 'The Ocean Depth Engine', intent: 'The storm is only on the surface. Dive deep — the massive slow currents are unshakeable.', physics: 'Z-axis volumetric fluid scattering, frequency dampening, low-pass audio filtering.', renderMode: 'webgl', defaultScale: 'full', surfaces: ['scrubable'], hapticEvents: ['drag_snap', 'step_advance', 'completion'], hapticSignature: 'Chaotic surface crashing dampening to deep peaceful indigo silence — subsonic comfort hum', stateRange: [0, 1], continuous: true, hasResolution: true, breathCoupling: 'modulates', deviceRequirements: ['haptics'], implementations: ['The Deep Current'], status: 'complete' },
  { id: 'complexity-breath', number: 229, series: 'fluidity-mechanics', seriesPosition: 9, name: 'The Complexity Breath Engine', intent: 'Breathe in: simple circle warps into stunning intricate spirograph. Breathe out: collapses back. Hold the complexity.', physics: 'Parametric oscillators, generative line art, breath-synced scaling.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['breathable', 'voice'], hapticEvents: ['breath_peak', 'step_advance', 'completion'], hapticSignature: 'Simple pulse expanding into complex vibrating geometry — collapsing back on exhale', stateRange: [0, 1], continuous: true, hasResolution: false, breathCoupling: 'drives', deviceRequirements: ['haptics', 'microphone'], implementations: ['Expanding the Box'], status: 'complete' },
  { id: 'shifter-seal', number: 230, series: 'fluidity-mechanics', seriesPosition: 10, name: 'The Shifter Seal', intent: 'The capstone: I contain multitudes. A single drop loses surface tension and becomes the entire flowing surface.', physics: 'Chromatic aberration, liquid surface tension, continuous blending.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['holdable'], hapticEvents: ['hold_start', 'hold_threshold', 'seal_stamp'], hapticSignature: 'Single drop spreading into gentle eternal pearlescent tide rocking', stateRange: [0, 1], continuous: true, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['The Multitudes'], status: 'complete' },
];

// SERIES 24: THE NET OF INDRA (Atoms 231–240)
export const S24: AtomMeta[] = [
  { id: 'indra-node', number: 231, series: 'net-of-indra', seriesPosition: 1, name: 'The Indra Node Engine', intent: 'Touch one jewel — light recursively reflects through every node in the network. Isolated actions do not exist.', physics: 'Ray-traced refraction, infinite recursive looping, nodal network propagation.', renderMode: 'webgl', defaultScale: 'field', surfaces: ['tappable'], hapticEvents: ['tap', 'step_advance', 'completion'], hapticSignature: 'Single brilliant tap cascading through recursive crystalline reflections — whole device vibrating', stateRange: [0, 1], continuous: false, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['The Jewel Reflection'], status: 'complete' },
  { id: 'mutual-respiration', number: 232, series: 'net-of-indra', seriesPosition: 2, name: 'The Mutual Respiration Engine', intent: 'You do not breathe the air — the air breathes you. Render breathing as a symbiotic exchange with a fractal forest.', physics: 'Fractal generation, volumetric expansion, microphone-gated animation loops.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['breathable', 'voice'], hapticEvents: ['breath_peak', 'step_advance', 'completion'], hapticSignature: 'Inhale draws glowing particles inward — exhale feeds the forest and it blooms', stateRange: [0, 1], continuous: true, hasResolution: false, breathCoupling: 'drives', deviceRequirements: ['haptics', 'microphone'], implementations: ['Symbiotic Respiration'], status: 'complete' },
  { id: 'mycelium-network', number: 233, series: 'net-of-indra', seriesPosition: 3, name: 'The Mycelium Network Engine', intent: 'Five isolated trees above ground — pull the camera underground to reveal the massive bioluminescent root network connecting them all.', physics: 'Z-axis subterranean scrolling, spline-curve drawing, bioluminescent pulsing.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['draggable', 'pinchable'], hapticEvents: ['drag_snap', 'step_advance', 'completion'], hapticSignature: 'Stark lonely silence transforming into deep pulsing bioluminescent hum of hidden connection', stateRange: [0, 1], continuous: true, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['The Hidden Network'], status: 'complete' },
  { id: 'dmn-deactivation', number: 234, series: 'net-of-indra', seriesPosition: 4, name: 'The DMN Deactivation Engine', intent: 'The Default Mode Network maintains the rigid self/other boundary. Tap the ego circle — dissolve its surface tension into the background flow.', physics: 'Surface tension collapse, particle dispersion, unified field blending.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['tappable'], hapticEvents: ['tap', 'step_advance', 'completion'], hapticSignature: 'Heavy aggressive buzz dissipating into vast open silent glide as boundary dissolves', stateRange: [0, 1], continuous: false, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Dissolving the Border'], status: 'complete' },
  { id: 'echo-chamber', number: 235, series: 'net-of-indra', seriesPosition: 5, name: 'The Echo Chamber Engine', intent: 'What you emit returns. Tap aggressively — a harsh red wave reflects back. Emit softly — a soft blue wave returns.', physics: 'Concentric wave propagation, boundary reflection, interference absorption.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['tappable'], hapticEvents: ['tap', 'error_boundary', 'completion'], hapticSignature: 'Harsh aggressive emission returning as jarring shock — soft emission returning as gentle warmth', stateRange: [0, 1], continuous: false, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Emission and Absorption'], status: 'complete' },
  { id: 'murmuration', number: 236, series: 'net-of-indra', seriesPosition: 6, name: 'The Murmuration Engine', intent: 'Do not herd the flock. Move one particle with grace — the Boids algorithm aligns the rest into a breathtaking murmuration.', physics: 'Boids algorithm (separation, alignment, cohesion), fluid flocking, swarm intelligence.', renderMode: 'canvas', defaultScale: 'field', surfaces: ['draggable'], hapticEvents: ['drag_snap', 'step_advance', 'completion'], hapticSignature: 'Chaotic scattering resolving into sweeping synchronized swarm whoosh', stateRange: [0, 1], continuous: true, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Emergent Harmony'], status: 'complete' },
  { id: 'gravity-well', number: 237, series: 'net-of-indra', seriesPosition: 7, name: 'The Gravity Well Engine', intent: 'Your mass affects their trajectory. Move with mindful slowness — let smaller nodes establish safe orbit.', physics: 'Newtonian gravitational attraction, orbital velocity, mass distortion.', renderMode: 'canvas', defaultScale: 'field', surfaces: ['draggable'], hapticEvents: ['drag_snap', 'error_boundary', 'completion'], hapticSignature: 'Erratic movement ripping planets off-screen — mindful slowness creating rhythmic orbital hum', stateRange: [0, 1], continuous: true, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['The Pull of the Other'], status: 'complete' },
  { id: 'butterfly-effect', number: 238, series: 'net-of-indra', seriesPosition: 8, name: 'The Butterfly Effect Engine', intent: 'A tiny shift changes the entire outcome. Nudge the microscopic slider — the chaotic storm resolves into a mandala.', physics: 'Chaos theory attractors (Lorenz), vector field manipulation, extreme sensitivity scaling.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['scrubable'], hapticEvents: ['drag_snap', 'completion'], hapticSignature: 'Chaotic storm vibration resolving into perfect symmetrical geometric stillness', stateRange: [0, 1], continuous: true, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Chaos and Grace'], status: 'complete' },
  { id: 'interference-pattern', number: 239, series: 'net-of-indra', seriesPosition: 9, name: 'The Interference Pattern Engine', intent: 'When your frequency aligns with reality, the waves amplify. Fight it and they cancel. Tap in rhythm.', physics: 'Wave superposition, phase alignment, constructive/destructive amplitude rendering.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['tappable'], hapticEvents: ['tap', 'error_boundary', 'completion'], hapticSignature: 'Out-of-sync grinding stutter — in-sync massive triumphant surf swell', stateRange: [0, 1], continuous: true, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Constructive Waves'], status: 'complete' },
  { id: 'cosmic-tapestry-seal', number: 240, series: 'net-of-indra', seriesPosition: 10, name: 'The Cosmic Tapestry Seal', intent: 'The capstone: pull a single thread — reveal it is woven into a massive, intricate, breathing masterpiece. You are essential.', physics: 'Cloth simulation, structural tension limits, extreme macro-to-micro camera easing.', renderMode: 'webgl', defaultScale: 'full', surfaces: ['draggable', 'pinchable'], hapticEvents: ['drag_snap', 'step_advance', 'seal_stamp'], hapticSignature: 'Single frayed thread resistance zooming into deep warm enveloping hum — heavy blanket embrace', stateRange: [0, 1], continuous: false, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['The One'], status: 'complete' },
];

// SERIES 25: THE DIALECTICAL ENGINE (Atoms 241–250)
export const S25: AtomMeta[] = [
  { id: 'tensegrity', number: 241, series: 'dialectical-engine', seriesPosition: 1, name: 'The Tensegrity Engine', intent: 'The structure floats because opposing tensions are perfectly balanced. Conflicting emotions hold the psyche together.', physics: 'Distance constraints, spring physics, anti-gravity node suspension.', renderMode: 'canvas', defaultScale: 'focus', surfaces: ['draggable'], hapticEvents: ['drag_snap', 'error_boundary', 'completion'], hapticSignature: 'Violent collapse on over-pull — perfect humming float at exact balanced tension', stateRange: [0, 1], continuous: true, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Suspended Tension'], status: 'complete' },
  { id: 'both-and', number: 242, series: 'dialectical-engine', seriesPosition: 2, name: 'The Both/And Engine', intent: 'Replace "Or" with "And." Force two magnetically repelling spheres to overlap — the Venn intersection bursts with light.', physics: 'Magnetic repulsion mapping, additive color blending, threshold fusion.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['draggable'], hapticEvents: ['drag_snap', 'error_boundary', 'completion'], hapticSignature: 'Grinding magnetic repulsion snapping to massive attraction — brilliant white fusion burst', stateRange: [0, 1], continuous: false, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['The Venn Fusion'], status: 'complete' },
  { id: 'zen-koan', number: 243, series: 'dialectical-engine', seriesPosition: 3, name: 'The Zen Koan Engine', intent: 'An impossible Penrose triangle. Trace the line — it loops forever. The solution: tap the empty center. Logic surrenders.', physics: 'Non-Euclidean geometry rendering, continuous path tracing, void interaction.', renderMode: 'canvas', defaultScale: 'focus', surfaces: ['draggable', 'tappable'], hapticEvents: ['drag_snap', 'tap', 'completion'], hapticSignature: 'Frustrating accelerating loop halted by liberating shatter into weightless flock of birds', stateRange: [0, 1], continuous: false, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Breaking the Logic Loop'], status: 'complete' },
  { id: 'complementary-color', number: 244, series: 'dialectical-engine', seriesPosition: 4, name: 'The Complementary Color Engine', intent: 'Opposite emotions neutralize each other. Drag the exact complementary wavelength over the aggression to reach calm grey.', physics: 'Chromatic wheel math, opposite-vector alignment, noise cancellation.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['draggable', 'scrubable'], hapticEvents: ['drag_snap', 'completion'], hapticSignature: 'Violent color buzz fading to absolute silence as complementary wavelengths cancel', stateRange: [0, 1], continuous: true, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['The Neutralizer'], status: 'complete' },
  { id: 'pendulum-arrest', number: 245, series: 'dialectical-engine', seriesPosition: 5, name: 'The Pendulum Arrest Engine', intent: 'Mania and depression are a pendulum. Apply friction to the fulcrum — not the weight — to arrest the swing.', physics: 'Pendulum kinetic energy, fulcrum friction dampening, gravity settling.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['holdable'], hapticEvents: ['hold_start', 'hold_threshold', 'completion'], hapticSignature: 'Wild jarring crashes narrowing to perfectly plumb dead-center silence', stateRange: [0, 1], continuous: true, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Arresting the Swing'], status: 'complete' },
  { id: 'magnetic-suspension', number: 246, series: 'dialectical-engine', seriesPosition: 6, name: 'The Magnetic Suspension Engine', intent: 'Truth is found hovering in the uncomfortable space between extremes. Hold the node in the dead zone.', physics: 'Multi-point magnetic repulsion, inverse-square law, zero-gravity hovering.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['draggable'], hapticEvents: ['drag_snap', 'error_boundary', 'completion'], hapticSignature: 'Aggressive magnetic snap on approach — perfectly spinning zero-gravity stillness at center', stateRange: [0, 1], continuous: true, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['The Hover'], status: 'complete' },
  { id: 'acceptance-change', number: 247, series: 'dialectical-engine', seriesPosition: 7, name: 'The Acceptance/Change Engine', intent: 'Pull the spring to exactly 50% tension. Pure acceptance droops; pure change tears. The sweet spot sings.', physics: 'Helical spring modeling, tension/compression limits, acoustic resonance mapping.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['draggable'], hapticEvents: ['drag_snap', 'error_boundary', 'completion'], hapticSignature: 'Limp droop or screaming tear at extremes — beautiful continuous singing note at perfect tension', stateRange: [0, 1], continuous: true, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['The Spring'], status: 'complete' },
  { id: 'mobius-strip', number: 248, series: 'dialectical-engine', seriesPosition: 8, name: 'The Mobius Strip Engine', intent: 'Inside and outside are the same continuous surface. Trace the white side — arrive on the black without crossing an edge.', physics: '3D topology rendering, continuous spline animation, seamless light-to-dark gradient mapping.', renderMode: 'webgl', defaultScale: 'focus', surfaces: ['draggable'], hapticEvents: ['drag_snap', 'step_advance', 'completion'], hapticSignature: 'High frequency shifting seamlessly to low rumble — no boundary, no sides', stateRange: [0, 1], continuous: true, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['The Single Surface'], status: 'complete' },
  { id: 'weight-of-opposites', number: 249, series: 'dialectical-engine', seriesPosition: 9, name: 'The Weight of Opposites Engine', intent: 'A gyroscope weighted on one side crashes. You need your darkness to balance your light.', physics: 'Angular momentum, rotational inertia, center-of-mass balancing.', renderMode: 'canvas', defaultScale: 'focus', surfaces: ['draggable'], hapticEvents: ['drag_snap', 'error_boundary', 'completion'], hapticSignature: 'Violent wobble on imbalance — flawless humming silent blur when grief balances joy', stateRange: [0, 1], continuous: false, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['The Gyroscope'], status: 'complete' },
  { id: 'dialectical-seal', number: 250, series: 'dialectical-engine', seriesPosition: 10, name: 'The Dialectical Seal', intent: 'The capstone: Taijitu. White and black particles catch a vortex and form a flawless Yin-Yang. The deep eternal cyclical breath.', physics: 'Fluid phase-locking, rotational symmetry, absolute kinetic balance.', renderMode: 'canvas', defaultScale: 'focus', surfaces: ['draggable'], hapticEvents: ['drag_snap', 'step_advance', 'seal_stamp'], hapticSignature: 'Chaotic storm resolving into deep eternal cyclical breath — Yin-Yang humming', stateRange: [0, 1], continuous: true, hasResolution: true, breathCoupling: 'modulates', deviceRequirements: ['haptics'], implementations: ['The Taijitu'], status: 'complete' },
];

// SERIES 26: THE IDENTITY DECOUPLING (Atoms 251–260)
export const S26: AtomMeta[] = [
  { id: 'matryoshka', number: 251, series: 'identity-decoupling', seriesPosition: 1, name: 'The Matryoshka Engine', intent: 'You are not the outermost doll — you are the space in the center. Peel identity layers to the luminous core.', physics: '3D mesh fracturing, radial outward peeling, Z-axis depth scaling.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['swipeable'], hapticEvents: ['swipe_commit', 'step_advance', 'completion'], hapticSignature: 'Heavy shell detaching and flying off — lighter with each layer until weightless luminous core', stateRange: [0, 1], continuous: false, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Layer Peeling'], status: 'complete' },
  { id: 'armor-drop', number: 252, series: 'identity-decoupling', seriesPosition: 2, name: 'The Armor Drop Engine', intent: 'Defense mechanisms that saved you in childhood are now suffocating you. Unlatch the iron plates — float.', physics: 'Heavy rigid-body constraints, latch snapping, gravity acceleration, buoyant lift.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['tappable'], hapticEvents: ['tap', 'step_advance', 'completion'], hapticSignature: 'Floor-shaking thuds as iron drops — each release lighter, node expanding and floating upward', stateRange: [0, 1], continuous: false, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Exhaustion Release'], status: 'complete' },
  { id: 'predicate-eraser', number: 253, series: 'identity-decoupling', seriesPosition: 3, name: 'The Predicate Eraser Engine', intent: 'Any word after "I AM" is a limitation. Erase the predicate — "I AM" alone emits a massive warm heartbeat.', physics: 'Typography particle dispersion, localized blurring, center-locking magnetic force.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['drawable'], hapticEvents: ['drag_snap', 'completion'], hapticSignature: 'Labels dissolving to ash — "I AM" locking center with undeniable warm haptic heartbeat', stateRange: [0, 1], continuous: false, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['The I AM Core'], status: 'complete' },
  { id: 'costume-closet', number: 254, series: 'identity-decoupling', seriesPosition: 4, name: 'The Costume Closet Engine', intent: 'Your personality is a suit for this incarnation. Slide the cloak off the avatar — reveal the glowing silhouette of pure potential.', physics: 'Cloth simulation, hanger sliding, translucent rendering.', renderMode: 'webgl', defaultScale: 'full', surfaces: ['draggable'], hapticEvents: ['drag_snap', 'completion'], hapticSignature: 'Heavy fabric sliding off with weight — avatar glowing through translucent freedom', stateRange: [0, 1], continuous: false, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['The Wardrobe'], status: 'complete' },
  { id: 'time-lapse-mirror', number: 255, series: 'identity-decoupling', seriesPosition: 5, name: 'The Time-Lapse Mirror Engine', intent: 'The face ages, the world changes — but the eyes remain absolutely stable, unchanging, glowing with quiet awareness.', physics: 'Procedural aging shaders, morph targets, rapid timeline scrubbing, stable pupil tracking.', renderMode: 'webgl', defaultScale: 'full', surfaces: ['scrubable'], hapticEvents: ['drag_snap', 'completion'], hapticSignature: 'Hurricane of time spinning around perfectly stable unchanging center warmth', stateRange: [0, 1], continuous: true, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['The Changeless Witness'], status: 'complete' },
  { id: 'resume-burner', number: 256, series: 'identity-decoupling', seriesPosition: 6, name: 'The Resume Burner Engine', intent: 'You are not your achievements or failures. Burn the resume — find the indestructible diamond beneath.', physics: 'Thermal combustion shaders, ash scattering, wind vectors.', renderMode: 'webgl', defaultScale: 'full', surfaces: ['holdable'], hapticEvents: ['hold_start', 'step_advance', 'completion'], hapticSignature: 'Crackling fire consuming text — smoke clearing to reveal a perfect ringing bell diamond', stateRange: [0, 1], continuous: true, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Unconditional Worth'], status: 'complete' },
  { id: 'space-container', number: 257, series: 'identity-decoupling', seriesPosition: 7, name: 'The Space Container Engine', intent: 'You are not the furniture — you are the room. Expand the bounding box into a massive cathedral; thoughts become insignificant marbles.', physics: 'Negative space highlighting, wireframe expansion, object miniaturization.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['pinchable'], hapticEvents: ['hold_start', 'step_advance', 'completion'], hapticSignature: 'Cluttered chaos shrinking into tiny rattling marbles in a vast silent cathedral', stateRange: [0, 1], continuous: true, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['The Room'], status: 'complete' },
  { id: 'nobody', number: 258, series: 'identity-decoupling', seriesPosition: 8, name: 'The Nobody Engine', intent: 'Profound relief in being absolutely nobody. Dissolve the avatar into the background color — total beautiful invisibility.', physics: 'Mosaic pixelation, feature smoothing, silhouette blending into background.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['scrubable'], hapticEvents: ['drag_snap', 'completion'], hapticSignature: 'Tight high-strung buzz releasing into expansive airy frictionless glide — total invisibility', stateRange: [0, 1], continuous: true, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['The Relief of Anonymity'], status: 'complete' },
  { id: 're-entry', number: 259, series: 'identity-decoupling', seriesPosition: 9, name: 'The Re-Entry Engine', intent: 'Put the costume back on — but now it is light, playful, frictionless. The soul shines through the fabric. You know it is a game.', physics: 'Holographic snapping, lightness mapping, zero-gravity attachment.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['draggable'], hapticEvents: ['drag_snap', 'completion'], hapticSignature: 'Heavy cloak returning as weightless playful snap — brilliant light clearly shining through', stateRange: [0, 1], continuous: false, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Choosing the Game'], status: 'complete' },
  { id: 'soul-seal', number: 260, series: 'identity-decoupling', seriesPosition: 10, name: 'The Soul Seal', intent: 'The capstone: a single brilliant spark. No text, no UI. It pulses in exact rhythm with your biometric pulse. Eternal, safe.', physics: 'Singularity glow, breathing light rhythms, frictionless hovering.', renderMode: 'canvas', defaultScale: 'point', surfaces: ['holdable'], hapticEvents: ['hold_start', 'hold_threshold', 'seal_stamp'], hapticSignature: 'Perfect warm silent pulse in exact rhythm with the user — unbothered, eternal, safe', stateRange: [0, 1], continuous: true, hasResolution: true, breathCoupling: 'modulates', deviceRequirements: ['haptics'], implementations: ['The Luminous Spark'], status: 'complete' },
];

// SERIES 27: THE COSMIC PLAY (Atoms 261–270)
export const S27: AtomMeta[] = [
  { id: 'destination-override', number: 261, series: 'cosmic-play', seriesPosition: 1, name: 'The Destination Override Engine', intent: 'If music\'s purpose was the end, conductors would play the final chord first. The progress bar bends into a circle — there is no end.', physics: 'Procedural audio sequencing, horizontal continuous scrolling, rhythm-based haptic gating.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['draggable', 'scrubable'], hapticEvents: ['drag_snap', 'step_advance', 'completion'], hapticSignature: 'Urgent ticking clock transforming into sweeping melodic waltz on the circular sequencer', stateRange: [0, 1], continuous: true, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics', 'audio-output'], implementations: ['The Symphony'], status: 'complete' },
  { id: 'sand-mandala', number: 262, series: 'cosmic-play', seriesPosition: 2, name: 'The Sand Mandala Engine', intent: 'Build a stunning mandala — then blow it away. The joy was in the building. Non-attachment.', physics: 'Granular synthesis, thousands of independent particles, directional wind vectors.', renderMode: 'webgl', defaultScale: 'full', surfaces: ['draggable', 'drawable', 'voice'], hapticEvents: ['drag_snap', 'swipe_commit', 'completion'], hapticSignature: 'Gritty satisfying sand friction dissolving into weightless chaotic beautiful cloud', stateRange: [0, 1], continuous: false, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics', 'microphone'], implementations: ['Beautiful Futility'], status: 'complete' },
  { id: 'toy-box', number: 263, series: 'cosmic-play', seriesPosition: 3, name: 'The Toy Box Engine', intent: 'The sharp aggressive threat drops — and bounces like a rubber ball. The monster is just a toy.', physics: 'Soft-body physics with high restitution, elastic bouncing, gravity inversion.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['tappable', 'draggable'], hapticEvents: ['tap', 'step_advance', 'completion'], hapticSignature: 'Bracing for harsh crash — silly high-pitched boing and playful bouncing instead', stateRange: [0, 1], continuous: false, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Threat Deflation'], status: 'complete' },
  { id: 'sisyphus-smile', number: 264, series: 'cosmic-play', seriesPosition: 4, name: 'The Sisyphus Smile Engine', intent: 'Pushing the boulder is only punishment if you hate the pushing. Establish rhythm — the grind becomes a kinetic game.', physics: 'Heavy mass simulation, rotational momentum, ascending incline planes.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['draggable', 'swipeable'], hapticEvents: ['drag_snap', 'step_advance', 'completion'], hapticSignature: 'Grinding heavy agony transforming into satisfying rhythmic sparks and harmonious notes', stateRange: [0, 1], continuous: true, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['The Joy of the Roll'], status: 'complete' },
  { id: 'improvisation', number: 265, series: 'cosmic-play', seriesPosition: 5, name: 'The Improvisation Engine', intent: 'You cannot script a dance. Follow the unpredictable dot — stop thinking, start flowing.', physics: 'Procedural path generation, randomized target spawning, fluid Bezier connection.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['draggable'], hapticEvents: ['drag_snap', 'error_boundary', 'completion'], hapticSignature: 'Line breaking on anticipation — smooth continuous ice-skate on pure real-time flow', stateRange: [0, 1], continuous: true, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['The Yes And'], status: 'complete' },
  { id: 'stakes-free', number: 266, series: 'cosmic-play', seriesPosition: 6, name: 'The Stakes-Free Engine', intent: 'Turn off the scoreboard. The spikes are just xylophone keys. The maze is an instrument to play, not a threat.', physics: 'Collision toggling, zero-penalty bounding boxes, infinite undo states.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['draggable'], hapticEvents: ['tap', 'step_advance', 'completion'], hapticSignature: 'Expected harsh buzz replaced by delightful musical chime — terror becoming play', stateRange: [0, 1], continuous: true, hasResolution: false, breathCoupling: 'none', deviceRequirements: ['haptics', 'audio-output'], implementations: ['The Practice Room'], status: 'complete' },
  { id: 'character-drop', number: 267, series: 'cosmic-play', seriesPosition: 7, name: 'The Character Drop Engine', intent: 'The curtain drops. Step out of the spotlight into the warm backstage. The performance is over.', physics: 'Spotlight masking, heavy curtain fabric simulation, ambient lighting shifts.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['swipeable'], hapticEvents: ['swipe_commit', 'completion'], hapticSignature: 'Frantic spotlight buzz extinguished — sinking into heavy warm amber backstage calm', stateRange: [0, 1], continuous: false, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['The Backstage'], status: 'complete' },
  { id: 'juggler', number: 268, series: 'cosmic-play', seriesPosition: 8, name: 'The Juggler Engine', intent: 'Your responsibilities are not glass — they are rubber. Drop them. They bounce right back.', physics: 'Multi-body projectile physics, elastic restitution, continuous arc trajectories.', renderMode: 'canvas', defaultScale: 'field', surfaces: ['tappable'], hapticEvents: ['tap', 'step_advance', 'completion'], hapticSignature: 'Terrifying glass fragility revealed as delightful bouncy rubber — playful juggling haptics', stateRange: [0, 1], continuous: true, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Lightening the Load'], status: 'complete' },
  { id: 'infinite-canvas', number: 269, series: 'cosmic-play', seriesPosition: 9, name: 'The Infinite Canvas Engine', intent: 'You made a mistake on a tiny canvas. Zoom out — the canvas is infinite. Your mistake is microscopic.', physics: 'Infinite scaling algorithms, procedural grid generation, seamless panning.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['pinchable', 'drawable'], hapticEvents: ['hold_start', 'step_advance', 'completion'], hapticSignature: 'Claustrophobic restriction expanding into vast infinite freedom — mistake vanishing to a speck', stateRange: [0, 1], continuous: true, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Boundlessness'], status: 'complete' },
  { id: 'lila-seal', number: 270, series: 'cosmic-play', seriesPosition: 10, name: 'The Lila Seal', intent: 'The capstone: I am not the dancer, I am the dance. No targets, no score. A ribbon follows your touch generating ambient chord.', physics: 'Harmonic oscillators, continuous fluid looping, generative ambient feedback.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['draggable', 'observable'], hapticEvents: ['drag_snap', 'seal_stamp'], hapticSignature: 'Perfect uninterrupted silken glide — ambient chord swelling with velocity — infinite play', stateRange: [0, 1], continuous: true, hasResolution: false, breathCoupling: 'modulates', deviceRequirements: ['haptics', 'audio-output'], implementations: ['The Dancer'], status: 'complete' },
];

// SERIES 28: THE IMPERMANENCE ENGINE (Atoms 271–280)
export const S28: AtomMeta[] = [
  { id: 'open-palm', number: 271, series: 'impermanence-engine', seriesPosition: 1, name: 'The Open Palm Engine', intent: 'You cannot hold water by clenching. Press too hard and it cracks. Rest weightlessly — the object heals and glows.', physics: 'Pressure-sensitive mesh distortion, fracture mechanics, buoyant resting states.', renderMode: 'canvas', defaultScale: 'focus', surfaces: ['holdable', 'pressure-sensitive'], hapticEvents: ['hold_start', 'error_boundary', 'completion'], hapticSignature: 'Grinding cracks under pressure — releasing to weightless glow of safe open-palm rest', stateRange: [0, 1], continuous: true, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['The Grip of Suffering'], status: 'complete' },
  { id: 'evaporation', number: 272, series: 'impermanence-engine', seriesPosition: 2, name: 'The Evaporation Engine', intent: 'Grief is heavy liquid. Heat (awareness) changes the state of matter — liquid becomes weightless golden steam.', physics: 'Thermodynamic particle state-shifting, fluid-to-gas phase rendering, vertical gravity inversion.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['holdable'], hapticEvents: ['hold_start', 'hold_threshold', 'completion'], hapticSignature: 'Heavy dense weight warming under sustained touch — golden steam floating upward, bottom clearing', stateRange: [0, 1], continuous: true, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Phase State Change'], status: 'complete' },
  { id: 'autumn-leaf', number: 273, series: 'impermanence-engine', seriesPosition: 3, name: 'The Autumn Leaf Engine', intent: 'The tree does not fight autumn. Swipe the stem — the chaotic wind dies, and the leaf drifts in gorgeous slow-motion peace.', physics: 'Procedural detachment, wind-resistance swaying, slow-motion gravity easing.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['swipeable'], hapticEvents: ['swipe_commit', 'completion'], hapticSignature: 'Chaotic desperate wind silenced the instant stem is cut — frictionless slow-motion peace', stateRange: [0, 1], continuous: false, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Graceful Yielding'], status: 'complete' },
  { id: 'wave-decay', number: 274, series: 'impermanence-engine', seriesPosition: 4, name: 'The Wave Decay Engine', intent: 'Stop striking the bell. Let the echo naturally fade to silence. Every tap restarts the pain.', physics: 'Web Audio API envelope generation (ADSR), amplitude reduction, waveform flattening.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['tappable', 'observable'], hapticEvents: ['tap', 'completion'], hapticSignature: 'Each tap spikes maximum volume — removing hand allows natural beautiful decay to flat silence', stateRange: [0, 1], continuous: true, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['The Echo'], status: 'complete' },
  { id: 'ebb-tide', number: 275, series: 'impermanence-engine', seriesPosition: 5, name: 'The Ebb Tide Engine', intent: 'Write your tragedy in the sand. Let the ocean wash it smooth.', physics: 'Height-map erosion, fluid simulation, particle smoothing.', renderMode: 'webgl', defaultScale: 'full', surfaces: ['drawable'], hapticEvents: ['drag_snap', 'completion'], hapticSignature: 'Gritty harsh carving soothed by crystal-clear wave sweep — perfectly smooth pristine silence', stateRange: [0, 1], continuous: false, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Washing the Sand'], status: 'complete' },
  { id: 'metamorphosis', number: 276, series: 'impermanence-engine', seriesPosition: 6, name: 'The Metamorphosis Engine', intent: 'What the caterpillar calls the end, the master calls a butterfly. Destruction is preamble to expansion.', physics: 'Voronoi fracturing, internal luminescence bursting, Z-axis soaring.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['tappable'], hapticEvents: ['tap', 'step_advance', 'completion'], hapticSignature: 'Claustrophobic tense tapping — blinding light cracks erupting into radiant Z-axis soaring', stateRange: [0, 1], continuous: false, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['The Necessary End'], status: 'complete' },
  { id: 'exhale-cycle', number: 277, series: 'impermanence-engine', seriesPosition: 7, name: 'The Exhale Cycle Engine', intent: 'Everything must be emptied to be refilled. Release the brilliant sphere — it diffuses into warm ambient glow.', physics: 'Volumetric compression, pressure-valve mechanics, radial diffusion.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['holdable', 'breathable'], hapticEvents: ['hold_start', 'hold_release', 'completion'], hapticSignature: 'Tight shaking stutter of holding too long — beautiful instant release into warm ambient spread', stateRange: [0, 1], continuous: true, hasResolution: true, breathCoupling: 'drives', deviceRequirements: ['haptics'], implementations: ['The Law of Cycles'], status: 'complete' },
  { id: 'kintsugi', number: 278, series: 'impermanence-engine', seriesPosition: 8, name: 'The Kintsugi Engine', intent: 'The break is not tragedy — it is history. Trace the cracks with liquid gold. More beautiful for having been broken.', physics: 'Spline tracing, metallic material rendering, geometric reassembly.', renderMode: 'canvas', defaultScale: 'focus', surfaces: ['draggable', 'drawable'], hapticEvents: ['drag_snap', 'step_advance', 'completion'], hapticSignature: 'Smooth rich heavy gold vibration flowing into cracks — undeniably more valuable than before', stateRange: [0, 1], continuous: true, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Beautiful Brokenness'], status: 'complete' },
  { id: 'sunset', number: 279, series: 'impermanence-engine', seriesPosition: 9, name: 'The Sunset Engine', intent: 'You do not cry when the sun sets — you marvel at the colors. Treat the end of this chapter the same way.', physics: 'Atmospheric light scattering (Rayleigh/Mie), color gradient interpolation, horizontal descent locking.', renderMode: 'webgl', defaultScale: 'full', surfaces: ['draggable'], hapticEvents: ['drag_snap', 'step_advance', 'completion'], hapticSignature: 'Bright noon descending into heart-achingly beautiful crimson-purple-gold — deep warm peaceful hum', stateRange: [0, 1], continuous: true, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['The Art of the End'], status: 'complete' },
  { id: 'anicca-seal', number: 280, series: 'impermanence-engine', seriesPosition: 10, name: 'The Anicca Seal', intent: 'The capstone: a sculpture naturally, softly dissolves on its own. Watch. This too shall pass. Total peace with the void.', physics: 'Particle evaporation, alpha channel fading, frictionless UI dissipation.', renderMode: 'canvas', defaultScale: 'focus', surfaces: ['observable'], hapticEvents: ['completion', 'seal_stamp'], hapticSignature: 'Solid beauty naturally dissolving to mist to light to nothing — soft chime in total peace', stateRange: [0, 1], continuous: true, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['The Passing Cloud'], status: 'complete' },
];

// SERIES 29: THE INTEROCEPTIVE ANCHOR (Atoms 281–290)
export const S29: AtomMeta[] = [
  { id: 'bio-mirror', number: 281, series: 'interoceptive-anchor', seriesPosition: 1, name: 'The Bio-Mirror Engine', intent: 'Track the blood pumping through your thumb right now. Each heartbeat creates a massive glowing sonic ring.', physics: 'Concentric wave generation, low-pass haptic filtering, real-time rhythmic interpolation.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['pressure-sensitive', 'holdable'], hapticEvents: ['hold_start', 'step_advance', 'completion'], hapticSignature: 'Deep subsonic double-thud (lub-dub) — phone physically feeling like a beating heart', stateRange: [0, 1], continuous: true, hasResolution: false, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Pulse Sync'], status: 'complete' },
  { id: 'respiration-pendulum', number: 282, series: 'interoceptive-anchor', seriesPosition: 2, name: 'The Respiration Pendulum Engine', intent: 'Make the breath visible and heavy. Blow on the glass to swing the pendulum — slow steady exhale creates perfect arc.', physics: 'Microphone input gating, pendulum swing physics, kinetic energy conversion.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['voice', 'breathable'], hapticEvents: ['breath_peak', 'error_boundary', 'completion'], hapticSignature: 'Chaotic erratic swinging smoothing into perfect wide hypnotic sweeping vibration', stateRange: [0, 1], continuous: true, hasResolution: true, breathCoupling: 'drives', deviceRequirements: ['haptics', 'microphone'], implementations: ['The Breath Weight'], status: 'complete' },
  { id: 'plumb-line', number: 283, series: 'interoceptive-anchor', seriesPosition: 3, name: 'The Plumb Line Engine', intent: 'Anxiety makes you float. Find the gravitational center — hold the device in absolute physical stillness.', physics: 'Device orientation API, gravity vectors, magnetic locking.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['gyroscopic'], hapticEvents: ['step_advance', 'completion'], hapticSignature: 'Rattling swinging plumb bob locking into dead-center ring with heavy unshakeable metallic clack', stateRange: [0, 1], continuous: true, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics', 'gyroscope'], implementations: ['Gravitational Center'], status: 'complete' },
  { id: 'cymatic-resonance', number: 284, series: 'interoceptive-anchor', seriesPosition: 4, name: 'The Cymatic Resonance Engine', intent: 'Sound is physical geometry. Hum a sustained note — chaotic particles sweep into a breathtaking symmetric mandala.', physics: 'Real-time audio FFT, particle nodal line mapping, resonance frequency simulation.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['voice'], hapticEvents: ['hold_start', 'step_advance', 'completion'], hapticSignature: 'Chaotic scatter resolving into crystalline geometric mandala under sustained vocal tone', stateRange: [0, 1], continuous: true, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics', 'microphone'], implementations: ['The Vocal Anchor'], status: 'complete' },
  { id: 'focal-collapse', number: 285, series: 'interoceptive-anchor', seriesPosition: 5, name: 'The Focal Collapse Engine', intent: 'Overwhelm = aperture too wide. Pinch the world down to a single safe 1-inch circle of focus.', physics: 'Radial vignette masking, extreme Gaussian blur, localized lighting.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['pinchable'], hapticEvents: ['hold_start', 'step_advance', 'completion'], hapticSignature: 'Overwhelming chaos collapsing into tiny perfect clear circle of singular calm focus', stateRange: [0, 1], continuous: true, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Peripheral Fade'], status: 'complete' },
  { id: 'tectonic-drop', number: 286, series: 'interoceptive-anchor', seriesPosition: 6, name: 'The Tectonic Drop Engine', intent: 'The ego hovers above the head. Drop it into the gut — the node becomes a heavy silent red anchor.', physics: 'Extreme Z-axis acceleration, heavy mass deceleration, shockwave rendering.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['swipeable'], hapticEvents: ['swipe_commit', 'completion'], hapticSignature: 'Frantic white buzz dropping like 10-ton boulder — massive screen-shake sonic boom into silent red anchor', stateRange: [0, 1], continuous: false, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['The Somatic Fall'], status: 'complete' },
  { id: 'micro-tremor', number: 287, series: 'interoceptive-anchor', seriesPosition: 7, name: 'The Micro-Tremor Engine', intent: 'The glass mirrors your hidden adrenaline at 100x magnification. Consciously relax until the mercury pools into a mirror.', physics: 'Accelerometer data amplification, particle jitter, exponential decay filtering.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['gyroscopic', 'observable'], hapticEvents: ['step_advance', 'completion'], hapticSignature: 'Violent mercury splashing calming to flawless glassy motionless mirror under conscious relaxation', stateRange: [0, 1], continuous: true, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics', 'gyroscope'], implementations: ['Stillness Magnification'], status: 'complete' },
  { id: 'thermal-boundary', number: 288, series: 'interoceptive-anchor', seriesPosition: 8, name: 'The Thermal Boundary Engine', intent: 'Where do you end and the world begin? Trace the outline of your hand on the glass — draw the perimeter of your safety.', physics: 'Thermal gradient shaders, continuous path logic, radiant heat rendering.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['drawable'], hapticEvents: ['drag_snap', 'step_advance', 'completion'], hapticSignature: 'Slow warm heavy drag tracing protective thermal border — completing the full somatic circuit', stateRange: [0, 1], continuous: true, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Skin Awareness'], status: 'complete' },
  { id: 'weight-of-world', number: 289, series: 'interoceptive-anchor', seriesPosition: 9, name: 'The Weight of the World Engine', intent: 'You are holding the sky with your shoulders. Let go — the ceiling shatters into a million weightless golden sparks.', physics: 'Upward gravitational resistance, friction locking, sudden-release physics.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['holdable'], hapticEvents: ['hold_start', 'hold_release', 'completion'], hapticSignature: 'Grinding painful exhausted pushing — explosive liberating shatter into weightless golden sparks', stateRange: [0, 1], continuous: false, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Atlas Release'], status: 'complete' },
  { id: 'anchor-seal', number: 290, series: 'interoceptive-anchor', seriesPosition: 10, name: 'The Anchor Seal', intent: 'The capstone: a wandering spark pulled to dead center under your thumb. A single perfect incredibly deep sustained note. You are Here.', physics: 'Multi-sensory convergence, absolute zero-velocity centering, deep harmonic resonance.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['holdable'], hapticEvents: ['hold_start', 'hold_threshold', 'seal_stamp'], hapticSignature: 'Chaotic wandering spark pulled into absolute center — brilliant flash and deep sustained note', stateRange: [0, 1], continuous: true, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['The Eternal Here'], status: 'complete' },
];

// SERIES 30: THE LOVING AWARENESS (Atoms 291–300)
export const S30: AtomMeta[] = [
  { id: 'shadow-embrace', number: 291, series: 'loving-awareness', seriesPosition: 1, name: 'The Shadow Embrace Engine', intent: 'The ego wars with darkness. Drag the shadow into your center — it does not destroy; it expands your light by 200%.', physics: 'Magnetic attraction overriding resistance, color-inversion blending, harmonic resonance.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['draggable'], hapticEvents: ['drag_snap', 'error_boundary', 'completion'], hapticSignature: 'Ego terror resistance melting into warm golden expansion as shadow integrates into light', stateRange: [0, 1], continuous: false, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Fierce Grace'], status: 'complete' },
  { id: 'metta-radiance', number: 292, series: 'loving-awareness', seriesPosition: 2, name: 'The Metta Radiance Engine', intent: 'Extend compassion in concentric rings — self, loved ones, strangers, enemies, cosmos. Drag the light to the absolute edge.', physics: 'Unbounded radial scaling, volumetric light emission, infinite Z-axis camera pull.', renderMode: 'webgl', defaultScale: 'full', surfaces: ['draggable'], hapticEvents: ['drag_snap', 'step_advance', 'completion'], hapticSignature: 'Warm ring expanding through each stage — reaching edges becomes blinding frictionless light source', stateRange: [0, 1], continuous: true, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Concentric Compassion'], status: 'complete' },
  { id: 'golden-thread', number: 293, series: 'loving-awareness', seriesPosition: 3, name: 'The Golden Thread Engine', intent: 'Connect the Pain, the Surviving, and the Now with a single thread. The pain is retroactively transformed into fuel.', physics: 'Bezier spline drawing, sequential node illumination, chronological sequencing.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['draggable'], hapticEvents: ['drag_snap', 'step_advance', 'completion'], hapticSignature: 'Deep heavy pain shudder turning gold — brilliant pulse of light traveling backward through the timeline', stateRange: [0, 1], continuous: false, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['The Lifeline'], status: 'complete' },
  { id: 'altar', number: 294, series: 'loving-awareness', seriesPosition: 4, name: 'The Altar Engine', intent: 'Some burdens are too heavy for the ego. Place them on the altar — the stone combusts into weightless glowing embers.', physics: 'Gravitational drop, particle combustion, ambient easing.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['draggable'], hapticEvents: ['drag_snap', 'hold_release', 'completion'], hapticSignature: 'Exhausting heavy holding releasing into instant combustion — weightless embers drifting peacefully upward', stateRange: [0, 1], continuous: false, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['The Sacred Offering'], status: 'complete' },
  { id: 'namaste-lens', number: 295, series: 'loving-awareness', seriesPosition: 5, name: 'The Namaste Lens Engine', intent: 'Underneath the terrifying armor of your enemy is the same Soul that lives in you. Pull the armor apart to find the identical light.', physics: 'Alpha-mask scraping, depth-of-field manipulation, inner-core revelation.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['pinchable'], hapticEvents: ['hold_start', 'step_advance', 'completion'], hapticSignature: 'Harsh jagged geometry splitting and fading — revealing softly pulsing identical light within', stateRange: [0, 1], continuous: true, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Seeing the Divine'], status: 'complete' },
  { id: 'karmic-severance', number: 296, series: 'loving-awareness', seriesPosition: 6, name: 'The Karmic Severance Engine', intent: 'Resentment is poison you drink yourself. Cut the chain — the weight plummets, and your avatar shoots into the open sky.', physics: 'Tensile rope physics, elastic snap, extreme buoyant acceleration.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['swipeable'], hapticEvents: ['swipe_commit', 'completion'], hapticSignature: 'High-tension chain vibration violently snapping — joyful effortless soaring into open sky', stateRange: [0, 1], continuous: false, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['The Release'], status: 'complete' },
  { id: 'infinite-heart', number: 297, series: 'loving-awareness', seriesPosition: 7, name: 'The Infinite Heart Engine', intent: 'The heart does not break — it breaks open to hold more. Press the center — the glass shatters but the light continues to expand.', physics: 'Volumetric expansion, rigid-body shattering from internal force, continuous radial growth.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['holdable', 'breathable'], hapticEvents: ['hold_start', 'step_advance', 'completion'], hapticSignature: 'Tight restricted heartbeat expanding until glass shatters — heartbeat becoming deep slow universal', stateRange: [0, 1], continuous: true, hasResolution: true, breathCoupling: 'drives', deviceRequirements: ['haptics'], implementations: ['Expansion over Fracture'], status: 'complete' },
  { id: 'i-am', number: 298, series: 'loving-awareness', seriesPosition: 8, name: 'The I AM Engine', intent: 'Strip every noun and adjective. What remains? "I AM" — merging into a single blindingly bright sphere of white light.', physics: 'Kinetic typography erasure, text-to-light morphing, absolute centering.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['drawable'], hapticEvents: ['drag_snap', 'step_advance', 'completion'], hapticSignature: 'Words dissolving under finger — "I AM" merging into blindingly bright perfectly silent white sphere', stateRange: [0, 1], continuous: false, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['The Verb'], status: 'complete' },
  { id: 'ocean-drop', number: 299, series: 'loving-awareness', seriesPosition: 9, name: 'The Ocean Drop Engine', intent: 'The drop is terrified of the ocean. Tap it — it loses its boundary, but its impact sends a massive silver ripple across the entire world.', physics: 'Surface tension collapse, fluid dynamics mixing, ripple generation.', renderMode: 'webgl', defaultScale: 'full', surfaces: ['tappable'], hapticEvents: ['tap', 'completion'], hapticSignature: 'Perfect drop striking surface — individual boundary dissolving into vast gorgeous silver ripple', stateRange: [0, 1], continuous: false, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['The Surrender'], status: 'complete' },
  { id: 'atlas-omega', number: 300, series: 'loving-awareness', seriesPosition: 10, name: 'The Atlas Omega', intent: 'The absolute end. 299 nodes swirling like a galaxy collapse into a single permanent pixel of pure white light. You are the light.', physics: 'Total UI collapse, singularity focusing, biometric pulse mirroring, absolute zero-friction stillness.', renderMode: 'canvas', defaultScale: 'point', surfaces: ['holdable'], hapticEvents: ['hold_start', 'hold_threshold', 'seal_stamp'], hapticSignature: 'Entire galaxy folding inward to single pixel — gentle life-affirming throb synced to heartbeat', stateRange: [0, 1], continuous: true, hasResolution: true, breathCoupling: 'modulates', deviceRequirements: ['haptics'], implementations: ['The Singularity of Love'], status: 'complete' },
];
