/**
 * ATOM REGISTRY — COLLECTION 2: THE TELEMETRIC NAVIGATOR
 * =======================================================
 * Metadata for atoms 101–200 across series 11–20.
 * Split from atom-registry.ts for maintainability.
 */

import type { AtomMeta } from './types';

// SERIES 11: THE EPISTEMIC CONSTRUCTS (Atoms 101–110)
export const S11: AtomMeta[] = [
  { id: 'centrifuge-engine', number: 101, series: 'epistemic-constructs', seriesPosition: 1, name: 'The Centrifuge Engine', intent: 'The anxious mind blends facts and feelings into a single terrifying smoothie. Rotational physics separates the heavy data from the lightweight anxiety.', physics: 'High-G rotational forces, mass-based particle sorting, density stratification.', renderMode: 'canvas', defaultScale: 'focus', surfaces: ['draggable', 'holdable', 'breathable'], hapticEvents: ['tap', 'step_advance', 'completion'], hapticSignature: 'Heavy mechanical spinning — grinding centrifuge that clicks into stratified clarity', stateRange: [0, 1], continuous: true, hasResolution: true, breathCoupling: 'modulates', deviceRequirements: ['haptics'], implementations: ['Fact vs Feeling'], status: 'complete' },
  { id: 'ladder-of-inference', number: 102, series: 'epistemic-constructs', seriesPosition: 2, name: 'The Ladder of Inference Engine', intent: 'Walk backward from catastrophic conclusion down to the boring data that triggered it.', physics: 'Z-axis descent, structural scaffolding disassembly, cascading drops.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['swipeable', 'tappable'], hapticEvents: ['swipe_commit', 'step_advance', 'completion'], hapticSignature: 'Each layer crumbles with a heavy structural drop — until only the harmless base remains', stateRange: [0, 1], continuous: false, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Deconstruction Ladder'], status: 'complete' },
  { id: 'logic-gate', number: 103, series: 'epistemic-constructs', seriesPosition: 3, name: 'The Logic Gate Engine', intent: 'Anxiety is an open loop. Peace is a closed circuit. Wire the circuit shut.', physics: 'Electrical pathfinding, snap-to-grid circuitry, current illumination.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['draggable', 'typeable'], hapticEvents: ['drag_snap', 'completion'], hapticSignature: 'Sparking open gap resolving into smooth golden electrical pulse flow', stateRange: [0, 1], continuous: false, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['If/Then Circuit'], status: 'complete' },
  { id: 'steel-man', number: 104, series: 'epistemic-constructs', seriesPosition: 4, name: 'The Steel-Man Engine', intent: 'Construct the strongest possible opposing argument to build empathy and dissolve black-and-white thinking.', physics: 'Tensile bridge building, counter-weight mechanics, structural load-testing.', renderMode: 'canvas', defaultScale: 'field', surfaces: ['tappable', 'draggable'], hapticEvents: ['tap', 'step_advance', 'completion'], hapticSignature: 'Building structural weight on both sides — then the satisfying lock of a balanced bridge', stateRange: [0, 1], continuous: false, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Antithesis Builder'], status: 'complete' },
  { id: 'blind-spot', number: 105, series: 'epistemic-constructs', seriesPosition: 5, name: 'The Blind Spot Engine', intent: 'Force the user to look precisely where they are avoiding looking.', physics: 'Radial masking, dynamic lighting (raycasting), shadow rendering.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['draggable'], hapticEvents: ['drag_snap', 'step_advance', 'completion'], hapticSignature: 'Volumetric flashlight cutting through darkness — shadows shrinking under sustained light', stateRange: [0, 1], continuous: true, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Illumination Sweep'], status: 'complete' },
  { id: 'sunk-cost-severance', number: 106, series: 'epistemic-constructs', seriesPosition: 6, name: 'The Sunk-Cost Severance Engine', intent: 'Provide the physical sensation of cutting the loss and feeling the immediate relief of the jettison.', physics: 'Snapping tension cables, rapid buoyant ascent, mass deletion.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['swipeable', 'draggable'], hapticEvents: ['swipe_commit', 'completion'], hapticSignature: 'Violent cable twang followed by soaring frictionless ascent into bright sky', stateRange: [0, 1], continuous: false, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Eject Seat'], status: 'complete' },
  { id: 'absurdity-deflation', number: 107, series: 'epistemic-constructs', seriesPosition: 7, name: 'The Absurdity Deflation Engine', intent: 'Logic cannot defeat irrational fear. Humor can. Physically deflate the seriousness of a monolithic belief.', physics: 'Soft-body inflation/deflation, elastic bouncing, helium audio-shifting.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['tappable'], hapticEvents: ['tap', 'step_advance', 'completion'], hapticSignature: 'Rigid block softening into comical balloon — erratic deflation squeak', stateRange: [0, 1], continuous: false, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['The Trickster'], status: 'complete' },
  { id: 'first-principles', number: 108, series: 'epistemic-constructs', seriesPosition: 8, name: 'The First Principles Engine', intent: 'Strip the problem down to fundamental truths that cannot be deduced any further.', physics: 'Geological excavation, seismic sorting, absolute rigidity.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['holdable', 'tappable'], hapticEvents: ['hold_start', 'step_advance', 'completion'], hapticSignature: 'Violent earthquake shattering fragile assumptions — one unshakeable monolith surviving', stateRange: [0, 1], continuous: false, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Bedrock Excavation'], status: 'complete' },
  { id: 'echo-cancellation', number: 109, series: 'epistemic-constructs', seriesPosition: 9, name: 'The Echo Cancellation Engine', intent: 'Dampen the echoes of parents, society, or trauma to find your own voice.', physics: 'Acoustic dampening walls, wave reflection, frequency isolation.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['draggable', 'tappable'], hapticEvents: ['drag_snap', 'step_advance', 'completion'], hapticSignature: 'Chaotic reflections dying as padding absorbs them — single quiet original remains', stateRange: [0, 1], continuous: false, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Source Verification'], status: 'complete' },
  { id: 'axiomatic-seal', number: 110, series: 'epistemic-constructs', seriesPosition: 10, name: 'The Axiomatic Seal', intent: 'Take the distilled truth and permanently stamp it into the architecture of the mind.', physics: 'Molten wax mechanics, heavy kinetic stamping, cooling crystallization.', renderMode: 'canvas', defaultScale: 'focus', surfaces: ['holdable'], hapticEvents: ['hold_start', 'hold_threshold', 'seal_stamp'], hapticSignature: 'Liquid wax cooling into stunning crystalline seal — heaviest vault-door thud', stateRange: [0, 1], continuous: false, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Foundation Laying'], status: 'complete' },
];

// SERIES 12: THE FRICTION MECHANICS (Atoms 111–120)
export const S12: AtomMeta[] = [
  { id: 'inertia-break', number: 111, series: 'friction-mechanics', seriesPosition: 1, name: 'The Inertia Break Engine', intent: 'Getting started requires massive energy, but keeping going requires almost none.', physics: 'Breakaway force thresholds, sudden mass-drop algorithms, kinetic gliding.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['draggable', 'holdable'], hapticEvents: ['hold_start', 'drag_snap', 'completion'], hapticSignature: 'Grinding stutter of static friction giving way to frictionless icy glide', stateRange: [0, 1], continuous: true, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Static to Dynamic'], status: 'complete' },
  { id: 'micro-step-shrink', number: 112, series: 'friction-mechanics', seriesPosition: 2, name: 'The Micro-Step Engine', intent: 'The mile is impossible; the inch is easy. Shrink the target until it is too small to fail.', physics: 'Radial downscaling, mass depletion, friction decay.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['tappable'], hapticEvents: ['tap', 'step_advance', 'completion'], hapticSignature: 'Boulder fracturing smaller with each tap — final pixel flicked effortlessly', stateRange: [0, 1], continuous: false, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Granularity Shrink'], status: 'complete' },
  { id: 'ulysses-pact', number: 113, series: 'friction-mechanics', seriesPosition: 3, name: 'The Ulysses Pact Engine', intent: 'Lock in a decision right now. Burn the boats so your future self cannot back out.', physics: 'One-way mechanical gates, irreversible animation timelines, heavy locking physics.', renderMode: 'canvas', defaultScale: 'focus', surfaces: ['draggable'], hapticEvents: ['drag_snap', 'seal_stamp'], hapticSignature: 'Reversible lever snapping into irreversible lockdown — massive metallic CLANG', stateRange: [0, 1], continuous: false, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Commitment Device'], status: 'complete' },
  { id: 'friction-injection', number: 114, series: 'friction-mechanics', seriesPosition: 4, name: 'The Friction Injection Engine', intent: 'Put rocks on the track. Introduce friction to behaviors you want to destroy.', physics: 'Collision generation, obstacle spawning, kinetic dampening.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['tappable'], hapticEvents: ['tap', 'step_advance', 'completion'], hapticSignature: 'Each tap spawns a heavy jagged rock — neon flow crashing and halting', stateRange: [0, 1], continuous: false, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Loop Breaking'], status: 'complete' },
  { id: 'flywheel', number: 115, series: 'friction-mechanics', seriesPosition: 5, name: 'The Flywheel Engine', intent: 'It takes 100 units of energy to start, but only 1 to keep going. Never let the top fall.', physics: 'Rotational momentum, angular velocity decay, gyroscopic stabilization.', renderMode: 'canvas', defaultScale: 'focus', surfaces: ['swipeable', 'observable'], hapticEvents: ['swipe_commit', 'completion'], hapticSignature: 'Wobbling erratic vibration correcting into perfect silent infinite blur', stateRange: [0, 1], continuous: true, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Momentum Save'], status: 'complete' },
  { id: 'good-enough', number: 116, series: 'friction-mechanics', seriesPosition: 6, name: 'The Good Enough Engine', intent: 'Perfectionism is procrastination in a tuxedo. 80% is done. Ship it.', physics: 'Progress bar snapping, elastic rejection, explosive release.', renderMode: 'canvas', defaultScale: 'focus', surfaces: ['draggable', 'tappable'], hapticEvents: ['drag_snap', 'error_boundary', 'completion'], hapticSignature: 'Rubber band violently rejecting past 80% — explosive rocket release on Ship', stateRange: [0, 1], continuous: true, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Perfectionism Defeat'], status: 'complete' },
  { id: 'burn-rate', number: 117, series: 'friction-mechanics', seriesPosition: 7, name: 'The Burn Rate Engine', intent: 'Drop to cruising speed. Dropping exertion from 100% to 70% increases total distance.', physics: 'Throttle deceleration, heat dissipation, aerodynamic gliding.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['draggable', 'scrubable'], hapticEvents: ['drag_snap', 'step_advance', 'completion'], hapticSignature: 'Violent red shaking ceasing into quiet cool blue hum — fuel bar stabilizing', stateRange: [0, 1], continuous: true, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Cruising Altitude'], status: 'complete' },
  { id: 'vector-pivot', number: 118, series: 'friction-mechanics', seriesPosition: 8, name: 'The Vector Pivot Engine', intent: 'When you hit a wall, you don\'t stop — you bounce. Change the angle.', physics: 'Elastic collision, angular deflection, mirror raytracing.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['draggable'], hapticEvents: ['drag_snap', 'completion'], hapticSignature: 'Dead stop sparks transforming into flawless frictionless ricochet', stateRange: [0, 1], continuous: false, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Redirection Mirror'], status: 'complete' },
  { id: 'friction-polish', number: 119, series: 'friction-mechanics', seriesPosition: 9, name: 'The Friction Polish Engine', intent: 'Remove the friction. Make the good habit slippery easy to slide into.', physics: 'Surface smoothing, bump-map reduction, zero-friction physics materials.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['draggable', 'drawable'], hapticEvents: ['drag_snap', 'step_advance', 'completion'], hapticSignature: 'Rocky gritty surface sanding into perfectly smooth iridescent ice glide', stateRange: [0, 1], continuous: true, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Greasing the Groove'], status: 'complete' },
  { id: 'kinetic-seal', number: 120, series: 'friction-mechanics', seriesPosition: 10, name: 'The Kinetic Seal', intent: 'You are a body in motion. Stay in motion. The capstone of Friction Mechanics.', physics: 'Perpetual motion, pendulum physics, continuous frictionless orbiting.', renderMode: 'canvas', defaultScale: 'focus', surfaces: ['tappable', 'observable'], hapticEvents: ['tap', 'seal_stamp'], hapticSignature: 'Single sweeping tap locking into eternal frictionless motion — gentle rhythmic heartbeat', stateRange: [0, 1], continuous: true, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Body in Motion'], status: 'complete' },
];

// SERIES 13: THE SEMANTIC TRANSLATORS (Atoms 121–130)
export const S13: AtomMeta[] = [
  { id: 'subtext-scanner', number: 121, series: 'semantic-translators', seriesPosition: 1, name: 'The Subtext Scanner Engine', intent: 'An angry message is rarely about anger — it is usually about fear or pain.', physics: 'Thermal imaging shaders, layer masking, infrared glow interpolation.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['draggable'], hapticEvents: ['drag_snap', 'step_advance', 'completion'], hapticSignature: 'Sharp cold clicks melting into warm radiating heartbeat as subtext is revealed', stateRange: [0, 1], continuous: true, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Thermal Reading'], status: 'complete' },
  { id: 'translator-peel', number: 122, series: 'semantic-translators', seriesPosition: 2, name: 'The Translator Engine', intent: 'Emotions are layered. Peel through anger to find fear, and fear to find the unmet need.', physics: 'Z-depth page peeling, corner-curl physics, opacity stripping.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['draggable', 'swipeable'], hapticEvents: ['swipe_commit', 'step_advance', 'completion'], hapticSignature: 'Thick paper tension and curl — each peel revealing a softer truer layer', stateRange: [0, 1], continuous: false, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Layer Peeling'], status: 'complete' },
  { id: 'yet-append', number: 123, series: 'semantic-translators', seriesPosition: 3, name: 'The Yet Append Engine', intent: 'The sentence is not finished. Never end on a defeat.', physics: 'Magnetic text docking, typographical expansion, illumination pulsing.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['draggable'], hapticEvents: ['drag_snap', 'completion'], hapticSignature: 'Golden word magnetically snapping — period becoming comma — triumphant rising chord', stateRange: [0, 1], continuous: false, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Syntactic Hope'], status: 'complete' },
  { id: 'conjunction-shift', number: 124, series: 'semantic-translators', seriesPosition: 4, name: 'The Conjunction Shift Engine', intent: 'But erases. And adds. Two opposing truths can exist in the same space.', physics: 'Crossfade text morphing, node linking, structural binding.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['tappable'], hapticEvents: ['tap', 'completion'], hapticSignature: 'Harsh red BUT spinning into calm blue AND — repulsion becoming attraction', stateRange: [0, 1], continuous: false, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['But to And'], status: 'complete' },
  { id: 'headline-rewrite', number: 125, series: 'semantic-translators', seriesPosition: 5, name: 'The Headline Rewrite Engine', intent: 'The amygdala writes clickbait. The prefrontal cortex writes the news.', physics: 'Typography weight interpolation, font-family transitioning, spatial compression.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['draggable', 'scrubable'], hapticEvents: ['drag_snap', 'step_advance', 'completion'], hapticSignature: 'Screaming bold red thinning into calm measured grey — drama physically deflating', stateRange: [0, 1], continuous: true, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Clickbait Deflation'], status: 'complete' },
  { id: 'label-inception', number: 126, series: 'semantic-translators', seriesPosition: 6, name: 'The Label Inception Engine', intent: 'Call them Kind before they are kind. People act out the labels they are given.', physics: 'Sticker adhesion, physics-based badging, aura propagation.', renderMode: 'canvas', defaultScale: 'field', surfaces: ['draggable'], hapticEvents: ['drag_snap', 'completion'], hapticSignature: 'Golden label absorbing into dark avatar — jagged geometry softening into warm glow', stateRange: [0, 1], continuous: false, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Identity Assignment'], status: 'complete' },
  { id: 'meaning-mine', number: 127, series: 'semantic-translators', seriesPosition: 7, name: 'The Meaning Mine Engine', intent: 'Suffering without meaning is despair. Give your pain a job.', physics: 'Voronoi fracturing, geode splitting, internal luminescence rendering.', renderMode: 'canvas', defaultScale: 'focus', surfaces: ['tappable'], hapticEvents: ['tap', 'step_advance', 'completion'], hapticSignature: 'Harsh dull thuds cracking dark rock — stunning brilliant crystal geode revealed', stateRange: [0, 1], continuous: false, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Extracting Gold'], status: 'complete' },
  { id: 'absurdity-filter', number: 128, series: 'semantic-translators', seriesPosition: 8, name: 'The Absurdity Filter Engine', intent: 'The problem is real, but the anxiety is a performance. Change the soundtrack.', physics: 'Kinetic typography bouncing, spatial distortion, playful auditory cues.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['draggable'], hapticEvents: ['drag_snap', 'completion'], hapticSignature: 'Heavy serif terror transforming into bubbly bouncing jelly — squeaking haptic pop', stateRange: [0, 1], continuous: false, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Comic Relief'], status: 'complete' },
  { id: 'silent-mirror', number: 129, series: 'semantic-translators', seriesPosition: 9, name: 'The Silent Mirror Engine', intent: 'Silence is a vacuum. They will rush to fill it with the truth.', physics: 'Inverse-pressure simulation, auditory dampening, radial absorption.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['holdable', 'observable'], hapticEvents: ['hold_start', 'hold_threshold', 'completion'], hapticSignature: 'Wild pulsing microphone calming into profound sustained stillness', stateRange: [0, 1], continuous: true, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['The Vacuum'], status: 'complete' },
  { id: 'interpreter-seal', number: 130, series: 'semantic-translators', seriesPosition: 10, name: 'The Interpreter Seal', intent: 'Judgment is a wall. Understanding is a door. The capstone seals the transition.', physics: 'Architectural transformation, 3D hinging mechanisms, volumetric light flooding.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['drawable'], hapticEvents: ['drag_snap', 'seal_stamp'], hapticSignature: 'Massive groaning stone slide — wall splitting into doors — resonant boom', stateRange: [0, 1], continuous: false, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['The Doorway'], status: 'complete' },
];

// SERIES 14: THE SOCIAL PHYSICS (Atoms 131–140)
export const S14: AtomMeta[] = [
  { id: 'reverse-orbit', number: 131, series: 'social-physics', seriesPosition: 1, name: 'The Reverse Orbit Engine', intent: 'When you chase, you create resistance. When you stand still, you create gravity.', physics: 'Inverse magnetic polarity, mass densification, orbital mechanics.', renderMode: 'canvas', defaultScale: 'field', surfaces: ['draggable', 'holdable'], hapticEvents: ['drag_snap', 'hold_start', 'completion'], hapticSignature: 'Frantic chasing repulsion settling into calm gravitational orbit', stateRange: [0, 1], continuous: true, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['The Magnet'], status: 'complete' },
  { id: 'forcefield', number: 132, series: 'social-physics', seriesPosition: 2, name: 'The Forcefield Engine', intent: 'A boundary is not a wall. It is a forcefield that absorbs and bounces back.', physics: 'Elastic collision, radial repulsion fields, wave ripple generation.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['holdable', 'tappable'], hapticEvents: ['hold_start', 'tap', 'completion'], hapticSignature: 'Soft satisfying muffled thuds on a tight trampoline — particles bouncing harmlessly', stateRange: [0, 1], continuous: true, hasResolution: false, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Elastic Boundaries'], status: 'complete' },
  { id: 'status-seesaw', number: 133, series: 'social-physics', seriesPosition: 3, name: 'The Status See-Saw Engine', intent: 'They are shouting to lower your status. Do not shrink. Level the plank.', physics: 'Fulcrum dynamics, weight distribution, gyroscopic auto-leveling.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['holdable'], hapticEvents: ['hold_start', 'hold_threshold', 'completion'], hapticSignature: 'Violent imbalance steadying under perfect sustained gravity — locking groove', stateRange: [0, 1], continuous: true, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Leveling the Plank'], status: 'complete' },
  { id: 'empathy-bridge', number: 134, series: 'social-physics', seriesPosition: 4, name: 'The Empathy Bridge Engine', intent: 'You cannot shout across the canyon. Build the bridge first.', physics: 'Cantilever construction, node tethering, tensile strength rendering.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['draggable', 'tappable'], hapticEvents: ['drag_snap', 'step_advance', 'completion'], hapticSignature: 'Stones locking into bridge structure — truth packet gliding safely across', stateRange: [0, 1], continuous: false, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Connection Under Fire'], status: 'complete' },
  { id: 'aikido-redirect', number: 135, series: 'social-physics', seriesPosition: 5, name: 'The Aikido Redirect Engine', intent: 'If you push back, collision. If you pull, a dance. Redirect momentum.', physics: 'Bezier path curving, momentum conservation, frictionless routing.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['draggable', 'tappable'], hapticEvents: ['tap', 'drag_snap', 'completion'], hapticSignature: 'Head-on clash vibration transforming into smooth frictionless whoosh', stateRange: [0, 1], continuous: false, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Momentum Mastery'], status: 'complete' },
  { id: 'social-battery', number: 136, series: 'social-physics', seriesPosition: 6, name: 'The Social Battery Engine', intent: 'You are not anti-social. You are solar-powered. Go home before 0%.', physics: 'Fluid drainage, luminescence decay, tether severing.', renderMode: 'canvas', defaultScale: 'field', surfaces: ['swipeable', 'observable'], hapticEvents: ['swipe_commit', 'step_advance', 'completion'], hapticSignature: 'Golden liquid draining stopping — warm light slowly refilling', stateRange: [0, 1], continuous: false, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Energy Economy'], status: 'complete' },
  { id: 'gossip-firewall', number: 137, series: 'social-physics', seriesPosition: 7, name: 'The Gossip Firewall Engine', intent: 'Be the dead end. Stop the spread of toxic social data.', physics: 'Thermal quenching, particle containment, firewall instantiation.', renderMode: 'canvas', defaultScale: 'field', surfaces: ['holdable'], hapticEvents: ['hold_start', 'hold_threshold', 'completion'], hapticSignature: 'Toxic green line absorbed into black sinkhole — virus extinguished', stateRange: [0, 1], continuous: false, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['The Dead End'], status: 'complete' },
  { id: 'lighthouse', number: 138, series: 'social-physics', seriesPosition: 8, name: 'The Lighthouse Engine', intent: 'The lighthouse does not run around looking for boats. Emit a stronger authentic signal.', physics: 'Volumetric light casting, radial sweeping, fog penetration.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['holdable', 'tappable'], hapticEvents: ['hold_start', 'step_advance', 'completion'], hapticSignature: 'Beacon igniting — distant nodes drifting toward light', stateRange: [0, 1], continuous: true, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Attracting the Tribe'], status: 'complete' },
  { id: 'roche-limit', number: 139, series: 'social-physics', seriesPosition: 9, name: 'The Roche Limit Engine', intent: 'Back up. You are crushing them. Getting too close tears the other person apart.', physics: 'Gravitational tearing, particle strain, proximity-based structural failure.', renderMode: 'canvas', defaultScale: 'field', surfaces: ['draggable'], hapticEvents: ['drag_snap', 'error_boundary', 'completion'], hapticSignature: 'Terrifying structural grinding when too close — healing silence at safe distance', stateRange: [0, 1], continuous: true, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Proximity & Crushing'], status: 'complete' },
  { id: 'diplomat-seal', number: 140, series: 'social-physics', seriesPosition: 10, name: 'The Diplomat Seal', intent: 'Peace is not the absence of conflict. It is the mastery of it.', physics: 'Yin-Yang fluid dynamics, perpetual motion, resonant locking.', renderMode: 'canvas', defaultScale: 'focus', surfaces: ['drawable'], hapticEvents: ['drag_snap', 'seal_stamp'], hapticSignature: 'Warring fluids morphing into balanced rotating Yin-Yang — dual-frequency hum', stateRange: [0, 1], continuous: true, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Dynamic Equilibrium'], status: 'complete' },
];

// SERIES 15: THE TIME CAPSULE & FUTURE WEAVING (Atoms 141–150)
export const S15: AtomMeta[] = [
  { id: 'open-when', number: 141, series: 'time-capsule', seriesPosition: 1, name: 'The Open When Engine', intent: 'Store this strength. You will need it later.', physics: 'Viscous fluid injection, pneumatic sealing, luminous battery charging.', renderMode: 'canvas', defaultScale: 'focus', surfaces: ['draggable', 'typeable'], hapticEvents: ['drag_snap', 'seal_stamp'], hapticSignature: 'Glowing liquid filling vial — tight cork squeak ending in pressurized pop', stateRange: [0, 1], continuous: false, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Strength Storage'], status: 'complete' },
  { id: 'rage-vault', number: 142, series: 'time-capsule', seriesPosition: 2, name: 'The Rage Vault Engine', intent: 'Do not send the angry text. Send it here.', physics: 'Heavy metal doors, dark UI absorption, localized high-frequency haptics.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['swipeable', 'typeable'], hapticEvents: ['swipe_commit', 'seal_stamp'], hapticSignature: 'Violent upward swipe — massive iron doors slamming — terrifying metallic CLANG', stateRange: [0, 1], continuous: false, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Destruction Containment'], status: 'complete' },
  { id: 'prediction-stake', number: 143, series: 'time-capsule', seriesPosition: 3, name: 'The Prediction Stake Engine', intent: 'Lock in your prediction. Audit the catastrophe later.', physics: 'Ground-penetrating stakes, heavy mechanical ratchets, depth locking.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['draggable', 'typeable'], hapticEvents: ['drag_snap', 'step_advance', 'seal_stamp'], hapticSignature: 'Deep grinding metallic clicks as stake drives into ground', stateRange: [0, 1], continuous: false, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Catastrophe Audit'], status: 'complete' },
  { id: 'dead-mans-switch', number: 144, series: 'time-capsule', seriesPosition: 4, name: 'The Dead Man\'s Switch Engine', intent: 'The clock is ticking. Accountability through tension and timers.', physics: 'Spring-loaded timers, tension cords, kinetic unwinding.', renderMode: 'canvas', defaultScale: 'focus', surfaces: ['draggable', 'holdable'], hapticEvents: ['drag_snap', 'hold_start', 'seal_stamp'], hapticSignature: 'Tight wound-up mechanical clicks — slow unstoppable heavy ticking', stateRange: [0, 1], continuous: true, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Accountability Timer'], status: 'complete' },
  { id: 'regret-minimization', number: 145, series: 'time-capsule', seriesPosition: 5, name: 'The Regret Minimization Engine', intent: 'Experience the long-term regret of both choices. Force out of analysis paralysis.', physics: 'Y-axis divergence, timeline splitting, visual aging algorithms.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['draggable'], hapticEvents: ['drag_snap', 'step_advance', 'completion'], hapticSignature: 'Fork splitting with heavy divergence — compounded weight of time', stateRange: [0, 1], continuous: true, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['The Fork'], status: 'complete' },
  { id: 'pre-hindsight', number: 146, series: 'time-capsule', seriesPosition: 6, name: 'The Pre-Hindsight Engine', intent: 'Reverse engineer the victory. A completed goal looking backward is just logistics.', physics: 'Z-axis reverse stacking, domino unwinding, path generation.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['draggable'], hapticEvents: ['drag_snap', 'step_advance', 'completion'], hapticSignature: 'Stepping stones mathematically populating backward — staircase from the top', stateRange: [0, 1], continuous: true, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Reverse Engineering'], status: 'complete' },
  { id: 'branch-pruner', number: 147, series: 'time-capsule', seriesPosition: 7, name: 'The Branch Pruner Engine', intent: 'Prune possibilities to feed the probability. Cut good to feed the great.', physics: 'Procedural branch severing, energy routing, luminescent decay.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['swipeable', 'tappable'], hapticEvents: ['swipe_commit', 'step_advance', 'completion'], hapticSignature: 'Cut branches falling — light flowing into remaining choice blazing bright', stateRange: [0, 1], continuous: false, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Probability Focus'], status: 'complete' },
  { id: 'worst-case-simulator', number: 148, series: 'time-capsule', seriesPosition: 8, name: 'The Worst-Case Simulator Engine', intent: 'Fear lives in the vague. Reality is concrete.', physics: 'Fog dissipation, wireframe rendering, harsh schematic lighting.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['draggable'], hapticEvents: ['drag_snap', 'step_advance', 'completion'], hapticSignature: 'Swirling black fog stripped into sterile clinical blue wireframe', stateRange: [0, 1], continuous: true, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Concrete Fear'], status: 'complete' },
  { id: 'ten-year-echo', number: 149, series: 'time-capsule', seriesPosition: 9, name: 'The 10-Year Echo Engine', intent: 'Preserve the voice. Create a literal time capsule for future delivery.', physics: 'Audio waveform embedding, deep Z-axis storage, cryogenic freezing.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['holdable', 'voice'], hapticEvents: ['hold_start', 'seal_stamp'], hapticSignature: 'Waveform crystallizing into diamond — dropping deep into infinite starfield', stateRange: [0, 1], continuous: false, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics', 'microphone'], implementations: ['The Ghost Voice'], status: 'complete' },
  { id: 'capsule-seal', number: 150, series: 'time-capsule', seriesPosition: 10, name: 'The Capsule Seal', intent: 'Time is a circle. You have planted a seed in your own timeline.', physics: 'Orbital insertion, clockwork locking, cosmic rendering.', renderMode: 'canvas', defaultScale: 'focus', surfaces: ['draggable'], hapticEvents: ['drag_snap', 'seal_stamp'], hapticSignature: 'Temporal rings aligning — deep grandfather clock strike', stateRange: [0, 1], continuous: false, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Temporal Planting'], status: 'complete' },
];

// SERIES 16: THE SOMA & PERCEPTION (Atoms 151–160)
export const S16: AtomMeta[] = [
  { id: 'skin-map', number: 151, series: 'soma-perception', seriesPosition: 1, name: 'The Skin Map Engine', intent: 'Draw where you hold it. Locate exactly where the trauma lives in the body.', physics: '3D mesh raycasting, UV texture painting, volumetric glow.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['drawable', 'draggable'], hapticEvents: ['drag_snap', 'step_advance'], hapticSignature: 'Tender sharp sensation warming into dull soothing pulse', stateRange: [0, 1], continuous: true, hasResolution: false, breathCoupling: 'modulates', deviceRequirements: ['haptics'], implementations: ['Somatic Localization'], status: 'complete' },
  { id: 'pulse-reader', number: 152, series: 'soma-perception', seriesPosition: 2, name: 'The Pulse Reader Engine', intent: 'Tap in rhythm with your heartbeat. Grounding through cardiac awareness.', physics: 'Metronomic time-stamping, predictive rhythm matching, concentric wave generation.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['tappable', 'observable'], hapticEvents: ['tap', 'breath_peak'], hapticSignature: 'Expanding light rings synchronized with heartbeat — haptic beating in sync', stateRange: [0, 1], continuous: true, hasResolution: false, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Cardiac Sync'], status: 'complete' },
  { id: 'fascia-wave', number: 153, series: 'soma-perception', seriesPosition: 3, name: 'The Fascia Wave Engine', intent: 'The slow wave moves through you. Let it. Release deep myofascial tension.', physics: 'Tensile spring physics, snapback easing, vibrational decay.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['draggable', 'holdable'], hapticEvents: ['hold_start', 'drag_snap', 'completion'], hapticSignature: 'Massive resistance — snap release — rolling slow-motion wave and rumble', stateRange: [0, 1], continuous: false, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Tension Discharge'], status: 'complete' },
  { id: 'proprioception', number: 154, series: 'soma-perception', seriesPosition: 4, name: 'The Proprioception Engine', intent: 'Find your center. It is not where you think.', physics: 'Gyroscope mapping, fluid leveling, dead-zone targeting.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['gyroscopic', 'observable'], hapticEvents: ['step_advance', 'completion'], hapticSignature: 'Directional buzzing guiding toward center — silence at equilibrium', stateRange: [0, 1], continuous: true, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics', 'gyroscope'], implementations: ['Spatial Grounding'], status: 'complete' },
  { id: 'micro-texture', number: 155, series: 'soma-perception', seriesPosition: 5, name: 'The Micro-Texture Engine', intent: 'The brain cannot panic about the future if consumed by sensory data of the present.', physics: 'SVG macro-scaling, bump-map haptic translation, parallax depth.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['draggable'], hapticEvents: ['drag_snap'], hapticSignature: 'Microscopic gritty clicks on stone — smooth glide on velvet', stateRange: [0, 1], continuous: true, hasResolution: false, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Sensory Anchoring'], status: 'complete' },
  { id: 'voice-box', number: 156, series: 'soma-perception', seriesPosition: 6, name: 'The Voice Box Engine', intent: 'Your throat wants to say something. Let it. Safe container for primal vocal release.', physics: 'Real-time audio FFT analysis, particle explosive force, waveform distortion.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['voice', 'observable'], hapticEvents: ['step_advance', 'completion'], hapticSignature: 'Tight knot violently shattered by vocal force — particles blown to edges', stateRange: [0, 1], continuous: true, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics', 'microphone'], implementations: ['Acoustic Discharge'], status: 'complete' },
  { id: 'blind-walk', number: 157, series: 'soma-perception', seriesPosition: 7, name: 'The Blind Walk Engine', intent: 'Restore trust in the physical body. The body already knows how to walk.', physics: 'Accelerometer step-detection, pitch-black rendering, sequential unlocking.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['gyroscopic', 'observable'], hapticEvents: ['step_advance', 'completion'], hapticSignature: 'Deep drumbeats for each step — golden light flood: the floor was always there', stateRange: [0, 3], continuous: false, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics', 'gyroscope'], implementations: ['Trusting the Dark'], status: 'complete' },
  { id: 'temperature-scan', number: 158, series: 'soma-perception', seriesPosition: 8, name: 'The Temperature Scan Engine', intent: 'Emotions are tied to body temperature. Consciously manipulate thermal perception.', physics: 'Thermal-camera color mapping, radial gradient shifts, localized cooling.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['draggable', 'tappable'], hapticEvents: ['tap', 'drag_snap', 'completion'], hapticSignature: 'Chaotic hot crackle resolving into slow cool glassy stillness', stateRange: [0, 1], continuous: true, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Thermal Regulation'], status: 'complete' },
  { id: 'gut-signal', number: 159, series: 'soma-perception', seriesPosition: 9, name: 'The Gut Signal Engine', intent: 'Your stomach knew before your brain did. Trust somatic reaction.', physics: 'Split-screen rendering, countdown timers, shatter mechanics.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['tappable'], hapticEvents: ['tap', 'completion'], hapticSignature: 'Frantic countdown — instant gut-tap — unchosen side shattering', stateRange: [0, 1], continuous: false, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Enteric Intuition'], status: 'complete' },
  { id: 'soma-seal', number: 160, series: 'soma-perception', seriesPosition: 10, name: 'The Soma Seal', intent: 'The body is an intelligent vessel. The capstone of Series 16.', physics: 'Fingerprint biometric scanning, organic shape expansion, synchronous pulse.', renderMode: 'canvas', defaultScale: 'focus', surfaces: ['holdable'], hapticEvents: ['hold_start', 'breath_peak', 'seal_stamp'], hapticSignature: 'Fingerprint generating outward — deep 60 BPM rhythm anchoring', stateRange: [0, 1], continuous: true, hasResolution: true, breathCoupling: 'drives', deviceRequirements: ['haptics'], implementations: ['The Body Knowing'], status: 'complete' },
];

// SERIES 17: THE DIPLOMAT & SOCIAL PHYSICS II (Atoms 161–170)
export const S17: AtomMeta[] = [
  { id: 'mirror-shield', number: 161, series: 'diplomat-empathy', seriesPosition: 1, name: 'The Mirror Shield Engine', intent: 'Tap each aggressive phrase to deflect without absorbing.', physics: 'Rigid-body collisions, trajectory reflection, kinetic rebounding.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['tappable'], hapticEvents: ['tap', 'step_advance', 'completion'], hapticSignature: 'Crisp metallic ping as each harsh word bounces off the shield', stateRange: [0, 1], continuous: false, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Kinetic Deflection'], status: 'complete' },
  { id: 'truce-table', number: 162, series: 'diplomat-empathy', seriesPosition: 2, name: 'The Truce Table Engine', intent: 'Place items of good faith one by one. De-escalation through reciprocal offerings.', physics: 'Gravitational anchoring, sequential unlocking, center-of-mass balancing.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['draggable'], hapticEvents: ['drag_snap', 'step_advance', 'completion'], hapticSignature: 'Heavy reassuring resonant thud as each offering locks into table', stateRange: [0, 1], continuous: false, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Vulnerability Sequencing'], status: 'complete' },
  { id: 'perspective-swap', number: 163, series: 'diplomat-empathy', seriesPosition: 3, name: 'The Perspective Swap Engine', intent: 'Two windows side by side. Force adoption of the opponent\'s coordinates.', physics: '3D camera rotation, viewport swapping, color-palette inversion.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['draggable'], hapticEvents: ['drag_snap', 'completion'], hapticSignature: 'Camera rotating 180 degrees — color shifting as perspective transforms', stateRange: [0, 1], continuous: false, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['The Other Window'], status: 'complete' },
  { id: 'translation-ear', number: 164, series: 'diplomat-empathy', seriesPosition: 4, name: 'The Translation Ear Engine', intent: 'Peel through three layers to the core human need beneath aggression.', physics: 'Opacity crossfading, Z-depth scraping, typographical softening.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['draggable'], hapticEvents: ['drag_snap', 'step_advance', 'completion'], hapticSignature: 'Sharp buzzes softening into flowing pulse as layers peel', stateRange: [0, 1], continuous: false, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Subtext Decryption'], status: 'complete' },
  { id: 'boundary-dance', number: 165, series: 'diplomat-empathy', seriesPosition: 5, name: 'The Boundary Dance Engine', intent: 'Two circles — you and them. Boundaries are dynamic negotiation of space.', physics: 'Magnetic repulsion, invisible tethering, spring-tension limits.', renderMode: 'canvas', defaultScale: 'field', surfaces: ['draggable'], hapticEvents: ['drag_snap', 'error_boundary', 'completion'], hapticSignature: 'Uncomfortable vibration too close — harmonious line at perfect distance', stateRange: [0, 1], continuous: true, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Dynamic Orbit'], status: 'complete' },
  { id: 'third-chair', number: 166, series: 'diplomat-empathy', seriesPosition: 6, name: 'The Third Chair Engine', intent: 'Stop fighting. Watch the fight. You are the audience.', physics: 'Z-axis elevation, isometric panning, depth-of-field blurring.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['pinchable', 'draggable'], hapticEvents: ['drag_snap', 'completion'], hapticSignature: 'Camera flying up — chaotic fight shrinking to tiny dots below', stateRange: [0, 1], continuous: false, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['The Observer'], status: 'complete' },
  { id: 'steel-man-build', number: 167, series: 'diplomat-empathy', seriesPosition: 7, name: 'The Steel Man Build Engine', intent: 'Strengthen their point before presenting yours.', physics: 'Structural reinforcement, node linking, architectural scaling.', renderMode: 'canvas', defaultScale: 'field', surfaces: ['draggable', 'tappable'], hapticEvents: ['drag_snap', 'step_advance', 'completion'], hapticSignature: 'Flimsy wireframe strengthening — glowing fully realized structure', stateRange: [0, 1], continuous: false, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Strengthening Opponent'], status: 'complete' },
  { id: 'de-escalation', number: 168, series: 'diplomat-empathy', seriesPosition: 8, name: 'The De-Escalation Engine', intent: 'Heat gauge at maximum. Anger is thermal. Lower the heat.', physics: 'Thermodynamic particles, color-temperature shifting, evaporation.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['draggable', 'holdable'], hapticEvents: ['hold_start', 'step_advance', 'completion'], hapticSignature: 'Erratic popping slowing into steady heartbeat — red cooling to icy blue', stateRange: [0, 1], continuous: true, hasResolution: true, breathCoupling: 'modulates', deviceRequirements: ['haptics'], implementations: ['Cooling the System'], status: 'complete' },
  { id: 'mirror-neuron', number: 169, series: 'diplomat-empathy', seriesPosition: 9, name: 'The Mirror Neuron Engine', intent: 'To understand them, you must become them. Mimic the expression.', physics: 'Dynamic meshing, biometric mirroring, symmetry detection.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['observable'], hapticEvents: ['step_advance', 'completion'], hapticSignature: 'Mask dissolving into warm connecting light — comforting hum', stateRange: [0, 1], continuous: true, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics', 'camera'], implementations: ['Facial Sync'], status: 'complete' },
  { id: 'common-ground-seal', number: 170, series: 'diplomat-empathy', seriesPosition: 10, name: 'The Common Ground Seal', intent: 'Beneath all surface conflict, there is a shared foundation.', physics: 'Geological excavation, layer deletion, bedrock illumination.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['tappable'], hapticEvents: ['tap', 'step_advance', 'seal_stamp'], hapticSignature: 'Layers shattering — unshakeable anchoring thud of shared bedrock', stateRange: [0, 1], continuous: false, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['The Common Ground'], status: 'complete' },
];

// SERIES 18: THE VISIONARY & STRATEGIST (Atoms 171–180)
export const S18: AtomMeta[] = [
  { id: 'essentialism', number: 171, series: 'visionary-strategist', seriesPosition: 1, name: 'The Essentialism Engine', intent: 'If everything is a priority, nothing is. Destroy good ideas to protect the great one.', physics: 'Rigid-body drag-and-drop, particle confetti, collision-triggered destruction.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['draggable'], hapticEvents: ['drag_snap', 'step_advance', 'completion'], hapticSignature: 'Aggressive grinding shredder crunch — remaining card expanding with clarity', stateRange: [0, 1], continuous: false, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['The Shredder'], status: 'complete' },
  { id: 'compound-interest', number: 172, series: 'visionary-strategist', seriesPosition: 2, name: 'The Compound Interest Engine', intent: 'Prove that micro-actions compound violently over time.', physics: 'Exponential Bezier curve rendering, node accumulation, velocity acceleration.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['tappable'], hapticEvents: ['tap', 'step_advance', 'completion'], hapticSignature: 'Frustrating flat taps then violent exponential arc rocketing upward', stateRange: [0, 1], continuous: false, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['The Curve'], status: 'complete' },
  { id: 'deep-work', number: 173, series: 'visionary-strategist', seriesPosition: 3, name: 'The Deep Work Engine', intent: 'A heavy vault door. Physical ritual for entering unbreakable focus.', physics: 'Heavy rigid body translation, momentum-based drag, light-occlusion.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['draggable'], hapticEvents: ['drag_snap', 'seal_stamp'], hapticSignature: 'Heavy drag choking off light — echoing resonant metallic BOOM at seal', stateRange: [0, 1], continuous: false, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['The Vault Door'], status: 'complete' },
  { id: 'leverage-engine', number: 174, series: 'visionary-strategist', seriesPosition: 4, name: 'The Leverage Engine', intent: 'You don\'t need more strength. You need a better angle.', physics: 'Seesaw mechanics, adjustable fulcrums, dynamic weight disparity.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['draggable', 'tappable'], hapticEvents: ['drag_snap', 'error_boundary', 'completion'], hapticSignature: 'Harsh failure rumble at brute force — effortless launch at proper fulcrum', stateRange: [0, 1], continuous: false, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['The Fulcrum'], status: 'complete' },
  { id: 'horizon-scan', number: 175, series: 'visionary-strategist', seriesPosition: 5, name: 'The Horizon Scan Engine', intent: 'A blank horizon line. Tap to place imagined landmarks.', physics: 'Infinite horizontal panning, Z-depth placement, parallax perspective.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['tappable', 'drawable'], hapticEvents: ['tap', 'step_advance'], hapticSignature: 'Each landmark locking with deep echoing thud — shaping the void', stateRange: [0, 1], continuous: true, hasResolution: false, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['The Blueprint'], status: 'complete' },
  { id: 'obstacle-flip', number: 176, series: 'visionary-strategist', seriesPosition: 6, name: 'The Obstacle Flip Engine', intent: 'The ego sees a wall; the Strategist sees a step.', physics: '3D rotational physics, bounding box restructuring, kinetic energy transfer.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['swipeable'], hapticEvents: ['swipe_commit', 'step_advance', 'completion'], hapticSignature: 'Immovable brick cascading into ascending welcoming staircase', stateRange: [0, 1], continuous: false, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['The Staircase'], status: 'complete' },
  { id: 'courage-map', number: 177, series: 'visionary-strategist', seriesPosition: 7, name: 'The Courage Map Engine', intent: 'Bravery is taking the step while terrified. Pre-meditate your bravery.', physics: 'Pathfinding algorithms, waypoint anchoring, luminescent pulsing.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['draggable', 'tappable'], hapticEvents: ['drag_snap', 'tap', 'completion'], hapticSignature: 'Beacon flaring — warm permanent light over dark patches', stateRange: [0, 1], continuous: true, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Lighting the Dark'], status: 'complete' },
  { id: 'abundance-scan', number: 178, series: 'visionary-strategist', seriesPosition: 8, name: 'The Abundance Scan Engine', intent: 'Scarcity is an optical illusion. Catalog the resources you already possess.', physics: 'Spotlight masking, ambient occlusion, radial illumination.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['draggable'], hapticEvents: ['drag_snap', 'step_advance', 'completion'], hapticSignature: 'Hidden nodes waking as spotlight passes — dark room becoming treasure vault', stateRange: [0, 1], continuous: true, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['The Asset Audit'], status: 'complete' },
  { id: 'permissionless', number: 179, series: 'visionary-strategist', seriesPosition: 9, name: 'The Permissionless Engine', intent: 'The ego waits to be picked. The Sovereign Mind picks itself.', physics: 'State machine toggling, emissive material lighting, mechanical click physics.', renderMode: 'canvas', defaultScale: 'focus', surfaces: ['holdable'], hapticEvents: ['hold_start', 'hold_threshold', 'completion'], hapticSignature: 'Dead glass cracking — blinding green light erupting — engine roar', stateRange: [0, 1], continuous: false, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['The Green Light'], status: 'complete' },
  { id: 'becoming-seal', number: 180, series: 'visionary-strategist', seriesPosition: 10, name: 'The Becoming Seal', intent: 'Three silhouettes — past, present, future. Integrate timeline.', physics: 'Opacity blending, shape morphing, convergent magnetic alignment.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['draggable'], hapticEvents: ['drag_snap', 'seal_stamp'], hapticSignature: 'Three silhouettes phase-locking — blinding unified white light flash', stateRange: [0, 1], continuous: false, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Temporal Convergence'], status: 'complete' },
];

// SERIES 19: THE MYSTIC & INFINITE PLAYER (Atoms 181–190)
export const S19: AtomMeta[] = [
  { id: 'maya-veil', number: 181, series: 'mystic-infinite', seriesPosition: 1, name: 'The Maya Veil Engine', intent: 'Rigid thoughts are projections on a screen. Interface elements ripple like water.', physics: 'Refraction shaders, water-ripple displacement, UI distortion.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['tappable'], hapticEvents: ['tap', 'completion'], hapticSignature: 'Soft liquid splash as rigid interface ripples — mere reflection revealed', stateRange: [0, 1], continuous: false, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Illusion Piercing'], status: 'complete' },
  { id: 'no-self', number: 182, series: 'mystic-infinite', seriesPosition: 2, name: 'The No-Self Engine', intent: 'The ego is a construct. Gently dismantle the heavy identity.', physics: 'Particle evaporation, alpha-channel decay, gentle wind simulation.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['tappable'], hapticEvents: ['tap', 'step_advance', 'completion'], hapticSignature: 'Stone pieces turning to glowing dust — massive unburdened relief', stateRange: [0, 1], continuous: false, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Ego Dissolution'], status: 'complete' },
  { id: 'cosmic-joke', number: 183, series: 'mystic-infinite', seriesPosition: 3, name: 'The Cosmic Joke Engine', intent: 'Profoundly serious, but fundamentally not. Primate on a rock. Smile.', physics: 'Bezier curve manipulation, facial morphing, harmonic lighting shifts.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['draggable'], hapticEvents: ['drag_snap', 'completion'], hapticSignature: 'Rigid oppressive lines bending into smile — grey flipping to warm gold', stateRange: [0, 1], continuous: false, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['The Smile'], status: 'complete' },
  { id: 'space-between', number: 184, series: 'mystic-infinite', seriesPosition: 4, name: 'The Space Between Engine', intent: 'Thoughts are clouds; you are the sky. You are the observer, not the panic.', physics: 'Z-depth parallax, continuous horizontal scrolling, extreme focal blurring.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['tappable', 'observable'], hapticEvents: ['tap', 'completion'], hapticSignature: 'Frantic clouds blurring — deep blue background anchoring presence', stateRange: [0, 1], continuous: true, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['The Sky & Clouds'], status: 'complete' },
  { id: 'beginners-mind', number: 185, series: 'mystic-infinite', seriesPosition: 5, name: 'The Beginner\'s Mind Engine', intent: 'Expertise is a trap. Wipe the board clean. See fresh.', physics: 'Multi-touch erasure, particle masking, white-point blooming.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['swipeable', 'drawable'], hapticEvents: ['swipe_commit', 'completion'], hapticSignature: 'Labels destroyed — pristine glowing white canvas of total potential', stateRange: [0, 1], continuous: false, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Shoshin Reset'], status: 'complete' },
  { id: 'dance-of-shiva', number: 186, series: 'mystic-infinite', seriesPosition: 6, name: 'The Dance of Shiva Engine', intent: 'Creation and Destruction are the same energy. Nothing is lost, only transformed.', physics: 'Particle recycling, orbital fluid dynamics, continuous color cycling.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['draggable', 'observable'], hapticEvents: ['drag_snap', 'step_advance', 'completion'], hapticSignature: 'Structures crumbling — same particles building stunning new lotus', stateRange: [0, 1], continuous: true, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Creation & Destruction'], status: 'complete' },
  { id: 'unplanned-hour', number: 187, series: 'mystic-infinite', seriesPosition: 7, name: 'The Unplanned Hour Engine', intent: 'Time anxiety is a prison. Step outside linear time. Dismantle the clock.', physics: 'Rigidbody detachment, gravity drops, UI fading.', renderMode: 'canvas', defaultScale: 'focus', surfaces: ['draggable', 'tappable'], hapticEvents: ['drag_snap', 'step_advance', 'completion'], hapticSignature: 'Clock hands plucked and dropping — ticking stopping — soft breathing circle', stateRange: [0, 1], continuous: false, hasResolution: true, breathCoupling: 'modulates', deviceRequirements: ['haptics'], implementations: ['Clock Breaking'], status: 'complete' },
  { id: 'wonder-walk', number: 188, series: 'mystic-infinite', seriesPosition: 8, name: 'The Wonder Walk Engine', intent: 'Curiosity cures anxiety. Enjoy revealing the next step.', physics: 'Volumetric fog shaders, proximity-based revealing, hidden asset rendering.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['draggable'], hapticEvents: ['drag_snap', 'step_advance'], hapticSignature: 'Fog swirling and parting — unexpected micro-interactions emerging', stateRange: [0, 1], continuous: true, hasResolution: false, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['The Fog'], status: 'complete' },
  { id: 'light-source', number: 189, series: 'mystic-infinite', seriesPosition: 9, name: 'The Light Source Engine', intent: 'Turn around. Look at the light that makes the movie possible.', physics: '180-degree camera panning, volumetric raycasting, silhouette casting.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['draggable'], hapticEvents: ['drag_snap', 'completion'], hapticSignature: 'Camera rotating away from chaos — pure white light filling entire device', stateRange: [0, 1], continuous: false, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['The Watcher'], status: 'complete' },
  { id: 'mystic-seal', number: 190, series: 'mystic-infinite', seriesPosition: 10, name: 'The Mystic Seal', intent: 'I Am That. Boundless play, non-dual existence, total integration.', physics: 'Continuous loop tracing, luminescent particle trails, zero-friction easing.', renderMode: 'canvas', defaultScale: 'focus', surfaces: ['drawable'], hapticEvents: ['breath_peak'], hapticSignature: 'Continuous soothing harmonic glide — infinity traced forever', stateRange: [0, 1], continuous: true, hasResolution: false, breathCoupling: 'drives', deviceRequirements: ['haptics'], implementations: ['I Am That'], status: 'complete' },
];

// SERIES 20: THE OMEGA & INTEGRATION (Atoms 191–200)
export const S20: AtomMeta[] = [
  { id: 'prism-return', number: 191, series: 'omega-integration', seriesPosition: 1, name: 'The Prism Return Engine', intent: 'Pull all refracted colors back into a single blinding white truth.', physics: 'Reverse-raytracing, spectral fusion, additive color blending.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['draggable'], hapticEvents: ['drag_snap', 'completion'], hapticSignature: 'Beams gathering — additive blending into pure white — harmonic major chord', stateRange: [0, 1], continuous: false, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['White Light Synthesis'], status: 'complete' },
  { id: 'golden-spiral', number: 192, series: 'omega-integration', seriesPosition: 2, name: 'The Golden Spiral Engine', intent: 'Growth is a spiral. You are not circling. You are ascending.', physics: 'Fibonacci sequence rendering, 3D helical rotation, Z-axis elevation.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['pinchable', 'draggable'], hapticEvents: ['drag_snap', 'step_advance', 'completion'], hapticSignature: 'Flat circle revealing massive 3D spiral — camera flying along golden ratio', stateRange: [0, 1], continuous: true, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Ascension'], status: 'complete' },
  { id: 'time-collapse', number: 193, series: 'omega-integration', seriesPosition: 3, name: 'The Time Collapse Engine', intent: 'Collapse future anxiety and past regret into the only place where power exists: Now.', physics: 'Bi-directional collapsing timelines, mass density concentration, radial blooming.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['holdable'], hapticEvents: ['hold_start', 'seal_stamp'], hapticSignature: 'Timelines retracting — condensing into dense vibrating sphere — heavy heartbeat', stateRange: [0, 1], continuous: false, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['The Eternal Now'], status: 'complete' },
  { id: 'mirror-of-truth', number: 194, series: 'omega-integration', seriesPosition: 4, name: 'The Mirror of Truth Engine', intent: 'Look at the hero. Look at the villain. Total radical self-acceptance.', physics: 'Multi-mesh overlaying, opacity crossfading, final-state fusion.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['draggable'], hapticEvents: ['drag_snap', 'completion'], hapticSignature: 'Dark and bright masks blending into breathtakingly human glowing face', stateRange: [0, 1], continuous: false, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Complete Acceptance'], status: 'complete' },
  { id: 'event-horizon', number: 195, series: 'omega-integration', seriesPosition: 5, name: 'The Event Horizon Engine', intent: 'The next step is off the map. Trust your feet. Step.', physics: 'Gravitational singularity mechanics, extreme UI stretching, void transition.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['draggable'], hapticEvents: ['drag_snap', 'completion'], hapticSignature: 'Massive gravitational pull — beautiful spaghettification — perfect black then calm safety', stateRange: [0, 1], continuous: false, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['The Leap'], status: 'complete' },
  { id: 'alpha-omega', number: 196, series: 'omega-integration', seriesPosition: 6, name: 'The Alpha Omega Engine', intent: 'Every ending is simultaneously a beginning.', physics: 'Orbital locking, symbol morphing, kinetic energy conservation.', renderMode: 'canvas', defaultScale: 'focus', surfaces: ['draggable'], hapticEvents: ['drag_snap', 'completion'], hapticSignature: 'Chaotic rattling symbols morphing into smooth frictionless infinity glide', stateRange: [0, 1], continuous: true, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['Synthesis'], status: 'complete' },
  { id: 'circle-close', number: 197, series: 'omega-integration', seriesPosition: 7, name: 'The Circle Close Engine', intent: 'Tap 5 points to close the loop. Finish what you started.', physics: 'Bezier curve drawing, node connecting, threshold-triggered flashing.', renderMode: 'canvas', defaultScale: 'focus', surfaces: ['tappable'], hapticEvents: ['tap', 'step_advance', 'completion'], hapticSignature: 'Heavy click at each gap — blindingly bright flash and final chord at completion', stateRange: [0, 5], continuous: false, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['The Completion'], status: 'complete' },
  { id: 'final-exhale', number: 198, series: 'omega-integration', seriesPosition: 8, name: 'The Final Exhale Engine', intent: 'Hold everything. Now let it all go. Drop the app and live.', physics: 'Lung-capacity simulation, pressure-valve release, total particle evaporation.', renderMode: 'canvas', defaultScale: 'full', surfaces: ['holdable'], hapticEvents: ['hold_start', 'hold_threshold', 'completion'], hapticSignature: 'Fierce compressed buzzing — exhale — instant total evaporation into void', stateRange: [0, 1], continuous: false, hasResolution: true, breathCoupling: 'drives', deviceRequirements: ['haptics'], implementations: ['Absolute Surrender'], status: 'complete' },
  { id: 'tail-swallow', number: 199, series: 'omega-integration', seriesPosition: 9, name: 'The Tail Swallow Engine', intent: 'A serpent chasing its tail. The end is the beginning. The Ouroboros Loop.', physics: 'SVG path tracing, continuous loop interpolation, infinite scrolling.', renderMode: 'canvas', defaultScale: 'focus', surfaces: ['drawable'], hapticEvents: ['drag_snap', 'seal_stamp'], hapticSignature: 'Head catching tail — mesh fusing into perfect ring — continuous smooth vibration', stateRange: [0, 1], continuous: true, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['The Ouroboros Loop'], status: 'complete' },
  { id: 'atlas-seal', number: 200, series: 'omega-integration', seriesPosition: 10, name: 'The Atlas Seal', intent: 'You are the atlas. You always were. A single point of light. The absolute culmination.', physics: 'Total UI collapse, singularity focusing, absolute stillness.', renderMode: 'canvas', defaultScale: 'point', surfaces: ['tappable'], hapticEvents: ['tap', 'seal_stamp'], hapticSignature: 'Universe collapsing to single permanent pixel of soft pulsing light — silence', stateRange: [0, 1], continuous: false, hasResolution: true, breathCoupling: 'none', deviceRequirements: ['haptics'], implementations: ['The Singularity'], status: 'complete' },
];
