/** ATOM 366: FIBER OPTIC · S37 P6 — Draw curved fiber route. Light bounces perfectly along it with zero loss. */
import { useRef, useEffect } from 'react'; import type { AtomProps } from '../types'; import { parseColor, rgba, setupCanvas, advanceEntrance, drawAtmosphere, ALPHA, px, motionScale } from '../atom-utils';
export default function FiberOpticAtom({ breathAmplitude, reducedMotion, color, accentColor, viewport, phase, composed, onHaptic, onStateChange }: AtomProps) {
  const canvasRef = useRef<HTMLCanvasElement>(null); const cbRef = useRef({ onHaptic, onStateChange }); const propsRef = useRef({ breathAmplitude, reducedMotion, phase, color, accentColor, composed }); useEffect(() => { cbRef.current = { onHaptic, onStateChange }; }, [onHaptic, onStateChange]); useEffect(() => { propsRef.current = { breathAmplitude, reducedMotion, phase, color, accentColor, composed }; }, [breathAmplitude, reducedMotion, phase, color, accentColor, composed]);
  const st = useRef({ entranceProgress: 0, frameCount: 0, primaryRgb: parseColor(color), accentRgb: parseColor(accentColor), path: [] as {x:number;y:number}[], drawing: false, signalPos: 0, signalActive: false, completed: false, compAnim: 0 });
  useEffect(() => { st.current.primaryRgb = parseColor(color); st.current.accentRgb = parseColor(accentColor); }, [color, accentColor]);
  useEffect(() => { const canvas = canvasRef.current; if (!canvas) return; const ctx = canvas.getContext('2d'); if (!ctx) return; let animId: number;
    const render = () => { const s = st.current; const p = propsRef.current; const cb = cbRef.current; const { w, h, cx, cy, minDim } = setupCanvas(canvas, ctx, viewport.width, viewport.height); const ms = motionScale(p.reducedMotion); s.frameCount++; const { progress, entrance } = advanceEntrance(s.entranceProgress, p.phase); s.entranceProgress = progress; if (!p.composed) drawAtmosphere(ctx, cx, cy, w, h, minDim, s.primaryRgb, entrance);
      if (s.signalActive) { s.signalPos += 0.008 * ms; if (s.signalPos >= 1 && !s.completed) { s.completed = true; cb.onHaptic('completion'); } } if (s.completed) s.compAnim = Math.min(1, s.compAnim + 0.01 * ms);
      cb.onStateChange?.(s.completed ? 0.5 + s.compAnim * 0.5 : s.signalPos * 0.5);
      if (s.path.length > 1) { ctx.beginPath(); ctx.moveTo(s.path[0].x * w, s.path[0].y * h); for (let i = 1; i < s.path.length; i++) ctx.lineTo(s.path[i].x * w, s.path[i].y * h); ctx.strokeStyle = rgba(s.accentRgb, ALPHA.content.max * 0.15 * entrance); ctx.lineWidth = px(0.008, minDim); ctx.stroke(); ctx.strokeStyle = rgba(s.accentRgb, ALPHA.content.max * 0.06 * entrance); ctx.lineWidth = px(0.012, minDim); ctx.stroke(); }
      if (s.signalActive && s.path.length > 2) { const idx = Math.floor(s.signalPos * (s.path.length - 1)); const pt = s.path[Math.min(idx, s.path.length - 1)]; const gR = px(0.02, minDim); const gg = ctx.createRadialGradient(pt.x * w, pt.y * h, 0, pt.x * w, pt.y * h, gR); gg.addColorStop(0, rgba(s.primaryRgb, ALPHA.glow.max * 0.6 * entrance)); gg.addColorStop(1, rgba(s.primaryRgb, 0)); ctx.fillStyle = gg; ctx.fillRect(pt.x * w - gR, pt.y * h - gR, gR * 2, gR * 2);
        for (let i = 0; i <= idx; i++) { const pp = s.path[i]; ctx.beginPath(); ctx.arc(pp.x * w, pp.y * h, px(0.001, minDim), 0, Math.PI * 2); ctx.fillStyle = rgba(s.primaryRgb, ALPHA.content.max * 0.3 * entrance); ctx.fill(); } }
      if (s.completed) { const last = s.path[s.path.length - 1]; if (last) { const gR = minDim * 0.06 * s.compAnim; const gg = ctx.createRadialGradient(last.x * w, last.y * h, 0, last.x * w, last.y * h, gR); gg.addColorStop(0, rgba(s.primaryRgb, ALPHA.glow.max * 0.4 * s.compAnim * entrance)); gg.addColorStop(1, rgba(s.primaryRgb, 0)); ctx.fillStyle = gg; ctx.fillRect(last.x * w - gR, last.y * h - gR, gR * 2, gR * 2); } }
      ctx.restore(); animId = requestAnimationFrame(render); };
    animId = requestAnimationFrame(render);
    const onDown = () => { st.current.drawing = true; st.current.path = []; }; const onMove = (e: PointerEvent) => { if (!st.current.drawing) return; const rect = canvas.getBoundingClientRect(); st.current.path.push({ x: (e.clientX - rect.left) / rect.width, y: (e.clientY - rect.top) / rect.height }); };
    const onUp = () => { st.current.drawing = false; if (st.current.path.length > 5) { st.current.signalActive = true; cbRef.current.onHaptic('drag_snap'); } };
    canvas.addEventListener('pointerdown', onDown); canvas.addEventListener('pointermove', onMove); canvas.addEventListener('pointerup', onUp); canvas.addEventListener('pointercancel', onUp);
    return () => { cancelAnimationFrame(animId); canvas.removeEventListener('pointerdown', onDown); canvas.removeEventListener('pointermove', onMove); canvas.removeEventListener('pointerup', onUp); canvas.removeEventListener('pointercancel', onUp); };
  }, [viewport.width, viewport.height]);
  return (<div style={{ position: 'absolute', inset: 0, overflow: 'hidden' }}><canvas ref={canvasRef} style={{ display: 'block', width: '100%', height: '100%', touchAction: 'none', cursor: 'crosshair' }} /></div>);
}
