/**
 * COMPLETE CREATIVE BRIEF: 90 BESPOKE NAVICUES
 * 
 * Ready for one-by-one execution when you say "go"
 * Each has unique visual language, interaction, and atmosphere
 * 
 * LEGEND:
 * - Form: Base visual structure (signal/directional/reflective/action/depth)
 * - Mechanism: Accent aesthetic layer
 * - Interaction: User gesture pattern
 * - Magic: Timing/atmosphere signature
 * - KBE: Energy level (Believing = trust-building / Embodying = active-sealing)
 */

export const navicueBespokeCreativeBrief = [
  // ========================================
  // ALREADY CREATED (5/90)
  // ========================================
  {
    id: 1,
    filename: 'InventorySpark_Integrate_BehavioralActivation_B.tsx',
    status: '✅ CREATED',
    essence: 'Choose one concrete action path',
    visualApproach: 'Central orb with branching momentum paths',
    uniqueElement: 'Arrow vs circle endpoints, asymmetric button placement',
  },
  {
    id: 2,
    filename: 'InventorySpark_Integrate_BehavioralActivation_E.tsx',
    status: '✅ CREATED',
    essence: 'Hold to charge and release energy into action',
    visualApproach: 'Charging orb with radial energy burst',
    uniqueElement: 'Progress ring fills during hold, explosive release',
  },
  {
    id: 3,
    filename: 'InventorySpark_Integrate_Exposure_B.tsx',
    status: '✅ CREATED',
    essence: 'Flip the card to reveal the threshold',
    visualApproach: '3D card flip with closed door → open doorway',
    uniqueElement: 'Perspective shift, keyhole detail',
  },
  {
    id: 4,
    filename: 'InventorySpark_Integrate_Exposure_E.tsx',
    status: '✅ CREATED',
    essence: 'Step through comfort zone rings toward edge',
    visualApproach: 'Concentric circles with progressive stepping',
    uniqueElement: 'Multiple stages, layer-by-layer courage',
  },
  {
    id: 5,
    filename: 'InventorySpark_Integrate_Metacognition_B.tsx',
    status: '✅ CREATED',
    essence: 'Notice thought bubbles from observer perspective',
    visualApproach: 'Eye at bottom, floating thought clouds above',
    uniqueElement: 'Connection lines from observer to thoughts',
  },

  // ========================================
  // TO CREATE (85/90)
  // ========================================
  
  // 6-10: Inventory Spark variations
  {
    id: 6,
    filename: 'InventorySpark_Integrate_Metacognition_E.tsx',
    form: 'signal',
    mechanism: 'metacognition',
    interaction: 'hold_to_reveal',
    magic: 'witness_ritual',
    kbe: 'E',
    essence: 'Hold to separate self from thought stream',
    visualApproach: 'Observer eye in center, thought stream flows past - hold to slow and examine',
    uniqueElement: 'Flowing particles that slow to reveal when held, creates distance effect',
    atmosphere: 'Spacious awareness, gentle detachment',
  },
  {
    id: 7,
    filename: 'InventorySpark_Integrate_SelfCompassion_B.tsx',
    form: 'signal',
    mechanism: 'self_compassion',
    interaction: 'swatch_constellation',
    magic: 'sacred_ordinary',
    kbe: 'B',
    essence: 'Touch points of self-kindness to build warmth',
    visualApproach: 'Constellation of glowing heart points, tap each to activate network',
    uniqueElement: 'Web of warm connections forms between activated points',
    atmosphere: 'Gentle nurturing, building safety net',
  },
  {
    id: 8,
    filename: 'InventorySpark_Integrate_SelfCompassion_E.tsx',
    form: 'signal',
    mechanism: 'self_compassion',
    interaction: 'hold_to_continue',
    magic: 'witness_ritual',
    kbe: 'E',
    essence: 'Hold to embrace yourself fully in this moment',
    visualApproach: 'Two hands forming heart shape, hold to complete the embrace',
    uniqueElement: 'Progress fills the heart from edges to center, warm glow expands',
    atmosphere: 'Deep self-acceptance, completion',
  },
  {
    id: 9,
    filename: 'InventorySpark_Integrate_ValuesClarification_B.tsx',
    form: 'signal',
    mechanism: 'values_clarification',
    interaction: 'branch_fork',
    magic: 'sacred_ordinary',
    kbe: 'B',
    essence: 'Choose which direction aligns with your north star',
    visualApproach: 'Compass in center with two diverging paths, needle wavers',
    uniqueElement: 'Compass needle animates toward hovered choice',
    atmosphere: 'Directional clarity, purposeful choosing',
  },
  {
    id: 10,
    filename: 'InventorySpark_Integrate_ValuesClarification_E.tsx',
    form: 'signal',
    mechanism: 'values_clarification',
    interaction: 'tap_reveal',
    magic: 'witness_ritual',
    kbe: 'E',
    essence: 'Tap to anchor into your deepest value',
    visualApproach: 'Anchor descending through water layers to ocean floor',
    uniqueElement: 'Ripples spread from anchor point, settling with stability',
    atmosphere: 'Grounded commitment, roots deepening',
  },

  // 11-20: Key variations (directional form)
  {
    id: 11,
    filename: 'Key_Integrate_BehavioralActivation_B.tsx',
    form: 'directional',
    mechanism: 'behavioral_activation',
    interaction: 'tap_reveal',
    magic: 'sacred_ordinary',
    kbe: 'B',
    essence: 'Insert key to unlock forward motion',
    visualApproach: 'Key approaching lock, tap to turn and open door',
    uniqueElement: 'Tumbler mechanism visible through translucent lock',
    atmosphere: 'Unlocking potential, access granted',
  },
  {
    id: 12,
    filename: 'Key_Integrate_BehavioralActivation_E.tsx',
    form: 'directional',
    mechanism: 'behavioral_activation',
    interaction: 'hold_to_continue',
    magic: 'witness_ritual',
    kbe: 'E',
    essence: 'Hold key steady to open the passage completely',
    visualApproach: 'Key turning slowly in lock, hold to complete rotation',
    uniqueElement: 'Door swings open revealing lit pathway as key turns',
    atmosphere: 'Commitment to passage, threshold authority',
  },
  {
    id: 13,
    filename: 'Key_Integrate_Exposure_B.tsx',
    form: 'directional',
    mechanism: 'exposure',
    interaction: 'paradox_flip',
    magic: 'sacred_ordinary',
    kbe: 'B',
    essence: 'Flip to see the key unlocks from inside too',
    visualApproach: 'Key flips to show both sides - freedom is bidirectional',
    uniqueElement: 'Lock appears on both sides, revealing choice not trap',
    atmosphere: 'Safe exploration, autonomy preserved',
  },
  {
    id: 14,
    filename: 'Key_Integrate_Exposure_E.tsx',
    form: 'directional',
    mechanism: 'exposure',
    interaction: 'hold_to_reveal',
    magic: 'witness_ritual',
    kbe: 'E',
    essence: 'Hold to gradually reveal what lies beyond the door',
    visualApproach: 'Door becomes transparent as you hold, showing safe space beyond',
    uniqueElement: 'Opacity fades in sections, giving preview before commitment',
    atmosphere: 'Titrated courage, informed choice',
  },
  {
    id: 15,
    filename: 'Key_Integrate_Metacognition_B.tsx',
    form: 'directional',
    mechanism: 'metacognition',
    interaction: 'branch_fork',
    magic: 'sacred_ordinary',
    kbe: 'B',
    essence: 'Choose which door to observe your patterns through',
    visualApproach: 'One key, two different keyholes - different perspectives',
    uniqueElement: 'Keyholes show preview of thought patterns inside each door',
    atmosphere: 'Meta-awareness, choosing vantage point',
  },
  {
    id: 16,
    filename: 'Key_Integrate_Metacognition_E.tsx',
    form: 'directional',
    mechanism: 'metacognition',
    interaction: 'tap_reveal',
    magic: 'witness_ritual',
    kbe: 'E',
    essence: 'Unlock the room where you can see your own mind',
    visualApproach: 'Key opens observatory with telescopes pointing inward',
    uniqueElement: 'Mirrors and lenses revealing thought architecture',
    atmosphere: 'Clarity chamber, witnessing position secured',
  },
  {
    id: 17,
    filename: 'Key_Integrate_SelfCompassion_B.tsx',
    form: 'directional',
    mechanism: 'self_compassion',
    interaction: 'hold_to_continue',
    magic: 'sacred_ordinary',
    kbe: 'B',
    essence: 'Hold key gently to unlock self-kindness',
    visualApproach: 'Key made of soft light, hold to fill lock with warmth',
    uniqueElement: 'Lock melts rather than clicks, gentleness is the mechanism',
    atmosphere: 'Tender unlocking, force releases',
  },
  {
    id: 18,
    filename: 'Key_Integrate_SelfCompassion_E.tsx',
    form: 'directional',
    mechanism: 'self_compassion',
    interaction: 'swatch_constellation',
    magic: 'witness_ritual',
    kbe: 'E',
    essence: 'Touch each key to complete the ring of self-care',
    visualApproach: 'Circle of keys, each unlocking one aspect of self-compassion',
    uniqueElement: 'Keys light up in sequence forming protective circle',
    atmosphere: 'Complete self-support system activated',
  },
  {
    id: 19,
    filename: 'Key_Integrate_ValuesClarification_B.tsx',
    form: 'directional',
    mechanism: 'values_clarification',
    interaction: 'paradox_flip',
    magic: 'sacred_ordinary',
    kbe: 'B',
    essence: 'Flip key to see what you\'re really unlocking',
    visualApproach: 'Key flips to reveal true door label vs assumption',
    uniqueElement: 'Door transforms to show alignment with actual values',
    atmosphere: 'Truth alignment, seeing clearly',
  },
  {
    id: 20,
    filename: 'Key_Integrate_ValuesClarification_E.tsx',
    form: 'directional',
    mechanism: 'values_clarification',
    interaction: 'hold_to_reveal',
    magic: 'witness_ritual',
    kbe: 'E',
    essence: 'Hold to etch your value into the key itself',
    visualApproach: 'Blank key fills with engraved value as you hold',
    uniqueElement: 'Your value word/symbol becomes permanent on key',
    atmosphere: 'Identity forging, commitment crystallized',
  },

  // 21-30: Mirror variations (reflective form)
  {
    id: 21,
    filename: 'Mirror_Integrate_BehavioralActivation_B.tsx',
    form: 'reflective',
    mechanism: 'behavioral_activation',
    interaction: 'tap_reveal',
    magic: 'sacred_ordinary',
    kbe: 'B',
    essence: 'See yourself already in motion',
    visualApproach: 'Mirror shows future-self taking action when tapped',
    uniqueElement: 'Reflection leads current self by one step',
    atmosphere: 'Future-pull, becoming visible',
  },
  {
    id: 22,
    filename: 'Mirror_Integrate_BehavioralActivation_E.tsx',
    form: 'reflective',
    mechanism: 'behavioral_activation',
    interaction: 'hold_to_continue',
    magic: 'witness_ritual',
    kbe: 'E',
    essence: 'Hold gaze to merge with action-self',
    visualApproach: 'Mirror-self and real-self converge as you hold',
    uniqueElement: 'Boundary between reflection and reality dissolves',
    atmosphere: 'Integration complete, embodiment sealed',
  },
  {
    id: 23,
    filename: 'Mirror_Integrate_Exposure_B.tsx',
    form: 'reflective',
    mechanism: 'exposure',
    interaction: 'paradox_flip',
    magic: 'sacred_ordinary',
    kbe: 'B',
    essence: 'Flip mirror to see the avoided part of yourself',
    visualApproach: 'Mirror flips between visible self and shadow self',
    uniqueElement: 'Both sides are gentle, safety maintained in revelation',
    atmosphere: 'Safe seeing, wholeness recognized',
  },
  {
    id: 24,
    filename: 'Mirror_Integrate_Exposure_E.tsx',
    form: 'reflective',
    mechanism: 'exposure',
    interaction: 'hold_to_reveal',
    magic: 'witness_ritual',
    kbe: 'E',
    essence: 'Hold to clarify the foggy parts of reflection',
    visualApproach: 'Foggy mirror clears gradually as you hold steady',
    uniqueElement: 'Breath/warmth clears fog in organic pattern',
    atmosphere: 'Emerging clarity, patience rewarded',
  },
  {
    id: 25,
    filename: 'Mirror_Integrate_Metacognition_B.tsx',
    form: 'reflective',
    mechanism: 'metacognition',
    interaction: 'branch_fork',
    magic: 'sacred_ordinary',
    kbe: 'B',
    essence: 'Choose which angle to observe yourself from',
    visualApproach: 'Two mirrors at different angles showing different perspectives',
    uniqueElement: 'Each angle reveals different thought pattern',
    atmosphere: 'Perspective choice, observer flexibility',
  },
  {
    id: 26,
    filename: 'Mirror_Integrate_Metacognition_E.tsx',
    form: 'reflective',
    mechanism: 'metacognition',
    interaction: 'swatch_constellation',
    magic: 'witness_ritual',
    kbe: 'E',
    essence: 'Touch each mirror to build full self-awareness',
    visualApproach: 'Multiple small mirrors forming compound eye view',
    uniqueElement: 'Faceted perspective all angles simultaneously',
    atmosphere: 'Complete witnessing, 360° awareness',
  },
  {
    id: 27,
    filename: 'Mirror_Integrate_SelfCompassion_B.tsx',
    form: 'reflective',
    mechanism: 'self_compassion',
    interaction: 'hold_to_continue',
    magic: 'sacred_ordinary',
    kbe: 'B',
    essence: 'Hold your own gaze with kindness',
    visualApproach: 'Eyes in mirror soften and warm as you hold',
    uniqueElement: 'Facial expression shifts to compassionate witness',
    atmosphere: 'Self-meeting, gentle regard',
  },
  {
    id: 28,
    filename: 'Mirror_Integrate_SelfCompassion_E.tsx',
    form: 'reflective',
    mechanism: 'self_compassion',
    interaction: 'tap_reveal',
    magic: 'witness_ritual',
    kbe: 'E',
    essence: 'Tap to embrace your reflection',
    visualApproach: 'Arms extend from edges to embrace the viewer',
    uniqueElement: 'Self-hug visualization, warmth radiates',
    atmosphere: 'Self-embrace complete, integration',
  },
  {
    id: 29,
    filename: 'Mirror_Integrate_ValuesClarification_B.tsx',
    form: 'reflective',
    mechanism: 'values_clarification',
    interaction: 'paradox_flip',
    magic: 'sacred_ordinary',
    kbe: 'B',
    essence: 'Flip to see your values reflected in your actions',
    visualApproach: 'One side shows values list, flip shows matching behaviors',
    uniqueElement: 'Connections illuminate between stated and lived values',
    atmosphere: 'Integrity check, alignment visible',
  },
  {
    id: 30,
    filename: 'Mirror_Integrate_ValuesClarification_E.tsx',
    form: 'reflective',
    mechanism: 'values_clarification',
    interaction: 'hold_to_reveal',
    magic: 'witness_ritual',
    kbe: 'E',
    essence: 'Hold to see your deepest value written in your eyes',
    visualApproach: 'Eyes become clear pools, value word emerges from depths',
    uniqueElement: 'Core value surfaces from pupil outward',
    atmosphere: 'Soul recognition, essence seen',
  },

  // 31-40: Parts Rollcall variations (reflective form, group dynamic)
  {
    id: 31,
    filename: 'PartsRollcall_Integrate_BehavioralActivation_B.tsx',
    form: 'reflective',
    mechanism: 'behavioral_activation',
    interaction: 'swatch_constellation',
    magic: 'sacred_ordinary',
    kbe: 'B',
    essence: 'Call each part to action council',
    visualApproach: 'Circle of figures, tap each to bring to council table',
    uniqueElement: 'Parts walk to center as activated, forming team',
    atmosphere: 'Assembly of action, all parts coordinated',
  },
  {
    id: 32,
    filename: 'PartsRollcall_Integrate_BehavioralActivation_E.tsx',
    form: 'reflective',
    mechanism: 'behavioral_activation',
    interaction: 'hold_to_continue',
    magic: 'witness_ritual',
    kbe: 'E',
    essence: 'Hold to mobilize all parts as one',
    visualApproach: 'Separate figures merge into unified moving form',
    uniqueElement: 'Parts flow together like mercury, unified action',
    atmosphere: 'Integration embodied, singular motion',
  },
  {
    id: 33,
    filename: 'PartsRollcall_Integrate_Exposure_B.tsx',
    form: 'reflective',
    mechanism: 'exposure',
    interaction: 'tap_reveal',
    magic: 'sacred_ordinary',
    kbe: 'B',
    essence: 'Tap to reveal hidden parts waiting backstage',
    visualApproach: 'Curtain lifts to show parts in shadows, tap to spotlight each',
    uniqueElement: 'Spotlight moves part from shadow to visible circle',
    atmosphere: 'Safe revelation, all parts welcomed',
  },
  {
    id: 34,
    filename: 'PartsRollcall_Integrate_Exposure_E.tsx',
    form: 'reflective',
    mechanism: 'exposure',
    interaction: 'hold_to_reveal',
    magic: 'witness_ritual',
    kbe: 'E',
    essence: 'Hold to bring exiled parts home',
    visualApproach: 'Distant figures walk closer as you hold',
    uniqueElement: 'Path illuminates under their feet as they return',
    atmosphere: 'Homecoming, exile ended',
  },
  {
    id: 35,
    filename: 'PartsRollcall_Integrate_Metacognition_B.tsx',
    form: 'reflective',
    mechanism: 'metacognition',
    interaction: 'branch_fork',
    magic: 'sacred_ordinary',
    kbe: 'B',
    essence: 'Choose which part to observe from',
    visualApproach: 'Multiple parts, choose one as observer of others',
    uniqueElement: 'Chosen part gets elevated view, others become visible',
    atmosphere: 'Meta-part activated, witness position',
  },
  {
    id: 36,
    filename: 'PartsRollcall_Integrate_Metacognition_E.tsx',
    form: 'reflective',
    mechanism: 'metacognition',
    interaction: 'hold_to_continue',
    magic: 'witness_ritual',
    kbe: 'E',
    essence: 'Hold to see the conductor part emerge',
    visualApproach: 'Central figure rises holding baton, orchestrating others',
    uniqueElement: 'Parts arrange in harmony as conductor appears',
    atmosphere: 'Leadership from Self, coordination complete',
  },
  {
    id: 37,
    filename: 'PartsRollcall_Integrate_SelfCompassion_B.tsx',
    form: 'reflective',
    mechanism: 'self_compassion',
    interaction: 'swatch_constellation',
    magic: 'sacred_ordinary',
    kbe: 'B',
    essence: 'Touch each part to offer kindness',
    visualApproach: 'Parts sitting in circle, tap each to give warm glow',
    uniqueElement: 'Warmth spreads between parts like passing candle',
    atmosphere: 'Inter-part compassion, system care',
  },
  {
    id: 38,
    filename: 'PartsRollcall_Integrate_SelfCompassion_E.tsx',
    form: 'reflective',
    mechanism: 'self_compassion',
    interaction: 'hold_to_reveal',
    magic: 'witness_ritual',
    kbe: 'E',
    essence: 'Hold to wrap all parts in shared warmth',
    visualApproach: 'Blanket of light wraps around gathered parts',
    uniqueElement: 'Parts huddle closer, collective embrace',
    atmosphere: 'System soothing, all held',
  },
  {
    id: 39,
    filename: 'PartsRollcall_Integrate_ValuesClarification_B.tsx',
    form: 'reflective',
    mechanism: 'values_clarification',
    interaction: 'paradox_flip',
    magic: 'sacred_ordinary',
    kbe: 'B',
    essence: 'Flip to see which parts align with core value',
    visualApproach: 'Parts highlighted/dimmed by value alignment',
    uniqueElement: 'Value filter reveals aligned coalition',
    atmosphere: 'Values team identified, clarity',
  },
  {
    id: 40,
    filename: 'PartsRollcall_Integrate_ValuesClarification_E.tsx',
    form: 'reflective',
    mechanism: 'values_clarification',
    interaction: 'tap_reveal',
    magic: 'witness_ritual',
    kbe: 'E',
    essence: 'Tap to give each part their value role',
    visualApproach: 'Parts receive value badges/colors, forming rainbow',
    uniqueElement: 'Each part carries one aspect of whole value system',
    atmosphere: 'Distributed purpose, all have place',
  },

  // 41-50: Practice variations (action form, kinetic)
  {
    id: 41,
    filename: 'Practice_Integrate_BehavioralActivation_B.tsx',
    form: 'action',
    mechanism: 'behavioral_activation',
    interaction: 'tap_reveal',
    magic: 'sacred_ordinary',
    kbe: 'B',
    essence: 'Tap to demonstrate the micro-action',
    visualApproach: 'Hand/body showing movement sequence in animation',
    uniqueElement: 'Gesture breaks into numbered steps',
    atmosphere: 'Kinesthetic learning, body knows',
  },
  {
    id: 42,
    filename: 'Practice_Integrate_BehavioralActivation_E.tsx',
    form: 'action',
    mechanism: 'behavioral_activation',
    interaction: 'hold_to_continue',
    magic: 'witness_ritual',
    kbe: 'E',
    essence: 'Hold to complete the full movement',
    visualApproach: 'Action sequence plays as you hold, seal at end',
    uniqueElement: 'Progress through full practice cycle',
    atmosphere: 'Completion embodied, practice sealed',
  },
  {
    id: 43,
    filename: 'Practice_Integrate_Exposure_B.tsx',
    form: 'action',
    mechanism: 'exposure',
    interaction: 'branch_fork',
    magic: 'sacred_ordinary',
    kbe: 'B',
    essence: 'Choose which edge to practice approaching',
    visualApproach: 'Two practice paths diverging, preview each',
    uniqueElement: 'Difficulty meter shown for each path',
    atmosphere: 'Titrated choice, appropriate challenge',
  },
  {
    id: 44,
    filename: 'Practice_Integrate_Exposure_E.tsx',
    form: 'action',
    mechanism: 'exposure',
    interaction: 'hold_to_reveal',
    magic: 'witness_ritual',
    kbe: 'E',
    essence: 'Hold to move through exposure hierarchy',
    visualApproach: 'Ladder/steps ascending, hold to climb each',
    uniqueElement: 'Progress saved at each step, can pause',
    atmosphere: 'Graduated exposure, safety maintained',
  },
  {
    id: 45,
    filename: 'Practice_Integrate_Metacognition_B.tsx',
    form: 'action',
    mechanism: 'metacognition',
    interaction: 'paradox_flip',
    magic: 'sacred_ordinary',
    kbe: 'B',
    essence: 'Flip between doing and observing doing',
    visualApproach: 'Action view flips to observer view of same action',
    uniqueElement: 'Dual perspective - actor and witness',
    atmosphere: 'Meta-practice, awareness during action',
  },
  {
    id: 46,
    filename: 'Practice_Integrate_Metacognition_E.tsx',
    form: 'action',
    mechanism: 'metacognition',
    interaction: 'swatch_constellation',
    magic: 'witness_ritual',
    kbe: 'E',
    essence: 'Touch checkpoints of aware practice',
    visualApproach: 'Action path with awareness bells to ring',
    uniqueElement: 'Bell tone at each mindful checkpoint',
    atmosphere: 'Embodied awareness, awake action',
  },
  {
    id: 47,
    filename: 'Practice_Integrate_SelfCompassion_B.tsx',
    form: 'action',
    mechanism: 'self_compassion',
    interaction: 'hold_to_continue',
    magic: 'sacred_ordinary',
    kbe: 'B',
    essence: 'Hold to practice self-kindness gesture',
    visualApproach: 'Hand on heart, warmth spreads as held',
    uniqueElement: 'Heartbeat visible, warmth radiates with pulse',
    atmosphere: 'Soothing practice, nervous system care',
  },
  {
    id: 48,
    filename: 'Practice_Integrate_SelfCompassion_E.tsx',
    form: 'action',
    mechanism: 'self_compassion',
    interaction: 'tap_reveal',
    magic: 'witness_ritual',
    kbe: 'E',
    essence: 'Tap to complete compassion practice cycle',
    visualApproach: 'Circle closes - recognize, allow, care, embody',
    uniqueElement: 'Four quadrants light up in sequence',
    atmosphere: 'Practice completion, cycle internalized',
  },
  {
    id: 49,
    filename: 'Practice_Integrate_ValuesClarification_B.tsx',
    form: 'action',
    mechanism: 'values_clarification',
    interaction: 'branch_fork',
    magic: 'sacred_ordinary',
    kbe: 'B',
    essence: 'Choose which value-aligned action to practice',
    visualApproach: 'Two gestures representing different values',
    uniqueElement: 'Value name appears under each gesture',
    atmosphere: 'Purposeful practice, meaning visible',
  },
  {
    id: 50,
    filename: 'Practice_Integrate_ValuesClarification_E.tsx',
    form: 'action',
    mechanism: 'values_clarification',
    interaction: 'hold_to_reveal',
    magic: 'witness_ritual',
    kbe: 'E',
    essence: 'Hold to etch practice into value-body',
    visualApproach: 'Action leaves light trail forming value symbol',
    uniqueElement: 'Movement creates lasting mark, practice becomes identity',
    atmosphere: 'Embodiment complete, value lived',
  },

  // 51-60: Probe variations (depth form, inquiry)
  {
    id: 51,
    filename: 'Probe_Integrate_BehavioralActivation_B.tsx',
    form: 'depth',
    mechanism: 'behavioral_activation',
    interaction: 'tap_reveal',
    magic: 'sacred_ordinary',
    kbe: 'B',
    essence: 'Tap to drill into why action matters',
    visualApproach: 'Concentric circles descending into motivation core',
    uniqueElement: 'Each tap goes deeper, reveals next "why" layer',
    atmosphere: 'Purposeful excavation, meaning uncovered',
  },
  {
    id: 52,
    filename: 'Probe_Integrate_BehavioralActivation_E.tsx',
    form: 'depth',
    mechanism: 'behavioral_activation',
    interaction: 'hold_to_continue',
    magic: 'witness_ritual',
    kbe: 'E',
    essence: 'Hold to reach bedrock motivation',
    visualApproach: 'Drill descends continuously to core truth',
    uniqueElement: 'Light emerges from bottom when core reached',
    atmosphere: 'Foundation found, unshakeable ground',
  },
  {
    id: 53,
    filename: 'Probe_Integrate_Exposure_B.tsx',
    form: 'depth',
    mechanism: 'exposure',
    interaction: 'hold_to_reveal',
    magic: 'sacred_ordinary',
    kbe: 'B',
    essence: 'Hold to gently illuminate what\'s below surface',
    visualApproach: 'Flashlight beam extends into dark water as held',
    uniqueElement: 'Gradual visibility, control over how much seen',
    atmosphere: 'Safe curiosity, titrated depth',
  },
  {
    id: 54,
    filename: 'Probe_Integrate_Exposure_E.tsx',
    form: 'depth',
    mechanism: 'exposure',
    interaction: 'paradox_flip',
    magic: 'witness_ritual',
    kbe: 'E',
    essence: 'Flip to see avoided depth from new angle',
    visualApproach: 'Cross-section rotates revealing hidden dimension',
    uniqueElement: 'New perspective makes previously scary seem approachable',
    atmosphere: 'Reframe through rotation, safety in new view',
  },
  {
    id: 55,
    filename: 'Probe_Integrate_Metacognition_B.tsx',
    form: 'depth',
    mechanism: 'metacognition',
    interaction: 'branch_fork',
    magic: 'sacred_ordinary',
    kbe: 'B',
    essence: 'Choose which thought layer to examine',
    visualApproach: 'Thought archaeology - multiple dig sites',
    uniqueElement: 'Each site reveals different cognitive fossil',
    atmosphere: 'Cognitive curiosity, pattern excavation',
  },
  {
    id: 56,
    filename: 'Probe_Integrate_Metacognition_E.tsx',
    form: 'depth',
    mechanism: 'metacognition',
    interaction: 'swatch_constellation',
    magic: 'witness_ritual',
    kbe: 'E',
    essence: 'Touch each depth point to map full mental terrain',
    visualApproach: 'Sonar pings revealing underwater topography',
    uniquelement: 'Complete depth map emerges from constellation',
    atmosphere: 'Full cartography, mental landscape known',
  },
  {
    id: 57,
    filename: 'Probe_Integrate_SelfCompassion_B.tsx',
    form: 'depth',
    mechanism: 'self_compassion',
    interaction: 'hold_to_continue',
    magic: 'sacred_ordinary',
    kbe: 'B',
    essence: 'Hold to send compassion into deep wound',
    visualApproach: 'Warm light descending into dark well',
    uniqueElement: 'Light fills from bottom up, healing from depth',
    atmosphere: 'Deep care, reaching old hurt',
  },
  {
    id: 58,
    filename: 'Probe_Integrate_SelfCompassion_E.tsx',
    form: 'depth',
    mechanism: 'self_compassion',
    interaction: 'tap_reveal',
    magic: 'witness_ritual',
    kbe: 'E',
    essence: 'Tap to plant compassion at the root',
    visualApproach: 'Tree roots receiving water/light, growth begins',
    uniqueElement: 'Compassion becomes structural support',
    atmosphere: 'Foundation healed, growth from depth',
  },
  {
    id: 59,
    filename: 'Probe_Integrate_ValuesClarification_B.tsx',
    form: 'depth',
    mechanism: 'values_clarification',
    interaction: 'paradox_flip',
    magic: 'sacred_ordinary',
    kbe: 'B',
    essence: 'Flip to see surface value vs root value',
    visualApproach: 'Tree flips to show branches vs roots',
    uniqueElement: 'Root system reveals what truly matters',
    atmosphere: 'Core truth, beneath performance',
  },
  {
    id: 60,
    filename: 'Probe_Integrate_ValuesClarification_E.tsx',
    form: 'depth',
    mechanism: 'values_clarification',
    interaction: 'hold_to_reveal',
    magic: 'witness_ritual',
    kbe: 'E',
    essence: 'Hold to excavate deepest value',
    visualApproach: 'Archaeologist brushing away layers to reveal artifact',
    uniqueElement: 'Value emerges as ancient solid object',
    atmosphere: 'Timeless truth, unshakeable core',
  },

  // 61-70: Reframe Seed variations (reflective form, transformation)
  {
    id: 61,
    filename: 'ReframeSeed_Integrate_BehavioralActivation_B.tsx',
    form: 'reflective',
    mechanism: 'behavioral_activation',
    interaction: 'tap_reveal',
    magic: 'sacred_ordinary',
    kbe: 'B',
    essence: 'Plant seed that reframes stuck as preparation',
    visualApproach: 'Seed glowing in soil, tap to show first sprout',
    uniqueElement: 'Old story becomes compost for new growth',
    atmosphere: 'Regenerative reframe, stuck becomes fertile',
  },
  {
    id: 62,
    filename: 'ReframeSeed_Integrate_BehavioralActivation_E.tsx',
    form: 'reflective',
    mechanism: 'behavioral_activation',
    interaction: 'hold_to_continue',
    magic: 'witness_ritual',
    kbe: 'E',
    essence: 'Hold to grow reframe into full action plant',
    visualApproach: 'Time-lapse growth from seed to flowering action',
    uniqueElement: 'New narrative blooms into behavior',
    atmosphere: 'Story embodied, growth sealed',
  },
  {
    id: 63,
    filename: 'ReframeSeed_Integrate_Exposure_B.tsx',
    form: 'reflective',
    mechanism: 'exposure',
    interaction: 'branch_fork',
    magic: 'sacred_ordinary',
    kbe: 'B',
    essence: 'Choose which reframe makes edge approachable',
    visualApproach: 'Two seeds - "challenge" vs "threat" frame',
    uniqueElement: 'Plants grow into different safety levels',
    atmosphere: 'Frame selection, safety through story',
  },
  {
    id: 64,
    filename: 'ReframeSeed_Integrate_Exposure_E.tsx',
    form: 'reflective',
    mechanism: 'exposure',
    interaction: 'hold_to_reveal',
    magic: 'witness_ritual',
    kbe: 'E',
    essence: 'Hold to watch fear reframe to curiosity',
    visualApproach: 'Dark seed transforms into light seed as held',
    uniqueElement: 'Color shift represents emotional tone change',
    atmosphere: 'Transmutation, same thing different light',
  },
  {
    id: 65,
    filename: 'ReframeSeed_Integrate_Metacognition_B.tsx',
    form: 'reflective',
    mechanism: 'metacognition',
    interaction: 'paradox_flip',
    magic: 'sacred_ordinary',
    kbe: 'B',
    essence: 'Flip seed to see thought vs meta-thought',
    visualApproach: 'Seed flips between "I am anxious" and "I notice anxiety"',
    uniqueElement: 'Language shift visible in seed transformation',
    atmosphere: 'Linguistic distance, observer position',
  },
  {
    id: 66,
    filename: 'ReframeSeed_Integrate_Metacognition_E.tsx',
    form: 'reflective',
    mechanism: 'metacognition',
    interaction: 'swatch_constellation',
    magic: 'witness_ritual',
    kbe: 'E',
    essence: 'Touch each seed to build meta-awareness garden',
    visualApproach: 'Multiple seeds each holding different reframe',
    uniqueElement: 'Garden of perspectives, rich ecosystem',
    atmosphere: 'Cognitive flexibility embodied, many views held',
  },
  {
    id: 67,
    filename: 'ReframeSeed_Integrate_SelfCompassion_B.tsx',
    form: 'reflective',
    mechanism: 'self_compassion',
    interaction: 'hold_to_continue',
    magic: 'sacred_ordinary',
    kbe: 'B',
    essence: 'Hold to water harsh story with kindness',
    visualApproach: 'Watering can above seed, hold to pour compassion',
    uniqueElement: 'Harsh words dissolve, kind words emerge',
    atmosphere: 'Narrative softening, self-talk transformed',
  },
  {
    id: 68,
    filename: 'ReframeSeed_Integrate_SelfCompassion_E.tsx',
    form: 'reflective',
    mechanism: 'self_compassion',
    interaction: 'tap_reveal',
    magic: 'witness_ritual',
    kbe: 'E',
    essence: 'Tap to bloom compassionate reframe fully',
    visualApproach: 'Flower opens revealing kind truth at center',
    uniqueElement: 'Petals are old harsh words, center is compassionate core',
    atmosphere: 'Kind story embodied, new default',
  },
  {
    id: 69,
    filename: 'ReframeSeed_Integrate_ValuesClarification_B.tsx',
    form: 'reflective',
    mechanism: 'values_clarification',
    interaction: 'branch_fork',
    magic: 'sacred_ordinary',
    kbe: 'B',
    essence: 'Choose which value lens to plant',
    visualApproach: 'Two seeds representing different value frames',
    uniqueElement: 'Same situation grows different meaning tree',
    atmosphere: 'Value filter visible, purpose clarified',
  },
  {
    id: 70,
    filename: 'ReframeSeed_Integrate_ValuesClarification_E.tsx',
    form: 'reflective',
    mechanism: 'values_clarification',
    interaction: 'hold_to_reveal',
    magic: 'witness_ritual',
    kbe: 'E',
    essence: 'Hold to grow value-aligned story fully',
    visualApproach: 'Seed grows into tree bearing value as fruit',
    uniqueElement: 'Story structure now supports core value',
    atmosphere: 'Narrative integrity, meaning embodied',
  },

  // 71-80: Reveal variations (signal form, emergence)
  {
    id: 71,
    filename: 'Reveal_Integrate_BehavioralActivation_B.tsx',
    form: 'signal',
    mechanism: 'behavioral_activation',
    interaction: 'tap_reveal',
    magic: 'sacred_ordinary',
    kbe: 'B',
    essence: 'Tap curtain to reveal action possibility',
    visualApproach: 'Stage curtain opens on possible future action',
    uniqueElement: 'Spotlight on single clear next step',
    atmosphere: 'Clarity arrival, fog lifts',
  },
  {
    id: 72,
    filename: 'Reveal_Integrate_BehavioralActivation_E.tsx',
    form: 'signal',
    mechanism: 'behavioral_activation',
    interaction: 'hold_to_continue',
    magic: 'witness_ritual',
    kbe: 'E',
    essence: 'Hold to unveil full action sequence',
    visualApproach: 'Progressive reveal of dominoes ready to fall',
    uniqueElement: 'First push visible, momentum clear',
    atmosphere: 'Path illuminated, commitment moment',
  },
  {
    id: 73,
    filename: 'Reveal_Integrate_Exposure_B.tsx',
    form: 'signal',
    mechanism: 'exposure',
    interaction: 'hold_to_reveal',
    magic: 'sacred_ordinary',
    kbe: 'B',
    essence: 'Hold to gradually reveal the safe truth',
    visualApproach: 'Fog slowly clears revealing gentle landscape',
    uniqueElement: 'Control over reveal speed, safety maintained',
    atmosphere: 'Titrated truth, paced revelation',
  },
  {
    id: 74,
    filename: 'Reveal_Integrate_Exposure_E.tsx',
    form: 'signal',
    mechanism: 'exposure',
    interaction: 'paradox_flip',
    magic: 'witness_ritual',
    kbe: 'E',
    essence: 'Flip to reveal opposite of feared outcome',
    visualApproach: 'Card flips from imagined catastrophe to likely reality',
    uniqueElement: 'Contrast makes distortion visible',
    atmosphere: 'Reality check, fear dissolves',
  },
  {
    id: 75,
    filename: 'Reveal_Integrate_Metacognition_B.tsx',
    form: 'signal',
    mechanism: 'metacognition',
    interaction: 'branch_fork',
    magic: 'sacred_ordinary',
    kbe: 'B',
    essence: 'Choose which cognitive layer to reveal',
    visualApproach: 'Multiple curtains at different depths',
    uniqueElement: 'Each reveals different level of thought structure',
    atmosphere: 'Layered awareness, depth choice',
  },
  {
    id: 76,
    filename: 'Reveal_Integrate_Metacognition_E.tsx',
    form: 'signal',
    mechanism: 'metacognition',
    interaction: 'swatch_constellation',
    magic: 'witness_ritual',
    kbe: 'E',
    essence: 'Touch each point to reveal full mental map',
    visualApproach: 'Constellation points light up revealing thought network',
    uniqueElement: 'Complete cognitive architecture visible',
    atmosphere: 'Full transparency, system understood',
  },
  {
    id: 77,
    filename: 'Reveal_Integrate_SelfCompassion_B.tsx',
    form: 'signal',
    mechanism: 'self_compassion',
    interaction: 'hold_to_continue',
    magic: 'sacred_ordinary',
    kbe: 'B',
    essence: 'Hold to reveal your inherent worthiness',
    visualApproach: 'Clouds part revealing sun that was always there',
    uniqueElement: 'Light was present but obscured, now seen',
    atmosphere: 'Truth uncovered, worth revealed',
  },
  {
    id: 78,
    filename: 'Reveal_Integrate_SelfCompassion_E.tsx',
    form: 'signal',
    mechanism: 'self_compassion',
    interaction: 'tap_reveal',
    magic: 'witness_ritual',
    kbe: 'E',
    essence: 'Tap to unveil complete self-acceptance',
    visualApproach: 'Mirror cloth drops revealing clear reflection',
    uniqueElement: 'Self seen without distortion, accepted wholly',
    atmosphere: 'Recognition complete, love unconcealed',
  },
  {
    id: 79,
    filename: 'Reveal_Integrate_ValuesClarification_B.tsx',
    form: 'signal',
    mechanism: 'values_clarification',
    interaction: 'paradox_flip',
    magic: 'sacred_ordinary',
    kbe: 'B',
    essence: 'Flip to reveal true value behind behavior',
    visualApproach: 'Action card flips to show underlying value',
    uniqueElement: 'Hidden motivation made visible',
    atmosphere: 'Insight moment, "oh that\'s why"',
  },
  {
    id: 80,
    filename: 'Reveal_Integrate_ValuesClarification_E.tsx',
    form: 'signal',
    mechanism: 'values_clarification',
    interaction: 'hold_to_reveal',
    magic: 'witness_ritual',
    kbe: 'E',
    essence: 'Hold to reveal your core value constellation',
    visualApproach: 'Stars emerge forming value constellation pattern',
    uniqueElement: 'Pattern shows how values relate and support each other',
    atmosphere: 'Value system visible, integrity constellation',
  },

  // 81-90: Route variations (directional form, pathfinding)
  {
    id: 81,
    filename: 'Route_Integrate_BehavioralActivation_B.tsx',
    form: 'directional',
    mechanism: 'behavioral_activation',
    interaction: 'branch_fork',
    magic: 'sacred_ordinary',
    kbe: 'B',
    essence: 'Choose which action path to follow',
    visualApproach: 'Diverging trails with preview of destinations',
    uniqueElement: 'Footprints show where each path leads',
    atmosphere: 'Path clarity, informed choosing',
  },
  {
    id: 82,
    filename: 'Route_Integrate_BehavioralActivation_E.tsx',
    form: 'directional',
    mechanism: 'behavioral_activation',
    interaction: 'hold_to_continue',
    magic: 'witness_ritual',
    kbe: 'E',
    essence: 'Hold to walk the full route with commitment',
    visualApproach: 'Path lights up progressively as you hold',
    uniqueElement: 'Journey completes, arrival celebrated',
    atmosphere: 'Path embodied, destination reached',
  },
  {
    id: 83,
    filename: 'Route_Integrate_Exposure_B.tsx',
    form: 'directional',
    mechanism: 'exposure',
    interaction: 'tap_reveal',
    magic: 'sacred_ordinary',
    kbe: 'B',
    essence: 'Tap waypoints on route to edge',
    visualApproach: 'Path with checkpoints, tap to preview each stop',
    uniqueElement: 'Can see next step without full commitment',
    atmosphere: 'Graduated approach, safety stops visible',
  },
  {
    id: 84,
    filename: 'Route_Integrate_Exposure_E.tsx',
    form: 'directional',
    mechanism: 'exposure',
    interaction: 'hold_to_reveal',
    magic: 'witness_ritual',
    kbe: 'E',
    essence: 'Hold to illuminate full path through fear',
    visualApproach: 'Flashlight beam extends showing complete safe route',
    uniqueElement: 'Entire journey visible, manageable when seen',
    atmosphere: 'Full map, courage from clarity',
  },
  {
    id: 85,
    filename: 'Route_Integrate_Metacognition_B.tsx',
    form: 'directional',
    mechanism: 'metacognition',
    interaction: 'paradox_flip',
    magic: 'sacred_ordinary',
    kbe: 'B',
    essence: 'Flip between path and map of path',
    visualApproach: 'Ground view flips to aerial view',
    uniqueElement: 'Meta-perspective shows patterns invisible from ground',
    atmosphere: 'Perspective shift, pattern recognition',
  },
  {
    id: 86,
    filename: 'Route_Integrate_Metacognition_E.tsx',
    form: 'directional',
    mechanism: 'metacognition',
    interaction: 'swatch_constellation',
    magic: 'witness_ritual',
    kbe: 'E',
    essence: 'Touch each vantage point on route',
    visualApproach: 'Multiple viewpoints along path, touch to see from each',
    uniqueElement: 'Journey seen from many perspectives simultaneously',
    atmosphere: 'Multi-angle awareness, wisdom path',
  },
  {
    id: 87,
    filename: 'Route_Integrate_SelfCompassion_B.tsx',
    form: 'directional',
    mechanism: 'self_compassion',
    interaction: 'hold_to_continue',
    magic: 'sacred_ordinary',
    kbe: 'B',
    essence: 'Hold to place rest stops along your route',
    visualApproach: 'Path gains benches and shade as you hold',
    uniqueElement: 'Self-care infrastructure built into journey',
    atmosphere: 'Sustainable pacing, kindness designed in',
  },
  {
    id: 88,
    filename: 'Route_Integrate_SelfCompassion_E.tsx',
    form: 'directional',
    mechanism: 'self_compassion',
    interaction: 'tap_reveal',
    magic: 'witness_ritual',
    kbe: 'E',
    essence: 'Tap to complete route with celebration',
    visualApproach: 'Path ends at welcoming home with light on',
    uniqueElement: 'Journey honored, return celebrated',
    atmosphere: 'Completion with love, hero\'s return',
  },
  {
    id: 89,
    filename: 'Route_Integrate_ValuesClarification_B.tsx',
    form: 'directional',
    mechanism: 'values_clarification',
    interaction: 'branch_fork',
    magic: 'sacred_ordinary',
    kbe: 'B',
    essence: 'Choose route aligned with core value',
    visualApproach: 'Paths labeled with destination values',
    uniqueElement: 'Value compass shows which way is "north"',
    atmosphere: 'Purposeful navigation, integrity path',
  },
  {
    id: 90,
    filename: 'Route_Integrate_ValuesClarification_E.tsx',
    form: 'directional',
    mechanism: 'values_clarification',
    interaction: 'hold_to_reveal',
    magic: 'witness_ritual',
    kbe: 'E',
    essence: 'Hold to see your value as the path itself',
    visualApproach: 'Path becomes luminous with your core value',
    uniqueElement: 'Walking the value, not toward it - you are the way',
    atmosphere: 'Identity as direction, essence embodied',
  },
];

/**
 * EXECUTION NOTES:
 * 
 * When user says "go":
 * 1. Create files sequentially from id 6-90
 * 2. Each file gets full bespoke treatment following its creative brief
 * 3. Maintain compact but unique code style
 * 4. Use @/design-tokens for imports
 * 5. Each should be 100-150 lines, focused on the unique visual element
 * 6. All include proper TypeScript types, Motion animations, stage management
 * 7. Atmosphere and essence should be palpable in every detail
 * 
 * Ready for batch execution ✨
 */
